api:
  alias: add-md
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-04T14:56:17Z
  description: 添加积木方法
  id: 269
  method: POST
  name: 添加积木方法
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: add-md
    attributes: null
    description: null
    id: 371
    index: 1
    legoAlias: add
    oiAlias: ty_method_describe
    processControllerAlias: null
    uuid: '371'
  inputFields:
  - alias: name
    apiLegoId: 371
    apiLegoUuid: '371'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1023
    ift: create
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '1023'
    validate: null
  - alias: description
    apiLegoId: 371
    apiLegoUuid: '371'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1024
    ift: create
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '1024'
    validate: null
  - alias: buildingBlockAlias
    apiLegoId: 371
    apiLegoUuid: '371'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: buildingBlockAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1025
    ift: create
    inputFieldDescribeId: 0
    name: 积木别名
    requestParamName: buildingBlockAlias
    sessionParamName: null
    uuid: '1025'
    validate: null
  - alias: methodName
    apiLegoId: 371
    apiLegoUuid: '371'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: methodName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1026
    ift: create
    inputFieldDescribeId: 0
    name: 方法名
    requestParamName: methodName
    sessionParamName: null
    uuid: '1026'
    validate: null
  outputFields:
  - alias: unique_value
    apiLegoId: 371
    apiLegoUuid: '371'
    description: null
    dt: string
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 147
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 33
    response: true
    uuid: '147'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
