api:
  alias: add-apiLego
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-11T14:58:22Z
  description: 添加apilego
  id: 26
  method: POST
  name: 添加apiLego
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: add-apiLego
    attributes: ''
    description: null
    id: 31
    index: 1
    legoAlias: add
    oiAlias: ty_api_lego
    processControllerAlias: null
    uuid: '31'
  inputFields:
  - alias: apiAlias
    apiLegoId: 31
    apiLegoUuid: '31'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: apiAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 84
    ift: create
    inputFieldDescribeId: 0
    name: api别名
    requestParamName: apiAlias
    sessionParamName: ''
    uuid: '84'
    validate: '[{"validateName":"required"}]'
  - alias: legoAlias
    apiLegoId: 31
    apiLegoUuid: '31'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: legoAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 85
    ift: create
    inputFieldDescribeId: 0
    name: lego别名
    requestParamName: legoAlias
    sessionParamName: ''
    uuid: '85'
    validate: '[{"validateName":"required"}]'
  - alias: oiAlias
    apiLegoId: 31
    apiLegoUuid: '31'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: oiAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 86
    ift: create
    inputFieldDescribeId: 0
    name: oi别名
    requestParamName: oiAlias
    sessionParamName: null
    uuid: '86'
    validate: null
  - alias: index
    apiLegoId: 31
    apiLegoUuid: '31'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: index
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 87
    ift: create
    inputFieldDescribeId: 0
    name: 顺序
    requestParamName: index
    sessionParamName: null
    uuid: '87'
    validate: null
  outputFields:
  - alias: unique_value
    apiLegoId: 31
    apiLegoUuid: '31'
    description: null
    dt: string
    fieldName: unique_value
    fieldValue: null
    handle: null
    id: 31
    name: id
    oft: create
    outputFieldDescribeId: 0
    response: true
    uuid: '31'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
