api:
  alias: add-inputfield
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-17T11:16:05Z
  description: null
  id: 203
  method: POST
  name: 添加inputField
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: add-inputfield
    attributes: null
    description: null
    id: 250
    index: 1
    legoAlias: add
    oiAlias: ty_input_field
    processControllerAlias: null
    uuid: '250'
  inputFields:
  - alias: name
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 216
    ift: create
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '216'
    validate: null
  - alias: description
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 217
    ift: create
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '217'
    validate: null
  - alias: apiLegoId
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: apiLegoId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 218
    ift: create
    inputFieldDescribeId: 0
    name: apiLegoId
    requestParamName: apiLegoId
    sessionParamName: ''
    uuid: '218'
    validate: '[{"validateName":"required"}]'
  - alias: fieldName
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 219
    ift: create
    inputFieldDescribeId: 0
    name: 字段名
    requestParamName: fieldName
    sessionParamName: ''
    uuid: '219'
    validate: '[{"validateName":"required"}]'
  - alias: constant
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: constant
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 220
    ift: create
    inputFieldDescribeId: 0
    name: 常量值
    requestParamName: constant
    sessionParamName: null
    uuid: '220'
    validate: null
  - alias: ct
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: ct
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 221
    ift: create
    inputFieldDescribeId: 0
    name: 条件类型
    requestParamName: ct
    sessionParamName: null
    uuid: '221'
    validate: null
  - alias: ift
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: ift
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 222
    ift: create
    inputFieldDescribeId: 0
    name: 输入类型
    requestParamName: ift
    sessionParamName: null
    uuid: '222'
    validate: null
  - alias: fvt
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fvt
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 223
    ift: create
    inputFieldDescribeId: 0
    name: 数据来源
    requestParamName: fvt
    sessionParamName: null
    uuid: '223'
    validate: null
  - alias: fromApiLegoId
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fromApiLegoId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 224
    ift: create
    inputFieldDescribeId: 0
    name: output来源id
    requestParamName: fromApiLegoId
    sessionParamName: null
    uuid: '224'
    validate: null
  - alias: alias
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 225
    ift: create
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '225'
    validate: null
  - alias: attributes
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: attributes
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 226
    ift: create
    inputFieldDescribeId: 0
    name: 属性
    requestParamName: attributes
    sessionParamName: null
    uuid: '226'
    validate: null
  - alias: validate
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: validate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 227
    ift: create
    inputFieldDescribeId: 0
    name: 校验
    requestParamName: validate
    sessionParamName: null
    uuid: '227'
    validate: null
  - alias: connectorPath
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: connectorPath
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 228
    ift: create
    inputFieldDescribeId: 0
    name: 连接器
    requestParamName: connectorPath
    sessionParamName: null
    uuid: '228'
    validate: null
  - alias: dt
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: dt
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 229
    ift: create
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: dt
    sessionParamName: null
    uuid: '229'
    validate: null
  - alias: inputFieldDescribeId
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: inputFieldDescribeId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 230
    ift: create
    inputFieldDescribeId: 0
    name: 描述id
    requestParamName: inputFieldDescribeId
    sessionParamName: null
    uuid: '230'
    validate: ''
  - alias: requestParamName
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: requestParamName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 654
    ift: create
    inputFieldDescribeId: 0
    name: 请求参数名称
    requestParamName: requestParamName
    sessionParamName: null
    uuid: '654'
    validate: ''
  - alias: sessionParamName
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: sessionParamName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 655
    ift: create
    inputFieldDescribeId: 0
    name: session参数名称
    requestParamName: sessionParamName
    sessionParamName: null
    uuid: '655'
    validate: ''
  - alias: fromApiLegoOutputFieldAlias
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fromApiLegoOutputFieldAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 656
    ift: create
    inputFieldDescribeId: 0
    name: output参数名称
    requestParamName: fromApiLegoOutputFieldAlias
    sessionParamName: null
    uuid: '656'
    validate: ''
  - alias: fieldTpl
    apiLegoId: 250
    apiLegoUuid: '250'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fieldTpl
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 8786
    ift: create
    inputFieldDescribeId: 0
    name: 字段值模板
    requestParamName: fieldTpl
    sessionParamName: null
    uuid: '8786'
    validate: null
  outputFields:
  - alias: unique_value
    apiLegoId: 250
    apiLegoUuid: '250'
    description: null
    dt: string
    fieldName: unique_value
    fieldValue: null
    handle: null
    id: 45
    name: id
    oft: create
    outputFieldDescribeId: 0
    response: true
    uuid: '45'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
