api:
  alias: add-bb
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-01T10:45:55Z
  description: 添加积木
  id: 251
  method: POST
  name: 添加积木
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: add-bb
    attributes: null
    description: ''
    id: 2406
    index: 1
    legoAlias: uniqueness
    oiAlias: ty_building_block
    processControllerAlias: null
    uuid: EA8D601E-C231-466D-9F74-C655D24C20391523876723428
  inputFields:
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: EA8D601E-C231-466D-9F74-C655D24C20391523876723428
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 18071
    ift: condition
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: ''
    uuid: 24A6E30B-4EDB-4978-842D-7FEA481B0F731523876747190
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: EA8D601E-C231-466D-9F74-C655D24C20391523876723428
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 18072
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: ACBACAF5-C034-45A5-A3E7-32EB496BA1981523876762893
    validate: null
  outputFields:
  - alias: is_unique
    apiLegoId: 0
    apiLegoUuid: EA8D601E-C231-466D-9F74-C655D24C20391523876723428
    description: ''
    dt: ''
    fieldName: is_unique
    fieldValue: null
    handle: '[{"handleName":"dataResultJudge","params":"true,别名必须唯一"}]'
    id: 2814
    name: 是否唯一
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: F07B3E67-A861-466B-82CE-10262F55A2A21523876723429
- apiLego:
    apiAlias: add-bb
    attributes: null
    description: ''
    id: 2407
    index: 2
    legoAlias: add
    oiAlias: ty_building_block
    processControllerAlias: null
    uuid: '349'
  inputFields:
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 18073
    ift: create
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: ''
    uuid: '924'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 18074
    ift: create
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: ''
    uuid: '925'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 18075
    ift: create
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: ''
    uuid: '926'
    validate: null
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 18076
    ift: create
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: ''
    uuid: '927'
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: type
    apiLegoId: 0
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 18077
    ift: create
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: ''
    uuid: '2367'
    validate: null
  - alias: icon
    apiLegoId: 0
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: icon
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 18078
    ift: create
    inputFieldDescribeId: 0
    name: 图标
    requestParamName: icon
    sessionParamName: ''
    uuid: '8986'
    validate: null
  - alias: platform
    apiLegoId: 0
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: platform
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 18079
    ift: create
    inputFieldDescribeId: 0
    name: 平台
    requestParamName: platform
    sessionParamName: ''
    uuid: '8987'
    validate: null
  - alias: tags
    apiLegoId: 0
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: tags
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 18080
    ift: create
    inputFieldDescribeId: 0
    name: 标签
    requestParamName: tags
    sessionParamName: ''
    uuid: '8988'
    validate: null
  - alias: createrId
    apiLegoId: 0
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: createrId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 18081
    ift: create
    inputFieldDescribeId: 0
    name: 创建人id
    requestParamName: createrId
    sessionParamName: ''
    uuid: '8989'
    validate: ''
  - alias: createrName
    apiLegoId: 0
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: createrName
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.xingMing}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 18082
    ift: create
    inputFieldDescribeId: 0
    name: 创建人姓名
    requestParamName: createrName
    sessionParamName: ''
    uuid: '8990'
    validate: ''
  - alias: owerId
    apiLegoId: 0
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: owerId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 18083
    ift: create
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: ''
    uuid: '8991'
    validate: ''
  - alias: owerName
    apiLegoId: 0
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: owerName
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.xingMing}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 18084
    ift: create
    inputFieldDescribeId: 0
    name: 负责人名称
    requestParamName: owerName
    sessionParamName: ''
    uuid: '8992'
    validate: ''
  - alias: interactive
    apiLegoId: null
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: interactive
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: create
    inputFieldDescribeId: null
    name: 交互
    requestParamName: interactive
    sessionParamName: null
    uuid: 10AE33F4-5608-4721-9505-53C6197696161533621508866
    validate: null
  - alias: defaultProps
    apiLegoId: null
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: defaultProps
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: create
    inputFieldDescribeId: null
    name: 默认属性
    requestParamName: defaultProps
    sessionParamName: null
    uuid: CFE18C97-92BE-484C-B4E6-5E93A04DB0F91533621508866
    validate: null
  - alias: module
    apiLegoId: null
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: boolean
    fieldName: module
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: create
    inputFieldDescribeId: null
    name: 是否模块
    requestParamName: module
    sessionParamName: null
    uuid: E74718C9-9501-4DAD-977F-F1EE2F7E802D1533984838752
    validate: null
  - alias: content
    apiLegoId: null
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: content
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: create
    inputFieldDescribeId: null
    name: 模块内容
    requestParamName: content
    sessionParamName: null
    uuid: 9CAA3520-95B8-4177-9D1D-E7040E8E94461533984838752
    validate: null
  - alias: config
    apiLegoId: null
    apiLegoUuid: '349'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: boolean
    fieldName: config
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: create
    inputFieldDescribeId: null
    name: 配置使用
    requestParamName: config
    sessionParamName: null
    uuid: 35E67D1D-5FAD-4989-AA84-C3BD2D2F44D31534836027689
    validate: null
  outputFields:
  - alias: unique_value
    apiLegoId: 0
    apiLegoUuid: '349'
    description: ''
    dt: string
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 2815
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '136'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
