api:
  alias: add-ifd
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-31T15:04:27Z
  description: 添加输入字段描述
  id: 242
  method: POST
  name: 添加输入字段描述
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: add-ifd
    attributes: null
    description: null
    id: 340
    index: 1
    legoAlias: add
    oiAlias: ty_input_field_describe
    processControllerAlias: null
    uuid: '340'
  inputFields:
  - alias: name
    apiLegoId: 340
    apiLegoUuid: '340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 876
    ift: create
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: '876'
    validate: null
  - alias: description
    apiLegoId: 340
    apiLegoUuid: '340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 877
    ift: create
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: null
    uuid: '877'
    validate: null
  - alias: legoAlias
    apiLegoId: 340
    apiLegoUuid: '340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: legoAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 878
    ift: create
    inputFieldDescribeId: 0
    name: legoAlias
    requestParamName: legoAlias
    sessionParamName: null
    uuid: '878'
    validate: null
  - alias: fieldName
    apiLegoId: 340
    apiLegoUuid: '340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: fieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 879
    ift: create
    inputFieldDescribeId: 0
    name: fieldName
    requestParamName: fieldName
    sessionParamName: null
    uuid: '879'
    validate: null
  - alias: multiple
    apiLegoId: 340
    apiLegoUuid: '340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: multiple
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 880
    ift: create
    inputFieldDescribeId: 0
    name: multiple
    requestParamName: multiple
    sessionParamName: null
    uuid: '880'
    validate: null
  - alias: ift
    apiLegoId: 340
    apiLegoUuid: '340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: ift
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 881
    ift: create
    inputFieldDescribeId: 0
    name: ift
    requestParamName: ift
    sessionParamName: null
    uuid: '881'
    validate: null
  - alias: fromOIFields
    apiLegoId: 340
    apiLegoUuid: '340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: fromOIFields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 882
    ift: create
    inputFieldDescribeId: 0
    name: fromOIFields
    requestParamName: fromOIFields
    sessionParamName: null
    uuid: '882'
    validate: null
  outputFields:
  - alias: unique_value
    apiLegoId: 340
    apiLegoUuid: '340'
    description: null
    dt: string
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 132
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 33
    response: true
    uuid: '132'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
