api:
  alias: add-batch-outputfield
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-17T11:16:05Z
  description: ''
  id: 201
  method: POST
  name: 批量添加输出字段
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: add-batch-outputfield
    attributes: null
    description: null
    id: 246
    index: 1
    legoAlias: batchSave
    oiAlias: ty_output_field
    processControllerAlias: null
    uuid: '246'
  inputFields:
  - alias: name
    apiLegoId: 246
    apiLegoUuid: '246'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 187
    ift: create
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: null
    sessionParamName: null
    uuid: '187'
    validate: null
  - alias: description
    apiLegoId: 246
    apiLegoUuid: '246'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 188
    ift: create
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: null
    sessionParamName: null
    uuid: '188'
    validate: null
  - alias: apiLegoId
    apiLegoId: 246
    apiLegoUuid: '246'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: apiLegoId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 189
    ift: create
    inputFieldDescribeId: 0
    name: apiLegoId
    requestParamName: null
    sessionParamName: null
    uuid: '189'
    validate: null
  - alias: fieldName
    apiLegoId: 246
    apiLegoUuid: '246'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 190
    ift: create
    inputFieldDescribeId: 0
    name: 字段名
    requestParamName: null
    sessionParamName: null
    uuid: '190'
    validate: null
  - alias: fieldValue
    apiLegoId: 246
    apiLegoUuid: '246'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fieldValue
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 191
    ift: create
    inputFieldDescribeId: 0
    name: 字段值
    requestParamName: null
    sessionParamName: null
    uuid: '191'
    validate: null
  - alias: oft
    apiLegoId: 246
    apiLegoUuid: '246'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: oft
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 192
    ift: create
    inputFieldDescribeId: 0
    name: 输入类型
    requestParamName: null
    sessionParamName: null
    uuid: '192'
    validate: null
  - alias: response
    apiLegoId: 246
    apiLegoUuid: '246'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: response
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 193
    ift: create
    inputFieldDescribeId: 0
    name: 是否返回前端
    requestParamName: null
    sessionParamName: null
    uuid: '193'
    validate: null
  - alias: alias
    apiLegoId: 246
    apiLegoUuid: '246'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 194
    ift: create
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: null
    sessionParamName: null
    uuid: '194'
    validate: null
  - alias: handle
    apiLegoId: 246
    apiLegoUuid: '246'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: handle
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 195
    ift: create
    inputFieldDescribeId: 0
    name: 格式化
    requestParamName: null
    sessionParamName: null
    uuid: '195'
    validate: null
  - alias: dt
    apiLegoId: 246
    apiLegoUuid: '246'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: dt
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 196
    ift: create
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: null
    sessionParamName: null
    uuid: '196'
    validate: null
  - alias: list_Param
    apiLegoId: 246
    apiLegoUuid: '246'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: list_Param
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 197
    ift: common
    inputFieldDescribeId: 0
    name: 批量添加参数
    requestParamName: list_Param
    sessionParamName: ''
    uuid: '197'
    validate: '[{"validateName":"required"}]'
  - alias: outputFieldDescribeId
    apiLegoId: 246
    apiLegoUuid: '246'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: outputFieldDescribeId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 199
    ift: create
    inputFieldDescribeId: 0
    name: 描述id
    requestParamName: null
    sessionParamName: null
    uuid: '199'
    validate: ''
  outputFields:
  - alias: list_unique_value
    apiLegoId: 246
    apiLegoUuid: '246'
    description: 主键列表，和参数顺序一样
    dt: string
    fieldName: list_unique_value
    fieldValue: null
    handle: null
    id: 42
    name: 批量添加返回参数
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '42'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
