api:
  alias: add-outputfield
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-17T11:16:05Z
  description: null
  id: 204
  method: POST
  name: 添加outputField
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: add-outputfield
    attributes: null
    description: null
    id: 251
    index: 1
    legoAlias: add
    oiAlias: ty_output_field
    processControllerAlias: null
    uuid: '251'
  inputFields:
  - alias: name
    apiLegoId: 251
    apiLegoUuid: '251'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 247
    ift: create
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '247'
    validate: null
  - alias: description
    apiLegoId: 251
    apiLegoUuid: '251'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 248
    ift: create
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '248'
    validate: null
  - alias: apiLegoId
    apiLegoId: 251
    apiLegoUuid: '251'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: apiLegoId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 249
    ift: create
    inputFieldDescribeId: 0
    name: apiLegoId
    requestParamName: apiLegoId
    sessionParamName: ''
    uuid: '249'
    validate: '[{"validateName":"required"}]'
  - alias: fieldName
    apiLegoId: 251
    apiLegoUuid: '251'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 250
    ift: create
    inputFieldDescribeId: 0
    name: 字段名
    requestParamName: fieldName
    sessionParamName: ''
    uuid: '250'
    validate: '[{"validateName":"required"}]'
  - alias: fieldValue
    apiLegoId: 251
    apiLegoUuid: '251'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fieldValue
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 251
    ift: create
    inputFieldDescribeId: 0
    name: 字段值
    requestParamName: fieldValue
    sessionParamName: null
    uuid: '251'
    validate: null
  - alias: oft
    apiLegoId: 251
    apiLegoUuid: '251'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: oft
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 252
    ift: create
    inputFieldDescribeId: 0
    name: 输入类型
    requestParamName: oft
    sessionParamName: null
    uuid: '252'
    validate: null
  - alias: response
    apiLegoId: 251
    apiLegoUuid: '251'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: response
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 253
    ift: create
    inputFieldDescribeId: 0
    name: 是否返回前端
    requestParamName: response
    sessionParamName: null
    uuid: '253'
    validate: null
  - alias: alias
    apiLegoId: 251
    apiLegoUuid: '251'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 254
    ift: create
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '254'
    validate: null
  - alias: handle
    apiLegoId: 251
    apiLegoUuid: '251'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: handle
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 255
    ift: create
    inputFieldDescribeId: 0
    name: 格式化
    requestParamName: handle
    sessionParamName: null
    uuid: '255'
    validate: null
  - alias: dt
    apiLegoId: 251
    apiLegoUuid: '251'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: dt
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 256
    ift: create
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: dt
    sessionParamName: null
    uuid: '256'
    validate: null
  - alias: outputFieldDescribeId
    apiLegoId: 251
    apiLegoUuid: '251'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: outputFieldDescribeId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 257
    ift: create
    inputFieldDescribeId: 0
    name: 描述id
    requestParamName: outputFieldDescribeId
    sessionParamName: null
    uuid: '257'
    validate: ''
  outputFields:
  - alias: unique_value
    apiLegoId: 251
    apiLegoUuid: '251'
    description: null
    dt: string
    fieldName: unique_value
    fieldValue: null
    handle: null
    id: 46
    name: id
    oft: create
    outputFieldDescribeId: 0
    response: true
    uuid: '46'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
