api:
  alias: add-lego
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-31T10:30:14Z
  description: ''
  id: 237
  method: POST
  name: 添加lego
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: add-lego
    attributes: null
    description: ''
    id: 2404
    index: 1
    legoAlias: uniqueness
    oiAlias: ty_lego
    processControllerAlias: null
    uuid: '405'
  inputFields:
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '405'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 18058
    ift: condition
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: ''
    uuid: '1141'
    validate: '[{"validateName":"required"}]'
  outputFields:
  - alias: is_unique
    apiLegoId: 0
    apiLegoUuid: '405'
    description: ''
    dt: string
    fieldName: is_unique
    fieldValue: null
    handle: '[{"handleName":"dataResultJudge","params":"true,别名必须唯一"}]'
    id: 2812
    name: 是否唯一
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: '163'
- apiLego:
    apiAlias: add-lego
    attributes: null
    description: ''
    id: 2405
    index: 2
    legoAlias: add
    oiAlias: ty_lego
    processControllerAlias: null
    uuid: '329'
  inputFields:
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '329'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 18059
    ift: create
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: '825'
    validate: '[{"validateName":"required"}]'
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '329'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 18060
    ift: create
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: '826'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '329'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 18061
    ift: create
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: ''
    uuid: '827'
    validate: '[{"validateName":"required"}]'
  - alias: supportDST
    apiLegoId: 0
    apiLegoUuid: '329'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: supportDST
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 18062
    ift: create
    inputFieldDescribeId: 0
    name: 支持的DST
    requestParamName: supportDST
    sessionParamName: ''
    uuid: '1316'
    validate: null
  - alias: icon
    apiLegoId: 0
    apiLegoUuid: '329'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: icon
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 18063
    ift: create
    inputFieldDescribeId: 0
    name: icon
    requestParamName: icon
    sessionParamName: ''
    uuid: '8942'
    validate: null
  - alias: generateSupport
    apiLegoId: 0
    apiLegoUuid: '329'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: boolean
    fieldName: generateSupport
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 18064
    ift: create
    inputFieldDescribeId: 0
    name: 支持一键生成
    requestParamName: generateSupport
    sessionParamName: ''
    uuid: '8943'
    validate: null
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: '329'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: time
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 18065
    ift: create
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: ''
    uuid: '8944'
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: createrId
    apiLegoId: 0
    apiLegoUuid: '329'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: createrId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 18066
    ift: create
    inputFieldDescribeId: 0
    name: 创建人id
    requestParamName: createrId
    sessionParamName: ''
    uuid: '8945'
    validate: ''
  - alias: createrName
    apiLegoId: 0
    apiLegoUuid: '329'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: createrName
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.xingMing}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 18067
    ift: create
    inputFieldDescribeId: 0
    name: 创建人姓名
    requestParamName: createrName
    sessionParamName: ''
    uuid: '8946'
    validate: ''
  - alias: owerId
    apiLegoId: 0
    apiLegoUuid: '329'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: owerId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 18068
    ift: create
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: ''
    uuid: '8947'
    validate: ''
  - alias: owerName
    apiLegoId: 0
    apiLegoUuid: '329'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: owerName
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.xingMing}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 18069
    ift: create
    inputFieldDescribeId: 0
    name: 负责人名称
    requestParamName: owerName
    sessionParamName: ''
    uuid: '8948'
    validate: ''
  - alias: type
    apiLegoId: 0
    apiLegoUuid: '329'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 18070
    ift: create
    inputFieldDescribeId: 0
    name: 乐高类型
    requestParamName: type
    sessionParamName: ''
    uuid: '11213'
    validate: '[{"validateName":"required"}]'
  outputFields:
  - alias: unique_value
    apiLegoId: 0
    apiLegoUuid: '329'
    description: ''
    dt: string
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 2813
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '125'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
