api:
  alias: config-list-ds-by-lego-alias
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-06-01T10:57:22Z
  description: 值获取自己能管理的数据源
  id: 1235
  method: GET
  name: 根据lego获取数据源列表(config)
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: config-list-ds-by-lego-alias
    attributes: null
    description: ''
    id: 5835
    index: 1
    legoAlias: read
    oiAlias: ty_lego
    processControllerAlias: null
    uuid: 684D75BF-F525-4823-A43C-525AE990507A1527822384907
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 684D75BF-F525-4823-A43C-525AE990507A1527822384907
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 54411
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: 1ED018FC-7617-49D9-A0C3-34AB290A37B21527822384907
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 684D75BF-F525-4823-A43C-525AE990507A1527822384907
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 54412
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: 7C586A24-232A-4372-BAE8-3D82B4FF96A31527822384907
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 684D75BF-F525-4823-A43C-525AE990507A1527822384907
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 54413
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: 5C85C35C-4DB9-4FAF-959E-95FE8245FBAA1527822384907
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 684D75BF-F525-4823-A43C-525AE990507A1527822384907
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 54414
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: FF03693F-256B-4EB4-940F-4CAA5BF27AE51527822399158
    validate: null
  - alias: supportDST
    apiLegoId: 0
    apiLegoUuid: 684D75BF-F525-4823-A43C-525AE990507A1527822384907
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: supportDST
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 54415
    ift: read
    inputFieldDescribeId: 0
    name: 支持的DST
    requestParamName: supportDST
    sessionParamName: ''
    uuid: 0D9102AE-4BF1-4BB3-83C6-51619E4D9BC11527822399158
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: 684D75BF-F525-4823-A43C-525AE990507A1527822384907
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 54416
    ift: condition
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: ''
    uuid: 938DF159-F97B-440D-8705-592811F206641527822402792
    validate: '[{"validateName":"required"}]'
  outputFields:
  - alias: data
    apiLegoId: 0
    apiLegoUuid: 684D75BF-F525-4823-A43C-525AE990507A1527822384907
    description: ''
    dt: ''
    fieldName: data
    fieldValue: null
    handle: ''
    id: 8111
    name: data
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: 0AD4D89B-4A61-434F-9BE5-54FEF37D48E81527822384908
  - alias: supportDST
    apiLegoId: 0
    apiLegoUuid: 684D75BF-F525-4823-A43C-525AE990507A1527822384907
    description: ''
    dt: string
    fieldName: supportDST
    fieldValue: null
    handle: ''
    id: 8112
    name: 支持的DST
    oft: read
    outputFieldDescribeId: 0
    response: true
    uuid: F3DBC16E-3482-484B-829F-84DC6F2A5C801527822424901
- apiLego:
    apiAlias: config-list-ds-by-lego-alias
    attributes: null
    description: ''
    id: 5836
    index: 2
    legoAlias: list
    oiAlias: ty_ds
    processControllerAlias: null
    uuid: BD06921B-EBDB-46D3-AA46-346AAC5A19DC1527822432650
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: BD06921B-EBDB-46D3-AA46-346AAC5A19DC1527822432650
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 54417
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: 24D71956-75AC-4482-A93C-C9A337EEB8201527822432651
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: BD06921B-EBDB-46D3-AA46-346AAC5A19DC1527822432650
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 54418
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: EC753319-672C-4072-9924-8B56D6B95AD41527822432651
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: BD06921B-EBDB-46D3-AA46-346AAC5A19DC1527822432650
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 54419
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: 86155453-FFCD-4119-8BEC-59B861DE3E551527822432651
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: BD06921B-EBDB-46D3-AA46-346AAC5A19DC1527822432650
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 54420
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: 329AA5A9-4ADA-41CB-888D-8ED6AEB7BA261527822432651
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: BD06921B-EBDB-46D3-AA46-346AAC5A19DC1527822432650
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 54421
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: B52AA927-D04B-4A10-9A0C-5482CD77F5161527822432651
    validate: null
  - alias: dst
    apiLegoId: 0
    apiLegoUuid: BD06921B-EBDB-46D3-AA46-346AAC5A19DC1527822432650
    attributes: null
    connectorPath: ''
    constant: ''
    ct: In
    description: ''
    dt: string
    fieldName: dst
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: supportDST
    fromApiLegoUuid: 684D75BF-F525-4823-A43C-525AE990507A1527822384907
    fvt: output
    id: 54422
    ift: condition
    inputFieldDescribeId: 0
    name: 数据源类型
    requestParamName: dst
    sessionParamName: ''
    uuid: 05553DEC-FE7A-4C4F-B8C1-F085774253701527822453560
    validate: '[{"validateName":"jsonToData"}]'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: BD06921B-EBDB-46D3-AA46-346AAC5A19DC1527822432650
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 54423
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: 95ABF91A-6C90-4442-B528-B5D26D506C4A1527822460285
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: BD06921B-EBDB-46D3-AA46-346AAC5A19DC1527822432650
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 54424
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: ''
    uuid: 01390E50-0658-4CC3-A9B8-9C3E187E8C551527822460285
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: BD06921B-EBDB-46D3-AA46-346AAC5A19DC1527822432650
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 54425
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: ''
    uuid: D4827ABD-A3DD-40F4-965B-AD4F3A5F5FA51527822460285
    validate: null
  - alias: ownerType
    apiLegoId: 0
    apiLegoUuid: BD06921B-EBDB-46D3-AA46-346AAC5A19DC1527822432650
    attributes: null
    connectorPath: '[{"alias":"ty_ds_c1"}]'
    constant: ds
    ct: eq
    description: ''
    dt: string
    fieldName: ownerType
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 54426
    ift: condition
    inputFieldDescribeId: 0
    name: 别名-ownerType
    requestParamName: ownerType
    sessionParamName: ''
    uuid: F0B4F14D-AD20-4A6D-B411-D1A3034732F21527822534006
    validate: null
  - alias: ownerCode
    apiLegoId: 0
    apiLegoUuid: BD06921B-EBDB-46D3-AA46-346AAC5A19DC1527822432650
    attributes: null
    connectorPath: '[{"alias":"ty_ds_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: ownerCode
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.alias}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 54427
    ift: condition
    inputFieldDescribeId: 0
    name: 别名-ownerCode
    requestParamName: ownerCode
    sessionParamName: ''
    uuid: D43AD478-8F84-4F6C-BE7C-520001BE16D81527822534006
    validate: null
  - alias: deleteStatus
    apiLegoId: 0
    apiLegoUuid: BD06921B-EBDB-46D3-AA46-346AAC5A19DC1527822432650
    attributes: null
    connectorPath: '[{"alias":"ty_ds_c1"}]'
    constant: '0'
    ct: eq
    description: ''
    dt: int
    fieldName: deleteStatus
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 54428
    ift: condition
    inputFieldDescribeId: 0
    name: 别名-deleteStatus
    requestParamName: deleteStatus
    sessionParamName: ''
    uuid: CE30A49A-9394-4541-964C-9A8A68ACA1B31527822534006
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 0
    apiLegoUuid: BD06921B-EBDB-46D3-AA46-346AAC5A19DC1527822432650
    description: ''
    dt: ''
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 8113
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 7148C6CD-2F3C-4900-80DD-8EB8175DFB551527822432651
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
