api:
  alias: config_oi_and_field_import
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-08-02T14:45:08Z
  description: ''
  id: 1965
  method: POST
  name: Config模型导入
  type: ty
  url: ''
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: config_oi_and_field_import
    attributes: null
    description: null
    id: null
    index: null
    legoAlias: csvRead
    oiAlias: null
    processControllerAlias: null
    uuid: 434A81C3-BFF6-4C90-B6D0-5691EC3C6BC91533192627937
  inputFields:
  - alias: csv_filestream
    apiLegoId: null
    apiLegoUuid: 434A81C3-BFF6-4C90-B6D0-5691EC3C6BC91533192627937
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: multipart
    fieldName: csv_filestream
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: common
    inputFieldDescribeId: 217
    name: csv文件流
    requestParamName: file
    sessionParamName: null
    uuid: 7BBA4B88-E734-4F59-98F6-74C174CACBDA1533192627937
    validate: null
  - alias: header_row_num
    apiLegoId: null
    apiLegoUuid: 434A81C3-BFF6-4C90-B6D0-5691EC3C6BC91533192627937
    attributes: null
    connectorPath: null
    constant: '2'
    ct: null
    description: null
    dt: null
    fieldName: header_row_num
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: null
    ift: common
    inputFieldDescribeId: 218
    name: 表头行数
    requestParamName: header_row_num
    sessionParamName: null
    uuid: CBA0B134-A19F-4931-83E1-C7DE0CEF53671533192627937
    validate: null
  outputFields:
  - alias: headers
    apiLegoId: null
    apiLegoUuid: 434A81C3-BFF6-4C90-B6D0-5691EC3C6BC91533192627937
    description: null
    dt: null
    fieldName: headers
    fieldValue: null
    handle: null
    id: null
    name: 表头数据
    oft: common
    outputFieldDescribeId: 133
    response: true
    uuid: 19D951AA-78E1-4925-A916-C8C39500016C1533192627937
  - alias: data_list
    apiLegoId: null
    apiLegoUuid: 434A81C3-BFF6-4C90-B6D0-5691EC3C6BC91533192627937
    description: null
    dt: null
    fieldName: data_list
    fieldValue: null
    handle: null
    id: null
    name: csv文件内容
    oft: common
    outputFieldDescribeId: 134
    response: true
    uuid: 93B4FDC2-639B-436C-82D0-D3A39BC435601533192627937
- apiLego:
    apiAlias: config_oi_and_field_import
    attributes: null
    description: null
    id: null
    index: null
    legoAlias: cascadeAdd
    oiAlias: ty_oi
    processControllerAlias: null
    uuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
  inputFields:
  - alias: index_data
    apiLegoId: null
    apiLegoUuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: index_data
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: data_list
    fromApiLegoUuid: 434A81C3-BFF6-4C90-B6D0-5691EC3C6BC91533192627937
    fvt: output
    id: null
    ift: common
    inputFieldDescribeId: 215
    name: 主数据源
    requestParamName: index_data
    sessionParamName: null
    uuid: A78C8405-944E-4414-95FE-C379DAC606421533195371277
    validate: null
  - alias: '0'
    apiLegoId: null
    apiLegoUuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: create
    inputFieldDescribeId: null
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: C3EDD5F9-1F1A-4AED-8ACC-A47631940D8E1533195431691
    validate: null
  - alias: '3'
    apiLegoId: null
    apiLegoUuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: create
    inputFieldDescribeId: null
    name: description
    requestParamName: description
    sessionParamName: null
    uuid: 3E66FC3C-EE8F-40C6-B3A3-3E921F6CA8DA1533195431691
    validate: null
  - alias: '1'
    apiLegoId: null
    apiLegoUuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: create
    inputFieldDescribeId: null
    name: alias
    requestParamName: alias
    sessionParamName: null
    uuid: EA6D7989-84CC-4F04-87B6-C01FE87AEBD61533195431691
    validate: null
  - alias: '2'
    apiLegoId: null
    apiLegoUuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: resource
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: create
    inputFieldDescribeId: null
    name: resource
    requestParamName: resource
    sessionParamName: null
    uuid: ACA6A2E0-1F29-4E0D-ABA4-B5D29A0F6C8A1533195431691
    validate: null
  - alias: dsAlias
    apiLegoId: null
    apiLegoUuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: dsAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: create
    inputFieldDescribeId: null
    name: dsAlias
    requestParamName: dsAlias
    sessionParamName: null
    uuid: 8854421E-59B3-4D9C-BBB1-FF0E4389CBB71533195431691
    validate: null
  - alias: '4'
    apiLegoId: null
    apiLegoUuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
    attributes: null
    connectorPath: '[{"alias":"field_oi"}]'
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: create
    inputFieldDescribeId: null
    name: alias-name(ty_field)
    requestParamName: name
    sessionParamName: null
    uuid: 6499D6EA-5BDF-412F-966B-C7E9FA1A89E31533195511311
    validate: null
  - alias: '9'
    apiLegoId: null
    apiLegoUuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
    attributes: null
    connectorPath: '[{"alias":"field_oi"}]'
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: create
    inputFieldDescribeId: null
    name: alias-description(ty_field)
    requestParamName: description
    sessionParamName: null
    uuid: B0713DB5-2B1A-46A9-B9A7-753D741ACB5F1533195511311
    validate: null
  - alias: '5'
    apiLegoId: null
    apiLegoUuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
    attributes: null
    connectorPath: '[{"alias":"field_oi"}]'
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: create
    inputFieldDescribeId: null
    name: alias-fieldName(ty_field)
    requestParamName: fieldName
    sessionParamName: null
    uuid: 044E5FE3-D979-4151-AF7A-6FF87714130B1533195511311
    validate: null
  - alias: '6'
    apiLegoId: null
    apiLegoUuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
    attributes: null
    connectorPath: '[{"alias":"field_oi"}]'
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: dt
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: create
    inputFieldDescribeId: null
    name: alias-dt(ty_field)
    requestParamName: dt
    sessionParamName: null
    uuid: 456779DE-8E0D-483C-A276-4598CB139BC51533195511311
    validate: null
  - alias: parentFieldId
    apiLegoId: null
    apiLegoUuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
    attributes: null
    connectorPath: '[{"alias":"field_oi"}]'
    constant: '0'
    ct: eq
    description: null
    dt: int
    fieldName: parentFieldId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: null
    ift: create
    inputFieldDescribeId: null
    name: alias-parentFieldId(ty_field)
    requestParamName: parentFieldId
    sessionParamName: null
    uuid: E881CFD7-42E1-4A6D-ADDE-A39ED4BC26E61533195511311
    validate: null
  - alias: '7'
    apiLegoId: null
    apiLegoUuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
    attributes: null
    connectorPath: '[{"alias":"field_oi"}]'
    constant: null
    ct: eq
    description: null
    dt: boolean
    fieldName: pk
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: create
    inputFieldDescribeId: null
    name: alias-pk(ty_field)
    requestParamName: pk
    sessionParamName: null
    uuid: 2CB5CAFF-803A-4557-92E1-87CEB1AF796B1533195511311
    validate: null
  - alias: '8'
    apiLegoId: null
    apiLegoUuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
    attributes: null
    connectorPath: '[{"alias":"field_oi"}]'
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: fieldLength
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: create
    inputFieldDescribeId: null
    name: alias-fieldLength(ty_field)
    requestParamName: fieldLength
    sessionParamName: null
    uuid: 68E75F88-CC86-4FE0-B59E-F022E105F6D01533195511311
    validate: null
  - alias: uuid
    apiLegoId: null
    apiLegoUuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
    attributes: null
    connectorPath: '[{"alias":"field_oi"}]'
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: uuid
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: create
    inputFieldDescribeId: null
    name: alias-uuid(ty_field)
    requestParamName: uuid
    sessionParamName: null
    uuid: BB1E855A-F05A-4E47-A30C-0F6A3045B92D1533195511311
    validate: '[{"validateName":"uuidAssign"}]'
  outputFields:
  - alias: unique_value_list
    apiLegoId: null
    apiLegoUuid: AC3F971A-4627-4BD5-9521-B8CB0A1A4C8E1533195371277
    description: null
    dt: null
    fieldName: unique_value_list
    fieldValue: null
    handle: null
    id: null
    name: 级联插入的唯一值列表
    oft: common
    outputFieldDescribeId: 132
    response: true
    uuid: B7C4330C-A41C-4155-91B9-DA90EFD3A7B51533195371277
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
