api:
  alias: delete-bb
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-01T15:50:37Z
  description: 删除积木
  id: 263
  method: POST
  name: 删除积木
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: delete-bb
    attributes: null
    description: null
    id: 361
    index: 1
    legoAlias: delete
    oiAlias: ty_attribute_describe
    processControllerAlias: null
    uuid: '361'
  inputFields:
  - alias: buildingBlockAlias
    apiLegoId: 361
    apiLegoUuid: '361'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: buildingBlockAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 986
    ift: condition
    inputFieldDescribeId: 0
    name: 积木别名
    requestParamName: bbAlias
    sessionParamName: null
    uuid: '986'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
- apiLego:
    apiAlias: delete-bb
    attributes: null
    description: null
    id: 362
    index: 2
    legoAlias: delete
    oiAlias: ty_event_describe
    processControllerAlias: null
    uuid: '362'
  inputFields:
  - alias: buildingBlockAlias
    apiLegoId: 362
    apiLegoUuid: '362'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: buildingBlockAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 987
    ift: condition
    inputFieldDescribeId: 0
    name: 积木别名
    requestParamName: bbAlias
    sessionParamName: null
    uuid: '987'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
- apiLego:
    apiAlias: delete-bb
    attributes: null
    description: null
    id: 363
    index: 3
    legoAlias: delete
    oiAlias: ty_method_describe
    processControllerAlias: null
    uuid: '363'
  inputFields:
  - alias: buildingBlockAlias
    apiLegoId: 363
    apiLegoUuid: '363'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: buildingBlockAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 988
    ift: condition
    inputFieldDescribeId: 0
    name: 积木别名
    requestParamName: bbAlias
    sessionParamName: null
    uuid: '988'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
- apiLego:
    apiAlias: delete-bb
    attributes: null
    description: null
    id: 364
    index: 4
    legoAlias: delete
    oiAlias: ty_building_block
    processControllerAlias: null
    uuid: '364'
  inputFields:
  - alias: alias
    apiLegoId: 364
    apiLegoUuid: '364'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 989
    ift: condition
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: bbAlias
    sessionParamName: null
    uuid: '989'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
