api:
  alias: delete-connector
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-05T15:34:10Z
  description: 删除连接器
  id: 285
  method: POST
  name: 删除连接器
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: delete-connector
    attributes: null
    description: ''
    id: 2245
    index: 1
    legoAlias: read
    oiAlias: ty_connector
    processControllerAlias: null
    uuid: BB25F45C-B796-4949-BE0A-338F23DF8B261523868117281
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: BB25F45C-B796-4949-BE0A-338F23DF8B261523868117281
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16663
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: 0A3C0B2E-A79C-4828-8994-DFFE5A50716F1523868117281
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: BB25F45C-B796-4949-BE0A-338F23DF8B261523868117281
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16664
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: 413AA551-DDF6-4343-860F-EA1D8B906CAB1523868117281
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: BB25F45C-B796-4949-BE0A-338F23DF8B261523868117281
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16665
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: F07A62DB-F532-4EAA-885E-97F08AB7A2811523868117281
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: BB25F45C-B796-4949-BE0A-338F23DF8B261523868117281
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16666
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: 8B724417-BFA3-4063-960D-C39EFBAAFFFB1523868155172
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: BB25F45C-B796-4949-BE0A-338F23DF8B261523868117281
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16667
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: FAFC354D-1A38-40C6-A11A-00554DD560401523868169489
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: BB25F45C-B796-4949-BE0A-338F23DF8B261523868117281
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16668
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: ''
    uuid: 72C2518F-5866-457B-AA6E-CCDC985037DC1523868169490
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: BB25F45C-B796-4949-BE0A-338F23DF8B261523868117281
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16669
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: ''
    uuid: 22DED422-7385-42F4-95AB-23D129FA47F31523868169490
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: BB25F45C-B796-4949-BE0A-338F23DF8B261523868117281
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16670
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: ''
    uuid: D1C54685-07C6-49F8-8FDB-3108AE00701D1523868169490
    validate: null
  - alias: fromOIAlias
    apiLegoId: 0
    apiLegoUuid: BB25F45C-B796-4949-BE0A-338F23DF8B261523868117281
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fromOIAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16671
    ift: read
    inputFieldDescribeId: 0
    name: 来源OI别名
    requestParamName: fromOIAlias
    sessionParamName: ''
    uuid: 80975048-26AC-4B96-8445-3E2F8827DC7F1523868169490
    validate: null
  - alias: fromFieldName
    apiLegoId: 0
    apiLegoUuid: BB25F45C-B796-4949-BE0A-338F23DF8B261523868117281
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fromFieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16672
    ift: read
    inputFieldDescribeId: 0
    name: 来源字段名
    requestParamName: fromFieldName
    sessionParamName: ''
    uuid: 6E4BDFD0-1360-4F74-A361-0C50AD729B031523868169490
    validate: null
  - alias: toOIAlias
    apiLegoId: 0
    apiLegoUuid: BB25F45C-B796-4949-BE0A-338F23DF8B261523868117281
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: toOIAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16673
    ift: read
    inputFieldDescribeId: 0
    name: 目标OI别名
    requestParamName: toOIAlias
    sessionParamName: ''
    uuid: D011E1B1-9EA2-495E-AE76-A4029853FF351523868169490
    validate: null
  - alias: toFieldName
    apiLegoId: 0
    apiLegoUuid: BB25F45C-B796-4949-BE0A-338F23DF8B261523868117281
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: toFieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16674
    ift: read
    inputFieldDescribeId: 0
    name: 目标字段名
    requestParamName: toFieldName
    sessionParamName: ''
    uuid: AE8F9337-32FF-43CB-858D-B01D3B79D8C31523868169490
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 0
    apiLegoUuid: BB25F45C-B796-4949-BE0A-338F23DF8B261523868117281
    description: ''
    dt: ''
    fieldName: data
    fieldValue: null
    handle: '[{"handleName":"objectToJson"}]'
    id: 2634
    name: data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 5B0F470E-5C65-4AEE-A38B-CE5C7AD4C9871523868117281
- apiLego:
    apiAlias: delete-connector
    attributes: null
    description: ''
    id: 2246
    index: 2
    legoAlias: delete
    oiAlias: ty_connector
    processControllerAlias: null
    uuid: '401'
  inputFields:
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '401'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16675
    ift: condition
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: '1127'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
- apiLego:
    apiAlias: delete-connector
    attributes: null
    description: ''
    id: 2247
    index: 3
    legoAlias: add
    oiAlias: ty_model_log
    processControllerAlias: null
    uuid: 5D05B5DC-9422-4B8E-8DAC-BD088F665FFB1523868187560
  inputFields:
  - alias: operatorId
    apiLegoId: 0
    apiLegoUuid: 5D05B5DC-9422-4B8E-8DAC-BD088F665FFB1523868187560
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: operatorId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 16676
    ift: create
    inputFieldDescribeId: 0
    name: 操作人ID
    requestParamName: operatorId
    sessionParamName: ''
    uuid: 1EF6C5FE-A6E9-4DDD-8B76-224998DB7C3C1523868197346
    validate: null
  - alias: operatorName
    apiLegoId: 0
    apiLegoUuid: 5D05B5DC-9422-4B8E-8DAC-BD088F665FFB1523868187560
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operatorName
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.xingMing}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 16677
    ift: create
    inputFieldDescribeId: 0
    name: 操作人姓名
    requestParamName: operatorName
    sessionParamName: ''
    uuid: D435755E-BD7D-42D4-AAB3-B167E8BCA9781523868197346
    validate: null
  - alias: operateDate
    apiLegoId: 0
    apiLegoUuid: 5D05B5DC-9422-4B8E-8DAC-BD088F665FFB1523868187560
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: time
    fieldName: operateDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16678
    ift: create
    inputFieldDescribeId: 0
    name: 操作时间
    requestParamName: operateDate
    sessionParamName: ''
    uuid: D16B467B-C9C9-432C-BC6E-5BAC75E369CB1523868197346
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: operateContent
    apiLegoId: 0
    apiLegoUuid: 5D05B5DC-9422-4B8E-8DAC-BD088F665FFB1523868187560
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateContent
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: data
    fromApiLegoUuid: BB25F45C-B796-4949-BE0A-338F23DF8B261523868117281
    fvt: output
    id: 16679
    ift: create
    inputFieldDescribeId: 0
    name: 详细操作内容
    requestParamName: operateContent
    sessionParamName: ''
    uuid: 5FDF2C8E-E552-4CFE-9062-92B07C6B1C641523868197346
    validate: null
  - alias: operateAlias
    apiLegoId: 0
    apiLegoUuid: 5D05B5DC-9422-4B8E-8DAC-BD088F665FFB1523868187560
    attributes: null
    connectorPath: ''
    constant: ty_connector
    ct: eq
    description: ''
    dt: string
    fieldName: operateAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 16680
    ift: create
    inputFieldDescribeId: 0
    name: 操作模型别名
    requestParamName: operateAlias
    sessionParamName: ''
    uuid: 3A38F378-125F-499C-B449-D14EED938E9D1523868197346
    validate: null
  - alias: operateDes
    apiLegoId: 0
    apiLegoUuid: 5D05B5DC-9422-4B8E-8DAC-BD088F665FFB1523868187560
    attributes: null
    connectorPath: ''
    constant: 删除连接器
    ct: eq
    description: ''
    dt: string
    fieldName: operateDes
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 16681
    ift: create
    inputFieldDescribeId: 0
    name: 操作描述
    requestParamName: operateDes
    sessionParamName: ''
    uuid: C91284DE-C8AF-4CD1-BF00-812080AFD3271523868197346
    validate: null
  outputFields:
  - alias: unique_value
    apiLegoId: 0
    apiLegoUuid: 5D05B5DC-9422-4B8E-8DAC-BD088F665FFB1523868187560
    description: ''
    dt: ''
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 2635
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: C594A671-C6A5-4C02-AD37-516B0D7C77C81523868187560
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
