api:
  alias: delete-pbb-inter
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-18T14:05:50Z
  description: 删除pbb交互接口
  id: 311
  method: POST
  name: 删除pbb交互接口
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: delete-pbb-inter
    attributes: null
    description: null
    id: 447
    index: 1
    legoAlias: delete
    oiAlias: ty_interactive
    processControllerAlias: null
    uuid: '447'
  inputFields:
  - alias: id
    apiLegoId: 447
    apiLegoUuid: '447'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1546
    ift: condition
    inputFieldDescribeId: 0
    name: 主键ID
    requestParamName: id
    sessionParamName: null
    uuid: '1546'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
