api:
  alias: delete-ofd
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-31T15:40:06Z
  description: 删除输出字段描述
  id: 249
  method: POST
  name: 删除输出字段描述
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: delete-ofd
    attributes: null
    description: null
    id: 347
    index: 1
    legoAlias: delete
    oiAlias: ty_output_field_describe
    processControllerAlias: null
    uuid: '347'
  inputFields:
  - alias: id
    apiLegoId: 347
    apiLegoUuid: '347'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 920
    ift: condition
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '920'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
