api:
  alias: delete-field
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-05T11:41:42Z
  description: 删除OI字段
  id: 280
  method: POST
  name: 删除OI字段
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: delete-field
    attributes: null
    description: ''
    id: 2217
    index: 1
    legoAlias: read
    oiAlias: ty_field
    processControllerAlias: null
    uuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16429
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: 014026FB-3DA9-431B-B589-4BFD7491843A1523867361870
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16430
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: B0822641-9BB8-46ED-9A1A-1C4E26D30A9C1523867361870
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16431
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: 5B9DF59B-2572-4C27-A116-FA7697B184941523867361871
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16432
    ift: condition
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: 7D95DF75-6016-4A25-96C4-AB80193DC3D81523867370535
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16433
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: EE5BDAC0-7B20-4BB2-8C21-5D6C0C233D2B1523867401395
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16434
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: 01E85EAF-D4DB-428F-9931-B82C1207FF5B1523867401395
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16435
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: 0CC97FA7-BF96-41D4-9609-C2D52D7309411523867401395
    validate: null
  - alias: fieldName
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16436
    ift: read
    inputFieldDescribeId: 0
    name: fieldName
    requestParamName: fieldName
    sessionParamName: ''
    uuid: 09516429-8D61-4401-A9F5-EB5A25B4FFB61523867401395
    validate: null
  - alias: oiAlias
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: oiAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16437
    ift: read
    inputFieldDescribeId: 0
    name: oiAlias
    requestParamName: oiAlias
    sessionParamName: ''
    uuid: 916E518E-131A-49F8-AD76-5CB1E058E7AE1523867401395
    validate: null
  - alias: dt
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: dt
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16438
    ift: read
    inputFieldDescribeId: 0
    name: dt
    requestParamName: dt
    sessionParamName: ''
    uuid: 2F765CB7-E0D1-429F-8346-24075501784A1523867401395
    validate: null
  - alias: parentFieldId
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: parentFieldId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16439
    ift: read
    inputFieldDescribeId: 0
    name: parentFieldId
    requestParamName: parentFieldId
    sessionParamName: ''
    uuid: 1DF6E6D5-29AA-4B60-B826-ED2CB36F886D1523867401395
    validate: null
  - alias: pk
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: boolean
    fieldName: pk
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16440
    ift: read
    inputFieldDescribeId: 0
    name: pk
    requestParamName: pk
    sessionParamName: ''
    uuid: AA7FFCD0-365B-4C63-B014-993857CB07311523867401395
    validate: null
  - alias: fieldValue
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fieldValue
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16441
    ift: read
    inputFieldDescribeId: 0
    name: fieldValue
    requestParamName: fieldValue
    sessionParamName: ''
    uuid: AF41ED17-EB11-40EE-88FF-B203302EF79F1523867401395
    validate: null
  - alias: fieldLength
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: fieldLength
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16442
    ift: read
    inputFieldDescribeId: 0
    name: fieldLength
    requestParamName: fieldLength
    sessionParamName: ''
    uuid: 7E9A4ED2-769F-4842-9D89-69CCDEF017091523867401395
    validate: null
  - alias: group
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: group
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16443
    ift: read
    inputFieldDescribeId: 0
    name: group
    requestParamName: group
    sessionParamName: ''
    uuid: 9E299D84-901B-4770-9A6E-BC7E5E3300D81523867401395
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 0
    apiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    description: ''
    dt: ''
    fieldName: data
    fieldValue: null
    handle: '[{"handleName":"objectToJson"}]'
    id: 2585
    name: data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 09F01D0B-7456-4304-83DD-36FB250D96E51523867361871
- apiLego:
    apiAlias: delete-field
    attributes: null
    description: ''
    id: 2218
    index: 2
    legoAlias: delete
    oiAlias: ty_field
    processControllerAlias: null
    uuid: '391'
  inputFields:
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '391'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16444
    ift: condition
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: '1103'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
- apiLego:
    apiAlias: delete-field
    attributes: null
    description: ''
    id: 2219
    index: 3
    legoAlias: add
    oiAlias: ty_model_log
    processControllerAlias: null
    uuid: 8BAD594C-0FC4-442D-91A2-F46DF537F4BF1523867425630
  inputFields:
  - alias: operatorId
    apiLegoId: 0
    apiLegoUuid: 8BAD594C-0FC4-442D-91A2-F46DF537F4BF1523867425630
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: operatorId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 16445
    ift: create
    inputFieldDescribeId: 0
    name: 操作人ID
    requestParamName: operatorId
    sessionParamName: ''
    uuid: DB3A609F-8F53-4BD8-BF5D-53DCDD002D051523867435760
    validate: null
  - alias: operatorName
    apiLegoId: 0
    apiLegoUuid: 8BAD594C-0FC4-442D-91A2-F46DF537F4BF1523867425630
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operatorName
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.xingMing}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 16446
    ift: create
    inputFieldDescribeId: 0
    name: 操作人姓名
    requestParamName: operatorName
    sessionParamName: ''
    uuid: C296C48A-20A2-4E85-AB1B-9398F33612931523867435760
    validate: null
  - alias: operateDate
    apiLegoId: 0
    apiLegoUuid: 8BAD594C-0FC4-442D-91A2-F46DF537F4BF1523867425630
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: time
    fieldName: operateDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16447
    ift: create
    inputFieldDescribeId: 0
    name: 操作时间
    requestParamName: operateDate
    sessionParamName: ''
    uuid: B313622F-E1E2-4FC6-9FF1-44DD45682FBB1523867435760
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: operateContent
    apiLegoId: 0
    apiLegoUuid: 8BAD594C-0FC4-442D-91A2-F46DF537F4BF1523867425630
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateContent
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: data
    fromApiLegoUuid: 228F6C47-5F4A-42AD-ADD5-08969057B7D91523867361870
    fvt: output
    id: 16448
    ift: create
    inputFieldDescribeId: 0
    name: 详细操作内容
    requestParamName: operateContent
    sessionParamName: ''
    uuid: 4EE855BB-8FDF-429E-9BCA-39389339D5CA1523867435760
    validate: null
  - alias: operateAlias
    apiLegoId: 0
    apiLegoUuid: 8BAD594C-0FC4-442D-91A2-F46DF537F4BF1523867425630
    attributes: null
    connectorPath: ''
    constant: ty_field
    ct: eq
    description: ''
    dt: string
    fieldName: operateAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 16449
    ift: create
    inputFieldDescribeId: 0
    name: 操作模型别名
    requestParamName: operateAlias
    sessionParamName: ''
    uuid: F02CC974-AE65-4B01-9CF2-F505812D79371523867435760
    validate: null
  - alias: operateDes
    apiLegoId: 0
    apiLegoUuid: 8BAD594C-0FC4-442D-91A2-F46DF537F4BF1523867425630
    attributes: null
    connectorPath: ''
    constant: 删除字段
    ct: eq
    description: ''
    dt: string
    fieldName: operateDes
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 16450
    ift: create
    inputFieldDescribeId: 0
    name: 操作描述
    requestParamName: operateDes
    sessionParamName: ''
    uuid: F7A9A47E-7C58-4456-BB30-7DFD5D3703721523867435760
    validate: null
  outputFields:
  - alias: unique_value
    apiLegoId: 0
    apiLegoUuid: 8BAD594C-0FC4-442D-91A2-F46DF537F4BF1523867425630
    description: ''
    dt: ''
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 2586
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: E86A8D4F-F557-4112-A8EE-8DB227B1CA401523867425630
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
