api:
  alias: delete-md
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-04T14:55:30Z
  description: 删除积木方法
  id: 268
  method: POST
  name: 删除积木方法
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: delete-md
    attributes: null
    description: null
    id: 370
    index: 1
    legoAlias: delete
    oiAlias: ty_method_describe
    processControllerAlias: null
    uuid: '370'
  inputFields:
  - alias: id
    apiLegoId: 370
    apiLegoUuid: '370'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1022
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '1022'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
