api:
  alias: delete-ad
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-01T11:19:24Z
  description: 删除积木属性
  id: 256
  method: POST
  name: 删除积木属性
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: delete-ad
    attributes: null
    description: null
    id: 354
    index: 1
    legoAlias: delete
    oiAlias: ty_attribute_describe
    processControllerAlias: null
    uuid: '354'
  inputFields:
  - alias: id
    apiLegoId: 354
    apiLegoUuid: '354'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 953
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '953'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
