api:
  alias: home
  authType: '["ty_auth"]'
  category: config
  content: null
  createDate: 2018-05-05T10:46:49Z
  description: 用于目前首页Home加载app列表的接口
  id: 1131
  method: GET
  name: Home页
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: home
    attributes: null
    description: ''
    id: 3755
    index: 1
    legoAlias: list
    oiAlias: ty_tenant_app
    processControllerAlias: null
    uuid: DC6B7B42-87F3-4C7A-BCC0-565ECD7BD5981525573054615
  inputFields:
  - alias: tenantSerialNumber
    apiLegoId: 0
    apiLegoUuid: DC6B7B42-87F3-4C7A-BCC0-565ECD7BD5981525573054615
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: tenantSerialNumber
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.tenantSerialNumber}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 31015
    ift: condition
    inputFieldDescribeId: 0
    name: 租户序列号
    requestParamName: tenantSerialNumber
    sessionParamName: ''
    uuid: 3688BD59-0499-4163-AAC1-F6F1866D1B521525573877470
    validate: null
  - alias: appAlias
    apiLegoId: 0
    apiLegoUuid: DC6B7B42-87F3-4C7A-BCC0-565ECD7BD5981525573054615
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: appAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 31016
    ift: read
    inputFieldDescribeId: 0
    name: app别名
    requestParamName: appAlias
    sessionParamName: ''
    uuid: F11CB931-698F-42CE-A572-698A3A446D4C1525573890579
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 0
    apiLegoUuid: DC6B7B42-87F3-4C7A-BCC0-565ECD7BD5981525573054615
    description: ''
    dt: ''
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 5082
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: B1B52B79-5B74-4577-A2D1-864B2BE80B4D1525573054615
  - alias: appAlias
    apiLegoId: 0
    apiLegoUuid: DC6B7B42-87F3-4C7A-BCC0-565ECD7BD5981525573054615
    description: ''
    dt: string
    fieldName: appAlias
    fieldValue: null
    handle: ''
    id: 5083
    name: app别名
    oft: read
    outputFieldDescribeId: 0
    response: false
    uuid: 8D60B6F4-1E50-42B2-BB5B-57EB8F7E07821525582466188
- apiLego:
    apiAlias: home
    attributes: null
    description: ''
    id: 3756
    index: 2
    legoAlias: list
    oiAlias: ty_user_app_role
    processControllerAlias: null
    uuid: 6B756064-3BAB-47C3-A383-37F64F0C525A1525578695684
  inputFields:
  - alias: userAlias
    apiLegoId: 0
    apiLegoUuid: 6B756064-3BAB-47C3-A383-37F64F0C525A1525578695684
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: userAlias
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.alias}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 31017
    ift: condition
    inputFieldDescribeId: 0
    name: userAlias
    requestParamName: userAlias
    sessionParamName: ''
    uuid: F7E26F89-3974-4F56-812B-44C0021A47031525578781601
    validate: null
  - alias: appAlias
    apiLegoId: 0
    apiLegoUuid: 6B756064-3BAB-47C3-A383-37F64F0C525A1525578695684
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: appAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 31018
    ift: read
    inputFieldDescribeId: 0
    name: appAlias
    requestParamName: appAlias
    sessionParamName: ''
    uuid: 8873F6A7-83CF-4B42-9C74-77DC4AABB18D1525578786702
    validate: null
  - alias: appAlias
    apiLegoId: 0
    apiLegoUuid: 6B756064-3BAB-47C3-A383-37F64F0C525A1525578695684
    attributes: null
    connectorPath: ''
    constant: ''
    ct: In
    description: ''
    dt: string
    fieldName: appAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: appAlias
    fromApiLegoUuid: DC6B7B42-87F3-4C7A-BCC0-565ECD7BD5981525573054615
    fvt: output
    id: 31019
    ift: condition
    inputFieldDescribeId: 0
    name: appAlias
    requestParamName: appAlias
    sessionParamName: ''
    uuid: CC898553-74E8-4DCF-9D4E-61F453A4E74A1525589474406
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 6B756064-3BAB-47C3-A383-37F64F0C525A1525578695684
    attributes: null
    connectorPath: '[{"alias":"user_app_role_to_app"}]'
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 31020
    ift: read
    inputFieldDescribeId: 0
    name: appAlias-ID
    requestParamName: id
    sessionParamName: ''
    uuid: 91B215A1-E3B5-4301-8393-2CFA7E257BE41525590117669
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: 6B756064-3BAB-47C3-A383-37F64F0C525A1525578695684
    attributes: null
    connectorPath: '[{"alias":"user_app_role_to_app"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 31021
    ift: read
    inputFieldDescribeId: 0
    name: appAlias-名称
    requestParamName: name
    sessionParamName: ''
    uuid: 2BBD189B-D809-48DE-B862-613AE7885E751525590117670
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: 6B756064-3BAB-47C3-A383-37F64F0C525A1525578695684
    attributes: null
    connectorPath: '[{"alias":"user_app_role_to_app"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 31022
    ift: read
    inputFieldDescribeId: 0
    name: appAlias-描述
    requestParamName: description
    sessionParamName: ''
    uuid: 8797DF1D-A545-407D-9F9E-B018DF3EF7BA1525590117670
    validate: null
  - alias: entrance
    apiLegoId: 0
    apiLegoUuid: 6B756064-3BAB-47C3-A383-37F64F0C525A1525578695684
    attributes: null
    connectorPath: '[{"alias":"user_app_role_to_app"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: entrance
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 31023
    ift: read
    inputFieldDescribeId: 0
    name: appAlias-入口页
    requestParamName: entrance
    sessionParamName: ''
    uuid: B84E2403-17A5-4EFE-B9C2-4199FA15BCB01525590117670
    validate: null
  - alias: icon
    apiLegoId: 0
    apiLegoUuid: 6B756064-3BAB-47C3-A383-37F64F0C525A1525578695684
    attributes: null
    connectorPath: '[{"alias":"user_app_role_to_app"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: icon
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 31024
    ift: read
    inputFieldDescribeId: 0
    name: appAlias-ICON别名
    requestParamName: icon
    sessionParamName: ''
    uuid: 87887932-BA08-4C6D-B38A-10D3F2FA74341525590117671
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: 6B756064-3BAB-47C3-A383-37F64F0C525A1525578695684
    attributes: null
    connectorPath: '[{"alias":"user_app_role_to_app"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 31025
    ift: read
    inputFieldDescribeId: 0
    name: appAlias-别名
    requestParamName: alias
    sessionParamName: ''
    uuid: E9618A63-1E8C-41F5-A099-DDE2946E605F1525590342598
    validate: null
  - alias: buzzAlias
    apiLegoId: 0
    apiLegoUuid: 6B756064-3BAB-47C3-A383-37F64F0C525A1525578695684
    attributes: null
    connectorPath: '[{"alias":"user_app_role_to_app"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: buzzAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 31026
    ift: read
    inputFieldDescribeId: 0
    name: appAlias-巴斯别名
    requestParamName: buzzAlias
    sessionParamName: ''
    uuid: 47ABA4A6-2D89-4418-BEC4-4FD3069BA2031525590342600
    validate: null
  - alias: online
    apiLegoId: 0
    apiLegoUuid: 6B756064-3BAB-47C3-A383-37F64F0C525A1525578695684
    attributes: null
    connectorPath: '[{"alias":"user_app_role_to_app"}]'
    constant: '1'
    ct: eq
    description: ''
    dt: boolean
    fieldName: online
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 31027
    ift: condition
    inputFieldDescribeId: 0
    name: 'appAlias-是否上线 '
    requestParamName: online
    sessionParamName: ''
    uuid: 5F9B01B0-C574-4A46-8CDE-0F382D2A8D4F1525601839128
    validate: null
  outputFields:
  - alias: apps
    apiLegoId: 0
    apiLegoUuid: 6B756064-3BAB-47C3-A383-37F64F0C525A1525578695684
    description: ''
    dt: ''
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 5084
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: D73FD3DD-3108-4E59-997C-A1FEDDBB860E1525578695684
  - alias: appAlias2
    apiLegoId: 0
    apiLegoUuid: 6B756064-3BAB-47C3-A383-37F64F0C525A1525578695684
    description: ''
    dt: string
    fieldName: appAlias
    fieldValue: null
    handle: ''
    id: 5085
    name: appAlias
    oft: read
    outputFieldDescribeId: 0
    response: false
    uuid: 90AADF65-0A3A-4DA0-AD28-F6B482DA19B81525582486104
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
