api:
  alias: list-oi-and-conn-by-ds
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-05T17:20:04Z
  description: 查询ds下的oi和连接器
  id: 290
  method: GET
  name: 查询ds下的oi和连接器
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: list-oi-and-conn-by-ds
    attributes: null
    description: ''
    id: 1921
    index: 1
    legoAlias: list
    oiAlias: ty_oi
    processControllerAlias: null
    uuid: '408'
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '408'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 13949
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '1155'
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '408'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 13950
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '1156'
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '408'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 13951
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '1157'
    validate: null
  - alias: dsAlias
    apiLegoId: 0
    apiLegoUuid: '408'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: dsAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 13952
    ift: condition
    inputFieldDescribeId: 0
    name: dsAlias
    requestParamName: dsAlias
    sessionParamName: ''
    uuid: '1158'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '408'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 13953
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: '1159'
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '408'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 13954
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: '1160'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '408'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 13955
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: '1161'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '408'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 13956
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: ''
    uuid: '1162'
    validate: null
  - alias: resource
    apiLegoId: 0
    apiLegoUuid: '408'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: resource
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 13957
    ift: read
    inputFieldDescribeId: 0
    name: resource
    requestParamName: resource
    sessionParamName: ''
    uuid: '1163'
    validate: null
  - alias: dsAlias
    apiLegoId: 0
    apiLegoUuid: '408'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: dsAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 13958
    ift: read
    inputFieldDescribeId: 0
    name: dsAlias
    requestParamName: dsAlias
    sessionParamName: ''
    uuid: '1164'
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 0
    apiLegoUuid: '408'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 2253
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '166'
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '408'
    description: ''
    dt: string
    fieldName: alias
    fieldValue: null
    handle: ''
    id: 2254
    name: alias
    oft: read
    outputFieldDescribeId: 0
    response: true
    uuid: '167'
- apiLego:
    apiAlias: list-oi-and-conn-by-ds
    attributes: null
    description: ''
    id: 1922
    index: 2
    legoAlias: list
    oiAlias: ty_connector
    processControllerAlias: null
    uuid: '409'
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '409'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 13959
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '1165'
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '409'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 13960
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '1166'
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '409'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 13961
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '1167'
    validate: null
  - alias: fromOIAlias
    apiLegoId: 0
    apiLegoUuid: '409'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: In
    description: ''
    dt: string
    fieldName: fromOIAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: alias
    fromApiLegoUuid: '408'
    fvt: output
    id: 13962
    ift: condition
    inputFieldDescribeId: 0
    name: fromOIAlias
    requestParamName: fromOIAlias
    sessionParamName: ''
    uuid: '1168'
    validate: ''
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '409'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 13963
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: '1169'
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '409'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 13964
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: '1170'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '409'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 13965
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: '1171'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '409'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 13966
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: ''
    uuid: '1172'
    validate: null
  - alias: fromOIAlias
    apiLegoId: 0
    apiLegoUuid: '409'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: fromOIAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 13967
    ift: read
    inputFieldDescribeId: 0
    name: fromOIAlias
    requestParamName: fromOIAlias
    sessionParamName: ''
    uuid: '1173'
    validate: null
  - alias: fromFieldName
    apiLegoId: 0
    apiLegoUuid: '409'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: fromFieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 13968
    ift: read
    inputFieldDescribeId: 0
    name: fromFieldName
    requestParamName: fromFieldName
    sessionParamName: ''
    uuid: '1174'
    validate: null
  - alias: toOIAlias
    apiLegoId: 0
    apiLegoUuid: '409'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: toOIAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 13969
    ift: read
    inputFieldDescribeId: 0
    name: toOIAlias
    requestParamName: toOIAlias
    sessionParamName: ''
    uuid: '1175'
    validate: null
  - alias: toFieldName
    apiLegoId: 0
    apiLegoUuid: '409'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: toFieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 13970
    ift: read
    inputFieldDescribeId: 0
    name: toFieldName
    requestParamName: toFieldName
    sessionParamName: ''
    uuid: '1176'
    validate: null
  outputFields:
  - alias: conn_list
    apiLegoId: 0
    apiLegoUuid: '409'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 2255
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '168'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
