api:
  alias: list-lego
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-07T16:14:44Z
  description: 查询所有lego
  id: 17
  method: POST
  name: 查询所有lego
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: list-lego
    attributes: ''
    description: null
    id: 25
    index: 1
    legoAlias: list
    oiAlias: ty_lego
    processControllerAlias: null
    uuid: '25'
  inputFields:
  - alias: id
    apiLegoId: 25
    apiLegoUuid: '25'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 56
    ift: read
    inputFieldDescribeId: 0
    name: legoID
    requestParamName: null
    sessionParamName: null
    uuid: '56'
    validate: ''
  - alias: alias
    apiLegoId: 25
    apiLegoUuid: '25'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 57
    ift: read
    inputFieldDescribeId: 0
    name: lego别名
    requestParamName: null
    sessionParamName: null
    uuid: '57'
    validate: ''
  - alias: name
    apiLegoId: 25
    apiLegoUuid: '25'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 58
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: null
    sessionParamName: null
    uuid: '58'
    validate: ''
  - alias: description
    apiLegoId: 25
    apiLegoUuid: '25'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1121
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: null
    uuid: '1121'
    validate: null
  - alias: global_search_fields
    apiLegoId: 25
    apiLegoUuid: '25'
    attributes: ''
    connectorPath: ''
    constant: '["name"]'
    ct: eq
    description: ''
    dt: string
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 1288
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '1288'
    validate: ''
  - alias: keywords
    apiLegoId: 25
    apiLegoUuid: '25'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 1289
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '1289'
    validate: ''
  - alias: supportDST
    apiLegoId: 25
    apiLegoUuid: '25'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: supportDST
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1314
    ift: read
    inputFieldDescribeId: 0
    name: 支持的DST
    requestParamName: supportDST
    sessionParamName: null
    uuid: '1314'
    validate: null
  - alias: icon
    apiLegoId: 25
    apiLegoUuid: '25'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: icon
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 6563
    ift: read
    inputFieldDescribeId: 0
    name: icon
    requestParamName: icon
    sessionParamName: null
    uuid: '6563'
    validate: null
  - alias: useNum
    apiLegoId: 25
    apiLegoUuid: '25'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: useNum
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 6564
    ift: read
    inputFieldDescribeId: 0
    name: 使用数量
    requestParamName: useNum
    sessionParamName: null
    uuid: '6564'
    validate: null
  - alias: createDate
    apiLegoId: 25
    apiLegoUuid: '25'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: time
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8957
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: null
    uuid: '8957'
    validate: null
  - alias: createrId
    apiLegoId: 25
    apiLegoUuid: '25'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: createrId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8958
    ift: read
    inputFieldDescribeId: 0
    name: 创建人id
    requestParamName: createrId
    sessionParamName: null
    uuid: '8958'
    validate: null
  - alias: createrName
    apiLegoId: 25
    apiLegoUuid: '25'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: createrName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8959
    ift: read
    inputFieldDescribeId: 0
    name: 创建人姓名
    requestParamName: createrName
    sessionParamName: null
    uuid: '8959'
    validate: null
  - alias: owerId
    apiLegoId: 25
    apiLegoUuid: '25'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: owerId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8960
    ift: read
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: null
    uuid: '8960'
    validate: null
  - alias: owerName
    apiLegoId: 25
    apiLegoUuid: '25'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: owerName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8961
    ift: read
    inputFieldDescribeId: 0
    name: 负责人名称
    requestParamName: owerName
    sessionParamName: null
    uuid: '8961'
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 25
    apiLegoUuid: '25'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 25
    name: 查询数据
    oft: ''
    outputFieldDescribeId: 0
    response: true
    uuid: '25'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
