api:
  alias: list-oi-by-ds
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-14T14:57:19Z
  description: ''
  id: 126
  method: GET
  name: 查询某个ds下的oi
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: list-oi-by-ds
    attributes: null
    description: null
    id: 137
    index: 1
    legoAlias: list
    oiAlias: ty_oi
    processControllerAlias: null
    uuid: '137'
  inputFields:
  - alias: id
    apiLegoId: 137
    apiLegoUuid: '137'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 125
    ift: read
    inputFieldDescribeId: 0
    name: 主键id
    requestParamName: null
    sessionParamName: null
    uuid: '125'
    validate: null
  - alias: name
    apiLegoId: 137
    apiLegoUuid: '137'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 126
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: null
    sessionParamName: null
    uuid: '126'
    validate: null
  - alias: description
    apiLegoId: 137
    apiLegoUuid: '137'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 127
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: null
    sessionParamName: null
    uuid: '127'
    validate: null
  - alias: alias
    apiLegoId: 137
    apiLegoUuid: '137'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 128
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: null
    sessionParamName: null
    uuid: '128'
    validate: null
  - alias: resource
    apiLegoId: 137
    apiLegoUuid: '137'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: resource
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 129
    ift: read
    inputFieldDescribeId: 0
    name: 资源
    requestParamName: null
    sessionParamName: null
    uuid: '129'
    validate: null
  - alias: dsAlias
    apiLegoId: 137
    apiLegoUuid: '137'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: dsAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 130
    ift: read
    inputFieldDescribeId: 0
    name: ds别名
    requestParamName: null
    sessionParamName: null
    uuid: '130'
    validate: null
  - alias: dsAlias
    apiLegoId: 137
    apiLegoUuid: '137'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: dsAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 131
    ift: condition
    inputFieldDescribeId: 0
    name: ds条件
    requestParamName: dsAlias
    sessionParamName: ''
    uuid: '131'
    validate: '[{"validateName":"required"}]'
  - alias: global_search_fields
    apiLegoId: 137
    apiLegoUuid: '137'
    attributes: ''
    connectorPath: ''
    constant: '["name","alias","dsAlias"]'
    ct: eq
    description: ''
    dt: string
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 1300
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '1300'
    validate: ''
  - alias: keywords
    apiLegoId: 137
    apiLegoUuid: '137'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 1301
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '1301'
    validate: ''
  - alias: order_field
    apiLegoId: 137
    apiLegoUuid: '137'
    attributes: null
    connectorPath: ''
    constant: alias
    ct: eq
    description: null
    dt: string
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 5898
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: ''
    sessionParamName: null
    uuid: '5898'
    validate: ''
  - alias: order
    apiLegoId: 137
    apiLegoUuid: '137'
    attributes: null
    connectorPath: ''
    constant: ASC
    ct: eq
    description: null
    dt: string
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 5899
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: ''
    sessionParamName: null
    uuid: '5899'
    validate: ''
  outputFields:
  - alias: data_list
    apiLegoId: 137
    apiLegoUuid: '137'
    description: null
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: null
    id: 35
    name: 输出数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '35'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
