api:
  alias: list-ds
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-07T16:48:26Z
  description: ds
  id: 18
  method: POST
  name: 查询所有ds
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: list-ds
    attributes: null
    description: ''
    id: 5743
    index: 1
    legoAlias: list
    oiAlias: ty_ds
    processControllerAlias: null
    uuid: '26'
  inputFields:
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 53394
    ift: read
    inputFieldDescribeId: 0
    name: 主键id
    requestParamName: ''
    sessionParamName: ''
    uuid: '59'
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 53395
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: ''
    sessionParamName: ''
    uuid: '60'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 53396
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: ''
    sessionParamName: ''
    uuid: '61'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 53397
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: ''
    sessionParamName: ''
    uuid: '62'
    validate: null
  - alias: dst
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: dst
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 53398
    ift: read
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: ''
    sessionParamName: ''
    uuid: '63'
    validate: null
  - alias: connectionUrl
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: connectionUrl
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 53399
    ift: read
    inputFieldDescribeId: 0
    name: 链接地址
    requestParamName: ''
    sessionParamName: ''
    uuid: '64'
    validate: null
  - alias: connectionUsername
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: connectionUsername
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 53400
    ift: read
    inputFieldDescribeId: 0
    name: 链接用户名
    requestParamName: ''
    sessionParamName: ''
    uuid: '65'
    validate: null
  - alias: connectionPassword
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: connectionPassword
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 53401
    ift: read
    inputFieldDescribeId: 0
    name: 链接密码
    requestParamName: ''
    sessionParamName: ''
    uuid: '66'
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: '["name","alias","description"]'
    ct: eq
    description: ''
    dt: string
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 53402
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '1290'
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 53403
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '1291'
    validate: null
  - alias: dsConfigFrom
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: dsConfigFrom
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53404
    ift: read
    inputFieldDescribeId: 0
    name: 数据库链接来源
    requestParamName: dsConfigFrom
    sessionParamName: ''
    uuid: '8911'
    validate: null
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: time
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53405
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: ''
    uuid: '8912'
    validate: null
  - alias: createrId
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: createrId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53406
    ift: read
    inputFieldDescribeId: 0
    name: 创建人id
    requestParamName: createrId
    sessionParamName: ''
    uuid: '8913'
    validate: null
  - alias: createrName
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: createrName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53407
    ift: read
    inputFieldDescribeId: 0
    name: 创建人姓名
    requestParamName: createrName
    sessionParamName: ''
    uuid: '8914'
    validate: null
  - alias: owerId
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: owerId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53408
    ift: read
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: ''
    uuid: '8915'
    validate: null
  - alias: owerName
    apiLegoId: 0
    apiLegoUuid: '26'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: owerName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53409
    ift: read
    inputFieldDescribeId: 0
    name: 负责人名称
    requestParamName: owerName
    sessionParamName: ''
    uuid: '8916'
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 0
    apiLegoUuid: '26'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 8005
    name: 输出数据
    oft: ''
    outputFieldDescribeId: 0
    response: true
    uuid: '26'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
