api:
  alias: list-adByBBAliasAndParentId
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-01T16:01:31Z
  description: 根据积木别名和父ID获取属性列表
  id: 264
  method: GET
  name: 根据积木别名和父ID获取属性列表
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: list-adByBBAliasAndParentId
    attributes: null
    description: ''
    id: 2664
    index: 1
    legoAlias: list
    oiAlias: ty_attribute_describe
    processControllerAlias: null
    uuid: '365'
  inputFields:
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '365'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20713
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '990'
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '365'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20714
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: ''
    uuid: '991'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '365'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20715
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: ''
    uuid: '992'
    validate: null
  - alias: buildingBlockAlias
    apiLegoId: 0
    apiLegoUuid: '365'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: buildingBlockAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20716
    ift: read
    inputFieldDescribeId: 0
    name: 积木别名
    requestParamName: buildingBlockAlias
    sessionParamName: ''
    uuid: '993'
    validate: null
  - alias: attributeName
    apiLegoId: 0
    apiLegoUuid: '365'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: attributeName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20717
    ift: read
    inputFieldDescribeId: 0
    name: 属性名
    requestParamName: attributeName
    sessionParamName: ''
    uuid: '994'
    validate: null
  - alias: dt
    apiLegoId: 0
    apiLegoUuid: '365'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: dt
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20718
    ift: read
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: dt
    sessionParamName: ''
    uuid: '995'
    validate: null
  - alias: parentId
    apiLegoId: 0
    apiLegoUuid: '365'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: parentId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20719
    ift: read
    inputFieldDescribeId: 0
    name: 父级id
    requestParamName: parentId
    sessionParamName: ''
    uuid: '996'
    validate: null
  - alias: et
    apiLegoId: 0
    apiLegoUuid: '365'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: et
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20720
    ift: read
    inputFieldDescribeId: 0
    name: 编辑器类型
    requestParamName: et
    sessionParamName: ''
    uuid: '997'
    validate: null
  - alias: buildingBlockAlias
    apiLegoId: 0
    apiLegoUuid: '365'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: buildingBlockAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 20721
    ift: condition
    inputFieldDescribeId: 0
    name: 积木别名
    requestParamName: bbAlias
    sessionParamName: ''
    uuid: '998'
    validate: '[{"validateName":"required"}]'
  - alias: parentId
    apiLegoId: 0
    apiLegoUuid: '365'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: parentId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 20722
    ift: condition
    inputFieldDescribeId: 0
    name: 父级id
    requestParamName: parentId
    sessionParamName: ''
    uuid: '999'
    validate: '[{"validateName":"required"}]'
  - alias: etData
    apiLegoId: 0
    apiLegoUuid: '365'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: etData
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20723
    ift: read
    inputFieldDescribeId: 0
    name: 编辑器数据
    requestParamName: etData
    sessionParamName: ''
    uuid: '1417'
    validate: null
  - alias: etProps
    apiLegoId: 0
    apiLegoUuid: '365'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: etProps
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20724
    ift: read
    inputFieldDescribeId: 0
    name: 编辑器属性
    requestParamName: etProps
    sessionParamName: ''
    uuid: '1970'
    validate: null
  - alias: rules
    apiLegoId: 0
    apiLegoUuid: '365'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: rules
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20725
    ift: read
    inputFieldDescribeId: 0
    name: 规则
    requestParamName: rules
    sessionParamName: ''
    uuid: 14A60B82-DF4C-4818-9C43-A98D80B807E71524018719830
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 0
    apiLegoUuid: '365'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 3146
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '143'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
