api:
  alias: list-adByBbAlias
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-01T11:14:14Z
  description: 查询积木的属性列表
  id: 252
  method: GET
  name: 查询积木的属性列表
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: list-adByBbAlias
    attributes: null
    description: ''
    id: 3546
    index: 1
    legoAlias: list
    oiAlias: ty_attribute_describe
    processControllerAlias: null
    uuid: '350'
  inputFields:
  - alias: buildingBlockAlias
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: buildingBlockAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 29698
    ift: condition
    inputFieldDescribeId: 0
    name: 积木别名
    requestParamName: bbAlias
    sessionParamName: ''
    uuid: '928'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29699
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '929'
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29700
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: ''
    uuid: '930'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29701
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: ''
    uuid: '931'
    validate: null
  - alias: buildingBlockAlias
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: buildingBlockAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29702
    ift: read
    inputFieldDescribeId: 0
    name: 积木别名
    requestParamName: buildingBlockAlias
    sessionParamName: ''
    uuid: '932'
    validate: null
  - alias: attributeName
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: attributeName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29703
    ift: read
    inputFieldDescribeId: 0
    name: 属性名
    requestParamName: attributeName
    sessionParamName: ''
    uuid: '933'
    validate: null
  - alias: dt
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: dt
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29704
    ift: read
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: dt
    sessionParamName: ''
    uuid: '934'
    validate: null
  - alias: parentId
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: parentId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29705
    ift: read
    inputFieldDescribeId: 0
    name: 父级id
    requestParamName: parentId
    sessionParamName: ''
    uuid: '935'
    validate: null
  - alias: et
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: et
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29706
    ift: read
    inputFieldDescribeId: 0
    name: 编辑器类型
    requestParamName: et
    sessionParamName: ''
    uuid: '936'
    validate: null
  - alias: etData
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: etData
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29707
    ift: read
    inputFieldDescribeId: 0
    name: 编辑器数据
    requestParamName: etData
    sessionParamName: ''
    uuid: '1419'
    validate: null
  - alias: etProps
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: etProps
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 29708
    ift: read
    inputFieldDescribeId: 0
    name: 编辑器属性
    requestParamName: etProps
    sessionParamName: ''
    uuid: '1967'
    validate: ''
  - alias: type
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29709
    ift: read
    inputFieldDescribeId: 0
    name: 积木属性类型
    requestParamName: type
    sessionParamName: ''
    uuid: '11176'
    validate: null
  - alias: sort
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: sort
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29710
    ift: read
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: sort
    sessionParamName: ''
    uuid: '11177'
    validate: null
  - alias: rules
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: rules
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29711
    ift: read
    inputFieldDescribeId: 0
    name: 规则
    requestParamName: rules
    sessionParamName: ''
    uuid: D2515702-E0E6-4EFE-BD54-33B86642F6251524018694085
    validate: null
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: sort
    ct: eq
    description: ''
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 29712
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: ''
    sessionParamName: ''
    uuid: D2D23047-0A07-43C5-A763-C429D2D086C71524901165985
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: ASC
    ct: eq
    description: ''
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 29713
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: ''
    sessionParamName: ''
    uuid: 8419A9F1-743D-4BC1-8C36-1A89DC1E7EC91524901183574
    validate: null
  - alias: disabled
    apiLegoId: null
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: boolean
    fieldName: disabled
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: read
    inputFieldDescribeId: null
    name: 禁用
    requestParamName: disabled
    sessionParamName: null
    uuid: 1F48E42A-B7CB-41A9-8EE4-60BE99B83CCA1533801555433
    validate: null
  - alias: supportXCX
    apiLegoId: null
    apiLegoUuid: '350'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: boolean
    fieldName: supportXCX
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: read
    inputFieldDescribeId: null
    name: 支持小程序
    requestParamName: supportXCX
    sessionParamName: null
    uuid: 915B9AB5-9E31-4B07-8228-94AD39E1CCC21533801555433
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 0
    apiLegoUuid: '350'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 4728
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '137'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
