api:
  alias: list-page
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-28T11:46:47Z
  description: ''
  id: 224
  method: GET
  name: 列出所有Page
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: list-page
    attributes: null
    description: null
    id: 760
    index: 2
    legoAlias: list
    oiAlias: ty_page
    processControllerAlias: null
    uuid: '760'
  inputFields:
  - alias: order_field
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: id
    ct: eq
    description: null
    dt: string
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 4153
    ift: common
    inputFieldDescribeId: 31
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '4153'
    validate: ''
  - alias: order
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: DESC
    ct: eq
    description: null
    dt: string
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 4154
    ift: common
    inputFieldDescribeId: 42
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '4154'
    validate: ''
  - alias: group_field
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 4155
    ift: common
    inputFieldDescribeId: 43
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '4155'
    validate: null
  - alias: keywords
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 4156
    ift: common
    inputFieldDescribeId: 51
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '4156'
    validate: ''
  - alias: global_search_fields
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: '["name"]'
    ct: eq
    description: null
    dt: string
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 4157
    ift: common
    inputFieldDescribeId: 52
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '4157'
    validate: ''
  - alias: id
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4158
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '4158'
    validate: null
  - alias: name
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4159
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '4159'
    validate: null
  - alias: description
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4160
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '4160'
    validate: null
  - alias: alias
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4161
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '4161'
    validate: null
  - alias: createDate
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4162
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: null
    uuid: '4162'
    validate: null
  - alias: template
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: template
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4163
    ift: read
    inputFieldDescribeId: 0
    name: 是否模板
    requestParamName: template
    sessionParamName: null
    uuid: '4163'
    validate: null
  - alias: templatePageAlias
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: templatePageAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4164
    ift: read
    inputFieldDescribeId: 0
    name: 所属模板
    requestParamName: templatePageAlias
    sessionParamName: null
    uuid: '4164'
    validate: null
  - alias: custom
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: custom
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4165
    ift: read
    inputFieldDescribeId: 0
    name: 定制化
    requestParamName: custom
    sessionParamName: null
    uuid: '4165'
    validate: null
  - alias: customFile
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: customFile
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4166
    ift: read
    inputFieldDescribeId: 0
    name: 定制文件
    requestParamName: customFile
    sessionParamName: null
    uuid: '4166'
    validate: null
  - alias: appAlias
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: appAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4167
    ift: read
    inputFieldDescribeId: 0
    name: 应用别名
    requestParamName: appAlias
    sessionParamName: null
    uuid: '4167'
    validate: null
  - alias: parentId
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: parentId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4168
    ift: read
    inputFieldDescribeId: 0
    name: 父ID
    requestParamName: parentId
    sessionParamName: null
    uuid: '4168'
    validate: null
  - alias: enable
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: enable
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4169
    ift: read
    inputFieldDescribeId: 0
    name: 是否可用
    requestParamName: enable
    sessionParamName: null
    uuid: '4169'
    validate: null
  - alias: type
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: type
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4170
    ift: read
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: null
    uuid: '4170'
    validate: null
  - alias: appAlias
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: appAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4171
    ift: condition
    inputFieldDescribeId: 0
    name: 应用别名
    requestParamName: appAlias
    sessionParamName: null
    uuid: '4171'
    validate: ''
  - alias: icon
    apiLegoId: 760
    apiLegoUuid: '760'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: icon
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5159
    ift: read
    inputFieldDescribeId: 0
    name: icon
    requestParamName: icon
    sessionParamName: null
    uuid: '5159'
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 760
    apiLegoUuid: '760'
    description: null
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 792
    name: 列表数据
    oft: common
    outputFieldDescribeId: 31
    response: true
    uuid: '792'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
