api:
  alias: list-api-res
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-29T14:01:22Z
  description: ''
  id: 226
  method: POST
  name: 获取接口响应
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: list-api-res
    attributes: null
    description: null
    id: 317
    index: 1
    legoAlias: list
    oiAlias: ty_output_field
    processControllerAlias: null
    uuid: '317'
  inputFields:
  - alias: apiLegoId
    apiLegoId: 317
    apiLegoUuid: '317'
    attributes: null
    connectorPath: ''
    constant: null
    ct: In
    description: null
    dt: string
    fieldName: apiLegoId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 748
    ift: condition
    inputFieldDescribeId: 0
    name: apiLegoId
    requestParamName: apiLegoId
    sessionParamName: null
    uuid: '748'
    validate: ''
  - alias: response
    apiLegoId: 317
    apiLegoUuid: '317'
    attributes: ''
    connectorPath: ''
    constant: '1'
    ct: eq
    description: ''
    dt: string
    fieldName: response
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 749
    ift: condition
    inputFieldDescribeId: 0
    name: response
    requestParamName: response
    sessionParamName: ''
    uuid: '749'
    validate: ''
  - alias: id
    apiLegoId: 317
    apiLegoUuid: '317'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 750
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '750'
    validate: null
  - alias: name
    apiLegoId: 317
    apiLegoUuid: '317'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 751
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: '751'
    validate: null
  - alias: description
    apiLegoId: 317
    apiLegoUuid: '317'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 752
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: null
    uuid: '752'
    validate: null
  - alias: apiLegoId
    apiLegoId: 317
    apiLegoUuid: '317'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: apiLegoId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 753
    ift: read
    inputFieldDescribeId: 0
    name: apiLegoId
    requestParamName: apiLegoId
    sessionParamName: null
    uuid: '753'
    validate: null
  - alias: fieldName
    apiLegoId: 317
    apiLegoUuid: '317'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: fieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 754
    ift: read
    inputFieldDescribeId: 0
    name: fieldName
    requestParamName: fieldName
    sessionParamName: null
    uuid: '754'
    validate: null
  - alias: oft
    apiLegoId: 317
    apiLegoUuid: '317'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: oft
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 755
    ift: read
    inputFieldDescribeId: 0
    name: oft
    requestParamName: oft
    sessionParamName: null
    uuid: '755'
    validate: null
  - alias: response
    apiLegoId: 317
    apiLegoUuid: '317'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: response
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 756
    ift: read
    inputFieldDescribeId: 0
    name: response
    requestParamName: response
    sessionParamName: null
    uuid: '756'
    validate: null
  - alias: alias
    apiLegoId: 317
    apiLegoUuid: '317'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 757
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: null
    uuid: '757'
    validate: null
  - alias: dt
    apiLegoId: 317
    apiLegoUuid: '317'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: dt
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 758
    ift: read
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: dt
    sessionParamName: null
    uuid: '758'
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 317
    apiLegoUuid: '317'
    description: null
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 116
    name: 列表数据
    oft: common
    outputFieldDescribeId: 31
    response: true
    uuid: '116'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
