api:
  alias: list-ds-by-dst-self
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-07T17:30:19Z
  description: 获取我的ds列表根据dst
  id: 660
  method: GET
  name: 获取我的ds列表根据dst
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: list-ds-by-dst-self
    attributes: null
    description: ''
    id: 5703
    index: 1
    legoAlias: list
    oiAlias: ty_owner
    processControllerAlias: null
    uuid: 908A57C5-BE5E-499B-85F8-93610018E6631527670625063
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 908A57C5-BE5E-499B-85F8-93610018E6631527670625063
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52761
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: B2790E82-A434-451A-9024-50BB727D1C5F1527670625063
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 908A57C5-BE5E-499B-85F8-93610018E6631527670625063
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52762
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: 63A83D70-341E-475B-8BAE-9A77D963096A1527670625063
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 908A57C5-BE5E-499B-85F8-93610018E6631527670625063
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52763
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: F30F943A-8EE4-4CA4-949F-EB32D17D4C9D1527670625063
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: 908A57C5-BE5E-499B-85F8-93610018E6631527670625063
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52764
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: 861B62E7-3CE0-4E23-B2E6-7C2DC14C26751527670625063
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: 908A57C5-BE5E-499B-85F8-93610018E6631527670625063
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52765
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: BEDC7707-6528-4F73-B73E-7C9089B9E24F1527670625063
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: 908A57C5-BE5E-499B-85F8-93610018E6631527670625063
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52766
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: ''
    uuid: 7E04DAD1-42D5-42AD-A98D-53E5C8813B2D1527670672016
    validate: null
  - alias: ownerCode
    apiLegoId: 0
    apiLegoUuid: 908A57C5-BE5E-499B-85F8-93610018E6631527670625063
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: ownerCode
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.alias}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 52767
    ift: condition
    inputFieldDescribeId: 0
    name: ownerCode
    requestParamName: ownerCode
    sessionParamName: ''
    uuid: 77B4AB6E-7981-47B3-A418-22387F3EF89F1527670679639
    validate: null
  - alias: deleteStatus
    apiLegoId: 0
    apiLegoUuid: 908A57C5-BE5E-499B-85F8-93610018E6631527670625063
    attributes: null
    connectorPath: ''
    constant: '0'
    ct: eq
    description: ''
    dt: int
    fieldName: deleteStatus
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 52768
    ift: condition
    inputFieldDescribeId: 0
    name: deleteStatus
    requestParamName: deleteStatus
    sessionParamName: ''
    uuid: 4AE1822C-8A4B-434E-8CD9-33A0BC06C0A71527670679639
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 0
    apiLegoUuid: 908A57C5-BE5E-499B-85F8-93610018E6631527670625063
    description: ''
    dt: ''
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 7958
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: 3795FD9A-35D6-4F83-A2B8-25DEBA52C5FC1527670625064
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: 908A57C5-BE5E-499B-85F8-93610018E6631527670625063
    description: ''
    dt: string
    fieldName: alias
    fieldValue: null
    handle: ''
    id: 7959
    name: alias
    oft: read
    outputFieldDescribeId: 0
    response: true
    uuid: E2762834-5FCA-46B7-BF76-4BD5CD3970A41527670712123
- apiLego:
    apiAlias: list-ds-by-dst-self
    attributes: null
    description: ''
    id: 5704
    index: 2
    legoAlias: list
    oiAlias: ty_ds
    processControllerAlias: null
    uuid: '1312'
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '1312'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 52769
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '9247'
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '1312'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 52770
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '9248'
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '1312'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 52771
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '9249'
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '1312'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 52772
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '9250'
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '1312'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 52773
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '9251'
    validate: null
  - alias: dst
    apiLegoId: 0
    apiLegoUuid: '1312'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: In
    description: ''
    dt: string
    fieldName: dst
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 52774
    ift: condition
    inputFieldDescribeId: 0
    name: dst
    requestParamName: dst
    sessionParamName: ''
    uuid: '9252'
    validate: ''
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '1312'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52775
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: '9253'
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '1312'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52776
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: '9254'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '1312'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52777
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: '9255'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '1312'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52778
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: ''
    uuid: '9256'
    validate: null
  - alias: dst
    apiLegoId: 0
    apiLegoUuid: '1312'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: dst
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52779
    ift: read
    inputFieldDescribeId: 0
    name: dst
    requestParamName: dst
    sessionParamName: ''
    uuid: '9257'
    validate: null
  - alias: connectionUrl
    apiLegoId: 0
    apiLegoUuid: '1312'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: connectionUrl
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52780
    ift: read
    inputFieldDescribeId: 0
    name: connectionUrl
    requestParamName: connectionUrl
    sessionParamName: ''
    uuid: '9258'
    validate: null
  - alias: connectionUsername
    apiLegoId: 0
    apiLegoUuid: '1312'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: connectionUsername
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52781
    ift: read
    inputFieldDescribeId: 0
    name: connectionUsername
    requestParamName: connectionUsername
    sessionParamName: ''
    uuid: '9259'
    validate: null
  - alias: connectionPassword
    apiLegoId: 0
    apiLegoUuid: '1312'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: connectionPassword
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52782
    ift: read
    inputFieldDescribeId: 0
    name: connectionPassword
    requestParamName: connectionPassword
    sessionParamName: ''
    uuid: '9260'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '1312'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: In
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: alias
    fromApiLegoUuid: 908A57C5-BE5E-499B-85F8-93610018E6631527670625063
    fvt: output
    id: 52783
    ift: condition
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: ''
    uuid: 39918139-C9B9-4479-A192-A57E67222A1E1527670739971
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 0
    apiLegoUuid: '1312'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 7960
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1455'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
