api:
  alias: list-oi-by-dsalias
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-25T17:20:56Z
  description: ''
  id: 222
  method: GET
  name: 通过dsAlias获取oi列表
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: list-oi-by-dsalias
    attributes: null
    description: null
    id: 307
    index: 1
    legoAlias: list
    oiAlias: ty_oi
    processControllerAlias: null
    uuid: '307'
  inputFields:
  - alias: id
    apiLegoId: 307
    apiLegoUuid: '307'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 699
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: null
    sessionParamName: null
    uuid: '699'
    validate: null
  - alias: name
    apiLegoId: 307
    apiLegoUuid: '307'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 700
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: null
    sessionParamName: null
    uuid: '700'
    validate: null
  - alias: description
    apiLegoId: 307
    apiLegoUuid: '307'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 701
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: null
    sessionParamName: null
    uuid: '701'
    validate: null
  - alias: alias
    apiLegoId: 307
    apiLegoUuid: '307'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 702
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: null
    sessionParamName: null
    uuid: '702'
    validate: null
  - alias: resource
    apiLegoId: 307
    apiLegoUuid: '307'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: resource
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 703
    ift: read
    inputFieldDescribeId: 0
    name: resource
    requestParamName: null
    sessionParamName: null
    uuid: '703'
    validate: null
  - alias: dsAlias
    apiLegoId: 307
    apiLegoUuid: '307'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: dsAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 704
    ift: read
    inputFieldDescribeId: 0
    name: dsAlias
    requestParamName: null
    sessionParamName: null
    uuid: '704'
    validate: null
  - alias: dsAlias
    apiLegoId: 307
    apiLegoUuid: '307'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: dsAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 705
    ift: condition
    inputFieldDescribeId: 0
    name: dsAlias
    requestParamName: dsAlias
    sessionParamName: null
    uuid: '705'
    validate: ''
  outputFields:
  - alias: data_list
    apiLegoId: 307
    apiLegoUuid: '307'
    description: null
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 101
    name: 列表数据
    oft: common
    outputFieldDescribeId: 31
    response: true
    uuid: '101'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
