api:
  alias: list-field-tree
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-16T10:32:02Z
  description: ''
  id: 135
  method: POST
  name: 树形字段列表
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: list-field-tree
    attributes: ''
    description: null
    id: 151
    index: 1
    legoAlias: list
    oiAlias: ty_field
    processControllerAlias: null
    uuid: '151'
  inputFields:
  - alias: oiAlias
    apiLegoId: 151
    apiLegoUuid: '151'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: oiAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 132
    ift: condition
    inputFieldDescribeId: 0
    name: oi别名
    requestParamName: oiAlias
    sessionParamName: ''
    uuid: '132'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 151
    apiLegoUuid: '151'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 133
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: null
    sessionParamName: null
    uuid: '133'
    validate: ''
  - alias: name
    apiLegoId: 151
    apiLegoUuid: '151'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 134
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: null
    sessionParamName: null
    uuid: '134'
    validate: ''
  - alias: fieldName
    apiLegoId: 151
    apiLegoUuid: '151'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 135
    ift: read
    inputFieldDescribeId: 0
    name: 字段名
    requestParamName: null
    sessionParamName: null
    uuid: '135'
    validate: ''
  - alias: oiAlias
    apiLegoId: 151
    apiLegoUuid: '151'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: oiAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 136
    ift: read
    inputFieldDescribeId: 0
    name: oi别名
    requestParamName: null
    sessionParamName: null
    uuid: '136'
    validate: ''
  - alias: dt
    apiLegoId: 151
    apiLegoUuid: '151'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: dt
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 137
    ift: read
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: null
    sessionParamName: null
    uuid: '137'
    validate: ''
  outputFields:
  - alias: field_list
    apiLegoId: 151
    apiLegoUuid: '151'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 36
    name: 数据列表
    oft: ''
    outputFieldDescribeId: 0
    response: true
    uuid: '36'
- apiLego:
    apiAlias: list-field-tree
    attributes: ''
    description: null
    id: 162
    index: 2
    legoAlias: list
    oiAlias: ty_connector
    processControllerAlias: null
    uuid: '162'
  inputFields:
  - alias: fromOIAlias
    apiLegoId: 162
    apiLegoUuid: '162'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fromOIAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 138
    ift: condition
    inputFieldDescribeId: 0
    name: 源oi别名
    requestParamName: fromOIAlias
    sessionParamName: null
    uuid: '138'
    validate: ''
  - alias: id
    apiLegoId: 162
    apiLegoUuid: '162'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 139
    ift: read
    inputFieldDescribeId: 0
    name: 主键iid
    requestParamName: null
    sessionParamName: null
    uuid: '139'
    validate: ''
  - alias: name
    apiLegoId: 162
    apiLegoUuid: '162'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 140
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: null
    sessionParamName: null
    uuid: '140'
    validate: ''
  - alias: alias
    apiLegoId: 162
    apiLegoUuid: '162'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 141
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: null
    sessionParamName: null
    uuid: '141'
    validate: ''
  - alias: fromOIAlias
    apiLegoId: 162
    apiLegoUuid: '162'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fromOIAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 142
    ift: read
    inputFieldDescribeId: 0
    name: 源oi别名
    requestParamName: null
    sessionParamName: null
    uuid: '142'
    validate: ''
  - alias: fromFieldName
    apiLegoId: 162
    apiLegoUuid: '162'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fromFieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 143
    ift: read
    inputFieldDescribeId: 0
    name: 源字段
    requestParamName: null
    sessionParamName: null
    uuid: '143'
    validate: ''
  - alias: toOIAlias
    apiLegoId: 162
    apiLegoUuid: '162'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: toOIAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 144
    ift: read
    inputFieldDescribeId: 0
    name: 目标oi别名
    requestParamName: null
    sessionParamName: null
    uuid: '144'
    validate: ''
  - alias: toFieldName
    apiLegoId: 162
    apiLegoUuid: '162'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: toFieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 145
    ift: read
    inputFieldDescribeId: 0
    name: 目标字段
    requestParamName: null
    sessionParamName: null
    uuid: '145'
    validate: ''
  outputFields:
  - alias: connector_list
    apiLegoId: 162
    apiLegoUuid: '162'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 37
    name: 链接列表
    oft: ''
    outputFieldDescribeId: 0
    response: true
    uuid: '37'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
