api:
  alias: page-api-self
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-05T17:11:15Z
  description: 我的API分页数据接口
  id: 650
  method: POST
  name: 我的API分页数据接口
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: page-api-self
    attributes: null
    description: ''
    id: 8202
    index: 1
    legoAlias: page
    oiAlias: ty_api
    processControllerAlias: null
    uuid: '1298'
  inputFields:
  - alias: page
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: page
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 75194
    ift: common
    inputFieldDescribeId: 0
    name: 请求页码
    requestParamName: page
    sessionParamName: ''
    uuid: '9047'
    validate: ''
  - alias: pageSize
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: pageSize
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 75195
    ift: common
    inputFieldDescribeId: 0
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: ''
    uuid: '9048'
    validate: ''
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 75196
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: '9049'
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 75197
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: '9050'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 75198
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: '9051'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 75199
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: ''
    uuid: '9052'
    validate: null
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 75200
    ift: read
    inputFieldDescribeId: 0
    name: createDate
    requestParamName: createDate
    sessionParamName: ''
    uuid: '9053'
    validate: null
  - alias: enable
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: enable
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 75201
    ift: read
    inputFieldDescribeId: 0
    name: enable
    requestParamName: enable
    sessionParamName: ''
    uuid: '9054'
    validate: null
  - alias: method
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: method
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 75202
    ift: read
    inputFieldDescribeId: 0
    name: method
    requestParamName: method
    sessionParamName: ''
    uuid: '9055'
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: '["name","id","alias","description"]'
    ct: eq
    description: ''
    dt: string
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 75203
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '9056'
    validate: ''
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 75204
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '9057'
    validate: ''
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 75205
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '9058'
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: DESC
    ct: eq
    description: ''
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 75206
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '9059'
    validate: ''
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: id
    ct: eq
    description: ''
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 75207
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '9060'
    validate: ''
  - alias: type
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 75208
    ift: read
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: ''
    uuid: '9061'
    validate: null
  - alias: type
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: api
    ct: eq
    description: ''
    dt: string
    fieldName: type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 75209
    ift: condition
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: ''
    uuid: '9062'
    validate: ''
  - alias: url
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: url
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 75210
    ift: read
    inputFieldDescribeId: 0
    name: 接口地址
    requestParamName: url
    sessionParamName: ''
    uuid: '9063'
    validate: null
  - alias: category
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: category
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 75211
    ift: read
    inputFieldDescribeId: 0
    name: 接口分类
    requestParamName: category
    sessionParamName: ''
    uuid: '9064'
    validate: null
  - alias: authType
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: authType
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 75212
    ift: read
    inputFieldDescribeId: 0
    name: 授权类型
    requestParamName: authType
    sessionParamName: ''
    uuid: '9065'
    validate: null
  - alias: deleteStatus
    apiLegoId: 0
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: '[{"alias":"ty_api_c1"}]'
    constant: '0'
    ct: eq
    description: ''
    dt: int
    fieldName: deleteStatus
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 75215
    ift: condition
    inputFieldDescribeId: 0
    name: 类型-deleteStatus
    requestParamName: deleteStatus
    sessionParamName: ''
    uuid: D66E853F-B5CB-4700-AF7B-8950B311C7861527670220756
    validate: null
  - alias: ownerType
    apiLegoId: null
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: '[{"alias":"ty_api_c1"}]'
    constant: api
    ct: eq
    description: null
    dt: string
    fieldName: ownerType
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: null
    ift: condition
    inputFieldDescribeId: null
    name: 别名-管理员类型
    requestParamName: ownerType
    sessionParamName: null
    uuid: DFC97741-BBC2-4161-84DA-AFF8E6D2D9BC1537868544138
    validate: null
  - alias: owerId
    apiLegoId: null
    apiLegoUuid: '1298'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: owerId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: template
    id: null
    ift: condition
    inputFieldDescribeId: null
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: null
    uuid: E0A68B9A-8179-4F81-8695-D30FF45042851539914423520
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 0
    apiLegoUuid: '1298'
    description: ''
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 10866
    name: page_data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1441'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
