api:
  alias: page-oi
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-11T14:58:22Z
  description: ''
  id: 37
  method: GET
  name: 分页查询oi
  type: ty
  url: ''
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: page-oi
    attributes: null
    description: ''
    id: 10568
    index: 1
    legoAlias: page
    oiAlias: ty_oi
    processControllerAlias: null
    uuid: '42'
  inputFields:
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '42'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 95168
    ift: read
    inputFieldDescribeId: 0
    name: 主键id
    requestParamName: ''
    sessionParamName: ''
    uuid: '88'
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '42'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 95169
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: ''
    sessionParamName: ''
    uuid: '89'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '42'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 95170
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: ''
    sessionParamName: ''
    uuid: '90'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '42'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 95171
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: ''
    sessionParamName: ''
    uuid: '91'
    validate: null
  - alias: resource
    apiLegoId: 0
    apiLegoUuid: '42'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: resource
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 95172
    ift: read
    inputFieldDescribeId: 0
    name: 资源
    requestParamName: ''
    sessionParamName: ''
    uuid: '92'
    validate: null
  - alias: dsAlias
    apiLegoId: 0
    apiLegoUuid: '42'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: dsAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 95173
    ift: read
    inputFieldDescribeId: 0
    name: ds别名
    requestParamName: ''
    sessionParamName: ''
    uuid: '93'
    validate: null
  - alias: page
    apiLegoId: 0
    apiLegoUuid: '42'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: page
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 95174
    ift: null
    inputFieldDescribeId: 0
    name: 第几页
    requestParamName: page
    sessionParamName: ''
    uuid: '94'
    validate: null
  - alias: pageSize
    apiLegoId: 0
    apiLegoUuid: '42'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: pageSize
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 95175
    ift: null
    inputFieldDescribeId: 0
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: ''
    uuid: '95'
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '42'
    attributes: null
    connectorPath: ''
    constant: '["name","alias","resource"]'
    ct: eq
    description: ''
    dt: string
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 95176
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '1294'
    validate: ''
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '42'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 95177
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '1295'
    validate: ''
  - alias: dsAlias
    apiLegoId: 0
    apiLegoUuid: '42'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: dsAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 95178
    ift: condition
    inputFieldDescribeId: 0
    name: dsAlias
    requestParamName: dsAlias
    sessionParamName: ''
    uuid: '11112'
    validate: '[{"validateName":"required"}]'
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '42'
    attributes: null
    connectorPath: ''
    constant: id
    ct: eq
    description: ''
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 95179
    ift: common
    inputFieldDescribeId: 0
    name: order_field
    requestParamName: ''
    sessionParamName: ''
    uuid: 36532D75-2244-42AC-B14E-E00E878521FA1532069393419
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '42'
    attributes: null
    connectorPath: ''
    constant: desc
    ct: eq
    description: ''
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 95180
    ift: common
    inputFieldDescribeId: 0
    name: order
    requestParamName: ''
    sessionParamName: ''
    uuid: 4F4DBBB9-CE9F-4A39-B6E9-613FB961F01B1532069413143
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 0
    apiLegoUuid: '42'
    description: ''
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 13657
    name: 输出数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '32'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
