api:
  alias: page-page
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-08T16:24:45Z
  description: ''
  id: 302
  method: POST
  name: 翻页Page API
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: page-page
    attributes: null
    description: 翻页Page组件
    id: 430
    index: 1
    legoAlias: page
    oiAlias: ty_page
    processControllerAlias: null
    uuid: '430'
  inputFields:
  - alias: page
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: page
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 1401
    ift: common
    inputFieldDescribeId: 3
    name: 请求页码
    requestParamName: page
    sessionParamName: ''
    uuid: '1401'
    validate: ''
  - alias: pageSize
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: pageSize
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 1402
    ift: common
    inputFieldDescribeId: 4
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: ''
    uuid: '1402'
    validate: ''
  - alias: keywords
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 1406
    ift: common
    inputFieldDescribeId: 53
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '1406'
    validate: ''
  - alias: global_search_fields
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: ''
    connectorPath: ''
    constant: '["name"]'
    ct: eq
    description: ''
    dt: string
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 1407
    ift: common
    inputFieldDescribeId: 54
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '1407'
    validate: ''
  - alias: id
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1408
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '1408'
    validate: null
  - alias: name
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1409
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '1409'
    validate: null
  - alias: description
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1410
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '1410'
    validate: null
  - alias: alias
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1411
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '1411'
    validate: null
  - alias: createDate
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1412
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: null
    uuid: '1412'
    validate: null
  - alias: layout
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: layout
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1413
    ift: read
    inputFieldDescribeId: 0
    name: 布局
    requestParamName: layout
    sessionParamName: null
    uuid: '1413'
    validate: null
  - alias: layoutType
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: layoutType
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1414
    ift: read
    inputFieldDescribeId: 0
    name: 布局类型
    requestParamName: layoutType
    sessionParamName: null
    uuid: '1414'
    validate: null
  - alias: template
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: template
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1483
    ift: read
    inputFieldDescribeId: 0
    name: 是否模板
    requestParamName: template
    sessionParamName: null
    uuid: '1483'
    validate: null
  - alias: templatePageAlias
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: templatePageAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1484
    ift: read
    inputFieldDescribeId: 0
    name: 所属模板
    requestParamName: templatePageAlias
    sessionParamName: null
    uuid: '1484'
    validate: null
  - alias: custom
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: custom
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1578
    ift: read
    inputFieldDescribeId: 0
    name: 定制化
    requestParamName: custom
    sessionParamName: null
    uuid: '1578'
    validate: null
  - alias: customFile
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: customFile
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1579
    ift: read
    inputFieldDescribeId: 0
    name: 定制文件
    requestParamName: customFile
    sessionParamName: null
    uuid: '1579'
    validate: null
  - alias: order
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: null
    constant: DESC
    ct: eq
    description: null
    dt: string
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 2491
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: null
    sessionParamName: null
    uuid: '2491'
    validate: ''
  - alias: order_field
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: null
    constant: id
    ct: eq
    description: null
    dt: string
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 2492
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: null
    sessionParamName: null
    uuid: '2492'
    validate: ''
  - alias: appAlias
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: appAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 3994
    ift: read
    inputFieldDescribeId: 0
    name: 应用别名
    requestParamName: appAlias
    sessionParamName: null
    uuid: '3994'
    validate: null
  - alias: parentId
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: parentId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 3995
    ift: read
    inputFieldDescribeId: 0
    name: 父ID
    requestParamName: parentId
    sessionParamName: null
    uuid: '3995'
    validate: null
  - alias: enable
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: enable
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 3996
    ift: read
    inputFieldDescribeId: 0
    name: 是否可用
    requestParamName: enable
    sessionParamName: null
    uuid: '3996'
    validate: null
  - alias: type
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: type
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 3997
    ift: read
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: null
    uuid: '3997'
    validate: null
  - alias: appAlias
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: appAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4050
    ift: condition
    inputFieldDescribeId: 0
    name: 应用别名
    requestParamName: appAlias
    sessionParamName: null
    uuid: '4050'
    validate: ''
  - alias: icon
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: icon
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5156
    ift: read
    inputFieldDescribeId: 0
    name: icon
    requestParamName: icon
    sessionParamName: null
    uuid: '5156'
    validate: null
  - alias: sort
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: sort
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5699
    ift: read
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: sort
    sessionParamName: null
    uuid: '5699'
    validate: null
  - alias: platform
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: platform
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8972
    ift: read
    inputFieldDescribeId: 0
    name: 所属平台
    requestParamName: platform
    sessionParamName: null
    uuid: '8972'
    validate: null
  - alias: createrId
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: createrId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8973
    ift: read
    inputFieldDescribeId: 0
    name: 创建人id
    requestParamName: createrId
    sessionParamName: null
    uuid: '8973'
    validate: null
  - alias: createrName
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: createrName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8974
    ift: read
    inputFieldDescribeId: 0
    name: 创建人姓名
    requestParamName: createrName
    sessionParamName: null
    uuid: '8974'
    validate: null
  - alias: owerId
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: owerId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8975
    ift: read
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: null
    uuid: '8975'
    validate: null
  - alias: owerName
    apiLegoId: 430
    apiLegoUuid: '430'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: owerName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8976
    ift: read
    inputFieldDescribeId: 0
    name: 负责人名称
    requestParamName: owerName
    sessionParamName: null
    uuid: '8976'
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 430
    apiLegoUuid: '430'
    description: null
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 188
    name: page_data
    oft: common
    outputFieldDescribeId: 2
    response: true
    uuid: '188'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
