api:
  alias: page-field-by-oi
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-03-20T14:54:16Z
  description: null
  id: 757
  method: GET
  name: 分页获取oi的所有字段
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: page-field-by-oi
    attributes: null
    description: ''
    id: 2095
    index: 1
    legoAlias: page
    oiAlias: ty_field
    processControllerAlias: null
    uuid: '1568'
  inputFields:
  - alias: page
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: page
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 15478
    ift: common
    inputFieldDescribeId: 0
    name: 请求页码
    requestParamName: page
    sessionParamName: ''
    uuid: '11137'
    validate: ''
  - alias: pageSize
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: pageSize
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 15479
    ift: common
    inputFieldDescribeId: 0
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: ''
    uuid: '11138'
    validate: ''
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: id
    ct: ''
    description: ''
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 15480
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '11139'
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: DESC
    ct: ''
    description: ''
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 15481
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '11140'
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 15482
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '11141'
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 15483
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '11142'
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 15484
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '11143'
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 15485
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: '11144'
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 15486
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: '11145'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 15487
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: '11146'
    validate: null
  - alias: fieldName
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 15488
    ift: read
    inputFieldDescribeId: 0
    name: fieldName
    requestParamName: fieldName
    sessionParamName: ''
    uuid: '11147'
    validate: null
  - alias: oiAlias
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: oiAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 15489
    ift: read
    inputFieldDescribeId: 0
    name: oiAlias
    requestParamName: oiAlias
    sessionParamName: ''
    uuid: '11148'
    validate: null
  - alias: dt
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: dt
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 15490
    ift: read
    inputFieldDescribeId: 0
    name: dt
    requestParamName: dt
    sessionParamName: ''
    uuid: '11149'
    validate: null
  - alias: parentFieldId
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: parentFieldId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 15491
    ift: read
    inputFieldDescribeId: 0
    name: parentFieldId
    requestParamName: parentFieldId
    sessionParamName: ''
    uuid: '11150'
    validate: null
  - alias: pk
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: boolean
    fieldName: pk
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 15492
    ift: read
    inputFieldDescribeId: 0
    name: pk
    requestParamName: pk
    sessionParamName: ''
    uuid: '11151'
    validate: null
  - alias: fieldValue
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fieldValue
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 15493
    ift: read
    inputFieldDescribeId: 0
    name: fieldValue
    requestParamName: fieldValue
    sessionParamName: ''
    uuid: '11152'
    validate: null
  - alias: fieldLength
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: fieldLength
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 15494
    ift: read
    inputFieldDescribeId: 0
    name: fieldLength
    requestParamName: fieldLength
    sessionParamName: ''
    uuid: '11153'
    validate: null
  - alias: oiAlias
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: oiAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15495
    ift: condition
    inputFieldDescribeId: 0
    name: oiAlias
    requestParamName: oiAlias
    sessionParamName: ''
    uuid: '11154'
    validate: '[{"validateName":"required"}]'
  - alias: group
    apiLegoId: 0
    apiLegoUuid: '1568'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: group
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 15496
    ift: read
    inputFieldDescribeId: 0
    name: group
    requestParamName: group
    sessionParamName: ''
    uuid: '12696'
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 0
    apiLegoUuid: '1568'
    description: ''
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 2474
    name: page_data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1743'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
