api:
  alias: page-bb
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-07T17:19:03Z
  description: 分页列出积木
  id: 295
  method: POST
  name: 分页列出积木
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: page-bb
    attributes: null
    description: null
    id: 420
    index: 1
    legoAlias: page
    oiAlias: ty_building_block
    processControllerAlias: null
    uuid: '420'
  inputFields:
  - alias: page
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: page
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 1319
    ift: common
    inputFieldDescribeId: 3
    name: 请求页码
    requestParamName: page
    sessionParamName: ''
    uuid: '1319'
    validate: ''
  - alias: pageSize
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: pageSize
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 1320
    ift: common
    inputFieldDescribeId: 4
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: ''
    uuid: '1320'
    validate: ''
  - alias: order_field
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 1321
    ift: common
    inputFieldDescribeId: 7
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '1321'
    validate: null
  - alias: order
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 1322
    ift: common
    inputFieldDescribeId: 8
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '1322'
    validate: null
  - alias: group_field
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 1323
    ift: common
    inputFieldDescribeId: 9
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '1323'
    validate: null
  - alias: keywords
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 1324
    ift: common
    inputFieldDescribeId: 53
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '1324'
    validate: ''
  - alias: global_search_fields
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: ''
    connectorPath: ''
    constant: '["name","alias","type","description","createrName"]'
    ct: eq
    description: ''
    dt: string
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 1325
    ift: common
    inputFieldDescribeId: 54
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '1325'
    validate: ''
  - alias: id
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1326
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '1326'
    validate: null
  - alias: name
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1327
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '1327'
    validate: null
  - alias: description
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 1328
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: ''
    uuid: '1328'
    validate: ''
  - alias: alias
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 1329
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: ''
    uuid: '1329'
    validate: ''
  - alias: createDate
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1330
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: null
    uuid: '1330'
    validate: null
  - alias: type
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: type
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 2369
    ift: read
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: null
    uuid: '2369'
    validate: null
  - alias: type
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: type
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 2386
    ift: condition
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: null
    uuid: '2386'
    validate: null
  - alias: icon
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: icon
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9148
    ift: read
    inputFieldDescribeId: 0
    name: 图标
    requestParamName: icon
    sessionParamName: null
    uuid: '9148'
    validate: null
  - alias: platform
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: platform
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9149
    ift: read
    inputFieldDescribeId: 0
    name: 平台
    requestParamName: platform
    sessionParamName: null
    uuid: '9149'
    validate: null
  - alias: tags
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: tags
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9150
    ift: read
    inputFieldDescribeId: 0
    name: 标签
    requestParamName: tags
    sessionParamName: null
    uuid: '9150'
    validate: null
  - alias: createrName
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: createrName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 9151
    ift: read
    inputFieldDescribeId: 0
    name: 创建人姓名
    requestParamName: createrName
    sessionParamName: ''
    uuid: '9151'
    validate: ''
  - alias: owerName
    apiLegoId: 420
    apiLegoUuid: '420'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: owerName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9152
    ift: read
    inputFieldDescribeId: 0
    name: 负责人名称
    requestParamName: owerName
    sessionParamName: null
    uuid: '9152'
    validate: null
  - alias: module
    apiLegoId: null
    apiLegoUuid: '420'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: boolean
    fieldName: module
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: read
    inputFieldDescribeId: null
    name: 是否模块
    requestParamName: module
    sessionParamName: null
    uuid: 8AE5C2D1-0E60-4CCB-96F5-7E2D9122EE531533984991724
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 420
    apiLegoUuid: '420'
    description: null
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 179
    name: page_data
    oft: common
    outputFieldDescribeId: 2
    response: true
    uuid: '179'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
