api:
  alias: page-api
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-05T17:11:15Z
  description: 分页读取API数据
  id: 289
  method: GET
  name: API分页数据接口
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: page-api
    attributes: null
    description: ''
    id: 5176
    index: 1
    legoAlias: page
    oiAlias: ty_api
    processControllerAlias: null
    uuid: '407'
  inputFields:
  - alias: page
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: page
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 47155
    ift: common
    inputFieldDescribeId: 0
    name: 请求页码
    requestParamName: page
    sessionParamName: ''
    uuid: '1143'
    validate: ''
  - alias: pageSize
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: pageSize
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 47156
    ift: common
    inputFieldDescribeId: 0
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: ''
    uuid: '1144'
    validate: ''
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 47157
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: '1148'
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 47158
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: '1149'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 47159
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: '1150'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 47160
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: ''
    uuid: '1151'
    validate: null
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 47161
    ift: read
    inputFieldDescribeId: 0
    name: createDate
    requestParamName: createDate
    sessionParamName: ''
    uuid: '1152'
    validate: null
  - alias: enable
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: enable
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 47162
    ift: read
    inputFieldDescribeId: 0
    name: enable
    requestParamName: enable
    sessionParamName: ''
    uuid: '1153'
    validate: null
  - alias: method
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: method
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 47163
    ift: read
    inputFieldDescribeId: 0
    name: method
    requestParamName: method
    sessionParamName: ''
    uuid: '1154'
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: '["name","id","alias","description"]'
    ct: eq
    description: ''
    dt: string
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 47164
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '1281'
    validate: ''
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 47165
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '1282'
    validate: ''
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 47166
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '1283'
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: DESC
    ct: eq
    description: ''
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 47167
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '1284'
    validate: ''
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: id
    ct: eq
    description: ''
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 47168
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '1285'
    validate: ''
  - alias: type
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 47169
    ift: read
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: ''
    uuid: '2374'
    validate: null
  - alias: type
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 47170
    ift: condition
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: ''
    uuid: '2375'
    validate: ''
  - alias: url
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: url
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 47171
    ift: read
    inputFieldDescribeId: 0
    name: 接口地址
    requestParamName: url
    sessionParamName: ''
    uuid: '3025'
    validate: null
  - alias: category
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: category
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 47172
    ift: read
    inputFieldDescribeId: 0
    name: 接口分类
    requestParamName: category
    sessionParamName: ''
    uuid: '3026'
    validate: null
  - alias: authType
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: authType
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 47173
    ift: read
    inputFieldDescribeId: 0
    name: 授权类型
    requestParamName: authType
    sessionParamName: ''
    uuid: '6874'
    validate: null
  - alias: method
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: method
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 47174
    ift: condition
    inputFieldDescribeId: 0
    name: 调用方法
    requestParamName: method
    sessionParamName: ''
    uuid: 997CAD2C-FA02-4E35-A9C1-E9569E141D201526437531548
    validate: null
  - alias: category
    apiLegoId: 0
    apiLegoUuid: '407'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: category
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 47175
    ift: condition
    inputFieldDescribeId: 0
    name: 接口分类
    requestParamName: category
    sessionParamName: ''
    uuid: 1FF587D9-E3BC-47DD-98A4-5F170A5D68241526437531548
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 0
    apiLegoUuid: '407'
    description: ''
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 7220
    name: page_data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '165'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
