api:
  alias: page-connector-by-oi
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-03-20T15:12:18Z
  description: null
  id: 758
  method: GET
  name: 分页获取oi下的所有连接器
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: page-connector-by-oi
    attributes: null
    description: null
    id: 1569
    index: 1
    legoAlias: page
    oiAlias: ty_connector
    processControllerAlias: null
    uuid: '1569'
  inputFields:
  - alias: page
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: page
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 11155
    ift: common
    inputFieldDescribeId: 3
    name: 请求页码
    requestParamName: page
    sessionParamName: null
    uuid: '11155'
    validate: ''
  - alias: pageSize
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: pageSize
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 11156
    ift: common
    inputFieldDescribeId: 4
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: null
    uuid: '11156'
    validate: ''
  - alias: order_field
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 11157
    ift: common
    inputFieldDescribeId: 7
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '11157'
    validate: null
  - alias: order
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 11158
    ift: common
    inputFieldDescribeId: 8
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '11158'
    validate: null
  - alias: group_field
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 11159
    ift: common
    inputFieldDescribeId: 9
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '11159'
    validate: null
  - alias: keywords
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 11160
    ift: common
    inputFieldDescribeId: 53
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '11160'
    validate: null
  - alias: global_search_fields
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 11161
    ift: common
    inputFieldDescribeId: 54
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '11161'
    validate: null
  - alias: fromOIAlias
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fromOIAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 11162
    ift: condition
    inputFieldDescribeId: 0
    name: 来源OI别名
    requestParamName: oiAlias
    sessionParamName: null
    uuid: '11162'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11163
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '11163'
    validate: null
  - alias: name
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11164
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '11164'
    validate: null
  - alias: description
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11165
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '11165'
    validate: null
  - alias: alias
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11166
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '11166'
    validate: null
  - alias: fromOIAlias
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fromOIAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11167
    ift: read
    inputFieldDescribeId: 0
    name: 来源OI别名
    requestParamName: fromOIAlias
    sessionParamName: null
    uuid: '11167'
    validate: null
  - alias: fromFieldName
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fromFieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11168
    ift: read
    inputFieldDescribeId: 0
    name: 来源字段名
    requestParamName: fromFieldName
    sessionParamName: null
    uuid: '11168'
    validate: null
  - alias: toOIAlias
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: toOIAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11169
    ift: read
    inputFieldDescribeId: 0
    name: 目标OI别名
    requestParamName: toOIAlias
    sessionParamName: null
    uuid: '11169'
    validate: null
  - alias: toFieldName
    apiLegoId: 1569
    apiLegoUuid: '1569'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: toFieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11170
    ift: read
    inputFieldDescribeId: 0
    name: 目标字段名
    requestParamName: toFieldName
    sessionParamName: null
    uuid: '11170'
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 1569
    apiLegoUuid: '1569'
    description: null
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 1744
    name: page_data
    oft: common
    outputFieldDescribeId: 2
    response: true
    uuid: '1744'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
