api:
  alias: page-buzz
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-08T10:34:43Z
  description: 巴斯分页列表
  id: 298
  method: GET
  name: 巴斯分页列表
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: page-buzz
    attributes: null
    description: null
    id: 426
    index: 1
    legoAlias: page
    oiAlias: ty_code
    processControllerAlias: null
    uuid: '426'
  inputFields:
  - alias: page
    apiLegoId: 426
    apiLegoUuid: '426'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: page
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 1377
    ift: common
    inputFieldDescribeId: 3
    name: 请求页码
    requestParamName: page
    sessionParamName: null
    uuid: '1377'
    validate: ''
  - alias: pageSize
    apiLegoId: 426
    apiLegoUuid: '426'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: pageSize
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 1378
    ift: common
    inputFieldDescribeId: 4
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: null
    uuid: '1378'
    validate: ''
  - alias: order_field
    apiLegoId: 426
    apiLegoUuid: '426'
    attributes: ''
    connectorPath: ''
    constant: id
    ct: eq
    description: ''
    dt: string
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 1379
    ift: common
    inputFieldDescribeId: 7
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '1379'
    validate: ''
  - alias: order
    apiLegoId: 426
    apiLegoUuid: '426'
    attributes: ''
    connectorPath: ''
    constant: DESC
    ct: eq
    description: ''
    dt: string
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 1380
    ift: common
    inputFieldDescribeId: 8
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '1380'
    validate: ''
  - alias: group_field
    apiLegoId: 426
    apiLegoUuid: '426'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 1381
    ift: common
    inputFieldDescribeId: 9
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '1381'
    validate: null
  - alias: keywords
    apiLegoId: 426
    apiLegoUuid: '426'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 1382
    ift: common
    inputFieldDescribeId: 53
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '1382'
    validate: ''
  - alias: global_search_fields
    apiLegoId: 426
    apiLegoUuid: '426'
    attributes: ''
    connectorPath: ''
    constant: '["name","alias","appAlias"]'
    ct: eq
    description: ''
    dt: string
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 1383
    ift: common
    inputFieldDescribeId: 54
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '1383'
    validate: ''
  - alias: id
    apiLegoId: 426
    apiLegoUuid: '426'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1384
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '1384'
    validate: null
  - alias: name
    apiLegoId: 426
    apiLegoUuid: '426'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1385
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '1385'
    validate: null
  - alias: description
    apiLegoId: 426
    apiLegoUuid: '426'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1386
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '1386'
    validate: null
  - alias: createDate
    apiLegoId: 426
    apiLegoUuid: '426'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1387
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: null
    uuid: '1387'
    validate: null
  - alias: code
    apiLegoId: 426
    apiLegoUuid: '426'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: code
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1388
    ift: read
    inputFieldDescribeId: 0
    name: 代码
    requestParamName: code
    sessionParamName: null
    uuid: '1388'
    validate: null
  - alias: type
    apiLegoId: 426
    apiLegoUuid: '426'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: type
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1389
    ift: read
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: null
    uuid: '1389'
    validate: null
  - alias: alias
    apiLegoId: 426
    apiLegoUuid: '426'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1710
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '1710'
    validate: null
  - alias: appAlias
    apiLegoId: null
    apiLegoUuid: '426'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: appAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: read
    inputFieldDescribeId: null
    name: 对应app
    requestParamName: appAlias
    sessionParamName: null
    uuid: B90EF392-31EB-4C63-B77C-D253E12E9E321536832013596
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 426
    apiLegoUuid: '426'
    description: null
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 186
    name: page_data
    oft: common
    outputFieldDescribeId: 2
    response: true
    uuid: '186'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
