api:
  alias: read-bb
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-01T11:17:07Z
  description: 获取积木详情
  id: 254
  method: POST
  name: 获取积木详情
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: read-bb
    attributes: null
    description: ''
    id: 3536
    index: 1
    legoAlias: read
    oiAlias: ty_building_block
    processControllerAlias: null
    uuid: '352'
  inputFields:
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 29591
    ift: condition
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: bbAlias
    sessionParamName: ''
    uuid: '943'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29592
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '944'
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29593
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: ''
    uuid: '945'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29594
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: ''
    uuid: '946'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29595
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: ''
    uuid: '947'
    validate: null
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29596
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: ''
    uuid: '948'
    validate: null
  - alias: type
    apiLegoId: 0
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29597
    ift: read
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: ''
    uuid: '2366'
    validate: null
  - alias: icon
    apiLegoId: 0
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: icon
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29598
    ift: read
    inputFieldDescribeId: 0
    name: 图标
    requestParamName: icon
    sessionParamName: ''
    uuid: '4578'
    validate: null
  - alias: platform
    apiLegoId: 0
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: platform
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29599
    ift: read
    inputFieldDescribeId: 0
    name: 平台
    requestParamName: platform
    sessionParamName: ''
    uuid: '9140'
    validate: null
  - alias: tags
    apiLegoId: 0
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: tags
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29600
    ift: read
    inputFieldDescribeId: 0
    name: 标签
    requestParamName: tags
    sessionParamName: ''
    uuid: '9141'
    validate: null
  - alias: createrId
    apiLegoId: 0
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: createrId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29601
    ift: read
    inputFieldDescribeId: 0
    name: 创建人id
    requestParamName: createrId
    sessionParamName: ''
    uuid: '9142'
    validate: null
  - alias: createrName
    apiLegoId: 0
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: createrName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29602
    ift: read
    inputFieldDescribeId: 0
    name: 创建人姓名
    requestParamName: createrName
    sessionParamName: ''
    uuid: '9143'
    validate: null
  - alias: owerId
    apiLegoId: 0
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: owerId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29603
    ift: read
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: ''
    uuid: '9144'
    validate: null
  - alias: owerName
    apiLegoId: 0
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: owerName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29604
    ift: read
    inputFieldDescribeId: 0
    name: 负责人名称
    requestParamName: owerName
    sessionParamName: ''
    uuid: '9145'
    validate: null
  - alias: 'on'
    apiLegoId: 0
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: interactive
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 29605
    ift: read
    inputFieldDescribeId: 0
    name: 交互
    requestParamName: interactive
    sessionParamName: ''
    uuid: C125A479-27C6-4C72-B8AA-CA02E757AB891524898327604
    validate: null
  - alias: defaultProps
    apiLegoId: null
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: defaultProps
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: read
    inputFieldDescribeId: null
    name: 默认属性
    requestParamName: defaultProps
    sessionParamName: null
    uuid: FAE3FED0-13C2-4458-8610-F8060FA035A41533621541873
    validate: null
  - alias: module
    apiLegoId: null
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: boolean
    fieldName: module
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: read
    inputFieldDescribeId: null
    name: 是否模块
    requestParamName: module
    sessionParamName: null
    uuid: 2E2A2C18-77BA-4B6D-8FBB-014C1CE802FC1533984819353
    validate: null
  - alias: content
    apiLegoId: null
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: content
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: read
    inputFieldDescribeId: null
    name: 模块内容
    requestParamName: content
    sessionParamName: null
    uuid: B2A770FA-5B6B-484C-AFE3-31778DE6AA931533984819353
    validate: null
  - alias: config
    apiLegoId: null
    apiLegoUuid: '352'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: boolean
    fieldName: config
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: read
    inputFieldDescribeId: null
    name: 配置使用
    requestParamName: config
    sessionParamName: null
    uuid: 92172DDE-EA97-46CD-8AD2-AD2FE836AF421534836090617
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 0
    apiLegoUuid: '352'
    description: ''
    dt: string
    fieldName: data
    fieldValue: null
    handle: ''
    id: 4719
    name: data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '139'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
