api:
  alias: read-oi
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-05T11:17:40Z
  description: 读取OI详情
  id: 278
  method: GET
  name: 读取OI详情
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: read-oi
    attributes: null
    description: null
    id: 389
    index: 1
    legoAlias: read
    oiAlias: ty_oi
    processControllerAlias: null
    uuid: '389'
  inputFields:
  - alias: alias
    apiLegoId: 389
    apiLegoUuid: '389'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1092
    ift: condition
    inputFieldDescribeId: 0
    name: alias
    requestParamName: oiAlias
    sessionParamName: null
    uuid: '1092'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 389
    apiLegoUuid: '389'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1093
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '1093'
    validate: null
  - alias: name
    apiLegoId: 389
    apiLegoUuid: '389'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1094
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: '1094'
    validate: null
  - alias: description
    apiLegoId: 389
    apiLegoUuid: '389'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1095
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: null
    uuid: '1095'
    validate: null
  - alias: alias
    apiLegoId: 389
    apiLegoUuid: '389'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1096
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: null
    uuid: '1096'
    validate: null
  - alias: resource
    apiLegoId: 389
    apiLegoUuid: '389'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: resource
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1097
    ift: read
    inputFieldDescribeId: 0
    name: resource
    requestParamName: resource
    sessionParamName: null
    uuid: '1097'
    validate: null
  - alias: dsAlias
    apiLegoId: 389
    apiLegoUuid: '389'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: dsAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1098
    ift: read
    inputFieldDescribeId: 0
    name: dsAlias
    requestParamName: dsAlias
    sessionParamName: null
    uuid: '1098'
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 389
    apiLegoUuid: '389'
    description: null
    dt: string
    fieldName: data
    fieldValue: null
    handle: ''
    id: 155
    name: data
    oft: common
    outputFieldDescribeId: 32
    response: true
    uuid: '155'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
