api:
  alias: read-lego
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-31T11:17:54Z
  description: 读取lego详情
  id: 239
  method: POST
  name: 读取lego详情
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: read-lego
    attributes: null
    description: null
    id: 333
    index: 1
    legoAlias: read
    oiAlias: ty_lego
    processControllerAlias: null
    uuid: '333'
  inputFields:
  - alias: id
    apiLegoId: 333
    apiLegoUuid: '333'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 832
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '832'
    validate: null
  - alias: name
    apiLegoId: 333
    apiLegoUuid: '333'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 833
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: '833'
    validate: null
  - alias: description
    apiLegoId: 333
    apiLegoUuid: '333'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 834
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: null
    uuid: '834'
    validate: null
  - alias: alias
    apiLegoId: 333
    apiLegoUuid: '333'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 835
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: null
    uuid: '835'
    validate: null
  - alias: alias
    apiLegoId: 333
    apiLegoUuid: '333'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 836
    ift: condition
    inputFieldDescribeId: 0
    name: alias
    requestParamName: legoAlias
    sessionParamName: null
    uuid: '836'
    validate: '[{"validateName":"required"}]'
  - alias: supportDST
    apiLegoId: 333
    apiLegoUuid: '333'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: supportDST
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 1317
    ift: read
    inputFieldDescribeId: 0
    name: 支持的DST
    requestParamName: supportDST
    sessionParamName: null
    uuid: '1317'
    validate: null
  - alias: icon
    apiLegoId: 333
    apiLegoUuid: '333'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: icon
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8934
    ift: read
    inputFieldDescribeId: 0
    name: icon
    requestParamName: icon
    sessionParamName: null
    uuid: '8934'
    validate: null
  - alias: generateSupport
    apiLegoId: 333
    apiLegoUuid: '333'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: boolean
    fieldName: generateSupport
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8935
    ift: read
    inputFieldDescribeId: 0
    name: 支持一键生成
    requestParamName: generateSupport
    sessionParamName: null
    uuid: '8935'
    validate: null
  - alias: useNum
    apiLegoId: 333
    apiLegoUuid: '333'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: useNum
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8936
    ift: read
    inputFieldDescribeId: 0
    name: 使用数量
    requestParamName: useNum
    sessionParamName: null
    uuid: '8936'
    validate: null
  - alias: createDate
    apiLegoId: 333
    apiLegoUuid: '333'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: time
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8937
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: null
    uuid: '8937'
    validate: null
  - alias: createrId
    apiLegoId: 333
    apiLegoUuid: '333'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: createrId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8938
    ift: read
    inputFieldDescribeId: 0
    name: 创建人id
    requestParamName: createrId
    sessionParamName: null
    uuid: '8938'
    validate: null
  - alias: createrName
    apiLegoId: 333
    apiLegoUuid: '333'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: createrName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8939
    ift: read
    inputFieldDescribeId: 0
    name: 创建人姓名
    requestParamName: createrName
    sessionParamName: null
    uuid: '8939'
    validate: null
  - alias: owerId
    apiLegoId: 333
    apiLegoUuid: '333'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: owerId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8940
    ift: read
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: null
    uuid: '8940'
    validate: null
  - alias: owerName
    apiLegoId: 333
    apiLegoUuid: '333'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: owerName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8941
    ift: read
    inputFieldDescribeId: 0
    name: 负责人名称
    requestParamName: owerName
    sessionParamName: null
    uuid: '8941'
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 333
    apiLegoUuid: '333'
    description: null
    dt: string
    fieldName: data
    fieldValue: null
    handle: ''
    id: 126
    name: data
    oft: common
    outputFieldDescribeId: 32
    response: true
    uuid: '126'
- apiLego:
    apiAlias: read-lego
    attributes: null
    description: null
    id: 334
    index: 2
    legoAlias: list
    oiAlias: ty_input_field_describe
    processControllerAlias: null
    uuid: '334'
  inputFields:
  - alias: legoAlias
    apiLegoId: 334
    apiLegoUuid: '334'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: legoAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 837
    ift: condition
    inputFieldDescribeId: 0
    name: legoAlias
    requestParamName: legoAlias
    sessionParamName: null
    uuid: '837'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 334
    apiLegoUuid: '334'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 838
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '838'
    validate: null
  - alias: name
    apiLegoId: 334
    apiLegoUuid: '334'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 839
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: '839'
    validate: null
  - alias: description
    apiLegoId: 334
    apiLegoUuid: '334'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 840
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: null
    uuid: '840'
    validate: null
  - alias: legoAlias
    apiLegoId: 334
    apiLegoUuid: '334'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: legoAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 841
    ift: read
    inputFieldDescribeId: 0
    name: legoAlias
    requestParamName: legoAlias
    sessionParamName: null
    uuid: '841'
    validate: null
  - alias: fieldName
    apiLegoId: 334
    apiLegoUuid: '334'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: fieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 842
    ift: read
    inputFieldDescribeId: 0
    name: fieldName
    requestParamName: fieldName
    sessionParamName: null
    uuid: '842'
    validate: null
  - alias: multiple
    apiLegoId: 334
    apiLegoUuid: '334'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: multiple
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 843
    ift: read
    inputFieldDescribeId: 0
    name: multiple
    requestParamName: multiple
    sessionParamName: null
    uuid: '843'
    validate: null
  - alias: ift
    apiLegoId: 334
    apiLegoUuid: '334'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: ift
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 844
    ift: read
    inputFieldDescribeId: 0
    name: ift
    requestParamName: ift
    sessionParamName: null
    uuid: '844'
    validate: null
  - alias: fromOIFields
    apiLegoId: 334
    apiLegoUuid: '334'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: fromOIFields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 845
    ift: read
    inputFieldDescribeId: 0
    name: fromOIFields
    requestParamName: fromOIFields
    sessionParamName: null
    uuid: '845'
    validate: null
  outputFields:
  - alias: ifd_list
    apiLegoId: 334
    apiLegoUuid: '334'
    description: null
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 127
    name: 列表数据
    oft: common
    outputFieldDescribeId: 31
    response: true
    uuid: '127'
- apiLego:
    apiAlias: read-lego
    attributes: null
    description: null
    id: 335
    index: 3
    legoAlias: list
    oiAlias: ty_output_field_describe
    processControllerAlias: null
    uuid: '335'
  inputFields:
  - alias: id
    apiLegoId: 335
    apiLegoUuid: '335'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 846
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '846'
    validate: null
  - alias: name
    apiLegoId: 335
    apiLegoUuid: '335'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 847
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: '847'
    validate: null
  - alias: description
    apiLegoId: 335
    apiLegoUuid: '335'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 848
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: null
    uuid: '848'
    validate: null
  - alias: legoAlias
    apiLegoId: 335
    apiLegoUuid: '335'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: legoAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 849
    ift: read
    inputFieldDescribeId: 0
    name: legoAlias
    requestParamName: legoAlias
    sessionParamName: null
    uuid: '849'
    validate: null
  - alias: fieldName
    apiLegoId: 335
    apiLegoUuid: '335'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: fieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 850
    ift: read
    inputFieldDescribeId: 0
    name: fieldName
    requestParamName: fieldName
    sessionParamName: null
    uuid: '850'
    validate: null
  - alias: oft
    apiLegoId: 335
    apiLegoUuid: '335'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: oft
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 851
    ift: read
    inputFieldDescribeId: 0
    name: oft
    requestParamName: oft
    sessionParamName: null
    uuid: '851'
    validate: null
  - alias: multiple
    apiLegoId: 335
    apiLegoUuid: '335'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: multiple
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 852
    ift: read
    inputFieldDescribeId: 0
    name: 是否多选
    requestParamName: multiple
    sessionParamName: null
    uuid: '852'
    validate: null
  - alias: legoAlias
    apiLegoId: 335
    apiLegoUuid: '335'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: legoAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 853
    ift: condition
    inputFieldDescribeId: 0
    name: legoAlias
    requestParamName: legoAlias
    sessionParamName: null
    uuid: '853'
    validate: '[{"validateName":"required"}]'
  outputFields:
  - alias: ofd_list
    apiLegoId: 335
    apiLegoUuid: '335'
    description: null
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 128
    name: 列表数据
    oft: common
    outputFieldDescribeId: 31
    response: true
    uuid: '128'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
