api:
  alias: read-api-ioft-fields
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-02T13:02:52Z
  description: 用来显示list，page，add，update等乐高接口的字段列表
  id: 427
  method: GET
  name: 读取接口的IOFT字段列表
  type: ty
  url: read-api-ioft-fields
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: read-api-ioft-fields
    attributes: null
    description: null
    id: 738
    index: 1
    legoAlias: list
    oiAlias: ty_input_field
    processControllerAlias: null
    uuid: '738'
  inputFields:
  - alias: apiAlias
    apiLegoId: 738
    apiLegoUuid: '738'
    attributes: null
    connectorPath: '[{"alias":"if_apiLego"}]'
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: apiAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 3947
    ift: condition
    inputFieldDescribeId: 0
    name: apiLegoId-API别名
    requestParamName: apiAlias
    sessionParamName: null
    uuid: '3947'
    validate: null
  - alias: id
    apiLegoId: 738
    apiLegoUuid: '738'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 3949
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '3949'
    validate: null
  - alias: name
    apiLegoId: 738
    apiLegoUuid: '738'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 3950
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: '3950'
    validate: null
  - alias: description
    apiLegoId: 738
    apiLegoUuid: '738'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 3951
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: null
    uuid: '3951'
    validate: null
  - alias: legoAlias
    apiLegoId: 738
    apiLegoUuid: '738'
    attributes: null
    connectorPath: '[{"alias":"if_apiLego"}]'
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: legoAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 3952
    ift: read
    inputFieldDescribeId: 0
    name: apiLegoId-乐高别名
    requestParamName: legoAlias
    sessionParamName: null
    uuid: '3952'
    validate: null
  - alias: ift
    apiLegoId: 738
    apiLegoUuid: '738'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: ift
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 3953
    ift: read
    inputFieldDescribeId: 0
    name: ift
    requestParamName: ift
    sessionParamName: null
    uuid: '3953'
    validate: null
  - alias: alias
    apiLegoId: 738
    apiLegoUuid: '738'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 3954
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: null
    uuid: '3954'
    validate: null
  - alias: dt
    apiLegoId: 738
    apiLegoUuid: '738'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: dt
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 3955
    ift: read
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: dt
    sessionParamName: null
    uuid: '3955'
    validate: null
  - alias: requestParamName
    apiLegoId: 738
    apiLegoUuid: '738'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: requestParamName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 3956
    ift: read
    inputFieldDescribeId: 0
    name: 请求参数别名
    requestParamName: requestParamName
    sessionParamName: null
    uuid: '3956'
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 738
    apiLegoUuid: '738'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 770
    name: 列表数据
    oft: common
    outputFieldDescribeId: 31
    response: true
    uuid: '770'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
