api:
  alias: read-connector
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-27T16:20:11Z
  description: ''
  id: 481
  method: GET
  name: 获取连接器信息
  type: ty
  url: read-connector
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: read-connector
    attributes: null
    description: null
    id: 936
    index: 1
    legoAlias: read
    oiAlias: ty_connector
    processControllerAlias: null
    uuid: '936'
  inputFields:
  - alias: order_field
    apiLegoId: 936
    apiLegoUuid: '936'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 5873
    ift: common
    inputFieldDescribeId: 32
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '5873'
    validate: null
  - alias: order
    apiLegoId: 936
    apiLegoUuid: '936'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 5874
    ift: common
    inputFieldDescribeId: 44
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '5874'
    validate: null
  - alias: group_field
    apiLegoId: 936
    apiLegoUuid: '936'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 5875
    ift: common
    inputFieldDescribeId: 45
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '5875'
    validate: null
  - alias: id
    apiLegoId: 936
    apiLegoUuid: '936'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 5876
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '5876'
    validate: null
  - alias: id
    apiLegoId: 936
    apiLegoUuid: '936'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5877
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '5877'
    validate: null
  - alias: name
    apiLegoId: 936
    apiLegoUuid: '936'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5878
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '5878'
    validate: null
  - alias: description
    apiLegoId: 936
    apiLegoUuid: '936'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5879
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '5879'
    validate: null
  - alias: alias
    apiLegoId: 936
    apiLegoUuid: '936'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5880
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '5880'
    validate: null
  - alias: fromOIAlias
    apiLegoId: 936
    apiLegoUuid: '936'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: fromOIAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5881
    ift: read
    inputFieldDescribeId: 0
    name: 来源OI别名
    requestParamName: fromOIAlias
    sessionParamName: null
    uuid: '5881'
    validate: null
  - alias: fromFieldName
    apiLegoId: 936
    apiLegoUuid: '936'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: fromFieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5882
    ift: read
    inputFieldDescribeId: 0
    name: 来源字段名
    requestParamName: fromFieldName
    sessionParamName: null
    uuid: '5882'
    validate: null
  - alias: toOIAlias
    apiLegoId: 936
    apiLegoUuid: '936'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: toOIAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5883
    ift: read
    inputFieldDescribeId: 0
    name: 目标OI别名
    requestParamName: toOIAlias
    sessionParamName: null
    uuid: '5883'
    validate: null
  - alias: toFieldName
    apiLegoId: 936
    apiLegoUuid: '936'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: toFieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5884
    ift: read
    inputFieldDescribeId: 0
    name: 目标字段名
    requestParamName: toFieldName
    sessionParamName: null
    uuid: '5884'
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 936
    apiLegoUuid: '936'
    description: null
    dt: string
    fieldName: data
    fieldValue: null
    handle: ''
    id: 1008
    name: data
    oft: common
    outputFieldDescribeId: 32
    response: true
    uuid: '1008'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
