api:
  alias: tenant_info
  authType: '["ty_auth"]'
  category: config
  content: null
  createDate: 2018-05-08T09:52:31Z
  description: 获取当前登录租户的信息
  id: 1148
  method: GET
  name: 登录租户信息
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: tenant_info
    attributes: null
    description: 根据session中的租户序列号来获取租户信息
    id: 4045
    index: 1
    legoAlias: read
    oiAlias: ty_tenant
    processControllerAlias: null
    uuid: 4E13D6C5-8A8F-4D0C-90ED-196D496210251525744377786
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 4E13D6C5-8A8F-4D0C-90ED-196D496210251525744377786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 33712
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: 1523B8C9-2D49-4AF5-9BAB-D91671F98F8D1525744377786
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 4E13D6C5-8A8F-4D0C-90ED-196D496210251525744377786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 33713
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: 11EACD8F-5D59-4E5A-9863-00076AD367B11525744377786
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 4E13D6C5-8A8F-4D0C-90ED-196D496210251525744377786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 33714
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: 48498FA3-7C17-4225-A841-648A418DBD301525744377786
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 4E13D6C5-8A8F-4D0C-90ED-196D496210251525744377786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 33715
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: D6E20A87-A6A1-456D-A5CC-4C2769A4E8251525744419989
    validate: null
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: 4E13D6C5-8A8F-4D0C-90ED-196D496210251525744377786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: time
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 33716
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: ''
    uuid: BC86D95E-FDB5-42B2-BBA5-C20FC4B55C221525744419989
    validate: null
  - alias: serialNumber
    apiLegoId: 0
    apiLegoUuid: 4E13D6C5-8A8F-4D0C-90ED-196D496210251525744377786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: serialNumber
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 33717
    ift: read
    inputFieldDescribeId: 0
    name: 序号
    requestParamName: serialNumber
    sessionParamName: ''
    uuid: 7AFE0EE8-9EC1-49AA-BAF2-76BD6FDFD0A51525744419989
    validate: null
  - alias: companyName
    apiLegoId: 0
    apiLegoUuid: 4E13D6C5-8A8F-4D0C-90ED-196D496210251525744377786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: companyName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 33718
    ift: read
    inputFieldDescribeId: 0
    name: 公司名称
    requestParamName: companyName
    sessionParamName: ''
    uuid: 89DF87FA-7307-4ACC-98DD-601CA352154C1525744419989
    validate: null
  - alias: logo
    apiLegoId: 0
    apiLegoUuid: 4E13D6C5-8A8F-4D0C-90ED-196D496210251525744377786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: logo
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 33719
    ift: read
    inputFieldDescribeId: 0
    name: LOGO
    requestParamName: logo
    sessionParamName: ''
    uuid: B03F62C5-BB1C-48FA-B243-1721C2357B431525744419989
    validate: null
  - alias: serialNumber
    apiLegoId: 0
    apiLegoUuid: 4E13D6C5-8A8F-4D0C-90ED-196D496210251525744377786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: serialNumber
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.tenantSerialNumber}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 33720
    ift: condition
    inputFieldDescribeId: 0
    name: 序号
    requestParamName: serialNumber
    sessionParamName: ''
    uuid: A1733DA4-9BDD-44BA-B760-4B7226AFDD331525744425336
    validate: null
  outputFields:
  - alias: tenant
    apiLegoId: 0
    apiLegoUuid: 4E13D6C5-8A8F-4D0C-90ED-196D496210251525744377786
    description: ''
    dt: ''
    fieldName: data
    fieldValue: null
    handle: ''
    id: 5485
    name: data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 9CF5B166-4FF9-4FE1-8274-847D7222E1A41525744377786
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
