api:
  alias: ty-add-icon
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-20T10:25:35Z
  description: ''
  id: 474
  method: POST
  name: 添加TY图标
  type: ty
  url: ty-add-icon
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-add-icon
    attributes: null
    description: null
    id: 898
    index: 1
    legoAlias: sessionRead
    oiAlias: null
    processControllerAlias: null
    uuid: '898'
  inputFields:
  - alias: E_SESSION_USER_DETAIL_KEY
    apiLegoId: 898
    apiLegoUuid: '898'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: E_SESSION_USER_DETAIL_KEY
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 5466
    ift: common
    inputFieldDescribeId: 0
    name: 用户信息
    requestParamName: ''
    sessionParamName: null
    uuid: '5466'
    validate: ''
  outputFields:
  - alias: data
    apiLegoId: 898
    apiLegoUuid: '898'
    description: null
    dt: null
    fieldName: data
    fieldValue: null
    handle: null
    id: 964
    name: 读取数据
    oft: common
    outputFieldDescribeId: 49
    response: false
    uuid: '964'
  - alias: name
    apiLegoId: 898
    apiLegoUuid: '898'
    description: null
    dt: string
    fieldName: name
    fieldValue: null
    handle: ''
    id: 965
    name: 员工姓名
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: '965'
- apiLego:
    apiAlias: ty-add-icon
    attributes: null
    description: null
    id: 900
    index: 2
    legoAlias: uniqueness
    oiAlias: ty_icon
    processControllerAlias: null
    uuid: '900'
  inputFields:
  - alias: iconClass
    apiLegoId: 900
    apiLegoUuid: '900'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: iconClass
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 5468
    ift: condition
    inputFieldDescribeId: 0
    name: 图标类
    requestParamName: iconClass
    sessionParamName: null
    uuid: '5468'
    validate: null
  outputFields:
  - alias: is_unique
    apiLegoId: 900
    apiLegoUuid: '900'
    description: null
    dt: string
    fieldName: is_unique
    fieldValue: null
    handle: '[{"handleName":"dataResultJudge","params":"true"}]'
    id: 966
    name: 是否唯一
    oft: common
    outputFieldDescribeId: 27
    response: false
    uuid: '966'
- apiLego:
    apiAlias: ty-add-icon
    attributes: null
    description: null
    id: 897
    index: 3
    legoAlias: add
    oiAlias: ty_icon
    processControllerAlias: null
    uuid: '897'
  inputFields:
  - alias: iconClass
    apiLegoId: 897
    apiLegoUuid: '897'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: iconClass
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 5462
    ift: create
    inputFieldDescribeId: 0
    name: 图标类
    requestParamName: iconClass
    sessionParamName: null
    uuid: '5462'
    validate: null
  - alias: type
    apiLegoId: 897
    apiLegoUuid: '897'
    attributes: ''
    connectorPath: ''
    constant: TY
    ct: eq
    description: ''
    dt: string
    fieldName: type
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 5463
    ift: create
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: ''
    uuid: '5463'
    validate: ''
  - alias: createDate
    apiLegoId: 897
    apiLegoUuid: '897'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5464
    ift: create
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: null
    uuid: '5464'
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: createUser
    apiLegoId: 897
    apiLegoUuid: '897'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: createUser
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 898
    fromApiLegoOutputFieldAlias: name
    fromApiLegoUuid: '898'
    fvt: output
    id: 5465
    ift: create
    inputFieldDescribeId: 0
    name: 创建用户
    requestParamName: createUser
    sessionParamName: null
    uuid: '5465'
    validate: ''
  outputFields:
  - alias: unique_value
    apiLegoId: 897
    apiLegoUuid: '897'
    description: null
    dt: string
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 963
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 33
    response: true
    uuid: '963'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
