api:
  alias: ty-add-app-role
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-09T18:16:33Z
  description: 添加应用角色
  id: 446
  method: POST
  name: 添加应用角色
  type: ty
  url: ty-add-app-role
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-add-app-role
    attributes: null
    description: null
    id: 779
    index: 1
    legoAlias: sessionRead
    oiAlias: null
    processControllerAlias: null
    uuid: '779'
  inputFields:
  - alias: E_SESSION_USER_DETAIL_KEY
    apiLegoId: 779
    apiLegoUuid: '779'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: E_SESSION_USER_DETAIL_KEY
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: ''
    id: 4295
    ift: common
    inputFieldDescribeId: 0
    name: 用户信息
    requestParamName: ''
    sessionParamName: null
    uuid: '4295'
    validate: ''
  outputFields:
  - alias: data
    apiLegoId: 779
    apiLegoUuid: '779'
    description: null
    dt: null
    fieldName: data
    fieldValue: null
    handle: null
    id: 816
    name: 读取数据
    oft: common
    outputFieldDescribeId: 49
    response: false
    uuid: '816'
  - alias: id
    apiLegoId: 779
    apiLegoUuid: '779'
    description: null
    dt: string
    fieldName: id
    fieldValue: null
    handle: ''
    id: 817
    name: 用户id
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: '817'
  - alias: name
    apiLegoId: 779
    apiLegoUuid: '779'
    description: null
    dt: string
    fieldName: name
    fieldValue: null
    handle: ''
    id: 818
    name: 用户姓名
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: '818'
- apiLego:
    apiAlias: ty-add-app-role
    attributes: null
    description: null
    id: 778
    index: 2
    legoAlias: add
    oiAlias: ty_app_role
    processControllerAlias: null
    uuid: '778'
  inputFields:
  - alias: name
    apiLegoId: 778
    apiLegoUuid: '778'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: 角色名称
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4296
    ift: create
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '4296'
    validate: ''
  - alias: description
    apiLegoId: 778
    apiLegoUuid: '778'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: 应用描述
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4297
    ift: create
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '4297'
    validate: ''
  - alias: appAlias
    apiLegoId: 778
    apiLegoUuid: '778'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: 应用别名
    dt: string
    fieldName: appAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4298
    ift: create
    inputFieldDescribeId: 0
    name: 应用别名
    requestParamName: appAlias
    sessionParamName: null
    uuid: '4298'
    validate: ''
  - alias: resources
    apiLegoId: 778
    apiLegoUuid: '778'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: 资源列表
    dt: string
    fieldName: resources
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4299
    ift: create
    inputFieldDescribeId: 0
    name: 资源列表
    requestParamName: resources
    sessionParamName: null
    uuid: '4299'
    validate: ''
  - alias: createDate
    apiLegoId: 778
    apiLegoUuid: '778'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4300
    ift: create
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: null
    uuid: '4300'
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: alias
    apiLegoId: 778
    apiLegoUuid: '778'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: 角色别名
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 4301
    ift: create
    inputFieldDescribeId: 0
    name: 角色别名
    requestParamName: alias
    sessionParamName: ''
    uuid: '4301'
    validate: ''
  - alias: superFlag
    apiLegoId: 778
    apiLegoUuid: '778'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: 超级角色
    dt: string
    fieldName: superFlag
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 4302
    ift: create
    inputFieldDescribeId: 0
    name: 超级角色
    requestParamName: superFlag
    sessionParamName: ''
    uuid: '4302'
    validate: ''
  outputFields:
  - alias: unique_value
    apiLegoId: 778
    apiLegoUuid: '778'
    description: null
    dt: null
    fieldName: unique_value
    fieldValue: null
    handle: null
    id: 815
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 33
    response: false
    uuid: '815'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
