api:
  alias: ty-add-user-app-role
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-13T13:52:56Z
  description: ''
  id: 461
  method: POST
  name: 添加TY用户授权
  type: ty
  url: ty-add-user-app-role
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-add-user-app-role
    attributes: null
    description: ''
    id: 5723
    index: 1
    legoAlias: read
    oiAlias: ty_user_app_role
    processControllerAlias: null
    uuid: 8F893EB1-6E94-4B91-8079-4ED77CA627151527665928445
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 8F893EB1-6E94-4B91-8079-4ED77CA627151527665928445
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53058
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: 29F0FF95-0765-475E-A1B2-BEDD40C014E01527665928445
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 8F893EB1-6E94-4B91-8079-4ED77CA627151527665928445
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53059
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: 468F9A95-FB2F-4F9E-B3EC-4086C2DEB23C1527665928445
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 8F893EB1-6E94-4B91-8079-4ED77CA627151527665928445
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53060
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: 99EBA491-FD2D-4124-B6C8-7C7F2631D33A1527665928445
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 8F893EB1-6E94-4B91-8079-4ED77CA627151527665928445
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53061
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: B147A2D9-60C6-475F-975F-03790986D2B51527665967861
    validate: null
  - alias: userAlias
    apiLegoId: 0
    apiLegoUuid: 8F893EB1-6E94-4B91-8079-4ED77CA627151527665928445
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: userAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53062
    ift: condition
    inputFieldDescribeId: 0
    name: userAlias
    requestParamName: userAlias
    sessionParamName: ''
    uuid: 2D306B0D-4555-450F-A3E8-3B9AFD63E9711527665988505
    validate: null
  - alias: appAlias
    apiLegoId: 0
    apiLegoUuid: 8F893EB1-6E94-4B91-8079-4ED77CA627151527665928445
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: appAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53063
    ift: condition
    inputFieldDescribeId: 0
    name: appAlias
    requestParamName: appAlias
    sessionParamName: ''
    uuid: 6E5D409B-287A-47FF-B1FE-EAEC0C44E96F1527665988505
    validate: null
  - alias: roles
    apiLegoId: 0
    apiLegoUuid: 8F893EB1-6E94-4B91-8079-4ED77CA627151527665928445
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: roles
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53064
    ift: condition
    inputFieldDescribeId: 0
    name: roles
    requestParamName: roles
    sessionParamName: ''
    uuid: FF3A8270-EDE2-4D42-A22C-E3B1759659801527665988505
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 0
    apiLegoUuid: 8F893EB1-6E94-4B91-8079-4ED77CA627151527665928445
    description: ''
    dt: ''
    fieldName: data
    fieldValue: null
    handle: '[]'
    id: 7985
    name: data
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: E2931FB9-93FC-41B0-B877-F408BCF612C11527665928445
- apiLego:
    apiAlias: ty-add-user-app-role
    attributes: null
    description: ''
    id: 5724
    index: 2
    legoAlias: read
    oiAlias: ty_user
    processControllerAlias: null
    uuid: 93587618-04C4-4E90-8541-C372275C5A781527665749365
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 93587618-04C4-4E90-8541-C372275C5A781527665749365
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53065
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: 8032DD0A-12BD-4209-86BB-D8B5B8DD24411527665749365
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 93587618-04C4-4E90-8541-C372275C5A781527665749365
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53066
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: E537A4A8-4980-4965-8BBE-0FD80D16CDE61527665749365
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 93587618-04C4-4E90-8541-C372275C5A781527665749365
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53067
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: 0C4015F3-65CE-40EB-BEF6-2DF25753DE151527665749365
    validate: null
  - alias: xingMing
    apiLegoId: 0
    apiLegoUuid: 93587618-04C4-4E90-8541-C372275C5A781527665749365
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: xingMing
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53068
    ift: read
    inputFieldDescribeId: 0
    name: 姓名
    requestParamName: xingMing
    sessionParamName: ''
    uuid: DC216312-A1DD-413C-B80B-C59EB96F22461527665786960
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: 93587618-04C4-4E90-8541-C372275C5A781527665749365
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53069
    ift: condition
    inputFieldDescribeId: 0
    name: 用户别名
    requestParamName: userAlias
    sessionParamName: ''
    uuid: F61ACB82-D11F-48E0-BE15-85C9FBA974951527665793605
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 0
    apiLegoUuid: 93587618-04C4-4E90-8541-C372275C5A781527665749365
    description: ''
    dt: ''
    fieldName: data
    fieldValue: null
    handle: ''
    id: 7986
    name: data
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: 1E2CB01C-1776-4C2C-A2DD-62A3BBF3B3A71527665749365
- apiLego:
    apiAlias: ty-add-user-app-role
    attributes: null
    description: ''
    id: 5725
    index: 3
    legoAlias: add
    oiAlias: ty_user_app_role
    processControllerAlias: null
    uuid: '834'
  inputFields:
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '834'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ${node.data.xingMing}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: 93587618-04C4-4E90-8541-C372275C5A781527665749365
    fvt: template
    id: 53070
    ift: create
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: '4818'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '834'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53071
    ift: create
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: '4819'
    validate: null
  - alias: userAlias
    apiLegoId: 0
    apiLegoUuid: '834'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: userAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53072
    ift: create
    inputFieldDescribeId: 0
    name: userAlias
    requestParamName: userAlias
    sessionParamName: ''
    uuid: '4820'
    validate: null
  - alias: roles
    apiLegoId: 0
    apiLegoUuid: '834'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: roles
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53073
    ift: create
    inputFieldDescribeId: 0
    name: roles
    requestParamName: roles
    sessionParamName: ''
    uuid: '4822'
    validate: null
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: '834'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 53074
    ift: create
    inputFieldDescribeId: 0
    name: createDate
    requestParamName: createDate
    sessionParamName: ''
    uuid: '4823'
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: appAlias
    apiLegoId: 0
    apiLegoUuid: '834'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: appAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53075
    ift: create
    inputFieldDescribeId: 0
    name: appAlias
    requestParamName: appAlias
    sessionParamName: ''
    uuid: '5077'
    validate: ''
  outputFields:
  - alias: unique_value
    apiLegoId: 0
    apiLegoUuid: '834'
    description: ''
    dt: ''
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 7987
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: '884'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
