api:
  alias: ty-all-page-log
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-05-29T15:37:56Z
  description: null
  id: 1223
  method: POST
  name: 分页获取TY日志（全部）
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-all-page-log
    attributes: null
    description: ''
    id: 5616
    index: 1
    legoAlias: page
    oiAlias: ty_log
    processControllerAlias: null
    uuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
  inputFields:
  - alias: page
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: page
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 51529
    ift: common
    inputFieldDescribeId: 0
    name: 请求页码
    requestParamName: page
    sessionParamName: ''
    uuid: 13A87ED0-1692-4CA7-981A-FD07EA4BC6A61527579491873
    validate: null
  - alias: pageSize
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: pageSize
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 51530
    ift: common
    inputFieldDescribeId: 0
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: ''
    uuid: 65CEA098-2E74-4DA1-91A9-2D7657DEA75E1527579491873
    validate: null
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: id
    ct: eq
    description: ''
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 51531
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: 46271FF2-635F-4320-882F-5CFD41DD45941527579491873
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: desc
    ct: eq
    description: ''
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 51532
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: C8FDDC87-A5E3-4BA2-9770-F7ECC303A4D61527579491873
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 51533
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: ADDCD515-EE18-40A9-BB8C-86C432C851FD1527579491873
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 51534
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: F7BF5BBE-8CF0-4740-8558-7D12B6F5C9C51527579491873
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: '["operateApi","operateLego","operateOi","operateUserName"]'
    ct: eq
    description: ''
    dt: string
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 51535
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: E25F7CF9-29BC-4988-B98A-5EE1B56247FA1527579491873
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 51536
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: 35E88EEE-165D-43E8-8717-5142127BE0E31527579588503
    validate: null
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: time
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 51537
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: ''
    uuid: 82FC5048-7BF2-424A-AC7F-EA91BE3B72C21527579588503
    validate: null
  - alias: operateUserName
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateUserName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 51538
    ift: read
    inputFieldDescribeId: 0
    name: 操作用户姓名
    requestParamName: operateUserName
    sessionParamName: ''
    uuid: FE16E7F0-7997-4129-9416-F27B9EB3FC971527579588504
    validate: null
  - alias: operateApi
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateApi
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 51539
    ift: read
    inputFieldDescribeId: 0
    name: 操作接口
    requestParamName: operateApi
    sessionParamName: ''
    uuid: 6AFE5A6C-C483-4D54-830B-E45EA1BF96021527579588505
    validate: null
  - alias: operateLego
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateLego
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 51540
    ift: read
    inputFieldDescribeId: 0
    name: 操作乐高
    requestParamName: operateLego
    sessionParamName: ''
    uuid: 2BEBAD91-B20A-49EE-8AE6-DE15C8C8DD6A1527579588505
    validate: null
  - alias: input
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: input
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 51541
    ift: read
    inputFieldDescribeId: 0
    name: 输入
    requestParamName: input
    sessionParamName: ''
    uuid: 8691F962-3E73-45DE-82E6-8C03EB994A9B1527579588505
    validate: null
  - alias: output
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: output
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 51542
    ift: read
    inputFieldDescribeId: 0
    name: 输出
    requestParamName: output
    sessionParamName: ''
    uuid: 40A1758A-3F84-43D5-B576-50302A7161541527579588505
    validate: null
  - alias: content
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: content
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 51543
    ift: read
    inputFieldDescribeId: 0
    name: 操作内容
    requestParamName: content
    sessionParamName: ''
    uuid: 556F0125-D301-43B6-B47F-ACD0937C7B7C1527579588505
    validate: null
  - alias: operateOi
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateOi
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 51544
    ift: read
    inputFieldDescribeId: 0
    name: 操作OI
    requestParamName: operateOi
    sessionParamName: ''
    uuid: 6AFDDB2F-C6A5-4FCD-9A8F-0EA6F02372671527579588505
    validate: null
  - alias: operateUserAlias
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateUserAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 51545
    ift: read
    inputFieldDescribeId: 0
    name: 操作用户标识
    requestParamName: operateUserAlias
    sessionParamName: ''
    uuid: 128A127A-C1B3-4EC2-8BBF-AD512D16BBAC1527579900851
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 0
    apiLegoUuid: 0B7B1732-F181-4859-8459-B3475E32781F1527579491873
    description: ''
    dt: ''
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 7860
    name: page_data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: BEB405A0-A8FB-489E-B39F-FD9AE0A881771527579491873
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
