api:
  alias: ty-api-generate
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-29T17:44:25Z
  description: 一键生成接口
  id: 485
  method: GET
  name: 一键生成接口
  type: ty
  url: ty-api-generate
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-api-generate
    attributes: null
    description: null
    id: 946
    index: 1
    legoAlias: uniqueness
    oiAlias: ty_api
    processControllerAlias: null
    uuid: '946'
  inputFields:
  - alias: alias
    apiLegoId: 946
    apiLegoUuid: '946'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 5951
    ift: condition
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '5951'
    validate: ''
  outputFields:
  - alias: is_unique
    apiLegoId: 946
    apiLegoUuid: '946'
    description: ''
    dt: string
    fieldName: is_unique
    fieldValue: null
    handle: '[{"handleName":"dataResultJudge","params":"true"}]'
    id: 1016
    name: 是否唯一
    oft: common
    outputFieldDescribeId: 27
    response: false
    uuid: '1016'
- apiLego:
    apiAlias: ty-api-generate
    attributes: null
    description: null
    id: 942
    index: 2
    legoAlias: add
    oiAlias: ty_api
    processControllerAlias: null
    uuid: '942'
  inputFields:
  - alias: name
    apiLegoId: 942
    apiLegoUuid: '942'
    attributes: null
    connectorPath: ''
    constant: 一键生成接口
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: 5924
    ift: create
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '5924'
    validate: ''
  - alias: description
    apiLegoId: 942
    apiLegoUuid: '942'
    attributes: null
    connectorPath: ''
    constant: 一键生成接口
    ct: eq
    description: null
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: 5925
    ift: create
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '5925'
    validate: ''
  - alias: alias
    apiLegoId: 942
    apiLegoUuid: '942'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 5926
    ift: create
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '5926'
    validate: '[{"validateName":"required"}]'
  - alias: createDate
    apiLegoId: 942
    apiLegoUuid: '942'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5927
    ift: create
    inputFieldDescribeId: 0
    name: 创建日期
    requestParamName: createDate
    sessionParamName: null
    uuid: '5927'
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: enable
    apiLegoId: 942
    apiLegoUuid: '942'
    attributes: null
    connectorPath: ''
    constant: '1'
    ct: eq
    description: null
    dt: string
    fieldName: enable
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: 5928
    ift: create
    inputFieldDescribeId: 0
    name: 可用
    requestParamName: enable
    sessionParamName: null
    uuid: '5928'
    validate: ''
  - alias: method
    apiLegoId: 942
    apiLegoUuid: '942'
    attributes: null
    connectorPath: ''
    constant: POST
    ct: eq
    description: null
    dt: string
    fieldName: method
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: 5929
    ift: create
    inputFieldDescribeId: 0
    name: 调用方法
    requestParamName: method
    sessionParamName: null
    uuid: '5929'
    validate: ''
  - alias: type
    apiLegoId: 942
    apiLegoUuid: '942'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: type
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 5930
    ift: create
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: null
    uuid: '5930'
    validate: '[{"validateName":"required"}]'
  - alias: category
    apiLegoId: 942
    apiLegoUuid: '942'
    attributes: null
    connectorPath: ''
    constant: config
    ct: eq
    description: null
    dt: string
    fieldName: category
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: 5931
    ift: create
    inputFieldDescribeId: 0
    name: 接口分类
    requestParamName: category
    sessionParamName: null
    uuid: '5931'
    validate: ''
  - alias: url
    apiLegoId: 942
    apiLegoUuid: '942'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: url
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 5956
    ift: create
    inputFieldDescribeId: 0
    name: 接口地址
    requestParamName: alias
    sessionParamName: null
    uuid: '5956'
    validate: ''
  outputFields:
  - alias: apiId
    apiLegoId: 942
    apiLegoUuid: '942'
    description: null
    dt: string
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 1013
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 33
    response: true
    uuid: '1013'
- apiLego:
    apiAlias: ty-api-generate
    attributes: null
    description: null
    id: 943
    index: 3
    legoAlias: add
    oiAlias: ty_api_lego
    processControllerAlias: null
    uuid: '943'
  inputFields:
  - alias: apiAlias
    apiLegoId: 943
    apiLegoUuid: '943'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: apiAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 5932
    ift: create
    inputFieldDescribeId: 0
    name: API别名
    requestParamName: alias
    sessionParamName: null
    uuid: '5932'
    validate: ''
  - alias: legoAlias
    apiLegoId: 943
    apiLegoUuid: '943'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: legoAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 5933
    ift: create
    inputFieldDescribeId: 0
    name: 乐高别名
    requestParamName: legoAlias
    sessionParamName: null
    uuid: '5933'
    validate: null
  - alias: oiAlias
    apiLegoId: 943
    apiLegoUuid: '943'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: oiAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 5934
    ift: create
    inputFieldDescribeId: 0
    name: OI别名
    requestParamName: oiAlias
    sessionParamName: null
    uuid: '5934'
    validate: null
  - alias: index
    apiLegoId: 943
    apiLegoUuid: '943'
    attributes: null
    connectorPath: ''
    constant: '1'
    ct: eq
    description: null
    dt: string
    fieldName: index
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: 5935
    ift: create
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: index
    sessionParamName: null
    uuid: '5935'
    validate: ''
  - alias: description
    apiLegoId: 943
    apiLegoUuid: '943'
    attributes: null
    connectorPath: ''
    constant: 一键生成接口
    ct: eq
    description: null
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: 5936
    ift: create
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '5936'
    validate: ''
  outputFields:
  - alias: apiLegoId
    apiLegoId: 943
    apiLegoUuid: '943'
    description: null
    dt: string
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 1014
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 33
    response: true
    uuid: '1014'
- apiLego:
    apiAlias: ty-api-generate
    attributes: null
    description: null
    id: 944
    index: 4
    legoAlias: legoBuilder
    oiAlias: null
    processControllerAlias: null
    uuid: '944'
  inputFields:
  - alias: apiLegoId
    apiLegoId: 944
    apiLegoUuid: '944'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: apiLegoId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 943
    fromApiLegoOutputFieldAlias: apiLegoId
    fromApiLegoUuid: '943'
    fvt: output
    id: 5937
    ift: common
    inputFieldDescribeId: 95
    name: 生成的apiLegoId
    requestParamName: apiLegoId
    sessionParamName: null
    uuid: '5937'
    validate: '[{"validateName":"required"}]'
  - alias: oiAlias
    apiLegoId: 944
    apiLegoUuid: '944'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: oiAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 5938
    ift: common
    inputFieldDescribeId: 96
    name: OI别名
    requestParamName: oiAlias
    sessionParamName: null
    uuid: '5938'
    validate: ''
  - alias: legoGenerator
    apiLegoId: 944
    apiLegoUuid: '944'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: legoGenerator
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 5939
    ift: common
    inputFieldDescribeId: 97
    name: Lego别名
    requestParamName: legoAlias
    sessionParamName: null
    uuid: '5939'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
