api:
  alias: ty-add-user
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-14T13:59:23Z
  description: ''
  id: 465
  method: POST
  name: TY添加用户
  type: ty
  url: ty-add-user
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-add-user
    attributes: null
    description: ''
    id: 5753
    index: 1
    legoAlias: add
    oiAlias: ty_user
    processControllerAlias: null
    uuid: '865'
  inputFields:
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: '865'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53494
    ift: create
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: ''
    uuid: '5092'
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: xingMing
    apiLegoId: 0
    apiLegoUuid: '865'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: xingMing
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53495
    ift: create
    inputFieldDescribeId: 0
    name: 姓名
    requestParamName: xingMing
    sessionParamName: ''
    uuid: '5093'
    validate: null
  - alias: userName
    apiLegoId: 0
    apiLegoUuid: '865'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: userName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53496
    ift: create
    inputFieldDescribeId: 0
    name: 用户名
    requestParamName: userName
    sessionParamName: ''
    uuid: '5094'
    validate: null
  - alias: password
    apiLegoId: 0
    apiLegoUuid: '865'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: password
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53497
    ift: create
    inputFieldDescribeId: 0
    name: 密码
    requestParamName: password
    sessionParamName: ''
    uuid: '5095'
    validate: '[{"validateName":"md5Encrypt"}]'
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '865'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53498
    ift: create
    inputFieldDescribeId: 0
    name: 用户别名
    requestParamName: alias
    sessionParamName: ''
    uuid: '5096'
    validate: null
  - alias: tenantSerialNumber
    apiLegoId: 0
    apiLegoUuid: '865'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: tenantSerialNumber
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53499
    ift: create
    inputFieldDescribeId: 0
    name: 租户序列号
    requestParamName: tenantSerialNumber
    sessionParamName: ''
    uuid: 35468CD5-4714-4004-B05B-97EB2A96438D1527770058686
    validate: null
  outputFields:
  - alias: unique_value
    apiLegoId: 0
    apiLegoUuid: '865'
    description: ''
    dt: string
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 8015
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '919'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
