api:
  alias: ty-add-task
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-12T15:30:39Z
  description: 一键生成接口
  id: 502
  method: POST
  name: 添加任务
  type: ty
  url: ty-add-task
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-add-task
    attributes: null
    description: 一键生成接口
    id: 979
    index: 1
    legoAlias: add
    oiAlias: ty_task
    processControllerAlias: null
    uuid: '979'
  inputFields:
  - alias: name
    apiLegoId: 979
    apiLegoUuid: '979'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6153
    ift: create
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '6153'
    validate: null
  - alias: description
    apiLegoId: 979
    apiLegoUuid: '979'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6154
    ift: create
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '6154'
    validate: null
  - alias: alias
    apiLegoId: 979
    apiLegoUuid: '979'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6155
    ift: create
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '6155'
    validate: null
  - alias: group
    apiLegoId: 979
    apiLegoUuid: '979'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: group
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6156
    ift: create
    inputFieldDescribeId: 0
    name: 组别
    requestParamName: group
    sessionParamName: null
    uuid: '6156'
    validate: null
  - alias: cron
    apiLegoId: 979
    apiLegoUuid: '979'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: cron
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6157
    ift: create
    inputFieldDescribeId: 0
    name: 执行规则
    requestParamName: cron
    sessionParamName: null
    uuid: '6157'
    validate: null
  - alias: status
    apiLegoId: 979
    apiLegoUuid: '979'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: status
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6158
    ift: create
    inputFieldDescribeId: 0
    name: 状态
    requestParamName: status
    sessionParamName: null
    uuid: '6158'
    validate: null
  - alias: createDate
    apiLegoId: 979
    apiLegoUuid: '979'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: 一键生成
    dt: string
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 6159
    ift: create
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: ''
    uuid: '6159'
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: apiAlias
    apiLegoId: 979
    apiLegoUuid: '979'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: apiAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6160
    ift: create
    inputFieldDescribeId: 0
    name: 接口别名
    requestParamName: apiAlias
    sessionParamName: null
    uuid: '6160'
    validate: null
  - alias: createrId
    apiLegoId: 979
    apiLegoUuid: '979'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: createrId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: template
    id: 9001
    ift: create
    inputFieldDescribeId: 0
    name: 创建人id
    requestParamName: createrId
    sessionParamName: null
    uuid: '9001'
    validate: ''
  - alias: createrName
    apiLegoId: 979
    apiLegoUuid: '979'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: createrName
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.xingMing}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: template
    id: 9002
    ift: create
    inputFieldDescribeId: 0
    name: 创建人姓名
    requestParamName: createrName
    sessionParamName: null
    uuid: '9002'
    validate: ''
  - alias: owerId
    apiLegoId: 979
    apiLegoUuid: '979'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: owerId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: template
    id: 9003
    ift: create
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: null
    uuid: '9003'
    validate: ''
  - alias: owerName
    apiLegoId: 979
    apiLegoUuid: '979'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: owerName
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.xingMing}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: template
    id: 9004
    ift: create
    inputFieldDescribeId: 0
    name: 负责人名称
    requestParamName: owerName
    sessionParamName: null
    uuid: '9004'
    validate: ''
  outputFields:
  - alias: unique_value
    apiLegoId: 979
    apiLegoUuid: '979'
    description: 一键生成
    dt: null
    fieldName: unique_value
    fieldValue: null
    handle: null
    id: 1047
    name: unique_value
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1047'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
