api:
  alias: ty-add-auth-type
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-20T15:28:56Z
  description: 一键生成接口
  id: 551
  method: POST
  name: 添加授权
  type: ty
  url: ty-add-auth-type
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-add-auth-type
    attributes: null
    description: 一键生成接口
    id: 1083
    index: 1
    legoAlias: add
    oiAlias: ty_auth_type
    processControllerAlias: null
    uuid: '1083'
  inputFields:
  - alias: name
    apiLegoId: 1083
    apiLegoUuid: '1083'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7025
    ift: create
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '7025'
    validate: null
  - alias: description
    apiLegoId: 1083
    apiLegoUuid: '1083'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7026
    ift: create
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '7026'
    validate: null
  - alias: alias
    apiLegoId: 1083
    apiLegoUuid: '1083'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7027
    ift: create
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '7027'
    validate: null
  - alias: judgeAPIAlias
    apiLegoId: 1083
    apiLegoUuid: '1083'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: judgeAPIAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7028
    ift: create
    inputFieldDescribeId: 0
    name: 判断执行的API
    requestParamName: judgeAPIAlias
    sessionParamName: null
    uuid: '7028'
    validate: null
  - alias: noAuthErrorCode
    apiLegoId: 1083
    apiLegoUuid: '1083'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: noAuthErrorCode
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7029
    ift: create
    inputFieldDescribeId: 0
    name: 错误代码
    requestParamName: noAuthErrorCode
    sessionParamName: null
    uuid: '7029'
    validate: null
  outputFields:
  - alias: unique_value
    apiLegoId: 1083
    apiLegoUuid: '1083'
    description: 一键生成
    dt: null
    fieldName: unique_value
    fieldValue: null
    handle: null
    id: 1185
    name: unique_value
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1185'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
