api:
  alias: ty-count-DOAP-self
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-14T16:35:50Z
  description: DS总数，OI总数，API总数，Page总数的接口
  id: 652
  method: GET
  name: 我的DOAP总数
  type: ty
  url: ty-count-DOAP-self
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-count-DOAP-self
    attributes: null
    description: null
    id: 1300
    index: 1
    legoAlias: count
    oiAlias: ty_ds
    processControllerAlias: null
    uuid: '1300'
  inputFields:
  - alias: global_search_fields
    apiLegoId: 1300
    apiLegoUuid: '1300'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9088
    ift: common
    inputFieldDescribeId: 75
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '9088'
    validate: null
  - alias: keywords
    apiLegoId: 1300
    apiLegoUuid: '1300'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9089
    ift: common
    inputFieldDescribeId: 76
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '9089'
    validate: null
  - alias: group_field
    apiLegoId: 1300
    apiLegoUuid: '1300'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9090
    ift: common
    inputFieldDescribeId: 77
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '9090'
    validate: null
  - alias: order
    apiLegoId: 1300
    apiLegoUuid: '1300'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9091
    ift: common
    inputFieldDescribeId: 78
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '9091'
    validate: null
  - alias: order_field
    apiLegoId: 1300
    apiLegoUuid: '1300'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9092
    ift: common
    inputFieldDescribeId: 79
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '9092'
    validate: null
  - alias: id
    apiLegoId: 1300
    apiLegoUuid: '1300'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9108
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '9108'
    validate: null
  - alias: owerId
    apiLegoId: 1300
    apiLegoUuid: '1300'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: owerId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: template
    id: 9124
    ift: condition
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: null
    uuid: '9124'
    validate: ''
  outputFields:
  - alias: dsCount
    apiLegoId: 1300
    apiLegoUuid: '1300'
    description: null
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 1443
    name: 记录条数
    oft: common
    outputFieldDescribeId: 64
    response: true
    uuid: '1443'
- apiLego:
    apiAlias: ty-count-DOAP-self
    attributes: null
    description: null
    id: 1301
    index: 2
    legoAlias: count
    oiAlias: ty_oi
    processControllerAlias: null
    uuid: '1301'
  inputFields:
  - alias: global_search_fields
    apiLegoId: 1301
    apiLegoUuid: '1301'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9093
    ift: common
    inputFieldDescribeId: 75
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '9093'
    validate: null
  - alias: keywords
    apiLegoId: 1301
    apiLegoUuid: '1301'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9094
    ift: common
    inputFieldDescribeId: 76
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '9094'
    validate: null
  - alias: group_field
    apiLegoId: 1301
    apiLegoUuid: '1301'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9095
    ift: common
    inputFieldDescribeId: 77
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '9095'
    validate: null
  - alias: order
    apiLegoId: 1301
    apiLegoUuid: '1301'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9096
    ift: common
    inputFieldDescribeId: 78
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '9096'
    validate: null
  - alias: order_field
    apiLegoId: 1301
    apiLegoUuid: '1301'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9097
    ift: common
    inputFieldDescribeId: 79
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '9097'
    validate: null
  - alias: id
    apiLegoId: 1301
    apiLegoUuid: '1301'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9109
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '9109'
    validate: null
  - alias: owerId
    apiLegoId: 1301
    apiLegoUuid: '1301'
    attributes: null
    connectorPath: '[{"alias":"oi_ds"}]'
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: owerId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: template
    id: 9125
    ift: condition
    inputFieldDescribeId: 0
    name: dsAlias-负责人ID
    requestParamName: owerId
    sessionParamName: null
    uuid: '9125'
    validate: ''
  outputFields:
  - alias: oiCount
    apiLegoId: 1301
    apiLegoUuid: '1301'
    description: null
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 1444
    name: 记录条数
    oft: common
    outputFieldDescribeId: 64
    response: true
    uuid: '1444'
- apiLego:
    apiAlias: ty-count-DOAP-self
    attributes: null
    description: null
    id: 1302
    index: 3
    legoAlias: count
    oiAlias: ty_api
    processControllerAlias: null
    uuid: '1302'
  inputFields:
  - alias: global_search_fields
    apiLegoId: 1302
    apiLegoUuid: '1302'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9098
    ift: common
    inputFieldDescribeId: 75
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '9098'
    validate: null
  - alias: keywords
    apiLegoId: 1302
    apiLegoUuid: '1302'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9099
    ift: common
    inputFieldDescribeId: 76
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '9099'
    validate: null
  - alias: group_field
    apiLegoId: 1302
    apiLegoUuid: '1302'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9100
    ift: common
    inputFieldDescribeId: 77
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '9100'
    validate: null
  - alias: order
    apiLegoId: 1302
    apiLegoUuid: '1302'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9101
    ift: common
    inputFieldDescribeId: 78
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '9101'
    validate: null
  - alias: order_field
    apiLegoId: 1302
    apiLegoUuid: '1302'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9102
    ift: common
    inputFieldDescribeId: 79
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '9102'
    validate: null
  - alias: id
    apiLegoId: 1302
    apiLegoUuid: '1302'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9110
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '9110'
    validate: null
  - alias: owerId
    apiLegoId: 1302
    apiLegoUuid: '1302'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: owerId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: template
    id: 9126
    ift: condition
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: null
    uuid: '9126'
    validate: ''
  outputFields:
  - alias: apiCount
    apiLegoId: 1302
    apiLegoUuid: '1302'
    description: null
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 1445
    name: 记录条数
    oft: common
    outputFieldDescribeId: 64
    response: true
    uuid: '1445'
- apiLego:
    apiAlias: ty-count-DOAP-self
    attributes: null
    description: null
    id: 1303
    index: 4
    legoAlias: count
    oiAlias: ty_page
    processControllerAlias: null
    uuid: '1303'
  inputFields:
  - alias: global_search_fields
    apiLegoId: 1303
    apiLegoUuid: '1303'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9103
    ift: common
    inputFieldDescribeId: 75
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '9103'
    validate: null
  - alias: keywords
    apiLegoId: 1303
    apiLegoUuid: '1303'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9104
    ift: common
    inputFieldDescribeId: 76
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '9104'
    validate: null
  - alias: group_field
    apiLegoId: 1303
    apiLegoUuid: '1303'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9105
    ift: common
    inputFieldDescribeId: 77
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '9105'
    validate: null
  - alias: order
    apiLegoId: 1303
    apiLegoUuid: '1303'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9106
    ift: common
    inputFieldDescribeId: 78
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '9106'
    validate: null
  - alias: order_field
    apiLegoId: 1303
    apiLegoUuid: '1303'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9107
    ift: common
    inputFieldDescribeId: 79
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '9107'
    validate: null
  - alias: id
    apiLegoId: 1303
    apiLegoUuid: '1303'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9111
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '9111'
    validate: null
  - alias: owerId
    apiLegoId: 1303
    apiLegoUuid: '1303'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: owerId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: template
    id: 9127
    ift: condition
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: null
    uuid: '9127'
    validate: ''
  outputFields:
  - alias: pageCount
    apiLegoId: 1303
    apiLegoUuid: '1303'
    description: null
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 1446
    name: 记录条数
    oft: common
    outputFieldDescribeId: 64
    response: true
    uuid: '1446'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
