api:
  alias: ty-count-lego-bb
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-14T16:44:24Z
  description: 乐高总数，积木总数的接口
  id: 520
  method: GET
  name: LegoBB总数
  type: ty
  url: ty-count-lego-bb
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-count-lego-bb
    attributes: null
    description: null
    id: 1010
    index: 1
    legoAlias: count
    oiAlias: ty_lego
    processControllerAlias: null
    uuid: '1010'
  inputFields:
  - alias: global_search_fields
    apiLegoId: 1010
    apiLegoUuid: '1010'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6470
    ift: common
    inputFieldDescribeId: 75
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '6470'
    validate: null
  - alias: keywords
    apiLegoId: 1010
    apiLegoUuid: '1010'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6471
    ift: common
    inputFieldDescribeId: 76
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '6471'
    validate: null
  - alias: group_field
    apiLegoId: 1010
    apiLegoUuid: '1010'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6472
    ift: common
    inputFieldDescribeId: 77
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '6472'
    validate: null
  - alias: order
    apiLegoId: 1010
    apiLegoUuid: '1010'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6473
    ift: common
    inputFieldDescribeId: 78
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '6473'
    validate: null
  - alias: order_field
    apiLegoId: 1010
    apiLegoUuid: '1010'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6474
    ift: common
    inputFieldDescribeId: 79
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '6474'
    validate: null
  - alias: id
    apiLegoId: 1010
    apiLegoUuid: '1010'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 6475
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '6475'
    validate: null
  outputFields:
  - alias: legoCount
    apiLegoId: 1010
    apiLegoUuid: '1010'
    description: null
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 1079
    name: 记录条数
    oft: common
    outputFieldDescribeId: 64
    response: true
    uuid: '1079'
- apiLego:
    apiAlias: ty-count-lego-bb
    attributes: null
    description: null
    id: 1011
    index: 2
    legoAlias: count
    oiAlias: ty_building_block
    processControllerAlias: null
    uuid: '1011'
  inputFields:
  - alias: global_search_fields
    apiLegoId: 1011
    apiLegoUuid: '1011'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6476
    ift: common
    inputFieldDescribeId: 75
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '6476'
    validate: null
  - alias: keywords
    apiLegoId: 1011
    apiLegoUuid: '1011'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6477
    ift: common
    inputFieldDescribeId: 76
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '6477'
    validate: null
  - alias: group_field
    apiLegoId: 1011
    apiLegoUuid: '1011'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6478
    ift: common
    inputFieldDescribeId: 77
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '6478'
    validate: null
  - alias: order
    apiLegoId: 1011
    apiLegoUuid: '1011'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6479
    ift: common
    inputFieldDescribeId: 78
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '6479'
    validate: null
  - alias: order_field
    apiLegoId: 1011
    apiLegoUuid: '1011'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6480
    ift: common
    inputFieldDescribeId: 79
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '6480'
    validate: null
  - alias: id
    apiLegoId: 1011
    apiLegoUuid: '1011'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 6481
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '6481'
    validate: null
  outputFields:
  - alias: bbCount
    apiLegoId: 1011
    apiLegoUuid: '1011'
    description: null
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 1080
    name: 记录条数
    oft: common
    outputFieldDescribeId: 64
    response: true
    uuid: '1080'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
