api:
  alias: ty-count-lego-bb-self
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-14T16:44:24Z
  description: 乐高总数，积木总数的接口
  id: 653
  method: GET
  name: 我的LegoBB总数
  type: ty
  url: ty-count-lego-bb-self
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-count-lego-bb-self
    attributes: null
    description: ''
    id: 7557
    index: 1
    legoAlias: count
    oiAlias: ty_lego
    processControllerAlias: null
    uuid: '1304'
  inputFields:
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '1304'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 68444
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '9112'
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '1304'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 68445
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '9113'
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '1304'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 68446
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '9114'
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '1304'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 68447
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '9115'
    validate: null
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '1304'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 68448
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '9116'
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '1304'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68449
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: '9117'
    validate: null
  - alias: owerId
    apiLegoId: 0
    apiLegoUuid: '1304'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: owerId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 68450
    ift: condition
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: ''
    uuid: '9128'
    validate: ''
  outputFields:
  - alias: legoCount
    apiLegoId: 0
    apiLegoUuid: '1304'
    description: ''
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 10024
    name: 记录条数
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1447'
- apiLego:
    apiAlias: ty-count-lego-bb-self
    attributes: null
    description: ''
    id: 7558
    index: 2
    legoAlias: count
    oiAlias: ty_building_block
    processControllerAlias: null
    uuid: '1305'
  inputFields:
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '1305'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 68451
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '9118'
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '1305'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 68452
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '9119'
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '1305'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 68453
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '9120'
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '1305'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 68454
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '9121'
    validate: null
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '1305'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 68455
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '9122'
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '1305'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68456
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '9123'
    validate: null
  - alias: owerId
    apiLegoId: 0
    apiLegoUuid: '1305'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: owerId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 68457
    ift: condition
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: ''
    uuid: '9129'
    validate: ''
  outputFields:
  - alias: bbCount
    apiLegoId: 0
    apiLegoUuid: '1305'
    description: ''
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 10025
    name: 记录条数
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1448'
- apiLego:
    apiAlias: ty-count-lego-bb-self
    attributes: null
    description: ''
    id: 7559
    index: 3
    legoAlias: count
    oiAlias: ty_code
    processControllerAlias: null
    uuid: 249D7A4E-3C9B-4FAD-8C72-8CD371AF816B1530095151259
  inputFields:
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: 249D7A4E-3C9B-4FAD-8C72-8CD371AF816B1530095151259
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68458
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: 01B61D8B-4EB0-4E94-8FFC-CBB2B4E2E2E71530095151259
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: 249D7A4E-3C9B-4FAD-8C72-8CD371AF816B1530095151259
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68459
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: 78D8B81B-F9E6-412A-B806-66F246FA1A211530095151259
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 249D7A4E-3C9B-4FAD-8C72-8CD371AF816B1530095151259
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68460
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: D7C0A24A-216C-47C4-AEDC-66E6ED3BEB7F1530095151259
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 249D7A4E-3C9B-4FAD-8C72-8CD371AF816B1530095151259
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68461
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: E8EAD836-3678-4E49-A5EB-6C9A73DA25E31530095151259
    validate: null
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 249D7A4E-3C9B-4FAD-8C72-8CD371AF816B1530095151259
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68462
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: 4045D46D-BB66-40C2-8491-79AB89E3AC961530095151259
    validate: null
  - alias: owerId
    apiLegoId: 0
    apiLegoUuid: 249D7A4E-3C9B-4FAD-8C72-8CD371AF816B1530095151259
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: owerId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 68463
    ift: condition
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: ''
    uuid: 9F43FA57-A8F2-4C1A-A30C-CF73912304691530095337563
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 249D7A4E-3C9B-4FAD-8C72-8CD371AF816B1530095151259
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68464
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: EF1C0BC9-2C2C-49BC-B092-86E3FD968BA01530095341693
    validate: null
  outputFields:
  - alias: bzCount
    apiLegoId: 0
    apiLegoUuid: 249D7A4E-3C9B-4FAD-8C72-8CD371AF816B1530095151259
    description: ''
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 10026
    name: 记录条数
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 1522AFF9-4D70-427E-9EC2-1DAF6A0E16941530095151260
- apiLego:
    apiAlias: ty-count-lego-bb-self
    attributes: null
    description: ''
    id: 7560
    index: 4
    legoAlias: count
    oiAlias: ty_task
    processControllerAlias: null
    uuid: 2C74FF3A-14D4-419C-99F5-7117D531130B1530095548850
  inputFields:
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: 2C74FF3A-14D4-419C-99F5-7117D531130B1530095548850
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68465
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: 742860B6-3F87-4DEC-AF20-5AF7B04D39781530095548850
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: 2C74FF3A-14D4-419C-99F5-7117D531130B1530095548850
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68466
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: DA3ACD3E-B3F0-49E2-9972-F68402CBB0221530095548850
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 2C74FF3A-14D4-419C-99F5-7117D531130B1530095548850
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68467
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: 11DCD0D1-905C-4DD7-9114-6B73583A25C01530095548850
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 2C74FF3A-14D4-419C-99F5-7117D531130B1530095548850
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68468
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: A8B08223-B9D3-469D-9A1D-B501D8195CD81530095548850
    validate: null
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 2C74FF3A-14D4-419C-99F5-7117D531130B1530095548850
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68469
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: 7EE51F32-DD2A-4CAD-8439-43734B57E92F1530095548850
    validate: null
  - alias: owerId
    apiLegoId: 0
    apiLegoUuid: 2C74FF3A-14D4-419C-99F5-7117D531130B1530095548850
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: owerId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 68470
    ift: condition
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: ''
    uuid: 6E9DCD49-1AD8-4E38-A5DC-0D6766B93FDF1530095573125
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 2C74FF3A-14D4-419C-99F5-7117D531130B1530095548850
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68471
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: 90A70937-733A-4C93-B7C4-F4122F7732451530095576739
    validate: null
  outputFields:
  - alias: taskCount
    apiLegoId: 0
    apiLegoUuid: 2C74FF3A-14D4-419C-99F5-7117D531130B1530095548850
    description: ''
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 10027
    name: 记录条数
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 0CEFD8EB-1D2A-4ABD-B3EC-6C2F3C69C4291530095548850
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
