api:
  alias: ty-count-DOAP
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-14T16:35:50Z
  description: DS总数，OI总数，API总数，Page总数的接口
  id: 519
  method: GET
  name: DOAP总数
  type: ty
  url: ty-count-DOAP
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-count-DOAP
    attributes: null
    description: null
    id: 1004
    index: 1
    legoAlias: count
    oiAlias: ty_ds
    processControllerAlias: null
    uuid: '1004'
  inputFields:
  - alias: global_search_fields
    apiLegoId: 1004
    apiLegoUuid: '1004'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6425
    ift: common
    inputFieldDescribeId: 75
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '6425'
    validate: null
  - alias: keywords
    apiLegoId: 1004
    apiLegoUuid: '1004'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6426
    ift: common
    inputFieldDescribeId: 76
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '6426'
    validate: null
  - alias: group_field
    apiLegoId: 1004
    apiLegoUuid: '1004'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6427
    ift: common
    inputFieldDescribeId: 77
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '6427'
    validate: null
  - alias: order
    apiLegoId: 1004
    apiLegoUuid: '1004'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6428
    ift: common
    inputFieldDescribeId: 78
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '6428'
    validate: null
  - alias: order_field
    apiLegoId: 1004
    apiLegoUuid: '1004'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6429
    ift: common
    inputFieldDescribeId: 79
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '6429'
    validate: null
  - alias: id
    apiLegoId: 1004
    apiLegoUuid: '1004'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 6445
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '6445'
    validate: null
  outputFields:
  - alias: dsCount
    apiLegoId: 1004
    apiLegoUuid: '1004'
    description: null
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 1073
    name: 记录条数
    oft: common
    outputFieldDescribeId: 64
    response: true
    uuid: '1073'
- apiLego:
    apiAlias: ty-count-DOAP
    attributes: null
    description: null
    id: 1005
    index: 2
    legoAlias: count
    oiAlias: ty_oi
    processControllerAlias: null
    uuid: '1005'
  inputFields:
  - alias: global_search_fields
    apiLegoId: 1005
    apiLegoUuid: '1005'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6430
    ift: common
    inputFieldDescribeId: 75
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '6430'
    validate: null
  - alias: keywords
    apiLegoId: 1005
    apiLegoUuid: '1005'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6431
    ift: common
    inputFieldDescribeId: 76
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '6431'
    validate: null
  - alias: group_field
    apiLegoId: 1005
    apiLegoUuid: '1005'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6432
    ift: common
    inputFieldDescribeId: 77
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '6432'
    validate: null
  - alias: order
    apiLegoId: 1005
    apiLegoUuid: '1005'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6433
    ift: common
    inputFieldDescribeId: 78
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '6433'
    validate: null
  - alias: order_field
    apiLegoId: 1005
    apiLegoUuid: '1005'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6434
    ift: common
    inputFieldDescribeId: 79
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '6434'
    validate: null
  - alias: id
    apiLegoId: 1005
    apiLegoUuid: '1005'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 6446
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '6446'
    validate: null
  outputFields:
  - alias: oiCount
    apiLegoId: 1005
    apiLegoUuid: '1005'
    description: null
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 1074
    name: 记录条数
    oft: common
    outputFieldDescribeId: 64
    response: true
    uuid: '1074'
- apiLego:
    apiAlias: ty-count-DOAP
    attributes: null
    description: null
    id: 1006
    index: 3
    legoAlias: count
    oiAlias: ty_api
    processControllerAlias: null
    uuid: '1006'
  inputFields:
  - alias: global_search_fields
    apiLegoId: 1006
    apiLegoUuid: '1006'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6435
    ift: common
    inputFieldDescribeId: 75
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '6435'
    validate: null
  - alias: keywords
    apiLegoId: 1006
    apiLegoUuid: '1006'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6436
    ift: common
    inputFieldDescribeId: 76
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '6436'
    validate: null
  - alias: group_field
    apiLegoId: 1006
    apiLegoUuid: '1006'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6437
    ift: common
    inputFieldDescribeId: 77
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '6437'
    validate: null
  - alias: order
    apiLegoId: 1006
    apiLegoUuid: '1006'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6438
    ift: common
    inputFieldDescribeId: 78
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '6438'
    validate: null
  - alias: order_field
    apiLegoId: 1006
    apiLegoUuid: '1006'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6439
    ift: common
    inputFieldDescribeId: 79
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '6439'
    validate: null
  - alias: id
    apiLegoId: 1006
    apiLegoUuid: '1006'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 6447
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '6447'
    validate: null
  outputFields:
  - alias: apiCount
    apiLegoId: 1006
    apiLegoUuid: '1006'
    description: null
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 1075
    name: 记录条数
    oft: common
    outputFieldDescribeId: 64
    response: true
    uuid: '1075'
- apiLego:
    apiAlias: ty-count-DOAP
    attributes: null
    description: null
    id: 1007
    index: 4
    legoAlias: count
    oiAlias: ty_page
    processControllerAlias: null
    uuid: '1007'
  inputFields:
  - alias: global_search_fields
    apiLegoId: 1007
    apiLegoUuid: '1007'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6440
    ift: common
    inputFieldDescribeId: 75
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '6440'
    validate: null
  - alias: keywords
    apiLegoId: 1007
    apiLegoUuid: '1007'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6441
    ift: common
    inputFieldDescribeId: 76
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '6441'
    validate: null
  - alias: group_field
    apiLegoId: 1007
    apiLegoUuid: '1007'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6442
    ift: common
    inputFieldDescribeId: 77
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '6442'
    validate: null
  - alias: order
    apiLegoId: 1007
    apiLegoUuid: '1007'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6443
    ift: common
    inputFieldDescribeId: 78
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '6443'
    validate: null
  - alias: order_field
    apiLegoId: 1007
    apiLegoUuid: '1007'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6444
    ift: common
    inputFieldDescribeId: 79
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '6444'
    validate: null
  - alias: id
    apiLegoId: 1007
    apiLegoUuid: '1007'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 6448
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '6448'
    validate: null
  outputFields:
  - alias: pageCount
    apiLegoId: 1007
    apiLegoUuid: '1007'
    description: null
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 1076
    name: 记录条数
    oft: common
    outputFieldDescribeId: 64
    response: true
    uuid: '1076'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
