api:
  alias: ty-down-apiLego
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-02-25T10:03:02Z
  description: null
  id: 667
  method: POST
  name: API乐高下移
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-down-apiLego
    attributes: null
    description: null
    id: 1346
    index: 1
    legoAlias: read
    oiAlias: ty_api_lego
    processControllerAlias: null
    uuid: '1346'
  inputFields:
  - alias: order_field
    apiLegoId: 1346
    apiLegoUuid: '1346'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9427
    ift: common
    inputFieldDescribeId: 32
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '9427'
    validate: null
  - alias: order
    apiLegoId: 1346
    apiLegoUuid: '1346'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9428
    ift: common
    inputFieldDescribeId: 44
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '9428'
    validate: null
  - alias: group_field
    apiLegoId: 1346
    apiLegoUuid: '1346'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9429
    ift: common
    inputFieldDescribeId: 45
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '9429'
    validate: null
  - alias: id
    apiLegoId: 1346
    apiLegoUuid: '1346'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 9430
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '9430'
    validate: '[{"validateName":"required"}]'
  - alias: index
    apiLegoId: 1346
    apiLegoUuid: '1346'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: index
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9431
    ift: read
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: index
    sessionParamName: null
    uuid: '9431'
    validate: null
  - alias: apiAlias
    apiLegoId: 1346
    apiLegoUuid: '1346'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: apiAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9437
    ift: read
    inputFieldDescribeId: 0
    name: API别名
    requestParamName: apiAlias
    sessionParamName: null
    uuid: '9437'
    validate: null
  - alias: id
    apiLegoId: 1346
    apiLegoUuid: '1346'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9440
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '9440'
    validate: null
  outputFields:
  - alias: currentApiLego
    apiLegoId: 1346
    apiLegoUuid: '1346'
    description: ''
    dt: string
    fieldName: data
    fieldValue: null
    handle: ''
    id: 1480
    name: data
    oft: common
    outputFieldDescribeId: 32
    response: false
    uuid: '1480'
- apiLego:
    apiAlias: ty-down-apiLego
    attributes: null
    description: null
    id: 1347
    index: 2
    legoAlias: read
    oiAlias: ty_api_lego
    processControllerAlias: null
    uuid: '1347'
  inputFields:
  - alias: order_field
    apiLegoId: 1347
    apiLegoUuid: '1347'
    attributes: null
    connectorPath: ''
    constant: index
    ct: eq
    description: null
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 9432
    ift: common
    inputFieldDescribeId: 32
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '9432'
    validate: ''
  - alias: order
    apiLegoId: 1347
    apiLegoUuid: '1347'
    attributes: ''
    connectorPath: ''
    constant: ASC
    ct: eq
    description: ''
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 9433
    ift: common
    inputFieldDescribeId: 44
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '9433'
    validate: ''
  - alias: group_field
    apiLegoId: 1347
    apiLegoUuid: '1347'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9434
    ift: common
    inputFieldDescribeId: 45
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '9434'
    validate: null
  - alias: apiAlias
    apiLegoId: 1347
    apiLegoUuid: '1347'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: apiAlias
    fieldTpl: ${node.currentApiLego.apiAlias}
    fieldValue: null
    fromApiLegoId: 1346
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '1346'
    fvt: template
    id: 9435
    ift: condition
    inputFieldDescribeId: 0
    name: API别名
    requestParamName: apiAlias
    sessionParamName: null
    uuid: '9435'
    validate: ''
  - alias: index
    apiLegoId: 1347
    apiLegoUuid: '1347'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: gt
    description: ''
    dt: int
    fieldName: index
    fieldTpl: ${node.currentApiLego.index}
    fieldValue: null
    fromApiLegoId: 1346
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '1346'
    fvt: template
    id: 9436
    ift: condition
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: index
    sessionParamName: ''
    uuid: '9436'
    validate: ''
  - alias: id
    apiLegoId: 1347
    apiLegoUuid: '1347'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9438
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '9438'
    validate: null
  - alias: index
    apiLegoId: 1347
    apiLegoUuid: '1347'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: index
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9439
    ift: read
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: index
    sessionParamName: null
    uuid: '9439'
    validate: null
  outputFields:
  - alias: prevApiLego
    apiLegoId: 1347
    apiLegoUuid: '1347'
    description: ''
    dt: string
    fieldName: data
    fieldValue: null
    handle: '[{"handleName":"notNullJudge","params":"不能下移"}]'
    id: 1481
    name: data
    oft: common
    outputFieldDescribeId: 32
    response: false
    uuid: '1481'
- apiLego:
    apiAlias: ty-down-apiLego
    attributes: null
    description: null
    id: 1348
    index: 3
    legoAlias: update
    oiAlias: ty_api_lego
    processControllerAlias: null
    uuid: '1348'
  inputFields:
  - alias: index
    apiLegoId: 1348
    apiLegoUuid: '1348'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: index
    fieldTpl: ${node.prevApiLego.index}
    fieldValue: null
    fromApiLegoId: 1347
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '1347'
    fvt: template
    id: 9441
    ift: update
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: index
    sessionParamName: ''
    uuid: '9441'
    validate: ''
  - alias: id
    apiLegoId: 1348
    apiLegoUuid: '1348'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 9442
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '9442'
    validate: null
  outputFields: [
    ]
- apiLego:
    apiAlias: ty-down-apiLego
    attributes: null
    description: null
    id: 1349
    index: 4
    legoAlias: update
    oiAlias: ty_api_lego
    processControllerAlias: null
    uuid: '1349'
  inputFields:
  - alias: id
    apiLegoId: 1349
    apiLegoUuid: '1349'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: ${node.prevApiLego.id}
    fieldValue: null
    fromApiLegoId: 1347
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '1347'
    fvt: template
    id: 9443
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '9443'
    validate: ''
  - alias: index
    apiLegoId: 1349
    apiLegoUuid: '1349'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: index
    fieldTpl: ${node.currentApiLego.index}
    fieldValue: null
    fromApiLegoId: 1346
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '1346'
    fvt: template
    id: 9444
    ift: update
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: index
    sessionParamName: null
    uuid: '9444'
    validate: ''
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
