api:
  alias: ty-delete-app
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-09T18:09:57Z
  description: 删除TY应用
  id: 445
  method: POST
  name: 删除TY应用
  type: ty
  url: ty-delete-app
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-delete-app
    attributes: null
    description: null
    id: 871
    index: 1
    legoAlias: read
    oiAlias: ty_app
    processControllerAlias: null
    uuid: '871'
  inputFields:
  - alias: order_field
    apiLegoId: 871
    apiLegoUuid: '871'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 5161
    ift: common
    inputFieldDescribeId: 32
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '5161'
    validate: null
  - alias: order
    apiLegoId: 871
    apiLegoUuid: '871'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 5162
    ift: common
    inputFieldDescribeId: 44
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '5162'
    validate: null
  - alias: group_field
    apiLegoId: 871
    apiLegoUuid: '871'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 5163
    ift: common
    inputFieldDescribeId: 45
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '5163'
    validate: null
  - alias: id
    apiLegoId: 871
    apiLegoUuid: '871'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 5164
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '5164'
    validate: null
  - alias: alias
    apiLegoId: 871
    apiLegoUuid: '871'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5165
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '5165'
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 871
    apiLegoUuid: '871'
    description: null
    dt: null
    fieldName: data
    fieldValue: null
    handle: null
    id: 934
    name: data
    oft: common
    outputFieldDescribeId: 32
    response: false
    uuid: '934'
  - alias: alias
    apiLegoId: 871
    apiLegoUuid: '871'
    description: null
    dt: string
    fieldName: alias
    fieldValue: null
    handle: ''
    id: 935
    name: 别名
    oft: read
    outputFieldDescribeId: 0
    response: false
    uuid: '935'
- apiLego:
    apiAlias: ty-delete-app
    attributes: null
    description: 删除应用下的角色
    id: 872
    index: 2
    legoAlias: delete
    oiAlias: ty_app_role
    processControllerAlias: null
    uuid: '872'
  inputFields:
  - alias: appAlias
    apiLegoId: 872
    apiLegoUuid: '872'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: appAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 871
    fromApiLegoOutputFieldAlias: alias
    fromApiLegoUuid: '871'
    fvt: output
    id: 5166
    ift: condition
    inputFieldDescribeId: 0
    name: 应用别名
    requestParamName: appAlias
    sessionParamName: null
    uuid: '5166'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
- apiLego:
    apiAlias: ty-delete-app
    attributes: null
    description: 删除应用下的授权
    id: 873
    index: 3
    legoAlias: delete
    oiAlias: ty_user_app_role
    processControllerAlias: null
    uuid: '873'
  inputFields:
  - alias: appAlias
    apiLegoId: 873
    apiLegoUuid: '873'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: appAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 871
    fromApiLegoOutputFieldAlias: alias
    fromApiLegoUuid: '871'
    fvt: output
    id: 5167
    ift: condition
    inputFieldDescribeId: 0
    name: appAlias
    requestParamName: appAlias
    sessionParamName: null
    uuid: '5167'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
- apiLego:
    apiAlias: ty-delete-app
    attributes: null
    description: null
    id: 776
    index: 4
    legoAlias: delete
    oiAlias: ty_app
    processControllerAlias: null
    uuid: '776'
  inputFields:
  - alias: id
    apiLegoId: 776
    apiLegoUuid: '776'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: 应用id
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 4293
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '4293'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
