api:
  alias: ty-delete-app-role
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-09T19:13:19Z
  description: 删除应用角色
  id: 448
  method: POST
  name: 删除应用角色
  type: ty
  url: ty-delete-app-role
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-delete-app-role
    attributes: null
    description: null
    id: 782
    index: 1
    legoAlias: delete
    oiAlias: ty_app_role
    processControllerAlias: null
    uuid: '782'
  inputFields:
  - alias: id
    apiLegoId: 782
    apiLegoUuid: '782'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4312
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '4312'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
