api:
  alias: ty-delete-task
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-12T15:31:13Z
  description: 一键生成接口
  id: 503
  method: POST
  name: 删除任务
  type: ty
  url: ty-delete-task
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-delete-task
    attributes: null
    description: 一键生成接口
    id: 980
    index: 1
    legoAlias: delete
    oiAlias: ty_task
    processControllerAlias: null
    uuid: '980'
  inputFields:
  - alias: id
    apiLegoId: 980
    apiLegoUuid: '980'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: 一键生成
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 6161
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '6161'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
- apiLego:
    apiAlias: ty-delete-task
    attributes: null
    description: null
    id: 1000
    index: 2
    legoAlias: delete
    oiAlias: ty_task_log
    processControllerAlias: null
    uuid: '1000'
  inputFields:
  - alias: taskId
    apiLegoId: 1000
    apiLegoUuid: '1000'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: taskId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6391
    ift: condition
    inputFieldDescribeId: 0
    name: 任务ID
    requestParamName: id
    sessionParamName: null
    uuid: '6391'
    validate: ''
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
