api:
  alias: ty-list-api-req
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-03-17T11:08:47Z
  description: 获取请求参数  去重
  id: 753
  method: GET
  name: 获取接口请求参数集合2.0
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-list-api-req
    attributes: null
    description: ''
    id: 2607
    index: 1
    legoAlias: list
    oiAlias: ty_api_lego
    processControllerAlias: null
    uuid: '1560'
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '1560'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 20028
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '11062'
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '1560'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 20029
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '11063'
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '1560'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 20030
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '11064'
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '1560'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 20031
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '11065'
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '1560'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 20032
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '11066'
    validate: null
  - alias: apiAlias
    apiLegoId: 0
    apiLegoUuid: '1560'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: apiAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 20033
    ift: condition
    inputFieldDescribeId: 0
    name: API别名
    requestParamName: apiAlias
    sessionParamName: ''
    uuid: '11067'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '1560'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20034
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '11068'
    validate: null
  - alias: uuid
    apiLegoId: 0
    apiLegoUuid: '1560'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: uuid
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20035
    ift: read
    inputFieldDescribeId: 0
    name: UUID
    requestParamName: uuid
    sessionParamName: ''
    uuid: 948239F9-841D-4085-B002-2AD135EDB4F11523960397979
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 0
    apiLegoUuid: '1560'
    description: ''
    dt: ''
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 3042
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: '1731'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '1560'
    description: ''
    dt: string
    fieldName: id
    fieldValue: null
    handle: ''
    id: 3043
    name: ID
    oft: read
    outputFieldDescribeId: 0
    response: false
    uuid: '1732'
  - alias: uuid
    apiLegoId: 0
    apiLegoUuid: '1560'
    description: ''
    dt: string
    fieldName: uuid
    fieldValue: null
    handle: ''
    id: 3044
    name: UUID
    oft: read
    outputFieldDescribeId: 0
    response: false
    uuid: 2174B662-9FAB-4DFD-AAAD-B6A398100D471523960414985
- apiLego:
    apiAlias: ty-list-api-req
    attributes: null
    description: ''
    id: 2608
    index: 2
    legoAlias: list
    oiAlias: ty_input_field
    processControllerAlias: null
    uuid: '1561'
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 20036
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '11069'
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 20037
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '11070'
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 20038
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '11071'
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 20039
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '11072'
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 20040
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '11073'
    validate: null
  - alias: requestParamName
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: requestParamName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20041
    ift: read
    inputFieldDescribeId: 0
    name: 请求参数别名
    requestParamName: requestParamName
    sessionParamName: ''
    uuid: '11075'
    validate: null
  - alias: fieldName
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20042
    ift: read
    inputFieldDescribeId: 0
    name: fieldName
    requestParamName: fieldName
    sessionParamName: ''
    uuid: '11076'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20043
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: ''
    uuid: '11077'
    validate: null
  - alias: fvt
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: request
    ct: eq
    description: ''
    dt: string
    fieldName: fvt
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 20044
    ift: condition
    inputFieldDescribeId: 0
    name: fvt
    requestParamName: fvt
    sessionParamName: ''
    uuid: '11078'
    validate: ''
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20045
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: '11187'
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20046
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: '11188'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20047
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: '11189'
    validate: null
  - alias: apiLegoId
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: apiLegoId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20048
    ift: read
    inputFieldDescribeId: 0
    name: apiLegoId
    requestParamName: apiLegoId
    sessionParamName: ''
    uuid: '11190'
    validate: null
  - alias: ct
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: ct
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20049
    ift: read
    inputFieldDescribeId: 0
    name: ct
    requestParamName: ct
    sessionParamName: ''
    uuid: '11191'
    validate: null
  - alias: ift
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: ift
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20050
    ift: read
    inputFieldDescribeId: 0
    name: ift
    requestParamName: ift
    sessionParamName: ''
    uuid: '11192'
    validate: null
  - alias: fvt
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fvt
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20051
    ift: read
    inputFieldDescribeId: 0
    name: fvt
    requestParamName: fvt
    sessionParamName: ''
    uuid: '11193'
    validate: null
  - alias: validate
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: validate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20052
    ift: read
    inputFieldDescribeId: 0
    name: validate
    requestParamName: validate
    sessionParamName: ''
    uuid: '11256'
    validate: null
  - alias: dt
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: dt
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 20053
    ift: read
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: dt
    sessionParamName: ''
    uuid: '11257'
    validate: null
  - alias: apiLegoUuid
    apiLegoId: 0
    apiLegoUuid: '1561'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: In
    description: ''
    dt: string
    fieldName: apiLegoUuid
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: uuid
    fromApiLegoUuid: '1560'
    fvt: output
    id: 20054
    ift: condition
    inputFieldDescribeId: 0
    name: apiLegoUuid
    requestParamName: apiLegoUuid
    sessionParamName: ''
    uuid: D723A51F-5599-4D90-BA66-DB3E22E390911523960430889
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 0
    apiLegoUuid: '1561'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: '[{"handleName":"resultRemoval","params":"requestParamName"}]'
    id: 3045
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1733'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
