api:
  alias: ty-list-page-by-app
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-03T16:18:44Z
  description: 列出应用下的所有页面
  id: 429
  method: GET
  name: 列出应用下的所有页面
  type: ty
  url: ty-list-page-by-app
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-list-page-by-app
    attributes: null
    description: null
    id: 742
    index: 1
    legoAlias: list
    oiAlias: ty_page
    processControllerAlias: null
    uuid: '742'
  inputFields:
  - alias: order_field
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 4023
    ift: common
    inputFieldDescribeId: 31
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '4023'
    validate: null
  - alias: order
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 4024
    ift: common
    inputFieldDescribeId: 42
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '4024'
    validate: null
  - alias: group_field
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 4025
    ift: common
    inputFieldDescribeId: 43
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '4025'
    validate: null
  - alias: keywords
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 4026
    ift: common
    inputFieldDescribeId: 51
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '4026'
    validate: ''
  - alias: global_search_fields
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: '["name","alias"]'
    ct: eq
    description: null
    dt: string
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 4027
    ift: common
    inputFieldDescribeId: 52
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '4027'
    validate: ''
  - alias: id
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4028
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '4028'
    validate: null
  - alias: name
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4029
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '4029'
    validate: null
  - alias: alias
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4030
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '4030'
    validate: null
  - alias: appAlias
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: appAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4031
    ift: read
    inputFieldDescribeId: 0
    name: 应用别名
    requestParamName: appAlias
    sessionParamName: null
    uuid: '4031'
    validate: null
  - alias: parentId
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: parentId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4032
    ift: read
    inputFieldDescribeId: 0
    name: 父ID
    requestParamName: parentId
    sessionParamName: null
    uuid: '4032'
    validate: null
  - alias: enable
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: enable
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4033
    ift: read
    inputFieldDescribeId: 0
    name: 是否可用
    requestParamName: enable
    sessionParamName: null
    uuid: '4033'
    validate: null
  - alias: type
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: type
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4034
    ift: read
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: null
    uuid: '4034'
    validate: null
  - alias: appAlias
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: appAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 4035
    ift: condition
    inputFieldDescribeId: 0
    name: 应用别名
    requestParamName: appAlias
    sessionParamName: ''
    uuid: '4035'
    validate: '[{"validateName":"required","params":"请先选择所属应用"}]'
  - alias: enable
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: '1'
    ct: eq
    description: null
    dt: string
    fieldName: enable
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: 4036
    ift: condition
    inputFieldDescribeId: 0
    name: 是否可用
    requestParamName: enable
    sessionParamName: null
    uuid: '4036'
    validate: ''
  - alias: icon
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: icon
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5696
    ift: read
    inputFieldDescribeId: 0
    name: 图标
    requestParamName: icon
    sessionParamName: null
    uuid: '5696'
    validate: null
  - alias: sort
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: sort
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5697
    ift: read
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: sort
    sessionParamName: null
    uuid: '5697'
    validate: null
  - alias: platform
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: platform
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8962
    ift: read
    inputFieldDescribeId: 0
    name: 所属平台
    requestParamName: platform
    sessionParamName: null
    uuid: '8962'
    validate: null
  - alias: createrId
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: createrId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8963
    ift: read
    inputFieldDescribeId: 0
    name: 创建人id
    requestParamName: createrId
    sessionParamName: null
    uuid: '8963'
    validate: null
  - alias: createrName
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: createrName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8964
    ift: read
    inputFieldDescribeId: 0
    name: 创建人姓名
    requestParamName: createrName
    sessionParamName: null
    uuid: '8964'
    validate: null
  - alias: owerId
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: owerId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8965
    ift: read
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: null
    uuid: '8965'
    validate: null
  - alias: owerName
    apiLegoId: 742
    apiLegoUuid: '742'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: owerName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8966
    ift: read
    inputFieldDescribeId: 0
    name: 负责人名称
    requestParamName: owerName
    sessionParamName: null
    uuid: '8966'
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 742
    apiLegoUuid: '742'
    description: null
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 774
    name: 列表数据
    oft: common
    outputFieldDescribeId: 31
    response: true
    uuid: '774'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
