api:
  alias: ty-list-response-by-apiAlias
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-02-24T16:13:14Z
  description: null
  id: 665
  method: GET
  name: 获取接口返回数据字段
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-list-response-by-apiAlias
    attributes: null
    description: null
    id: 1341
    index: 1
    legoAlias: list
    oiAlias: ty_output_field
    processControllerAlias: null
    uuid: '1341'
  inputFields:
  - alias: order_field
    apiLegoId: 1341
    apiLegoUuid: '1341'
    attributes: ''
    connectorPath: ''
    constant: id
    ct: eq
    description: ''
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 9381
    ift: common
    inputFieldDescribeId: 31
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '9381'
    validate: ''
  - alias: order
    apiLegoId: 1341
    apiLegoUuid: '1341'
    attributes: ''
    connectorPath: ''
    constant: DESC
    ct: eq
    description: ''
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 9382
    ift: common
    inputFieldDescribeId: 42
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '9382'
    validate: ''
  - alias: group_field
    apiLegoId: 1341
    apiLegoUuid: '1341'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9383
    ift: common
    inputFieldDescribeId: 43
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '9383'
    validate: null
  - alias: keywords
    apiLegoId: 1341
    apiLegoUuid: '1341'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9384
    ift: common
    inputFieldDescribeId: 51
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '9384'
    validate: null
  - alias: global_search_fields
    apiLegoId: 1341
    apiLegoUuid: '1341'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9385
    ift: common
    inputFieldDescribeId: 52
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '9385'
    validate: null
  - alias: apiAlias
    apiLegoId: 1341
    apiLegoUuid: '1341'
    attributes: null
    connectorPath: '[{"alias":"of_apiLego"}]'
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: apiAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 9386
    ift: condition
    inputFieldDescribeId: 0
    name: apiLegoId-API别名
    requestParamName: apiAlias
    sessionParamName: null
    uuid: '9386'
    validate: null
  - alias: id
    apiLegoId: 1341
    apiLegoUuid: '1341'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9402
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '9402'
    validate: null
  - alias: name
    apiLegoId: 1341
    apiLegoUuid: '1341'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9403
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: '9403'
    validate: null
  - alias: apiLegoId
    apiLegoId: 1341
    apiLegoUuid: '1341'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: apiLegoId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9404
    ift: read
    inputFieldDescribeId: 0
    name: apiLegoId
    requestParamName: apiLegoId
    sessionParamName: null
    uuid: '9404'
    validate: null
  - alias: fieldName
    apiLegoId: 1341
    apiLegoUuid: '1341'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9405
    ift: read
    inputFieldDescribeId: 0
    name: fieldName
    requestParamName: fieldName
    sessionParamName: null
    uuid: '9405'
    validate: null
  - alias: alias
    apiLegoId: 1341
    apiLegoUuid: '1341'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9406
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: null
    uuid: '9406'
    validate: null
  - alias: response
    apiLegoId: 1341
    apiLegoUuid: '1341'
    attributes: null
    connectorPath: ''
    constant: '1'
    ct: eq
    description: null
    dt: boolean
    fieldName: response
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: 9407
    ift: condition
    inputFieldDescribeId: 0
    name: response
    requestParamName: response
    sessionParamName: null
    uuid: '9407'
    validate: ''
  outputFields:
  - alias: data_list
    apiLegoId: 1341
    apiLegoUuid: '1341'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 1477
    name: 列表数据
    oft: common
    outputFieldDescribeId: 31
    response: true
    uuid: '1477'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
