api:
  alias: ty-list-dict-by-type
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-03-21T14:22:22Z
  description: null
  id: 761
  method: GET
  name: 根据分类获取字典列表
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-list-dict-by-type
    attributes: null
    description: null
    id: 1571
    index: 1
    legoAlias: list
    oiAlias: ty_dict
    processControllerAlias: null
    uuid: '1571'
  inputFields:
  - alias: order_field
    apiLegoId: 1571
    apiLegoUuid: '1571'
    attributes: null
    connectorPath: ''
    constant: id
    ct: eq
    description: null
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 11201
    ift: common
    inputFieldDescribeId: 31
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '11201'
    validate: ''
  - alias: order
    apiLegoId: 1571
    apiLegoUuid: '1571'
    attributes: null
    connectorPath: ''
    constant: DESC
    ct: eq
    description: null
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 11202
    ift: common
    inputFieldDescribeId: 42
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '11202'
    validate: ''
  - alias: group_field
    apiLegoId: 1571
    apiLegoUuid: '1571'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 11203
    ift: common
    inputFieldDescribeId: 43
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '11203'
    validate: null
  - alias: keywords
    apiLegoId: 1571
    apiLegoUuid: '1571'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 11204
    ift: common
    inputFieldDescribeId: 51
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '11204'
    validate: null
  - alias: global_search_fields
    apiLegoId: 1571
    apiLegoUuid: '1571'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 11205
    ift: common
    inputFieldDescribeId: 52
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '11205'
    validate: null
  - alias: type
    apiLegoId: 1571
    apiLegoUuid: '1571'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 11208
    ift: condition
    inputFieldDescribeId: 0
    name: 字典类型
    requestParamName: type
    sessionParamName: null
    uuid: '11208'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 1571
    apiLegoUuid: '1571'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11209
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '11209'
    validate: null
  - alias: type
    apiLegoId: 1571
    apiLegoUuid: '1571'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: type
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11210
    ift: read
    inputFieldDescribeId: 0
    name: 字典类型
    requestParamName: type
    sessionParamName: null
    uuid: '11210'
    validate: null
  - alias: alias
    apiLegoId: 1571
    apiLegoUuid: '1571'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11211
    ift: read
    inputFieldDescribeId: 0
    name: 类型别名
    requestParamName: alias
    sessionParamName: null
    uuid: '11211'
    validate: null
  - alias: name
    apiLegoId: 1571
    apiLegoUuid: '1571'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11212
    ift: read
    inputFieldDescribeId: 0
    name: 类型名称
    requestParamName: name
    sessionParamName: null
    uuid: '11212'
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 1571
    apiLegoUuid: '1571'
    description: null
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 1754
    name: 列表数据
    oft: common
    outputFieldDescribeId: 31
    response: true
    uuid: '1754'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
