api:
  alias: ty-list-dst
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-02-24T14:53:58Z
  description: null
  id: 662
  method: GET
  name: 获取所有数据源分类
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-list-dst
    attributes: null
    description: null
    id: 1338
    index: 1
    legoAlias: list
    oiAlias: ty_dict
    processControllerAlias: null
    uuid: '1338'
  inputFields:
  - alias: order_field
    apiLegoId: 1338
    apiLegoUuid: '1338'
    attributes: ''
    connectorPath: ''
    constant: id
    ct: eq
    description: ''
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 9345
    ift: common
    inputFieldDescribeId: 31
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '9345'
    validate: ''
  - alias: order
    apiLegoId: 1338
    apiLegoUuid: '1338'
    attributes: ''
    connectorPath: ''
    constant: DESC
    ct: eq
    description: ''
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 9346
    ift: common
    inputFieldDescribeId: 42
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '9346'
    validate: ''
  - alias: group_field
    apiLegoId: 1338
    apiLegoUuid: '1338'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9347
    ift: common
    inputFieldDescribeId: 43
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '9347'
    validate: null
  - alias: keywords
    apiLegoId: 1338
    apiLegoUuid: '1338'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9348
    ift: common
    inputFieldDescribeId: 51
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '9348'
    validate: null
  - alias: global_search_fields
    apiLegoId: 1338
    apiLegoUuid: '1338'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9349
    ift: common
    inputFieldDescribeId: 52
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '9349'
    validate: null
  - alias: type
    apiLegoId: 1338
    apiLegoUuid: '1338'
    attributes: null
    connectorPath: ''
    constant: ds
    ct: eq
    description: null
    dt: string
    fieldName: type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: 9350
    ift: condition
    inputFieldDescribeId: 0
    name: 字典类型
    requestParamName: type
    sessionParamName: null
    uuid: '9350'
    validate: ''
  - alias: alias
    apiLegoId: 1338
    apiLegoUuid: '1338'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9351
    ift: read
    inputFieldDescribeId: 0
    name: 类型别名
    requestParamName: alias
    sessionParamName: null
    uuid: '9351'
    validate: null
  - alias: name
    apiLegoId: 1338
    apiLegoUuid: '1338'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9352
    ift: read
    inputFieldDescribeId: 0
    name: 类型名称
    requestParamName: name
    sessionParamName: null
    uuid: '9352'
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 1338
    apiLegoUuid: '1338'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 1474
    name: 列表数据
    oft: common
    outputFieldDescribeId: 31
    response: true
    uuid: '1474'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
