api:
  alias: ty-list-icon
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-16T15:46:25Z
  description: ''
  id: 470
  method: GET
  name: 获取TY图标列表
  type: ty
  url: ty-list-icon
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-list-icon
    attributes: null
    description: null
    id: 886
    index: 1
    legoAlias: list
    oiAlias: ty_icon
    processControllerAlias: null
    uuid: '886'
  inputFields:
  - alias: order_field
    apiLegoId: 886
    apiLegoUuid: '886'
    attributes: null
    connectorPath: ''
    constant: id
    ct: eq
    description: null
    dt: string
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 5288
    ift: common
    inputFieldDescribeId: 31
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '5288'
    validate: ''
  - alias: order
    apiLegoId: 886
    apiLegoUuid: '886'
    attributes: null
    connectorPath: ''
    constant: DESC
    ct: eq
    description: null
    dt: string
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 5289
    ift: common
    inputFieldDescribeId: 42
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '5289'
    validate: ''
  - alias: group_field
    apiLegoId: 886
    apiLegoUuid: '886'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 5290
    ift: common
    inputFieldDescribeId: 43
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '5290'
    validate: null
  - alias: keywords
    apiLegoId: 886
    apiLegoUuid: '886'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 5291
    ift: common
    inputFieldDescribeId: 51
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '5291'
    validate: ''
  - alias: global_search_fields
    apiLegoId: 886
    apiLegoUuid: '886'
    attributes: null
    connectorPath: ''
    constant: '["iconClass","type"]'
    ct: eq
    description: null
    dt: string
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 5292
    ift: common
    inputFieldDescribeId: 52
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '5292'
    validate: ''
  - alias: id
    apiLegoId: 886
    apiLegoUuid: '886'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5293
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '5293'
    validate: null
  - alias: iconClass
    apiLegoId: 886
    apiLegoUuid: '886'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: iconClass
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5294
    ift: read
    inputFieldDescribeId: 0
    name: 图标类
    requestParamName: iconClass
    sessionParamName: null
    uuid: '5294'
    validate: null
  - alias: type
    apiLegoId: 886
    apiLegoUuid: '886'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: type
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5295
    ift: read
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: null
    uuid: '5295'
    validate: null
  - alias: createDate
    apiLegoId: 886
    apiLegoUuid: '886'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5296
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: null
    uuid: '5296'
    validate: null
  - alias: createUser
    apiLegoId: 886
    apiLegoUuid: '886'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: createUser
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5297
    ift: read
    inputFieldDescribeId: 0
    name: 创建用户
    requestParamName: createUser
    sessionParamName: null
    uuid: '5297'
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 886
    apiLegoUuid: '886'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 952
    name: 列表数据
    oft: common
    outputFieldDescribeId: 31
    response: true
    uuid: '952'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
