api:
  alias: ty-list-lego-by-type
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-02-24T15:15:57Z
  description: null
  id: 664
  method: GET
  name: 根据分类获取乐高列表
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-list-lego-by-type
    attributes: null
    description: null
    id: 1340
    index: 1
    legoAlias: list
    oiAlias: ty_lego
    processControllerAlias: null
    uuid: '1340'
  inputFields:
  - alias: order_field
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: id
    ct: eq
    description: null
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 9361
    ift: common
    inputFieldDescribeId: 31
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '9361'
    validate: ''
  - alias: order
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: DESC
    ct: eq
    description: null
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 9362
    ift: common
    inputFieldDescribeId: 42
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '9362'
    validate: ''
  - alias: group_field
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9363
    ift: common
    inputFieldDescribeId: 43
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '9363'
    validate: null
  - alias: keywords
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9364
    ift: common
    inputFieldDescribeId: 51
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '9364'
    validate: null
  - alias: global_search_fields
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9365
    ift: common
    inputFieldDescribeId: 52
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '9365'
    validate: null
  - alias: id
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9366
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '9366'
    validate: null
  - alias: name
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9367
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: '9367'
    validate: null
  - alias: description
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9368
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: null
    uuid: '9368'
    validate: null
  - alias: alias
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9369
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: null
    uuid: '9369'
    validate: null
  - alias: supportDST
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: supportDST
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9370
    ift: read
    inputFieldDescribeId: 0
    name: 支持的DST
    requestParamName: supportDST
    sessionParamName: null
    uuid: '9370'
    validate: null
  - alias: icon
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: icon
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9371
    ift: read
    inputFieldDescribeId: 0
    name: icon
    requestParamName: icon
    sessionParamName: null
    uuid: '9371'
    validate: null
  - alias: generateSupport
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: boolean
    fieldName: generateSupport
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9372
    ift: read
    inputFieldDescribeId: 0
    name: 支持一键生成
    requestParamName: generateSupport
    sessionParamName: null
    uuid: '9372'
    validate: null
  - alias: useNum
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: useNum
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9373
    ift: read
    inputFieldDescribeId: 0
    name: 使用数量
    requestParamName: useNum
    sessionParamName: null
    uuid: '9373'
    validate: null
  - alias: createDate
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: time
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9374
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: null
    uuid: '9374'
    validate: null
  - alias: createrId
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: createrId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9375
    ift: read
    inputFieldDescribeId: 0
    name: 创建人id
    requestParamName: createrId
    sessionParamName: null
    uuid: '9375'
    validate: null
  - alias: createrName
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: createrName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9376
    ift: read
    inputFieldDescribeId: 0
    name: 创建人姓名
    requestParamName: createrName
    sessionParamName: null
    uuid: '9376'
    validate: null
  - alias: owerId
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: owerId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9377
    ift: read
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: null
    uuid: '9377'
    validate: null
  - alias: owerName
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: owerName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9378
    ift: read
    inputFieldDescribeId: 0
    name: 负责人名称
    requestParamName: owerName
    sessionParamName: null
    uuid: '9378'
    validate: null
  - alias: type
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: type
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9379
    ift: read
    inputFieldDescribeId: 0
    name: 乐高类型
    requestParamName: type
    sessionParamName: null
    uuid: '9379'
    validate: null
  - alias: type
    apiLegoId: 1340
    apiLegoUuid: '1340'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 9380
    ift: condition
    inputFieldDescribeId: 0
    name: 乐高类型
    requestParamName: type
    sessionParamName: null
    uuid: '9380'
    validate: ''
  outputFields:
  - alias: data_list
    apiLegoId: 1340
    apiLegoUuid: '1340'
    description: null
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 1476
    name: 列表数据
    oft: common
    outputFieldDescribeId: 31
    response: true
    uuid: '1476'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
