api:
  alias: ty-list-generate-lego
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-04T19:06:46Z
  description: ''
  id: 495
  method: GET
  name: 支持一键乐高列表
  type: ty
  url: ty-list-generate-lego
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-list-generate-lego
    attributes: null
    description: null
    id: 962
    index: 1
    legoAlias: list
    oiAlias: ty_lego
    processControllerAlias: null
    uuid: '962'
  inputFields:
  - alias: order_field
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6033
    ift: common
    inputFieldDescribeId: 31
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '6033'
    validate: null
  - alias: order
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6034
    ift: common
    inputFieldDescribeId: 42
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '6034'
    validate: null
  - alias: group_field
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6035
    ift: common
    inputFieldDescribeId: 43
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '6035'
    validate: null
  - alias: keywords
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6036
    ift: common
    inputFieldDescribeId: 51
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '6036'
    validate: null
  - alias: global_search_fields
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 6037
    ift: common
    inputFieldDescribeId: 52
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '6037'
    validate: null
  - alias: generateSupport
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: ''
    constant: '1'
    ct: eq
    description: null
    dt: string
    fieldName: generateSupport
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: 6038
    ift: condition
    inputFieldDescribeId: 0
    name: generateSupport
    requestParamName: generateSupport
    sessionParamName: null
    uuid: '6038'
    validate: ''
  - alias: id
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 6039
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '6039'
    validate: null
  - alias: name
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 6040
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: '6040'
    validate: null
  - alias: alias
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 6041
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: null
    uuid: '6041'
    validate: null
  - alias: supportDST
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: supportDST
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 6042
    ift: read
    inputFieldDescribeId: 0
    name: 支持的DST
    requestParamName: supportDST
    sessionParamName: null
    uuid: '6042'
    validate: null
  - alias: icon
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: icon
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 6043
    ift: read
    inputFieldDescribeId: 0
    name: icon
    requestParamName: icon
    sessionParamName: null
    uuid: '6043'
    validate: null
  - alias: generateSupport
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: generateSupport
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 6044
    ift: read
    inputFieldDescribeId: 0
    name: generateSupport
    requestParamName: generateSupport
    sessionParamName: null
    uuid: '6044'
    validate: null
  - alias: useNum
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: useNum
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8917
    ift: read
    inputFieldDescribeId: 0
    name: 使用数量
    requestParamName: useNum
    sessionParamName: null
    uuid: '8917'
    validate: null
  - alias: createDate
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: time
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8918
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: null
    uuid: '8918'
    validate: null
  - alias: createrId
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: createrId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8919
    ift: read
    inputFieldDescribeId: 0
    name: 创建人id
    requestParamName: createrId
    sessionParamName: null
    uuid: '8919'
    validate: null
  - alias: createrName
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: createrName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8920
    ift: read
    inputFieldDescribeId: 0
    name: 创建人姓名
    requestParamName: createrName
    sessionParamName: null
    uuid: '8920'
    validate: null
  - alias: owerId
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: owerId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8921
    ift: read
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: null
    uuid: '8921'
    validate: null
  - alias: owerName
    apiLegoId: 962
    apiLegoUuid: '962'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: owerName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8922
    ift: read
    inputFieldDescribeId: 0
    name: 负责人名称
    requestParamName: owerName
    sessionParamName: null
    uuid: '8922'
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 962
    apiLegoUuid: '962'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 1031
    name: 列表数据
    oft: common
    outputFieldDescribeId: 31
    response: true
    uuid: '1031'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
