api:
  alias: ty-list-of-by-apilegoIdAndIft
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-03-22T17:36:00Z
  description: null
  id: 826
  method: GET
  name: 根据apilegoId和ift获取0f
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-list-of-by-apilegoIdAndIft
    attributes: null
    description: null
    id: 1740
    index: 1
    legoAlias: list
    oiAlias: ty_output_field
    processControllerAlias: null
    uuid: '1740'
  inputFields:
  - alias: order_field
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 12301
    ift: common
    inputFieldDescribeId: 31
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '12301'
    validate: null
  - alias: order
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 12302
    ift: common
    inputFieldDescribeId: 42
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '12302'
    validate: null
  - alias: group_field
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 12303
    ift: common
    inputFieldDescribeId: 43
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '12303'
    validate: null
  - alias: keywords
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 12304
    ift: common
    inputFieldDescribeId: 51
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '12304'
    validate: null
  - alias: global_search_fields
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 12305
    ift: common
    inputFieldDescribeId: 52
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '12305'
    validate: null
  - alias: apiLegoId
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: apiLegoId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 12306
    ift: condition
    inputFieldDescribeId: 0
    name: apiLegoId
    requestParamName: apiLegoId
    sessionParamName: null
    uuid: '12306'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 12308
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '12308'
    validate: null
  - alias: name
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 12309
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: '12309'
    validate: null
  - alias: description
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 12310
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: null
    uuid: '12310'
    validate: null
  - alias: apiLegoId
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: apiLegoId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 12311
    ift: read
    inputFieldDescribeId: 0
    name: apiLegoId
    requestParamName: apiLegoId
    sessionParamName: null
    uuid: '12311'
    validate: null
  - alias: fieldName
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 12312
    ift: read
    inputFieldDescribeId: 0
    name: fieldName
    requestParamName: fieldName
    sessionParamName: null
    uuid: '12312'
    validate: null
  - alias: alias
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 12316
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: null
    uuid: '12316'
    validate: null
  - alias: dt
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: dt
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 12318
    ift: read
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: dt
    sessionParamName: null
    uuid: '12318'
    validate: null
  - alias: oft
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: oft
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 12329
    ift: read
    inputFieldDescribeId: 0
    name: oft
    requestParamName: oft
    sessionParamName: null
    uuid: '12329'
    validate: null
  - alias: response
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: boolean
    fieldName: response
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 12330
    ift: read
    inputFieldDescribeId: 0
    name: response
    requestParamName: response
    sessionParamName: null
    uuid: '12330'
    validate: null
  - alias: handle
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: handle
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 12331
    ift: read
    inputFieldDescribeId: 0
    name: handle
    requestParamName: handle
    sessionParamName: null
    uuid: '12331'
    validate: null
  - alias: oft
    apiLegoId: 1740
    apiLegoUuid: '1740'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: oft
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 12333
    ift: condition
    inputFieldDescribeId: 0
    name: oft
    requestParamName: oft
    sessionParamName: null
    uuid: '12333'
    validate: '[{"validateName":"required"}]'
  outputFields:
  - alias: data_list
    apiLegoId: 1740
    apiLegoUuid: '1740'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 1988
    name: 列表数据
    oft: common
    outputFieldDescribeId: 31
    response: true
    uuid: '1988'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
