api:
  alias: ty-list-apiLego-by-api
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-03-30T14:53:59Z
  description: null
  id: 864
  method: GET
  name: 根据apiALias获取apileo列表
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-list-apiLego-by-api
    attributes: null
    description: null
    id: 1797
    index: 1
    legoAlias: list
    oiAlias: ty_api_lego
    processControllerAlias: null
    uuid: '1797'
  inputFields:
  - alias: order_field
    apiLegoId: 1797
    apiLegoUuid: '1797'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 12705
    ift: common
    inputFieldDescribeId: 31
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '12705'
    validate: null
  - alias: order
    apiLegoId: 1797
    apiLegoUuid: '1797'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 12706
    ift: common
    inputFieldDescribeId: 42
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '12706'
    validate: null
  - alias: group_field
    apiLegoId: 1797
    apiLegoUuid: '1797'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 12707
    ift: common
    inputFieldDescribeId: 43
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '12707'
    validate: null
  - alias: keywords
    apiLegoId: 1797
    apiLegoUuid: '1797'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 12708
    ift: common
    inputFieldDescribeId: 51
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '12708'
    validate: null
  - alias: global_search_fields
    apiLegoId: 1797
    apiLegoUuid: '1797'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 12709
    ift: common
    inputFieldDescribeId: 52
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '12709'
    validate: null
  - alias: apiAlias
    apiLegoId: 1797
    apiLegoUuid: '1797'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: apiAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 12710
    ift: condition
    inputFieldDescribeId: 0
    name: API别名
    requestParamName: apiAlias
    sessionParamName: null
    uuid: '12710'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 1797
    apiLegoUuid: '1797'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 12711
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '12711'
    validate: null
  - alias: uuid
    apiLegoId: 1797
    apiLegoUuid: '1797'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: uuid
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 12712
    ift: read
    inputFieldDescribeId: 0
    name: UUID
    requestParamName: uuid
    sessionParamName: null
    uuid: '12712'
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 1797
    apiLegoUuid: '1797'
    description: null
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 2060
    name: 列表数据
    oft: common
    outputFieldDescribeId: 31
    response: true
    uuid: '2060'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
