api:
  alias: ty-list-auth-type
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-19T15:28:06Z
  description: 一键生成接口
  id: 543
  method: GET
  name: 获取所有授权类型
  type: ty
  url: ty-list-auth-type
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-list-auth-type
    attributes: null
    description: 一键生成接口
    id: 1065
    index: 1
    legoAlias: list
    oiAlias: ty_auth_type
    processControllerAlias: null
    uuid: '1065'
  inputFields:
  - alias: global_search_fields
    apiLegoId: 1065
    apiLegoUuid: '1065'
    attributes: null
    connectorPath: null
    constant: '["id"]'
    ct: null
    description: 一键生成
    dt: string
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: 6875
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(表单)
    requestParamName: null
    sessionParamName: null
    uuid: '6875'
    validate: null
  - alias: id
    apiLegoId: 1065
    apiLegoUuid: '1065'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6876
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: null
    sessionParamName: null
    uuid: '6876'
    validate: null
  - alias: name
    apiLegoId: 1065
    apiLegoUuid: '1065'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6877
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: null
    sessionParamName: null
    uuid: '6877'
    validate: null
  - alias: description
    apiLegoId: 1065
    apiLegoUuid: '1065'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6878
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: null
    sessionParamName: null
    uuid: '6878'
    validate: null
  - alias: alias
    apiLegoId: 1065
    apiLegoUuid: '1065'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6879
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: null
    sessionParamName: null
    uuid: '6879'
    validate: null
  - alias: judgeAPIAlias
    apiLegoId: 1065
    apiLegoUuid: '1065'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: judgeAPIAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6880
    ift: read
    inputFieldDescribeId: 0
    name: 判断执行的API
    requestParamName: null
    sessionParamName: null
    uuid: '6880'
    validate: null
  - alias: noAuthErrorCode
    apiLegoId: 1065
    apiLegoUuid: '1065'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: noAuthErrorCode
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6881
    ift: read
    inputFieldDescribeId: 0
    name: 错误代码
    requestParamName: null
    sessionParamName: null
    uuid: '6881'
    validate: null
  - alias: keywords
    apiLegoId: 1065
    apiLegoUuid: '1065'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6882
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '6882'
    validate: null
  - alias: group_field
    apiLegoId: 1065
    apiLegoUuid: '1065'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6883
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: null
    sessionParamName: null
    uuid: '6883'
    validate: null
  - alias: order
    apiLegoId: 1065
    apiLegoUuid: '1065'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6884
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: null
    sessionParamName: null
    uuid: '6884'
    validate: null
  - alias: order_field
    apiLegoId: 1065
    apiLegoUuid: '1065'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6885
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: null
    sessionParamName: null
    uuid: '6885'
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 1065
    apiLegoUuid: '1065'
    description: 一键生成
    dt: null
    fieldName: data_list
    fieldValue: null
    handle: null
    id: 1155
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1155'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
