api:
  alias: ty-list-api-res
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-03-17T13:19:21Z
  description: null
  id: 754
  method: GET
  name: 获取接口返回参数集合2.0
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-list-api-res
    attributes: null
    description: ''
    id: 5311
    index: 1
    legoAlias: list
    oiAlias: ty_api_lego
    processControllerAlias: null
    uuid: '1562'
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '1562'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 48635
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '11079'
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '1562'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 48636
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '11080'
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '1562'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 48637
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '11081'
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '1562'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 48638
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '11082'
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '1562'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 48639
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '11083'
    validate: null
  - alias: apiAlias
    apiLegoId: 0
    apiLegoUuid: '1562'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: apiAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 48640
    ift: condition
    inputFieldDescribeId: 0
    name: API别名
    requestParamName: apiAlias
    sessionParamName: ''
    uuid: '11084'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '1562'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 48641
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '11085'
    validate: null
  - alias: uuid
    apiLegoId: 0
    apiLegoUuid: '1562'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: uuid
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 48642
    ift: read
    inputFieldDescribeId: 0
    name: UUID
    requestParamName: uuid
    sessionParamName: ''
    uuid: 6A4F85B2-849A-4C18-912F-5999790292C11526886356151
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 0
    apiLegoUuid: '1562'
    description: ''
    dt: ''
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 7405
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: '1734'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '1562'
    description: ''
    dt: string
    fieldName: id
    fieldValue: null
    handle: ''
    id: 7406
    name: ID
    oft: read
    outputFieldDescribeId: 0
    response: false
    uuid: '1735'
  - alias: uuid
    apiLegoId: 0
    apiLegoUuid: '1562'
    description: ''
    dt: string
    fieldName: uuid
    fieldValue: null
    handle: ''
    id: 7407
    name: UUID
    oft: read
    outputFieldDescribeId: 0
    response: true
    uuid: 8EDFE41C-F93F-4960-A6BA-E97149B6CF791526886365770
- apiLego:
    apiAlias: ty-list-api-res
    attributes: null
    description: ''
    id: 5312
    index: 2
    legoAlias: list
    oiAlias: ty_output_field
    processControllerAlias: null
    uuid: '1563'
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 48643
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '11086'
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 48644
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '11087'
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 48645
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '11088'
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 48646
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '11089'
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 48647
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '11090'
    validate: null
  - alias: response
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: '1'
    ct: eq
    description: ''
    dt: boolean
    fieldName: response
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 48648
    ift: condition
    inputFieldDescribeId: 0
    name: response
    requestParamName: response
    sessionParamName: ''
    uuid: '11092'
    validate: ''
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 48649
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: '11093'
    validate: null
  - alias: fieldName
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 48650
    ift: read
    inputFieldDescribeId: 0
    name: fieldName
    requestParamName: fieldName
    sessionParamName: ''
    uuid: '11094'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 48651
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: ''
    uuid: '11095'
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 48652
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: '11194'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 48653
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: '11195'
    validate: null
  - alias: apiLegoId
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: apiLegoId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 48654
    ift: read
    inputFieldDescribeId: 0
    name: apiLegoId
    requestParamName: apiLegoId
    sessionParamName: ''
    uuid: '11196'
    validate: null
  - alias: oft
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: oft
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 48655
    ift: read
    inputFieldDescribeId: 0
    name: oft
    requestParamName: oft
    sessionParamName: ''
    uuid: '11197'
    validate: null
  - alias: response
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: boolean
    fieldName: response
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 48656
    ift: read
    inputFieldDescribeId: 0
    name: response
    requestParamName: response
    sessionParamName: ''
    uuid: '11198'
    validate: null
  - alias: handle
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: handle
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 48657
    ift: read
    inputFieldDescribeId: 0
    name: handle
    requestParamName: handle
    sessionParamName: ''
    uuid: '11199'
    validate: null
  - alias: dt
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: dt
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 48658
    ift: read
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: dt
    sessionParamName: ''
    uuid: '11200'
    validate: null
  - alias: apiLegoUuid
    apiLegoId: 0
    apiLegoUuid: '1563'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: In
    description: ''
    dt: string
    fieldName: apiLegoUuid
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: uuid
    fromApiLegoUuid: '1562'
    fvt: output
    id: 48659
    ift: condition
    inputFieldDescribeId: 0
    name: apiLegoUuid
    requestParamName: apiLegoUuid
    sessionParamName: ''
    uuid: C75C72ED-DD86-4BDC-9BBF-ED2CE863BE2C1526886397205
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 0
    apiLegoUuid: '1563'
    description: ''
    dt: string
    fieldName: data_list
    fieldValue: null
    handle: '[{"handleName":"resultRemoval","params":"alias"}]'
    id: 7408
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1736'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
