api:
  alias: ty-page-icon
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-20T10:21:51Z
  description: ''
  id: 473
  method: GET
  name: 分页TY图标列表
  type: ty
  url: ty-page-icon
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-page-icon
    attributes: null
    description: null
    id: 896
    index: 1
    legoAlias: page
    oiAlias: ty_icon
    processControllerAlias: null
    uuid: '896'
  inputFields:
  - alias: page
    apiLegoId: 896
    apiLegoUuid: '896'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: page
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 5450
    ift: common
    inputFieldDescribeId: 3
    name: 请求页码
    requestParamName: page
    sessionParamName: null
    uuid: '5450'
    validate: ''
  - alias: pageSize
    apiLegoId: 896
    apiLegoUuid: '896'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: pageSize
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 5451
    ift: common
    inputFieldDescribeId: 4
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: null
    uuid: '5451'
    validate: ''
  - alias: order_field
    apiLegoId: 896
    apiLegoUuid: '896'
    attributes: null
    connectorPath: ''
    constant: id
    ct: eq
    description: null
    dt: string
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 5452
    ift: common
    inputFieldDescribeId: 7
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '5452'
    validate: ''
  - alias: order
    apiLegoId: 896
    apiLegoUuid: '896'
    attributes: null
    connectorPath: ''
    constant: DESC
    ct: eq
    description: null
    dt: string
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 5453
    ift: common
    inputFieldDescribeId: 8
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '5453'
    validate: ''
  - alias: group_field
    apiLegoId: 896
    apiLegoUuid: '896'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 5454
    ift: common
    inputFieldDescribeId: 9
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '5454'
    validate: null
  - alias: keywords
    apiLegoId: 896
    apiLegoUuid: '896'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 5455
    ift: common
    inputFieldDescribeId: 53
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '5455'
    validate: ''
  - alias: global_search_fields
    apiLegoId: 896
    apiLegoUuid: '896'
    attributes: null
    connectorPath: ''
    constant: '["iconClass"]'
    ct: eq
    description: null
    dt: string
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 5456
    ift: common
    inputFieldDescribeId: 54
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '5456'
    validate: ''
  - alias: id
    apiLegoId: 896
    apiLegoUuid: '896'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5457
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '5457'
    validate: null
  - alias: iconClass
    apiLegoId: 896
    apiLegoUuid: '896'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: iconClass
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5458
    ift: read
    inputFieldDescribeId: 0
    name: 图标类
    requestParamName: iconClass
    sessionParamName: null
    uuid: '5458'
    validate: null
  - alias: type
    apiLegoId: 896
    apiLegoUuid: '896'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: type
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5459
    ift: read
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: null
    uuid: '5459'
    validate: null
  - alias: createDate
    apiLegoId: 896
    apiLegoUuid: '896'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5460
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: null
    uuid: '5460'
    validate: null
  - alias: createUser
    apiLegoId: 896
    apiLegoUuid: '896'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: createUser
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5461
    ift: read
    inputFieldDescribeId: 0
    name: 创建用户
    requestParamName: createUser
    sessionParamName: null
    uuid: '5461'
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 896
    apiLegoUuid: '896'
    description: null
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 962
    name: page_data
    oft: common
    outputFieldDescribeId: 2
    response: true
    uuid: '962'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
