api:
  alias: ty-page-app
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-08T14:15:14Z
  description: 获取TY应用列表
  id: 438
  method: GET
  name: 获取TY应用列表
  type: ty
  url: ty-page-app
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-page-app
    attributes: null
    description: ''
    id: 10835
    index: 1
    legoAlias: page
    oiAlias: ty_tenant_app
    processControllerAlias: null
    uuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
  inputFields:
  - alias: page
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: page
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 97628
    ift: common
    inputFieldDescribeId: 0
    name: 请求页码
    requestParamName: page
    sessionParamName: ''
    uuid: 64E45214-DB93-44C7-886C-BC66F0CBE6951527751484256
    validate: null
  - alias: pageSize
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: pageSize
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 97629
    ift: common
    inputFieldDescribeId: 0
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: ''
    uuid: 16CFA5FA-A4FA-4DBF-9862-6D3F9F3098D81527751484256
    validate: null
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 97630
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: 9D5B313C-DF35-4D06-AF61-070C688139161527751484256
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 97631
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: AF5B3397-DB9A-44A9-8079-7460A3C8CFB41527751484256
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 97632
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: 7846253B-7ACB-4AA5-AAA5-20299756A9441527751484256
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 97633
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: ''
    sessionParamName: ''
    uuid: E90C02D6-5777-4D97-ACDE-28C2980777381527751484256
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 97634
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: 9CB08D99-24E2-4643-92D7-FD89DAE676521527751484256
    validate: null
  - alias: tenantSerialNumber
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: tenantSerialNumber
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.tenantSerialNumber}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 97635
    ift: condition
    inputFieldDescribeId: 0
    name: 租户序列号
    requestParamName: tenantSerialNumber
    sessionParamName: ''
    uuid: D67AE451-DC07-43FD-A688-3CCC2EA766E31527751529078
    validate: null
  - alias: tenantSerialNumber
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: tenantSerialNumber
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 97636
    ift: read
    inputFieldDescribeId: 0
    name: 租户序列号
    requestParamName: tenantSerialNumber
    sessionParamName: ''
    uuid: C302174E-F0A2-49DD-8B3F-60B26AAA8F391527751593715
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: '[{"alias":"ty_tenant_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 97637
    ift: read
    inputFieldDescribeId: 0
    name: app别名-ID
    requestParamName: id
    sessionParamName: ''
    uuid: B5515E71-669C-4BCC-8132-D725D2A572431532315925249
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: '[{"alias":"ty_tenant_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 97638
    ift: read
    inputFieldDescribeId: 0
    name: app别名-名称
    requestParamName: name
    sessionParamName: ''
    uuid: 5134200C-0A04-4D4A-932E-00F3C3DD422B1532315925250
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: '[{"alias":"ty_tenant_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 97639
    ift: read
    inputFieldDescribeId: 0
    name: app别名-描述
    requestParamName: description
    sessionParamName: ''
    uuid: 21B44A8C-7670-4D70-BCF1-0D57A2DBEA401532315925250
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: '[{"alias":"ty_tenant_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 97640
    ift: read
    inputFieldDescribeId: 0
    name: app别名-别名
    requestParamName: alias
    sessionParamName: ''
    uuid: 796C66FA-5EE3-4833-98E8-3AED55A1C49A1532315925250
    validate: null
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: '[{"alias":"ty_tenant_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: time
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 97641
    ift: read
    inputFieldDescribeId: 0
    name: app别名-创建时间
    requestParamName: createDate
    sessionParamName: ''
    uuid: 45044A9C-074F-43C3-AD0D-437032BC64AD1532315925250
    validate: null
  - alias: online
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: '[{"alias":"ty_tenant_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: boolean
    fieldName: online
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 97642
    ift: read
    inputFieldDescribeId: 0
    name: 'app别名-是否上线 '
    requestParamName: online
    sessionParamName: ''
    uuid: FC91352B-7196-48A4-AB3B-24FF83CA40581532315925250
    validate: null
  - alias: entrance
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: '[{"alias":"ty_tenant_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: entrance
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 97643
    ift: read
    inputFieldDescribeId: 0
    name: app别名-入口页
    requestParamName: entrance
    sessionParamName: ''
    uuid: 28C53757-A713-4FEF-AA2F-15CEDE4328951532315925250
    validate: null
  - alias: buzzAlias
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: '[{"alias":"ty_tenant_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: buzzAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 97644
    ift: read
    inputFieldDescribeId: 0
    name: app别名-巴斯别名
    requestParamName: buzzAlias
    sessionParamName: ''
    uuid: 20F5C81F-242A-42D8-A4A8-30FDD986CDF11532315925250
    validate: null
  - alias: icon
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    attributes: null
    connectorPath: '[{"alias":"ty_tenant_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: icon
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 97645
    ift: read
    inputFieldDescribeId: 0
    name: app别名-ICON别名
    requestParamName: icon
    sessionParamName: ''
    uuid: 02B8D4A0-D1A6-47FC-B11B-6459061C62811532315925250
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 0
    apiLegoUuid: 09214211-78AB-4AAD-8E2D-3A47293912831527751484255
    description: ''
    dt: ''
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 14055
    name: page_data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 9D94AE9D-DF0F-47C9-BE9F-657577B385681527751484256
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
