api:
  alias: ty-page-model-log
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-02-25T16:44:02Z
  description: null
  id: 672
  method: GET
  name: 分页获取模型操作日志
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-page-model-log
    attributes: null
    description: ''
    id: 2260
    index: 1
    legoAlias: page
    oiAlias: ty_model_log
    processControllerAlias: null
    uuid: '1354'
  inputFields:
  - alias: page
    apiLegoId: 0
    apiLegoUuid: '1354'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: page
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 16795
    ift: common
    inputFieldDescribeId: 0
    name: 请求页码
    requestParamName: page
    sessionParamName: ''
    uuid: '9509'
    validate: ''
  - alias: pageSize
    apiLegoId: 0
    apiLegoUuid: '1354'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: pageSize
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 16796
    ift: common
    inputFieldDescribeId: 0
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: ''
    uuid: '9510'
    validate: ''
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '1354'
    attributes: null
    connectorPath: ''
    constant: operateDate
    ct: eq
    description: ''
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 16797
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '9511'
    validate: ''
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '1354'
    attributes: null
    connectorPath: ''
    constant: DESC
    ct: eq
    description: ''
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 16798
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '9512'
    validate: ''
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '1354'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 16799
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '9513'
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '1354'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 16800
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '9514'
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '1354'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 16801
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '9515'
    validate: null
  - alias: operateAlias
    apiLegoId: 0
    apiLegoUuid: '1354'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16802
    ift: condition
    inputFieldDescribeId: 0
    name: 操作模型别名
    requestParamName: dsAlias
    sessionParamName: ''
    uuid: '9516'
    validate: '[]'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '1354'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16803
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '9517'
    validate: null
  - alias: operatorId
    apiLegoId: 0
    apiLegoUuid: '1354'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: operatorId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16804
    ift: read
    inputFieldDescribeId: 0
    name: 操作人ID
    requestParamName: operatorId
    sessionParamName: ''
    uuid: '9518'
    validate: null
  - alias: operatorName
    apiLegoId: 0
    apiLegoUuid: '1354'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operatorName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16805
    ift: read
    inputFieldDescribeId: 0
    name: 操作人姓名
    requestParamName: operatorName
    sessionParamName: ''
    uuid: '9519'
    validate: null
  - alias: operateDate
    apiLegoId: 0
    apiLegoUuid: '1354'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: time
    fieldName: operateDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16806
    ift: read
    inputFieldDescribeId: 0
    name: 操作时间
    requestParamName: operateDate
    sessionParamName: ''
    uuid: '9520'
    validate: null
  - alias: operateContent
    apiLegoId: 0
    apiLegoUuid: '1354'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateContent
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16807
    ift: read
    inputFieldDescribeId: 0
    name: 详细操作内容
    requestParamName: operateContent
    sessionParamName: ''
    uuid: '9521'
    validate: null
  - alias: operateAlias
    apiLegoId: 0
    apiLegoUuid: '1354'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16808
    ift: read
    inputFieldDescribeId: 0
    name: 操作模型别名
    requestParamName: operateAlias
    sessionParamName: ''
    uuid: '9522'
    validate: null
  - alias: operateDes
    apiLegoId: 0
    apiLegoUuid: '1354'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateDes
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16809
    ift: read
    inputFieldDescribeId: 0
    name: 操作描述
    requestParamName: operateDes
    sessionParamName: ''
    uuid: '9523'
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 0
    apiLegoUuid: '1354'
    description: ''
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 2655
    name: page_data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1485'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
