api:
  alias: ty-page-page-log
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-02-25T16:57:58Z
  description: null
  id: 673
  method: GET
  name: 分页获取页面操作日志
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-page-page-log
    attributes: null
    description: null
    id: 1355
    index: 1
    legoAlias: page
    oiAlias: ty_page_log
    processControllerAlias: null
    uuid: '1355'
  inputFields:
  - alias: page
    apiLegoId: 1355
    apiLegoUuid: '1355'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: page
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 9524
    ift: common
    inputFieldDescribeId: 3
    name: 请求页码
    requestParamName: page
    sessionParamName: null
    uuid: '9524'
    validate: ''
  - alias: pageSize
    apiLegoId: 1355
    apiLegoUuid: '1355'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: pageSize
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 9525
    ift: common
    inputFieldDescribeId: 4
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: null
    uuid: '9525'
    validate: ''
  - alias: order_field
    apiLegoId: 1355
    apiLegoUuid: '1355'
    attributes: null
    connectorPath: ''
    constant: operateDate
    ct: eq
    description: null
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 9526
    ift: common
    inputFieldDescribeId: 7
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '9526'
    validate: ''
  - alias: order
    apiLegoId: 1355
    apiLegoUuid: '1355'
    attributes: null
    connectorPath: ''
    constant: DESC
    ct: eq
    description: null
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 9527
    ift: common
    inputFieldDescribeId: 8
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '9527'
    validate: ''
  - alias: group_field
    apiLegoId: 1355
    apiLegoUuid: '1355'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9528
    ift: common
    inputFieldDescribeId: 9
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '9528'
    validate: null
  - alias: keywords
    apiLegoId: 1355
    apiLegoUuid: '1355'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9529
    ift: common
    inputFieldDescribeId: 53
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '9529'
    validate: null
  - alias: global_search_fields
    apiLegoId: 1355
    apiLegoUuid: '1355'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9530
    ift: common
    inputFieldDescribeId: 54
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '9530'
    validate: null
  - alias: operateAlias
    apiLegoId: 1355
    apiLegoUuid: '1355'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: operateAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 9531
    ift: condition
    inputFieldDescribeId: 0
    name: 操作页面别名
    requestParamName: pageAlias
    sessionParamName: null
    uuid: '9531'
    validate: ''
  - alias: id
    apiLegoId: 1355
    apiLegoUuid: '1355'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9532
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '9532'
    validate: null
  - alias: operatorId
    apiLegoId: 1355
    apiLegoUuid: '1355'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: operatorId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9533
    ift: read
    inputFieldDescribeId: 0
    name: 操作人ID
    requestParamName: operatorId
    sessionParamName: null
    uuid: '9533'
    validate: null
  - alias: operatorName
    apiLegoId: 1355
    apiLegoUuid: '1355'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: operatorName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9534
    ift: read
    inputFieldDescribeId: 0
    name: 操作人姓名
    requestParamName: operatorName
    sessionParamName: null
    uuid: '9534'
    validate: null
  - alias: operateDate
    apiLegoId: 1355
    apiLegoUuid: '1355'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: time
    fieldName: operateDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9535
    ift: read
    inputFieldDescribeId: 0
    name: 操作时间
    requestParamName: operateDate
    sessionParamName: null
    uuid: '9535'
    validate: null
  - alias: operateContent
    apiLegoId: 1355
    apiLegoUuid: '1355'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: operateContent
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9536
    ift: read
    inputFieldDescribeId: 0
    name: 详细操作内容
    requestParamName: operateContent
    sessionParamName: null
    uuid: '9536'
    validate: null
  - alias: operateAlias
    apiLegoId: 1355
    apiLegoUuid: '1355'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: operateAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9537
    ift: read
    inputFieldDescribeId: 0
    name: 操作页面别名
    requestParamName: operateAlias
    sessionParamName: null
    uuid: '9537'
    validate: null
  - alias: operateDes
    apiLegoId: 1355
    apiLegoUuid: '1355'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: operateDes
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9538
    ift: read
    inputFieldDescribeId: 0
    name: 操作描述
    requestParamName: operateDes
    sessionParamName: null
    uuid: '9538'
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 1355
    apiLegoUuid: '1355'
    description: null
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 1486
    name: page_data
    oft: common
    outputFieldDescribeId: 2
    response: true
    uuid: '1486'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
