api:
  alias: ty-page-app-role
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-08T16:13:34Z
  description: 获取TY应用角色列表
  id: 440
  method: GET
  name: 获取TY应用角色列表
  type: ty
  url: ty-page-app-role
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-page-app-role
    attributes: null
    description: null
    id: 766
    index: 1
    legoAlias: page
    oiAlias: ty_app_role
    processControllerAlias: null
    uuid: '766'
  inputFields:
  - alias: page
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: page
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 4222
    ift: common
    inputFieldDescribeId: 3
    name: 请求页码
    requestParamName: page
    sessionParamName: null
    uuid: '4222'
    validate: null
  - alias: pageSize
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: pageSize
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 4223
    ift: common
    inputFieldDescribeId: 4
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: null
    uuid: '4223'
    validate: null
  - alias: order_field
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 4224
    ift: common
    inputFieldDescribeId: 7
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '4224'
    validate: null
  - alias: order
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 4225
    ift: common
    inputFieldDescribeId: 8
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '4225'
    validate: null
  - alias: group_field
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 4226
    ift: common
    inputFieldDescribeId: 9
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '4226'
    validate: null
  - alias: keywords
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 4227
    ift: common
    inputFieldDescribeId: 53
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '4227'
    validate: ''
  - alias: global_search_fields
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: null
    connectorPath: ''
    constant: '["name","description'',"appAlias","superFlag","resources","alias","createDate"]'
    ct: eq
    description: null
    dt: string
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 4228
    ift: common
    inputFieldDescribeId: 54
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '4228'
    validate: ''
  - alias: id
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4229
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '4229'
    validate: null
  - alias: name
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4230
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '4230'
    validate: null
  - alias: description
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4231
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '4231'
    validate: null
  - alias: appAlias
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: appAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4232
    ift: read
    inputFieldDescribeId: 0
    name: 应用别名
    requestParamName: appAlias
    sessionParamName: null
    uuid: '4232'
    validate: null
  - alias: superFlag
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: superFlag
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4233
    ift: read
    inputFieldDescribeId: 0
    name: 超级角色
    requestParamName: superFlag
    sessionParamName: null
    uuid: '4233'
    validate: null
  - alias: resources
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: resources
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4234
    ift: read
    inputFieldDescribeId: 0
    name: 资源列表
    requestParamName: resources
    sessionParamName: null
    uuid: '4234'
    validate: null
  - alias: createDate
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4235
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: null
    uuid: '4235'
    validate: null
  - alias: alias
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4236
    ift: read
    inputFieldDescribeId: 0
    name: 角色别名
    requestParamName: alias
    sessionParamName: null
    uuid: '4236'
    validate: null
  - alias: appAlias
    apiLegoId: 766
    apiLegoUuid: '766'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: appAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 4692
    ift: condition
    inputFieldDescribeId: 0
    name: 应用别名
    requestParamName: appAlias
    sessionParamName: ''
    uuid: '4692'
    validate: '[{"validateName":"required"}]'
  outputFields:
  - alias: page_data
    apiLegoId: 766
    apiLegoUuid: '766'
    description: ''
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 804
    name: page_data
    oft: common
    outputFieldDescribeId: 2
    response: true
    uuid: '804'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
