api:
  alias: ty-page-api-log
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-02-25T16:33:26Z
  description: null
  id: 671
  method: GET
  name: 分页获取接口日志
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-page-api-log
    attributes: null
    description: null
    id: 1353
    index: 1
    legoAlias: page
    oiAlias: ty_api_log
    processControllerAlias: null
    uuid: '1353'
  inputFields:
  - alias: page
    apiLegoId: 1353
    apiLegoUuid: '1353'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: page
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 9494
    ift: common
    inputFieldDescribeId: 3
    name: 请求页码
    requestParamName: page
    sessionParamName: null
    uuid: '9494'
    validate: ''
  - alias: pageSize
    apiLegoId: 1353
    apiLegoUuid: '1353'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: pageSize
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 9495
    ift: common
    inputFieldDescribeId: 4
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: null
    uuid: '9495'
    validate: ''
  - alias: order_field
    apiLegoId: 1353
    apiLegoUuid: '1353'
    attributes: null
    connectorPath: ''
    constant: operateDate
    ct: eq
    description: null
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 9496
    ift: common
    inputFieldDescribeId: 7
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '9496'
    validate: ''
  - alias: order
    apiLegoId: 1353
    apiLegoUuid: '1353'
    attributes: null
    connectorPath: ''
    constant: DESC
    ct: eq
    description: null
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 9497
    ift: common
    inputFieldDescribeId: 8
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '9497'
    validate: ''
  - alias: group_field
    apiLegoId: 1353
    apiLegoUuid: '1353'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9498
    ift: common
    inputFieldDescribeId: 9
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '9498'
    validate: null
  - alias: keywords
    apiLegoId: 1353
    apiLegoUuid: '1353'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9499
    ift: common
    inputFieldDescribeId: 53
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '9499'
    validate: null
  - alias: global_search_fields
    apiLegoId: 1353
    apiLegoUuid: '1353'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9500
    ift: common
    inputFieldDescribeId: 54
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: null
    uuid: '9500'
    validate: null
  - alias: id
    apiLegoId: 1353
    apiLegoUuid: '1353'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9501
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '9501'
    validate: null
  - alias: operatorId
    apiLegoId: 1353
    apiLegoUuid: '1353'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: operatorId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9502
    ift: read
    inputFieldDescribeId: 0
    name: 操作人ID
    requestParamName: operatorId
    sessionParamName: null
    uuid: '9502'
    validate: null
  - alias: operatorName
    apiLegoId: 1353
    apiLegoUuid: '1353'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: operatorName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9503
    ift: read
    inputFieldDescribeId: 0
    name: 操作人姓名
    requestParamName: operatorName
    sessionParamName: null
    uuid: '9503'
    validate: null
  - alias: operateDate
    apiLegoId: 1353
    apiLegoUuid: '1353'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: time
    fieldName: operateDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9504
    ift: read
    inputFieldDescribeId: 0
    name: 操作时间
    requestParamName: operateDate
    sessionParamName: null
    uuid: '9504'
    validate: null
  - alias: operateContent
    apiLegoId: 1353
    apiLegoUuid: '1353'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: operateContent
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9505
    ift: read
    inputFieldDescribeId: 0
    name: 详细操作内容
    requestParamName: operateContent
    sessionParamName: null
    uuid: '9505'
    validate: null
  - alias: operateAlias
    apiLegoId: 1353
    apiLegoUuid: '1353'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: operateAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9506
    ift: read
    inputFieldDescribeId: 0
    name: 操作接口别名
    requestParamName: operateAlias
    sessionParamName: null
    uuid: '9506'
    validate: null
  - alias: operateDes
    apiLegoId: 1353
    apiLegoUuid: '1353'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: operateDes
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9507
    ift: read
    inputFieldDescribeId: 0
    name: 操作描述
    requestParamName: operateDes
    sessionParamName: null
    uuid: '9507'
    validate: null
  - alias: operateAlias
    apiLegoId: 1353
    apiLegoUuid: '1353'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: operateAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 9508
    ift: condition
    inputFieldDescribeId: 0
    name: 操作接口别名
    requestParamName: apiAlias
    sessionParamName: null
    uuid: '9508'
    validate: '[{"validateName":"required"}]'
  outputFields:
  - alias: page_data
    apiLegoId: 1353
    apiLegoUuid: '1353'
    description: null
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 1484
    name: page_data
    oft: common
    outputFieldDescribeId: 2
    response: true
    uuid: '1484'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
