api:
  alias: ty-page-log
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-16T14:19:45Z
  description: ''
  id: 466
  method: GET
  name: 分页获取TY日志
  type: ty
  url: ty-page-log
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-page-log
    attributes: null
    description: ''
    id: 5438
    index: 1
    legoAlias: page
    oiAlias: ty_log
    processControllerAlias: null
    uuid: '874'
  inputFields:
  - alias: page
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: page
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 50062
    ift: common
    inputFieldDescribeId: 0
    name: 请求页码
    requestParamName: page
    sessionParamName: ''
    uuid: '5168'
    validate: ''
  - alias: pageSize
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: pageSize
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 50063
    ift: common
    inputFieldDescribeId: 0
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: ''
    uuid: '5169'
    validate: ''
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: id
    ct: eq
    description: ''
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 50064
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '5170'
    validate: ''
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: DESC
    ct: eq
    description: ''
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 50065
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '5171'
    validate: ''
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 50066
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '5172'
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 50067
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '5173'
    validate: ''
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: '["operateApi","operateLego","operateOi","operateUserName"]'
    ct: eq
    description: ''
    dt: string
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 50068
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '5174'
    validate: ''
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 50069
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '5175'
    validate: null
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 50070
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: ''
    uuid: '5176'
    validate: null
  - alias: operateUserAlias
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: operateUserAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 50071
    ift: read
    inputFieldDescribeId: 0
    name: 操作用户标识
    requestParamName: operateUserAlias
    sessionParamName: ''
    uuid: '5177'
    validate: null
  - alias: operateUserName
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: operateUserName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 50072
    ift: read
    inputFieldDescribeId: 0
    name: 操作用户姓名
    requestParamName: operateUserName
    sessionParamName: ''
    uuid: '5178'
    validate: null
  - alias: operateApi
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: operateApi
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 50073
    ift: read
    inputFieldDescribeId: 0
    name: 操作接口
    requestParamName: operateApi
    sessionParamName: ''
    uuid: '5179'
    validate: null
  - alias: operateLego
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: operateLego
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 50074
    ift: read
    inputFieldDescribeId: 0
    name: 操作乐高
    requestParamName: operateLego
    sessionParamName: ''
    uuid: '5180'
    validate: null
  - alias: input
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: input
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 50075
    ift: read
    inputFieldDescribeId: 0
    name: 输入
    requestParamName: input
    sessionParamName: ''
    uuid: '5181'
    validate: null
  - alias: output
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: output
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 50076
    ift: read
    inputFieldDescribeId: 0
    name: 输出
    requestParamName: output
    sessionParamName: ''
    uuid: '5182'
    validate: null
  - alias: content
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: content
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 50077
    ift: read
    inputFieldDescribeId: 0
    name: 操作内容
    requestParamName: content
    sessionParamName: ''
    uuid: '5183'
    validate: null
  - alias: operateOi
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: operateOi
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 50078
    ift: read
    inputFieldDescribeId: 0
    name: 操作OI
    requestParamName: operateOi
    sessionParamName: ''
    uuid: '5184'
    validate: null
  - alias: tenantSerialNumber
    apiLegoId: 0
    apiLegoUuid: '874'
    attributes: null
    connectorPath: '[{"alias":"ty_log_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: tenantSerialNumber
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.tenantSerialNumber}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 50079
    ift: condition
    inputFieldDescribeId: 0
    name: 操作用户标识-租户序列号
    requestParamName: tenantSerialNumber
    sessionParamName: ''
    uuid: 1E424F75-8179-4D0E-92FB-FDBB475B17291527154788348
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 0
    apiLegoUuid: '874'
    description: ''
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 7588
    name: page_data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '936'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
