api:
  alias: ty-page-auth-type
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-20T15:29:34Z
  description: 一键生成接口
  id: 554
  method: GET
  name: 获取授权分页数据
  type: ty
  url: ty-page-auth-type
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-page-auth-type
    attributes: null
    description: 一键生成接口
    id: 1086
    index: 1
    legoAlias: page
    oiAlias: ty_auth_type
    processControllerAlias: null
    uuid: '1086'
  inputFields:
  - alias: global_search_fields
    apiLegoId: 1086
    apiLegoUuid: '1086'
    attributes: null
    connectorPath: null
    constant: '["id"]'
    ct: null
    description: 一键生成
    dt: string
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: constant
    id: 7042
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(表单)
    requestParamName: null
    sessionParamName: null
    uuid: '7042'
    validate: null
  - alias: id
    apiLegoId: 1086
    apiLegoUuid: '1086'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 7043
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: null
    sessionParamName: null
    uuid: '7043'
    validate: null
  - alias: name
    apiLegoId: 1086
    apiLegoUuid: '1086'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 7044
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: null
    sessionParamName: null
    uuid: '7044'
    validate: null
  - alias: description
    apiLegoId: 1086
    apiLegoUuid: '1086'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 7045
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: null
    sessionParamName: null
    uuid: '7045'
    validate: null
  - alias: alias
    apiLegoId: 1086
    apiLegoUuid: '1086'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 7046
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: null
    sessionParamName: null
    uuid: '7046'
    validate: null
  - alias: judgeAPIAlias
    apiLegoId: 1086
    apiLegoUuid: '1086'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: judgeAPIAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 7047
    ift: read
    inputFieldDescribeId: 0
    name: 判断执行的API
    requestParamName: null
    sessionParamName: null
    uuid: '7047'
    validate: null
  - alias: noAuthErrorCode
    apiLegoId: 1086
    apiLegoUuid: '1086'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: noAuthErrorCode
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 7048
    ift: read
    inputFieldDescribeId: 0
    name: 错误代码
    requestParamName: null
    sessionParamName: null
    uuid: '7048'
    validate: null
  - alias: keywords
    apiLegoId: 1086
    apiLegoUuid: '1086'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7049
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '7049'
    validate: null
  - alias: group_field
    apiLegoId: 1086
    apiLegoUuid: '1086'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 7050
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: null
    sessionParamName: null
    uuid: '7050'
    validate: null
  - alias: order
    apiLegoId: 1086
    apiLegoUuid: '1086'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 7051
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: null
    sessionParamName: null
    uuid: '7051'
    validate: null
  - alias: order_field
    apiLegoId: 1086
    apiLegoUuid: '1086'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 7052
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: null
    sessionParamName: null
    uuid: '7052'
    validate: null
  - alias: page
    apiLegoId: 1086
    apiLegoUuid: '1086'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: page
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7053
    ift: common
    inputFieldDescribeId: 0
    name: 请求页码
    requestParamName: page
    sessionParamName: null
    uuid: '7053'
    validate: null
  - alias: pageSize
    apiLegoId: 1086
    apiLegoUuid: '1086'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: pageSize
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7054
    ift: common
    inputFieldDescribeId: 0
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: null
    uuid: '7054'
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 1086
    apiLegoUuid: '1086'
    description: 一键生成
    dt: null
    fieldName: page_data
    fieldValue: null
    handle: null
    id: 1187
    name: 分页数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1187'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
