api:
  alias: ty-page-task
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-12T15:30:19Z
  description: 一键生成接口
  id: 501
  method: POST
  name: 分页获取任务列表
  type: ty
  url: ty-page-task
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-page-task
    attributes: null
    description: 一键生成接口
    id: 978
    index: 1
    legoAlias: page
    oiAlias: ty_task
    processControllerAlias: null
    uuid: '978'
  inputFields:
  - alias: global_search_fields
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: ''
    connectorPath: ''
    constant: '["id","name","alias"]'
    ct: eq
    description: 一键生成
    dt: string
    fieldName: global_search_fields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 6137
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(表单)
    requestParamName: ''
    sessionParamName: ''
    uuid: '6137'
    validate: ''
  - alias: id
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6138
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: null
    sessionParamName: null
    uuid: '6138'
    validate: null
  - alias: name
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6139
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: null
    sessionParamName: null
    uuid: '6139'
    validate: null
  - alias: description
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6140
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: null
    sessionParamName: null
    uuid: '6140'
    validate: null
  - alias: alias
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6141
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: null
    sessionParamName: null
    uuid: '6141'
    validate: null
  - alias: group
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: group
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6142
    ift: read
    inputFieldDescribeId: 0
    name: 组别
    requestParamName: null
    sessionParamName: null
    uuid: '6142'
    validate: null
  - alias: cron
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: cron
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6143
    ift: read
    inputFieldDescribeId: 0
    name: 执行规则
    requestParamName: null
    sessionParamName: null
    uuid: '6143'
    validate: null
  - alias: status
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: status
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6144
    ift: read
    inputFieldDescribeId: 0
    name: 状态
    requestParamName: null
    sessionParamName: null
    uuid: '6144'
    validate: null
  - alias: createDate
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6145
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: null
    sessionParamName: null
    uuid: '6145'
    validate: null
  - alias: apiAlias
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: apiAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6146
    ift: read
    inputFieldDescribeId: 0
    name: 接口别名
    requestParamName: null
    sessionParamName: null
    uuid: '6146'
    validate: null
  - alias: keywords
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: keywords
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6147
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: null
    uuid: '6147'
    validate: null
  - alias: group_field
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6148
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: null
    sessionParamName: null
    uuid: '6148'
    validate: null
  - alias: order
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6149
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: null
    sessionParamName: null
    uuid: '6149'
    validate: null
  - alias: order_field
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6150
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: null
    sessionParamName: null
    uuid: '6150'
    validate: null
  - alias: page
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: page
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6151
    ift: common
    inputFieldDescribeId: 0
    name: 请求页码
    requestParamName: page
    sessionParamName: null
    uuid: '6151'
    validate: null
  - alias: pageSize
    apiLegoId: 978
    apiLegoUuid: '978'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: pageSize
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6152
    ift: common
    inputFieldDescribeId: 0
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: null
    uuid: '6152'
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 978
    apiLegoUuid: '978'
    description: 一键生成
    dt: null
    fieldName: page_data
    fieldValue: null
    handle: null
    id: 1046
    name: 分页数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1046'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
