api:
  alias: ty-page-user
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-09T19:16:53Z
  description: 用户列表
  id: 449
  method: GET
  name: 用户列表
  type: ty
  url: ty-page-user
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-page-user
    attributes: null
    description: ''
    id: 5432
    index: 1
    legoAlias: page
    oiAlias: ty_user
    processControllerAlias: null
    uuid: '783'
  inputFields:
  - alias: page
    apiLegoId: 0
    apiLegoUuid: '783'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: page
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 49969
    ift: common
    inputFieldDescribeId: 0
    name: 请求页码
    requestParamName: page
    sessionParamName: ''
    uuid: '4313'
    validate: ''
  - alias: pageSize
    apiLegoId: 0
    apiLegoUuid: '783'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: pageSize
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 49970
    ift: common
    inputFieldDescribeId: 0
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: ''
    uuid: '4314'
    validate: ''
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '783'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 49971
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '4315'
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '783'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 49972
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '4316'
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '783'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 49973
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '4317'
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '783'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 49974
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '4318'
    validate: ''
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '783'
    attributes: null
    connectorPath: ''
    constant: '["xingMing","userName","alias"]'
    ct: eq
    description: ''
    dt: string
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 49975
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '4319'
    validate: ''
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '783'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 49976
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '4320'
    validate: null
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: '783'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 49977
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: ''
    uuid: '4321'
    validate: null
  - alias: xingMing
    apiLegoId: 0
    apiLegoUuid: '783'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: xingMing
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 49978
    ift: read
    inputFieldDescribeId: 0
    name: 姓名
    requestParamName: xingMing
    sessionParamName: ''
    uuid: '4322'
    validate: ''
  - alias: userName
    apiLegoId: 0
    apiLegoUuid: '783'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: userName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 49979
    ift: read
    inputFieldDescribeId: 0
    name: 用户名
    requestParamName: userName
    sessionParamName: ''
    uuid: '4323'
    validate: null
  - alias: password
    apiLegoId: 0
    apiLegoUuid: '783'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: password
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 49980
    ift: read
    inputFieldDescribeId: 0
    name: 密码
    requestParamName: password
    sessionParamName: ''
    uuid: '4324'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '783'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 49981
    ift: read
    inputFieldDescribeId: 0
    name: 用户别名
    requestParamName: alias
    sessionParamName: ''
    uuid: '4325'
    validate: null
  - alias: tenantSerialNumber
    apiLegoId: 0
    apiLegoUuid: '783'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: tenantSerialNumber
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.tenantSerialNumber}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 49982
    ift: condition
    inputFieldDescribeId: 0
    name: 租户序列号
    requestParamName: tenantSerialNumber
    sessionParamName: ''
    uuid: 20E5BDEB-F471-47E0-9F92-892DB5B6D8991527150789420
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 0
    apiLegoUuid: '783'
    description: ''
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 7582
    name: page_data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '822'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
