api:
  alias: ty-read-app-role
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-13T13:38:35Z
  description: ''
  id: 460
  method: GET
  name: 读取TY应用角色详情
  type: ty
  url: ty-read-app-role
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-read-app-role
    attributes: null
    description: null
    id: 833
    index: 1
    legoAlias: read
    oiAlias: ty_app_role
    processControllerAlias: null
    uuid: '833'
  inputFields:
  - alias: order_field
    apiLegoId: 833
    apiLegoUuid: '833'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 4806
    ift: common
    inputFieldDescribeId: 32
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '4806'
    validate: null
  - alias: order
    apiLegoId: 833
    apiLegoUuid: '833'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 4807
    ift: common
    inputFieldDescribeId: 44
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '4807'
    validate: null
  - alias: group_field
    apiLegoId: 833
    apiLegoUuid: '833'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 4808
    ift: common
    inputFieldDescribeId: 45
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '4808'
    validate: null
  - alias: id
    apiLegoId: 833
    apiLegoUuid: '833'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4809
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '4809'
    validate: null
  - alias: id
    apiLegoId: 833
    apiLegoUuid: '833'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4810
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '4810'
    validate: null
  - alias: name
    apiLegoId: 833
    apiLegoUuid: '833'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4811
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '4811'
    validate: null
  - alias: description
    apiLegoId: 833
    apiLegoUuid: '833'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4812
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '4812'
    validate: null
  - alias: appAlias
    apiLegoId: 833
    apiLegoUuid: '833'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: appAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4813
    ift: read
    inputFieldDescribeId: 0
    name: 应用别名
    requestParamName: appAlias
    sessionParamName: null
    uuid: '4813'
    validate: null
  - alias: superFlag
    apiLegoId: 833
    apiLegoUuid: '833'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: superFlag
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4814
    ift: read
    inputFieldDescribeId: 0
    name: 超级角色
    requestParamName: superFlag
    sessionParamName: null
    uuid: '4814'
    validate: null
  - alias: resources
    apiLegoId: 833
    apiLegoUuid: '833'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: resources
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4815
    ift: read
    inputFieldDescribeId: 0
    name: 资源列表
    requestParamName: resources
    sessionParamName: null
    uuid: '4815'
    validate: null
  - alias: createDate
    apiLegoId: 833
    apiLegoUuid: '833'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4816
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: null
    uuid: '4816'
    validate: null
  - alias: alias
    apiLegoId: 833
    apiLegoUuid: '833'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 4817
    ift: read
    inputFieldDescribeId: 0
    name: 角色别名
    requestParamName: alias
    sessionParamName: null
    uuid: '4817'
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 833
    apiLegoUuid: '833'
    description: null
    dt: string
    fieldName: data
    fieldValue: null
    handle: ''
    id: 883
    name: data
    oft: common
    outputFieldDescribeId: 32
    response: true
    uuid: '883'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
