api:
  alias: ty-read-user-app-role
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-13T13:53:51Z
  description: ''
  id: 462
  method: GET
  name: 读取TY用户授权信息
  type: ty
  url: ty-read-user-app-role
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-read-user-app-role
    attributes: null
    description: ''
    id: 7901
    index: 1
    legoAlias: read
    oiAlias: ty_user_app_role
    processControllerAlias: null
    uuid: '835'
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '835'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 72154
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '4824'
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '835'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 72155
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '4825'
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '835'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 72156
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '4826'
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '835'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 72157
    ift: condition
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: '4827'
    validate: '[{"params":"id为必填字段","validateName":"required"}]'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '835'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 72158
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: '4828'
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '835'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 72159
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: '4829'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '835'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 72160
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: '4830'
    validate: null
  - alias: userAlias
    apiLegoId: 0
    apiLegoUuid: '835'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: userAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 72161
    ift: read
    inputFieldDescribeId: 0
    name: userAlias
    requestParamName: userAlias
    sessionParamName: ''
    uuid: '4831'
    validate: null
  - alias: appAlias
    apiLegoId: 0
    apiLegoUuid: '835'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: appAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 72162
    ift: read
    inputFieldDescribeId: 0
    name: appAlias
    requestParamName: appAlias
    sessionParamName: ''
    uuid: '4832'
    validate: null
  - alias: roles
    apiLegoId: 0
    apiLegoUuid: '835'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: roles
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 72163
    ift: read
    inputFieldDescribeId: 0
    name: roles
    requestParamName: roles
    sessionParamName: ''
    uuid: '4833'
    validate: null
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: '835'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 72164
    ift: read
    inputFieldDescribeId: 0
    name: createDate
    requestParamName: createDate
    sessionParamName: ''
    uuid: '4834'
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 0
    apiLegoUuid: '835'
    description: ''
    dt: string
    fieldName: data
    fieldValue: null
    handle: ''
    id: 10471
    name: data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '885'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
