api:
  alias: ty-read-task
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-12T15:31:41Z
  description: 一键生成接口
  id: 505
  method: POST
  name: 读取任务详情
  type: ty
  url: ty-read-task
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-read-task
    attributes: null
    description: 一键生成接口
    id: 982
    index: 1
    legoAlias: read
    oiAlias: ty_task
    processControllerAlias: null
    uuid: '982'
  inputFields:
  - alias: id
    apiLegoId: 982
    apiLegoUuid: '982'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: 一键生成
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6171
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '6171'
    validate: null
  - alias: name
    apiLegoId: 982
    apiLegoUuid: '982'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6172
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: null
    sessionParamName: null
    uuid: '6172'
    validate: null
  - alias: description
    apiLegoId: 982
    apiLegoUuid: '982'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6173
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: null
    sessionParamName: null
    uuid: '6173'
    validate: null
  - alias: alias
    apiLegoId: 982
    apiLegoUuid: '982'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6174
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: null
    sessionParamName: null
    uuid: '6174'
    validate: null
  - alias: group
    apiLegoId: 982
    apiLegoUuid: '982'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: group
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6175
    ift: read
    inputFieldDescribeId: 0
    name: 组别
    requestParamName: null
    sessionParamName: null
    uuid: '6175'
    validate: null
  - alias: cron
    apiLegoId: 982
    apiLegoUuid: '982'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: cron
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6176
    ift: read
    inputFieldDescribeId: 0
    name: 执行规则
    requestParamName: null
    sessionParamName: null
    uuid: '6176'
    validate: null
  - alias: status
    apiLegoId: 982
    apiLegoUuid: '982'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: status
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6177
    ift: read
    inputFieldDescribeId: 0
    name: 状态
    requestParamName: null
    sessionParamName: null
    uuid: '6177'
    validate: null
  - alias: createDate
    apiLegoId: 982
    apiLegoUuid: '982'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6178
    ift: read
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: null
    sessionParamName: null
    uuid: '6178'
    validate: null
  - alias: apiAlias
    apiLegoId: 982
    apiLegoUuid: '982'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: apiAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 6179
    ift: read
    inputFieldDescribeId: 0
    name: 接口别名
    requestParamName: null
    sessionParamName: null
    uuid: '6179'
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 982
    apiLegoUuid: '982'
    description: 一键生成
    dt: null
    fieldName: data
    fieldValue: null
    handle: null
    id: 1048
    name: data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1048'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
