api:
  alias: ty-read-ofd
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-29T15:45:31Z
  description: ''
  id: 484
  method: GET
  name: 读取输出字段描述
  type: ty
  url: ty-read-ofd
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-read-ofd
    attributes: null
    description: null
    id: 941
    index: 1
    legoAlias: read
    oiAlias: ty_output_field_describe
    processControllerAlias: null
    uuid: '941'
  inputFields:
  - alias: order_field
    apiLegoId: 941
    apiLegoUuid: '941'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 5912
    ift: common
    inputFieldDescribeId: 32
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '5912'
    validate: null
  - alias: order
    apiLegoId: 941
    apiLegoUuid: '941'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 5913
    ift: common
    inputFieldDescribeId: 44
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '5913'
    validate: null
  - alias: group_field
    apiLegoId: 941
    apiLegoUuid: '941'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 5914
    ift: common
    inputFieldDescribeId: 45
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '5914'
    validate: null
  - alias: id
    apiLegoId: 941
    apiLegoUuid: '941'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 5915
    ift: condition
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '5915'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 941
    apiLegoUuid: '941'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5916
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '5916'
    validate: null
  - alias: name
    apiLegoId: 941
    apiLegoUuid: '941'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5917
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: '5917'
    validate: null
  - alias: description
    apiLegoId: 941
    apiLegoUuid: '941'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5918
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: null
    uuid: '5918'
    validate: null
  - alias: legoAlias
    apiLegoId: 941
    apiLegoUuid: '941'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: legoAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5919
    ift: read
    inputFieldDescribeId: 0
    name: legoAlias
    requestParamName: legoAlias
    sessionParamName: null
    uuid: '5919'
    validate: null
  - alias: fieldName
    apiLegoId: 941
    apiLegoUuid: '941'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: fieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5920
    ift: read
    inputFieldDescribeId: 0
    name: fieldName
    requestParamName: fieldName
    sessionParamName: null
    uuid: '5920'
    validate: null
  - alias: oft
    apiLegoId: 941
    apiLegoUuid: '941'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: oft
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5921
    ift: read
    inputFieldDescribeId: 0
    name: oft
    requestParamName: oft
    sessionParamName: null
    uuid: '5921'
    validate: null
  - alias: multiple
    apiLegoId: 941
    apiLegoUuid: '941'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: multiple
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5922
    ift: read
    inputFieldDescribeId: 0
    name: 是否多选
    requestParamName: multiple
    sessionParamName: null
    uuid: '5922'
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 941
    apiLegoUuid: '941'
    description: null
    dt: string
    fieldName: data
    fieldValue: null
    handle: ''
    id: 1012
    name: data
    oft: common
    outputFieldDescribeId: 32
    response: true
    uuid: '1012'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
