api:
  alias: ty-read-if
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-03-24T14:48:08Z
  description: null
  id: 776
  method: GET
  name: id获取inputfield
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-read-if
    attributes: null
    description: null
    id: 1644
    index: 1
    legoAlias: read
    oiAlias: ty_input_field
    processControllerAlias: null
    uuid: '1644'
  inputFields:
  - alias: order_field
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 11674
    ift: common
    inputFieldDescribeId: 32
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '11674'
    validate: null
  - alias: order
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 11675
    ift: common
    inputFieldDescribeId: 44
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '11675'
    validate: null
  - alias: group_field
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 11676
    ift: common
    inputFieldDescribeId: 45
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '11676'
    validate: null
  - alias: id
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 11677
    ift: condition
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '11677'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11678
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '11678'
    validate: null
  - alias: name
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11679
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: '11679'
    validate: null
  - alias: description
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11680
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: null
    uuid: '11680'
    validate: null
  - alias: apiLegoId
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: apiLegoId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11681
    ift: read
    inputFieldDescribeId: 0
    name: apiLegoId
    requestParamName: apiLegoId
    sessionParamName: null
    uuid: '11681'
    validate: null
  - alias: fieldName
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11682
    ift: read
    inputFieldDescribeId: 0
    name: fieldName
    requestParamName: fieldName
    sessionParamName: null
    uuid: '11682'
    validate: null
  - alias: ct
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: ct
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11683
    ift: read
    inputFieldDescribeId: 0
    name: ct
    requestParamName: ct
    sessionParamName: null
    uuid: '11683'
    validate: null
  - alias: ift
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: ift
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11684
    ift: read
    inputFieldDescribeId: 0
    name: ift
    requestParamName: ift
    sessionParamName: null
    uuid: '11684'
    validate: null
  - alias: fvt
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fvt
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11685
    ift: read
    inputFieldDescribeId: 0
    name: fvt
    requestParamName: fvt
    sessionParamName: null
    uuid: '11685'
    validate: null
  - alias: fromApiLegoId
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: fromApiLegoId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11686
    ift: read
    inputFieldDescribeId: 0
    name: fromApiLegoId
    requestParamName: fromApiLegoId
    sessionParamName: null
    uuid: '11686'
    validate: null
  - alias: alias
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11687
    ift: read
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: null
    uuid: '11687'
    validate: null
  - alias: validate
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: validate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11688
    ift: read
    inputFieldDescribeId: 0
    name: validate
    requestParamName: validate
    sessionParamName: null
    uuid: '11688'
    validate: null
  - alias: dt
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: dt
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11689
    ift: read
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: dt
    sessionParamName: null
    uuid: '11689'
    validate: null
  - alias: constant
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: constant
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11690
    ift: read
    inputFieldDescribeId: 0
    name: 常量值
    requestParamName: constant
    sessionParamName: null
    uuid: '11690'
    validate: null
  - alias: fromApiLegoOutputFieldAlias
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fromApiLegoOutputFieldAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11691
    ift: read
    inputFieldDescribeId: 0
    name: output输出字段别名
    requestParamName: fromApiLegoOutputFieldAlias
    sessionParamName: null
    uuid: '11691'
    validate: null
  - alias: requestParamName
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: requestParamName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11692
    ift: read
    inputFieldDescribeId: 0
    name: 请求参数别名
    requestParamName: requestParamName
    sessionParamName: null
    uuid: '11692'
    validate: null
  - alias: sessionParamName
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: sessionParamName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11693
    ift: read
    inputFieldDescribeId: 0
    name: session参数别名
    requestParamName: sessionParamName
    sessionParamName: null
    uuid: '11693'
    validate: null
  - alias: fieldTpl
    apiLegoId: 1644
    apiLegoUuid: '1644'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fieldTpl
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 11694
    ift: read
    inputFieldDescribeId: 0
    name: 字段值模板
    requestParamName: fieldTpl
    sessionParamName: null
    uuid: '11694'
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 1644
    apiLegoUuid: '1644'
    description: null
    dt: string
    fieldName: data
    fieldValue: null
    handle: ''
    id: 1833
    name: data
    oft: common
    outputFieldDescribeId: 32
    response: true
    uuid: '1833'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
