api:
  alias: ty-read-md
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-01-18T15:45:15Z
  description: null
  id: 637
  method: GET
  name: 获取积木方法详情
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-read-md
    attributes: null
    description: null
    id: 1267
    index: 1
    legoAlias: read
    oiAlias: ty_method_describe
    processControllerAlias: null
    uuid: '1267'
  inputFields:
  - alias: order_field
    apiLegoId: 1267
    apiLegoUuid: '1267'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 8624
    ift: common
    inputFieldDescribeId: 32
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '8624'
    validate: null
  - alias: order
    apiLegoId: 1267
    apiLegoUuid: '1267'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 8625
    ift: common
    inputFieldDescribeId: 44
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '8625'
    validate: null
  - alias: group_field
    apiLegoId: 1267
    apiLegoUuid: '1267'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 8626
    ift: common
    inputFieldDescribeId: 45
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '8626'
    validate: null
  - alias: id
    apiLegoId: 1267
    apiLegoUuid: '1267'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 8627
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '8627'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 1267
    apiLegoUuid: '1267'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8628
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '8628'
    validate: null
  - alias: name
    apiLegoId: 1267
    apiLegoUuid: '1267'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8629
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '8629'
    validate: null
  - alias: description
    apiLegoId: 1267
    apiLegoUuid: '1267'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8630
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '8630'
    validate: null
  - alias: buildingBlockAlias
    apiLegoId: 1267
    apiLegoUuid: '1267'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: buildingBlockAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8631
    ift: read
    inputFieldDescribeId: 0
    name: 积木别名
    requestParamName: buildingBlockAlias
    sessionParamName: null
    uuid: '8631'
    validate: null
  - alias: methodName
    apiLegoId: 1267
    apiLegoUuid: '1267'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: methodName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8632
    ift: read
    inputFieldDescribeId: 0
    name: 方法名
    requestParamName: methodName
    sessionParamName: null
    uuid: '8632'
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 1267
    apiLegoUuid: '1267'
    description: null
    dt: string
    fieldName: data
    fieldValue: null
    handle: ''
    id: 1405
    name: data
    oft: common
    outputFieldDescribeId: 32
    response: true
    uuid: '1405'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
