api:
  alias: ty-read-auth-type
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-20T15:29:09Z
  description: 一键生成接口
  id: 552
  method: GET
  name: 读取授权信息
  type: ty
  url: ty-read-auth-type
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-read-auth-type
    attributes: null
    description: 一键生成接口
    id: 1084
    index: 1
    legoAlias: read
    oiAlias: ty_auth_type
    processControllerAlias: null
    uuid: '1084'
  inputFields:
  - alias: id
    apiLegoId: 1084
    apiLegoUuid: '1084'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: 一键生成
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7030
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '7030'
    validate: null
  - alias: name
    apiLegoId: 1084
    apiLegoUuid: '1084'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 7031
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: null
    sessionParamName: null
    uuid: '7031'
    validate: null
  - alias: description
    apiLegoId: 1084
    apiLegoUuid: '1084'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 7032
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: null
    sessionParamName: null
    uuid: '7032'
    validate: null
  - alias: alias
    apiLegoId: 1084
    apiLegoUuid: '1084'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 7033
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: null
    sessionParamName: null
    uuid: '7033'
    validate: null
  - alias: judgeAPIAlias
    apiLegoId: 1084
    apiLegoUuid: '1084'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: judgeAPIAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 7034
    ift: read
    inputFieldDescribeId: 0
    name: 判断执行的API
    requestParamName: null
    sessionParamName: null
    uuid: '7034'
    validate: null
  - alias: noAuthErrorCode
    apiLegoId: 1084
    apiLegoUuid: '1084'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: noAuthErrorCode
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: 7035
    ift: read
    inputFieldDescribeId: 0
    name: 错误代码
    requestParamName: null
    sessionParamName: null
    uuid: '7035'
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 1084
    apiLegoUuid: '1084'
    description: 一键生成
    dt: null
    fieldName: data
    fieldValue: null
    handle: null
    id: 1186
    name: data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1186'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
