api:
  alias: ty-read-ed
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-01-18T15:43:54Z
  description: null
  id: 636
  method: GET
  name: 获取积木事件详情
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-read-ed
    attributes: null
    description: null
    id: 1266
    index: 1
    legoAlias: read
    oiAlias: ty_event_describe
    processControllerAlias: null
    uuid: '1266'
  inputFields:
  - alias: order_field
    apiLegoId: 1266
    apiLegoUuid: '1266'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 8615
    ift: common
    inputFieldDescribeId: 32
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '8615'
    validate: null
  - alias: order
    apiLegoId: 1266
    apiLegoUuid: '1266'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 8616
    ift: common
    inputFieldDescribeId: 44
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '8616'
    validate: null
  - alias: group_field
    apiLegoId: 1266
    apiLegoUuid: '1266'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 8617
    ift: common
    inputFieldDescribeId: 45
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '8617'
    validate: null
  - alias: id
    apiLegoId: 1266
    apiLegoUuid: '1266'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 8618
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '8618'
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 1266
    apiLegoUuid: '1266'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8619
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '8619'
    validate: null
  - alias: name
    apiLegoId: 1266
    apiLegoUuid: '1266'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8620
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '8620'
    validate: null
  - alias: description
    apiLegoId: 1266
    apiLegoUuid: '1266'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8621
    ift: read
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '8621'
    validate: null
  - alias: buildingBlockAlias
    apiLegoId: 1266
    apiLegoUuid: '1266'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: buildingBlockAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8622
    ift: read
    inputFieldDescribeId: 0
    name: 积木别名
    requestParamName: buildingBlockAlias
    sessionParamName: null
    uuid: '8622'
    validate: null
  - alias: eventName
    apiLegoId: 1266
    apiLegoUuid: '1266'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: eventName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 8623
    ift: read
    inputFieldDescribeId: 0
    name: 事件名称
    requestParamName: eventName
    sessionParamName: null
    uuid: '8623'
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 1266
    apiLegoUuid: '1266'
    description: null
    dt: string
    fieldName: data
    fieldValue: null
    handle: ''
    id: 1404
    name: data
    oft: common
    outputFieldDescribeId: 32
    response: true
    uuid: '1404'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
