api:
  alias: ty-read-ifd
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-29T15:44:34Z
  description: ''
  id: 483
  method: GET
  name: 读取输入描述
  type: ty
  url: ty-read-ifd
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-read-ifd
    attributes: null
    description: null
    id: 940
    index: 1
    legoAlias: read
    oiAlias: ty_input_field_describe
    processControllerAlias: null
    uuid: '940'
  inputFields:
  - alias: order_field
    apiLegoId: 940
    apiLegoUuid: '940'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 5900
    ift: common
    inputFieldDescribeId: 32
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '5900'
    validate: null
  - alias: order
    apiLegoId: 940
    apiLegoUuid: '940'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 5901
    ift: common
    inputFieldDescribeId: 44
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '5901'
    validate: null
  - alias: group_field
    apiLegoId: 940
    apiLegoUuid: '940'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 5902
    ift: common
    inputFieldDescribeId: 45
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '5902'
    validate: null
  - alias: id
    apiLegoId: 940
    apiLegoUuid: '940'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 5903
    ift: condition
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '5903'
    validate: null
  - alias: id
    apiLegoId: 940
    apiLegoUuid: '940'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5904
    ift: read
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '5904'
    validate: null
  - alias: name
    apiLegoId: 940
    apiLegoUuid: '940'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5905
    ift: read
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: '5905'
    validate: null
  - alias: description
    apiLegoId: 940
    apiLegoUuid: '940'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5906
    ift: read
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: null
    uuid: '5906'
    validate: null
  - alias: legoAlias
    apiLegoId: 940
    apiLegoUuid: '940'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: legoAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5907
    ift: read
    inputFieldDescribeId: 0
    name: legoAlias
    requestParamName: legoAlias
    sessionParamName: null
    uuid: '5907'
    validate: null
  - alias: fieldName
    apiLegoId: 940
    apiLegoUuid: '940'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: fieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5908
    ift: read
    inputFieldDescribeId: 0
    name: fieldName
    requestParamName: fieldName
    sessionParamName: null
    uuid: '5908'
    validate: null
  - alias: multiple
    apiLegoId: 940
    apiLegoUuid: '940'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: multiple
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5909
    ift: read
    inputFieldDescribeId: 0
    name: multiple
    requestParamName: multiple
    sessionParamName: null
    uuid: '5909'
    validate: null
  - alias: ift
    apiLegoId: 940
    apiLegoUuid: '940'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: ift
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5910
    ift: read
    inputFieldDescribeId: 0
    name: ift
    requestParamName: ift
    sessionParamName: null
    uuid: '5910'
    validate: null
  - alias: fromOIFields
    apiLegoId: 940
    apiLegoUuid: '940'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: fromOIFields
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 5911
    ift: read
    inputFieldDescribeId: 0
    name: fromOIFields
    requestParamName: fromOIFields
    sessionParamName: null
    uuid: '5911'
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 940
    apiLegoUuid: '940'
    description: null
    dt: string
    fieldName: data
    fieldValue: null
    handle: ''
    id: 1011
    name: data
    oft: common
    outputFieldDescribeId: 32
    response: true
    uuid: '1011'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
