api:
  alias: ty-read-session-user-info
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-29T17:54:10Z
  description: ''
  id: 575
  method: GET
  name: 读取TY登录信息
  type: ty
  url: ty-read-session-user-info
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-read-session-user-info
    attributes: null
    description: ''
    id: 6064
    index: 1
    legoAlias: sessionRead
    oiAlias: null
    processControllerAlias: null
    uuid: '1152'
  inputFields:
  - alias: formater_type
    apiLegoId: 0
    apiLegoUuid: '1152'
    attributes: null
    connectorPath: ''
    constant: json
    ct: eq
    description: 读取格式，默认是json
    dt: string
    fieldName: formater_type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 56233
    ift: common
    inputFieldDescribeId: 0
    name: 数据格式
    requestParamName: formater_type
    sessionParamName: ''
    uuid: '7521'
    validate: ''
  - alias: TY_SESSION_CONFIG_USER
    apiLegoId: 0
    apiLegoUuid: '1152'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: TY_SESSION_CONFIG_USER
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 56234
    ift: common
    inputFieldDescribeId: 0
    name: TY用户信息
    requestParamName: ''
    sessionParamName: ''
    uuid: '7523'
    validate: ''
  outputFields:
  - alias: data
    apiLegoId: 0
    apiLegoUuid: '1152'
    description: ''
    dt: ''
    fieldName: data
    fieldValue: null
    handle: ''
    id: 8448
    name: 读取数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1252'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '1152'
    description: ''
    dt: string
    fieldName: id
    fieldValue: null
    handle: ''
    id: 8449
    name: 用户别名
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1253'
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '1152'
    description: ''
    dt: string
    fieldName: xingMing
    fieldValue: null
    handle: ''
    id: 8450
    name: 用户名称
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1254'
  - alias: tenantSerialNumber
    apiLegoId: 0
    apiLegoUuid: '1152'
    description: ''
    dt: string
    fieldName: tenantSerialNumber
    fieldValue: null
    handle: ''
    id: 8451
    name: 租户序号
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 8C5FB0C6-FE27-47A7-ACE0-13296CB3946C1528771711804
- apiLego:
    apiAlias: ty-read-session-user-info
    attributes: null
    description: ''
    id: 6065
    index: 2
    legoAlias: read
    oiAlias: ty_tenant
    processControllerAlias: null
    uuid: 007F45C3-5A36-4123-AE76-3040DEC12D0C1528771723776
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 007F45C3-5A36-4123-AE76-3040DEC12D0C1528771723776
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 56235
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: 7EACF95D-9584-4A0D-BDA8-7834A10FFA691528771723776
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 007F45C3-5A36-4123-AE76-3040DEC12D0C1528771723776
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 56236
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: 64CA3BEE-EEB4-4F84-B7DE-B19118D6C9A21528771723776
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 007F45C3-5A36-4123-AE76-3040DEC12D0C1528771723776
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 56237
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: B415FE22-DF10-480E-88FE-01186E8FE8AD1528771723776
    validate: null
  - alias: serialNumber
    apiLegoId: 0
    apiLegoUuid: 007F45C3-5A36-4123-AE76-3040DEC12D0C1528771723776
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: serialNumber
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: tenantSerialNumber
    fromApiLegoUuid: '1152'
    fvt: output
    id: 56238
    ift: condition
    inputFieldDescribeId: 0
    name: 序号
    requestParamName: serialNumber
    sessionParamName: ''
    uuid: 7D365638-7BFE-4AB5-A05B-A6903616CCFC1528771737765
    validate: null
  - alias: logo
    apiLegoId: 0
    apiLegoUuid: 007F45C3-5A36-4123-AE76-3040DEC12D0C1528771723776
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: logo
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 56239
    ift: read
    inputFieldDescribeId: 0
    name: LOGO
    requestParamName: logo
    sessionParamName: ''
    uuid: F69F7BBA-21FE-469D-A4B5-E162E9CDCAC21528771751568
    validate: null
  - alias: companyName
    apiLegoId: 0
    apiLegoUuid: 007F45C3-5A36-4123-AE76-3040DEC12D0C1528771723776
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: companyName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 56240
    ift: read
    inputFieldDescribeId: 0
    name: 公司名称
    requestParamName: companyName
    sessionParamName: ''
    uuid: AAFB6138-B30F-4F55-AFCE-2E19DF65C8351528771764339
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 0
    apiLegoUuid: 007F45C3-5A36-4123-AE76-3040DEC12D0C1528771723776
    description: ''
    dt: ''
    fieldName: data
    fieldValue: null
    handle: ''
    id: 8452
    name: data
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: C8DED1BC-6B71-4791-AA7A-374085BE7A8D1528771723777
  - alias: companyName
    apiLegoId: 0
    apiLegoUuid: 007F45C3-5A36-4123-AE76-3040DEC12D0C1528771723776
    description: ''
    dt: string
    fieldName: companyName
    fieldValue: null
    handle: ''
    id: 8453
    name: 公司名称
    oft: read
    outputFieldDescribeId: 0
    response: true
    uuid: A082D5D5-EFC1-43D8-BCF4-EDDB7DE2497F1528771759768
  - alias: logo
    apiLegoId: 0
    apiLegoUuid: 007F45C3-5A36-4123-AE76-3040DEC12D0C1528771723776
    description: ''
    dt: string
    fieldName: logo
    fieldValue: null
    handle: ''
    id: 8454
    name: LOGO
    oft: read
    outputFieldDescribeId: 0
    response: true
    uuid: A39B5FB1-D24D-46CB-A07E-70746DB84C191528771759768
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
