api:
  alias: ty-read-session-b-user-info
  authType: ty_b_session
  category: config
  content: null
  createDate: 2018-07-17T20:35:30Z
  description: ''
  id: 1668
  method: GET
  name: 读取b端用户信息
  type: ty
  url: ''
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-read-session-b-user-info
    attributes: null
    description: ''
    id: 11386
    index: 1
    legoAlias: sessionRead
    oiAlias: null
    processControllerAlias: null
    uuid: 06CA270C-E3A7-4EF0-948C-713465FC416C1531830938913
  inputFields:
  - alias: formater_type
    apiLegoId: 0
    apiLegoUuid: 06CA270C-E3A7-4EF0-948C-713465FC416C1531830938913
    attributes: null
    connectorPath: ''
    constant: json
    ct: eq
    description: ''
    dt: string
    fieldName: formater_type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 103025
    ift: common
    inputFieldDescribeId: 0
    name: 数据格式(json/object)
    requestParamName: formater_type
    sessionParamName: ''
    uuid: FF451FC1-3BE6-4F1C-8894-B63B858B6B701531830938913
    validate: null
  - alias: TY_SESSION_B_USER
    apiLegoId: 0
    apiLegoUuid: 06CA270C-E3A7-4EF0-948C-713465FC416C1531830938913
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: TY_SESSION_B_USER
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 103026
    ift: common
    inputFieldDescribeId: 0
    name: 用户信息
    requestParamName: ''
    sessionParamName: ''
    uuid: D9F403CE-A31F-4439-B0D2-FFD4528BA7941531831080198
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 0
    apiLegoUuid: 06CA270C-E3A7-4EF0-948C-713465FC416C1531830938913
    description: ''
    dt: ''
    fieldName: data
    fieldValue: null
    handle: ''
    id: 14814
    name: 读取数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: F84D4105-5830-487B-BE16-8E55851B99421531830938913
  - alias: supplierCommpanySerialNumber
    apiLegoId: 0
    apiLegoUuid: 06CA270C-E3A7-4EF0-948C-713465FC416C1531830938913
    description: ''
    dt: string
    fieldName: supplierCommpanySerialNumber
    fieldValue: null
    handle: ''
    id: 14815
    name: 供应商公司序列号
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 9463B811-5481-4723-942A-3A2645E36B3C1532510446508
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 06CA270C-E3A7-4EF0-948C-713465FC416C1531830938913
    description: ''
    dt: string
    fieldName: id
    fieldValue: null
    handle: ''
    id: 14816
    name: id
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 3E57B320-1CCE-42E1-B1A6-9F845FACB75E1532510554550
  - alias: xingMing
    apiLegoId: 0
    apiLegoUuid: 06CA270C-E3A7-4EF0-948C-713465FC416C1531830938913
    description: ''
    dt: string
    fieldName: xingMing
    fieldValue: null
    handle: ''
    id: 14817
    name: 姓名
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 38E99A9E-CE52-4C3C-8CB7-B4DD0DFF3E4C1532510567578
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: 06CA270C-E3A7-4EF0-948C-713465FC416C1531830938913
    description: ''
    dt: string
    fieldName: alias
    fieldValue: null
    handle: ''
    id: 14818
    name: 用户标识
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 77182FCE-4B53-4E30-9A2D-FA6B3CED61B11532510612718
- apiLego:
    apiAlias: ty-read-session-b-user-info
    attributes: null
    description: ''
    id: 11387
    index: 2
    legoAlias: read
    oiAlias: ty_supplier_company
    processControllerAlias: null
    uuid: 0C54A86E-8336-4568-B9CE-DADE1D25E6E81532510359770
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 0C54A86E-8336-4568-B9CE-DADE1D25E6E81532510359770
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 103027
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: 94835831-A101-4F48-A73F-BD8A184C5FE81532510359770
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 0C54A86E-8336-4568-B9CE-DADE1D25E6E81532510359770
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 103028
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: AC057F19-291D-4F39-A727-D4EB44EC99ED1532510359770
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 0C54A86E-8336-4568-B9CE-DADE1D25E6E81532510359770
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 103029
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: A3C04DC1-D59E-4FF2-8186-9E2048DA052E1532510359770
    validate: null
  - alias: companyName
    apiLegoId: 0
    apiLegoUuid: 0C54A86E-8336-4568-B9CE-DADE1D25E6E81532510359770
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: companyName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 103030
    ift: read
    inputFieldDescribeId: 0
    name: companyName
    requestParamName: companyName
    sessionParamName: ''
    uuid: AC89518F-518F-4604-8970-8B9F6C18C2CF1532510394961
    validate: null
  - alias: logo
    apiLegoId: 0
    apiLegoUuid: 0C54A86E-8336-4568-B9CE-DADE1D25E6E81532510359770
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: logo
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 103031
    ift: read
    inputFieldDescribeId: 0
    name: logo
    requestParamName: logo
    sessionParamName: ''
    uuid: 905DD302-AA5B-444F-B718-4D79EC9692801532510394961
    validate: null
  - alias: serialNumber
    apiLegoId: 0
    apiLegoUuid: 0C54A86E-8336-4568-B9CE-DADE1D25E6E81532510359770
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: serialNumber
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: supplierCommpanySerialNumber
    fromApiLegoUuid: 06CA270C-E3A7-4EF0-948C-713465FC416C1531830938913
    fvt: output
    id: 103032
    ift: condition
    inputFieldDescribeId: 0
    name: serialNumber
    requestParamName: serialNumber
    sessionParamName: ''
    uuid: 5BBBD22A-F8D1-46AC-823E-244F3680CACF1532510404646
    validate: null
  outputFields:
  - alias: data2
    apiLegoId: 0
    apiLegoUuid: 0C54A86E-8336-4568-B9CE-DADE1D25E6E81532510359770
    description: ''
    dt: ''
    fieldName: data
    fieldValue: null
    handle: ''
    id: 14819
    name: data
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: A966875B-D401-4A57-80CA-0973FB4F63DA1532510359770
  - alias: companyName
    apiLegoId: 0
    apiLegoUuid: 0C54A86E-8336-4568-B9CE-DADE1D25E6E81532510359770
    description: ''
    dt: string
    fieldName: companyName
    fieldValue: null
    handle: ''
    id: 14820
    name: companyName
    oft: read
    outputFieldDescribeId: 0
    response: true
    uuid: 38FFC122-ADBE-47B0-9C3F-53C3D027477C1532510538682
  - alias: companyLogo
    apiLegoId: 0
    apiLegoUuid: 0C54A86E-8336-4568-B9CE-DADE1D25E6E81532510359770
    description: ''
    dt: string
    fieldName: logo
    fieldValue: null
    handle: ''
    id: 14821
    name: logo
    oft: read
    outputFieldDescribeId: 0
    response: true
    uuid: 52F221C2-64FE-4724-809D-39231D2AF3B71532510538682
  - alias: tenantSerialNumber
    apiLegoId: 0
    apiLegoUuid: 0C54A86E-8336-4568-B9CE-DADE1D25E6E81532510359770
    description: ''
    dt: string
    fieldName: tenantSerialNumber
    fieldValue: null
    handle: ''
    id: 14822
    name: tenantSerialNumber
    oft: read
    outputFieldDescribeId: 0
    response: true
    uuid: 1F809E06-ABD2-4DC0-AFA9-32BC556DB8281532510583458
- apiLego:
    apiAlias: ty-read-session-b-user-info
    attributes: null
    description: 以免上面获取不到logo，下面两个节点是获取logo的
    id: null
    index: null
    legoAlias: sessionUserRead
    oiAlias: null
    processControllerAlias: null
    uuid: B639F121-9E9E-4F90-9902-66905CFA262A1541902742672
  inputFields: [
    ]
  outputFields:
  - alias: user_unique_id
    apiLegoId: null
    apiLegoUuid: B639F121-9E9E-4F90-9902-66905CFA262A1541902742672
    description: null
    dt: null
    fieldName: user_unique_id
    fieldValue: null
    handle: null
    id: null
    name: 用户唯一ID
    oft: common
    outputFieldDescribeId: 92
    response: false
    uuid: D1EB28E3-F034-40F5-A81C-B3F02B6E8EF71541902742672
  - alias: user_xingming
    apiLegoId: null
    apiLegoUuid: B639F121-9E9E-4F90-9902-66905CFA262A1541902742672
    description: null
    dt: null
    fieldName: user_xingming
    fieldValue: null
    handle: null
    id: null
    name: 用户姓名
    oft: common
    outputFieldDescribeId: 93
    response: false
    uuid: 201ABA5E-7901-4A63-ACD3-9C118D984B361541902742672
  - alias: tenant_serial_number
    apiLegoId: null
    apiLegoUuid: B639F121-9E9E-4F90-9902-66905CFA262A1541902742672
    description: null
    dt: null
    fieldName: tenant_serial_number
    fieldValue: null
    handle: null
    id: null
    name: 租户序列号
    oft: common
    outputFieldDescribeId: 94
    response: true
    uuid: 3B2B574B-45AF-450C-BA51-B6ABBB9ED2A41541902742672
  - alias: market_id
    apiLegoId: null
    apiLegoUuid: B639F121-9E9E-4F90-9902-66905CFA262A1541902742672
    description: null
    dt: null
    fieldName: market_id
    fieldValue: null
    handle: null
    id: null
    name: 商场ID
    oft: common
    outputFieldDescribeId: 95
    response: false
    uuid: 08F7DAD8-F6EC-4529-A34C-E7597DA9C04F1541902742672
  - alias: market_desc
    apiLegoId: null
    apiLegoUuid: B639F121-9E9E-4F90-9902-66905CFA262A1541902742672
    description: null
    dt: null
    fieldName: market_desc
    fieldValue: null
    handle: null
    id: null
    name: 商场名称
    oft: common
    outputFieldDescribeId: 96
    response: false
    uuid: E1BFF5E3-6A48-4974-BFDE-B3410B99B0841541902742672
- apiLego:
    apiAlias: ty-read-session-b-user-info
    attributes: null
    description: null
    id: null
    index: null
    legoAlias: read
    oiAlias: ty_tenant
    processControllerAlias: null
    uuid: D477B5C0-FE7C-42BB-84E5-A744054547AD1541902755208
  inputFields:
  - alias: order_field
    apiLegoId: null
    apiLegoUuid: D477B5C0-FE7C-42BB-84E5-A744054547AD1541902755208
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: null
    ift: common
    inputFieldDescribeId: 32
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: 1E9A76C9-3371-468B-BF6C-2DF1B774D4D61541902755208
    validate: null
  - alias: order
    apiLegoId: null
    apiLegoUuid: D477B5C0-FE7C-42BB-84E5-A744054547AD1541902755208
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: null
    ift: common
    inputFieldDescribeId: 44
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: 6F2FA521-CF09-48C3-ACF3-9FF365323FA61541902755208
    validate: null
  - alias: group_field
    apiLegoId: null
    apiLegoUuid: D477B5C0-FE7C-42BB-84E5-A744054547AD1541902755208
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: null
    id: null
    ift: common
    inputFieldDescribeId: 45
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: 1942090A-A884-4A3F-AFC9-AD3FBA8C75B81541902755209
    validate: null
  - alias: companyName
    apiLegoId: null
    apiLegoUuid: D477B5C0-FE7C-42BB-84E5-A744054547AD1541902755208
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: companyName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: read
    inputFieldDescribeId: null
    name: 公司名称
    requestParamName: companyName
    sessionParamName: null
    uuid: 806CC890-4A6A-4617-A769-AF92C3351A2E1541902801809
    validate: null
  - alias: logo
    apiLegoId: null
    apiLegoUuid: D477B5C0-FE7C-42BB-84E5-A744054547AD1541902755208
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: logo
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: read
    inputFieldDescribeId: null
    name: LOGO
    requestParamName: logo
    sessionParamName: null
    uuid: 009D7CAB-336C-4A2A-BAD1-7E74B0F680A51541902801809
    validate: null
  - alias: serialNumber
    apiLegoId: null
    apiLegoUuid: D477B5C0-FE7C-42BB-84E5-A744054547AD1541902755208
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: serialNumber
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: tenant_serial_number
    fromApiLegoUuid: B639F121-9E9E-4F90-9902-66905CFA262A1541902742672
    fvt: output
    id: null
    ift: condition
    inputFieldDescribeId: null
    name: 序号
    requestParamName: serialNumber
    sessionParamName: null
    uuid: 6DCA451D-CF16-46B6-91F0-426B083D1ACB1541902806992
    validate: '[]'
  outputFields:
  - alias: data
    apiLegoId: null
    apiLegoUuid: D477B5C0-FE7C-42BB-84E5-A744054547AD1541902755208
    description: null
    dt: null
    fieldName: data
    fieldValue: null
    handle: null
    id: null
    name: data
    oft: common
    outputFieldDescribeId: 32
    response: false
    uuid: D90428CB-10FC-414B-AA41-1702A296BA891541902755209
  - alias: logo
    apiLegoId: null
    apiLegoUuid: D477B5C0-FE7C-42BB-84E5-A744054547AD1541902755208
    description: null
    dt: string
    fieldName: logo
    fieldValue: null
    handle: null
    id: null
    name: LOGO
    oft: read
    outputFieldDescribeId: null
    response: true
    uuid: 4D45C3BA-740D-4D68-86B8-62BD002F93EB1541902822672
authTypes:
- alias: ty_b_session
  description: TY的B端供应商session校验
  id: 4
  judgeAPIAlias: ty_b_session_check
  name: B端登录校验
  noAuthErrorCode: null
