api:
  alias: ty-save-page-config
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-02-25T16:26:11Z
  description: null
  id: 670
  method: POST
  name: 保存页面配置-2.0
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-save-page-config
    attributes: null
    description: ''
    id: 3729
    index: 1
    legoAlias: update
    oiAlias: ty_page
    processControllerAlias: null
    uuid: '1352'
  inputFields:
  - alias: ds
    apiLegoId: 0
    apiLegoUuid: '1352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: ds
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 30910
    ift: update
    inputFieldDescribeId: 0
    name: 数据源
    requestParamName: ds
    sessionParamName: ''
    uuid: '9489'
    validate: null
  - alias: layoutObject
    apiLegoId: 0
    apiLegoUuid: '1352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: layoutObject
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 30911
    ift: update
    inputFieldDescribeId: 0
    name: 属性json
    requestParamName: layoutObject
    sessionParamName: ''
    uuid: '9490'
    validate: null
  - alias: content
    apiLegoId: 0
    apiLegoUuid: '1352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: content
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 30912
    ift: update
    inputFieldDescribeId: 0
    name: pbb列表内容
    requestParamName: content
    sessionParamName: ''
    uuid: '9491'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '1352'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 30913
    ift: condition
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: ''
    uuid: '9493'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
