api:
  alias: ty-save-lego-config
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-03-30T14:12:32Z
  description: 先删除了原有的接口数据，再插入apilego inputField outputFIeld
  id: 863
  method: POST
  name: 保存api接口2.0
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-save-lego-config
    attributes: null
    description: ''
    id: 2297
    index: 1
    legoAlias: dataBaseTransaction
    oiAlias: null
    processControllerAlias: null
    uuid: '1796'
  inputFields:
  - alias: ds
    apiLegoId: 0
    apiLegoUuid: '1796'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: ds
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 17151
    ift: common
    inputFieldDescribeId: 0
    name: DS数据源的别名
    requestParamName: ds
    sessionParamName: ''
    uuid: '12703'
    validate: '[{"validateName":"required"}]'
  - alias: dataList
    apiLegoId: 0
    apiLegoUuid: '1796'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: dataList
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 17152
    ift: common
    inputFieldDescribeId: 0
    name: Transaction执行对象集合
    requestParamName: dataList
    sessionParamName: ''
    uuid: '12704'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
- apiLego:
    apiAlias: ty-save-lego-config
    attributes: null
    description: 保存配置接口日志
    id: 2298
    index: 2
    legoAlias: add
    oiAlias: ty_api_log
    processControllerAlias: null
    uuid: 9D112539-0223-4304-83D4-B3C57AEEF1341523871844283
  inputFields:
  - alias: operatorId
    apiLegoId: 0
    apiLegoUuid: 9D112539-0223-4304-83D4-B3C57AEEF1341523871844283
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: operatorId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 17153
    ift: create
    inputFieldDescribeId: 0
    name: 操作人ID
    requestParamName: operatorId
    sessionParamName: ''
    uuid: 8E7C5098-AC81-4BA1-A63A-260EB128DD8B1523871864321
    validate: null
  - alias: operatorName
    apiLegoId: 0
    apiLegoUuid: 9D112539-0223-4304-83D4-B3C57AEEF1341523871844283
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operatorName
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.xingMing}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 17154
    ift: create
    inputFieldDescribeId: 0
    name: 操作人姓名
    requestParamName: operatorName
    sessionParamName: ''
    uuid: F0B58454-97BA-49A2-B331-103DFEE11A9A1523871864321
    validate: null
  - alias: operateDate
    apiLegoId: 0
    apiLegoUuid: 9D112539-0223-4304-83D4-B3C57AEEF1341523871844283
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: time
    fieldName: operateDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 17155
    ift: create
    inputFieldDescribeId: 0
    name: 操作时间
    requestParamName: operateDate
    sessionParamName: ''
    uuid: 561F5288-5A90-405D-A141-20A371A662211523871864321
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: operateContent
    apiLegoId: 0
    apiLegoUuid: 9D112539-0223-4304-83D4-B3C57AEEF1341523871844283
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateContent
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 17156
    ift: create
    inputFieldDescribeId: 0
    name: 详细操作内容
    requestParamName: dataList
    sessionParamName: ''
    uuid: 50729C61-D7CF-4B76-B981-6143D673D5C01523871864321
    validate: '[{"validateName":"dataToJson"}]'
  - alias: operateAlias
    apiLegoId: 0
    apiLegoUuid: 9D112539-0223-4304-83D4-B3C57AEEF1341523871844283
    attributes: null
    connectorPath: ''
    constant: ty_api
    ct: eq
    description: ''
    dt: string
    fieldName: operateAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 17157
    ift: create
    inputFieldDescribeId: 0
    name: 操作接口别名
    requestParamName: operateAlias
    sessionParamName: ''
    uuid: E6E9CB3D-239C-431E-BC73-33B3D8C7E8E31523871864321
    validate: null
  - alias: operateDes
    apiLegoId: 0
    apiLegoUuid: 9D112539-0223-4304-83D4-B3C57AEEF1341523871844283
    attributes: null
    connectorPath: ''
    constant: 保存api配置
    ct: eq
    description: ''
    dt: string
    fieldName: operateDes
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 17158
    ift: create
    inputFieldDescribeId: 0
    name: 操作描述
    requestParamName: operateDes
    sessionParamName: ''
    uuid: 280F297C-5EFE-420F-886C-BBD4CA9E6D501523871864321
    validate: null
  outputFields:
  - alias: unique_value
    apiLegoId: 0
    apiLegoUuid: 9D112539-0223-4304-83D4-B3C57AEEF1341523871844283
    description: ''
    dt: ''
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 2686
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: 66DB96AE-9BE6-4CE4-9E0E-176E97EC30091523871844283
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
