api:
  alias: ty-update-task
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-12T15:31:30Z
  description: 一键生成接口
  id: 504
  method: POST
  name: 更新任务信息
  type: ty
  url: ty-update-task
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-update-task
    attributes: null
    description: 一键生成接口
    id: 981
    index: 1
    legoAlias: update
    oiAlias: ty_task
    processControllerAlias: null
    uuid: '981'
  inputFields:
  - alias: id
    apiLegoId: 981
    apiLegoUuid: '981'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: 一键生成
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6162
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '6162'
    validate: null
  - alias: name
    apiLegoId: 981
    apiLegoUuid: '981'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6163
    ift: update
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '6163'
    validate: null
  - alias: description
    apiLegoId: 981
    apiLegoUuid: '981'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6164
    ift: update
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '6164'
    validate: null
  - alias: alias
    apiLegoId: 981
    apiLegoUuid: '981'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6165
    ift: update
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '6165'
    validate: null
  - alias: group
    apiLegoId: 981
    apiLegoUuid: '981'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: group
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6166
    ift: update
    inputFieldDescribeId: 0
    name: 组别
    requestParamName: group
    sessionParamName: null
    uuid: '6166'
    validate: null
  - alias: cron
    apiLegoId: 981
    apiLegoUuid: '981'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: cron
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6167
    ift: update
    inputFieldDescribeId: 0
    name: 执行规则
    requestParamName: cron
    sessionParamName: null
    uuid: '6167'
    validate: null
  - alias: status
    apiLegoId: 981
    apiLegoUuid: '981'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: status
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6168
    ift: update
    inputFieldDescribeId: 0
    name: 状态
    requestParamName: status
    sessionParamName: null
    uuid: '6168'
    validate: null
  - alias: createDate
    apiLegoId: 981
    apiLegoUuid: '981'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: createDate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6169
    ift: update
    inputFieldDescribeId: 0
    name: 创建时间
    requestParamName: createDate
    sessionParamName: null
    uuid: '6169'
    validate: null
  - alias: apiAlias
    apiLegoId: 981
    apiLegoUuid: '981'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: apiAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 6170
    ift: update
    inputFieldDescribeId: 0
    name: 接口别名
    requestParamName: apiAlias
    sessionParamName: null
    uuid: '6170'
    validate: null
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
