api:
  alias: ty-update-app
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-09T18:00:25Z
  description: 修改TY应用
  id: 444
  method: POST
  name: 修改TY应用
  type: ty
  url: ty-update-app
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-update-app
    attributes: null
    description: null
    id: 775
    index: 2
    legoAlias: update
    oiAlias: ty_app
    processControllerAlias: null
    uuid: '775'
  inputFields:
  - alias: id
    apiLegoId: 775
    apiLegoUuid: '775'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: 应用id
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 4286
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '4286'
    validate: ''
  - alias: name
    apiLegoId: 775
    apiLegoUuid: '775'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: 应用名称
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4287
    ift: update
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '4287'
    validate: ''
  - alias: description
    apiLegoId: 775
    apiLegoUuid: '775'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: 应用描述
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4288
    ift: update
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '4288'
    validate: ''
  - alias: online
    apiLegoId: 775
    apiLegoUuid: '775'
    attributes: ''
    connectorPath: ''
    constant: '1'
    ct: eq
    description: ''
    dt: string
    fieldName: online
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 4291
    ift: update
    inputFieldDescribeId: 0
    name: '是否上线 '
    requestParamName: online
    sessionParamName: ''
    uuid: '4291'
    validate: ''
  - alias: entrance
    apiLegoId: 775
    apiLegoUuid: '775'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: 入口页
    dt: string
    fieldName: entrance
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4292
    ift: update
    inputFieldDescribeId: 0
    name: 入口页
    requestParamName: entrance
    sessionParamName: null
    uuid: '4292'
    validate: ''
  - alias: buzzAlias
    apiLegoId: 775
    apiLegoUuid: '775'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: buzzAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7503
    ift: update
    inputFieldDescribeId: 0
    name: 巴斯别名
    requestParamName: buzzAlias
    sessionParamName: null
    uuid: '7503'
    validate: null
  - alias: icon
    apiLegoId: 775
    apiLegoUuid: '775'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: icon
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 7504
    ift: update
    inputFieldDescribeId: 0
    name: ICON别名
    requestParamName: icon
    sessionParamName: ''
    uuid: '7504'
    validate: ''
  - alias: owerId
    apiLegoId: 775
    apiLegoUuid: '775'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: owerId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 8843
    ift: update
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: null
    uuid: '8843'
    validate: null
  - alias: owerName
    apiLegoId: 775
    apiLegoUuid: '775'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: owerName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 8844
    ift: update
    inputFieldDescribeId: 0
    name: 负责人名称
    requestParamName: owerName
    sessionParamName: null
    uuid: '8844'
    validate: null
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
