api:
  alias: ty-update-user-app-role
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-13T13:54:51Z
  description: ''
  id: 463
  method: POST
  name: 更新TY用户授权
  type: ty
  url: ty-update-user-app-role
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-update-user-app-role
    attributes: null
    description: null
    id: 836
    index: 1
    legoAlias: update
    oiAlias: ty_user_app_role
    processControllerAlias: null
    uuid: '836'
  inputFields:
  - alias: id
    apiLegoId: 836
    apiLegoUuid: '836'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4835
    ift: condition
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: null
    uuid: '4835'
    validate: null
  - alias: name
    apiLegoId: 836
    apiLegoUuid: '836'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4836
    ift: update
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: null
    uuid: '4836'
    validate: null
  - alias: description
    apiLegoId: 836
    apiLegoUuid: '836'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4837
    ift: update
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: null
    uuid: '4837'
    validate: null
  - alias: userAlias
    apiLegoId: 836
    apiLegoUuid: '836'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: userAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4838
    ift: update
    inputFieldDescribeId: 0
    name: userAlias
    requestParamName: userAlias
    sessionParamName: null
    uuid: '4838'
    validate: null
  - alias: roles
    apiLegoId: 836
    apiLegoUuid: '836'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: null
    fieldName: roles
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4839
    ift: update
    inputFieldDescribeId: 0
    name: roles
    requestParamName: roles
    sessionParamName: null
    uuid: '4839'
    validate: null
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
