api:
  alias: ty-update-user
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-05-31T21:04:51Z
  description: null
  id: 1232
  method: POST
  name: 更新用户信息
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-update-user
    attributes: null
    description: ''
    id: 5763
    index: 1
    legoAlias: update
    oiAlias: ty_user
    processControllerAlias: null
    uuid: 6FA938DC-7815-44F6-B9C5-9FC06458B4531527771898687
  inputFields:
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 6FA938DC-7815-44F6-B9C5-9FC06458B4531527771898687
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53545
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: 05F68B1C-9616-48F4-854D-3DBEBF7D6E111527771920827
    validate: null
  - alias: xingMing
    apiLegoId: 0
    apiLegoUuid: 6FA938DC-7815-44F6-B9C5-9FC06458B4531527771898687
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: xingMing
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53546
    ift: update
    inputFieldDescribeId: 0
    name: 姓名
    requestParamName: xingMing
    sessionParamName: ''
    uuid: CD6496BA-7BCA-4E32-B1C0-01809BEC615F1527771945523
    validate: null
  - alias: userName
    apiLegoId: 0
    apiLegoUuid: 6FA938DC-7815-44F6-B9C5-9FC06458B4531527771898687
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: userName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53547
    ift: update
    inputFieldDescribeId: 0
    name: 用户名
    requestParamName: userName
    sessionParamName: ''
    uuid: 19381A2B-925F-43AA-B325-70C39FE0AFFD1527771945523
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: 6FA938DC-7815-44F6-B9C5-9FC06458B4531527771898687
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53548
    ift: update
    inputFieldDescribeId: 0
    name: 用户别名
    requestParamName: alias
    sessionParamName: ''
    uuid: 6034844C-BB2D-472E-9846-BE0E9BCEB5521527771945523
    validate: null
  - alias: tenantSerialNumber
    apiLegoId: 0
    apiLegoUuid: 6FA938DC-7815-44F6-B9C5-9FC06458B4531527771898687
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: tenantSerialNumber
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53549
    ift: update
    inputFieldDescribeId: 0
    name: 租户序列号
    requestParamName: tenantSerialNumber
    sessionParamName: ''
    uuid: DB5D43E8-D539-40AB-8357-E059185DCBDB1527771945523
    validate: null
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
