api:
  alias: ty-update-auth-type
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-12-20T15:29:22Z
  description: 一键生成接口
  id: 553
  method: POST
  name: 更新授权
  type: ty
  url: ty-update-auth-type
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-update-auth-type
    attributes: null
    description: 一键生成接口
    id: 1085
    index: 1
    legoAlias: update
    oiAlias: ty_auth_type
    processControllerAlias: null
    uuid: '1085'
  inputFields:
  - alias: id
    apiLegoId: 1085
    apiLegoUuid: '1085'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: 一键生成
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7036
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '7036'
    validate: null
  - alias: name
    apiLegoId: 1085
    apiLegoUuid: '1085'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7037
    ift: update
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '7037'
    validate: null
  - alias: description
    apiLegoId: 1085
    apiLegoUuid: '1085'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7038
    ift: update
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '7038'
    validate: null
  - alias: alias
    apiLegoId: 1085
    apiLegoUuid: '1085'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7039
    ift: update
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '7039'
    validate: null
  - alias: judgeAPIAlias
    apiLegoId: 1085
    apiLegoUuid: '1085'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: judgeAPIAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7040
    ift: update
    inputFieldDescribeId: 0
    name: 判断执行的API
    requestParamName: judgeAPIAlias
    sessionParamName: null
    uuid: '7040'
    validate: null
  - alias: noAuthErrorCode
    apiLegoId: 1085
    apiLegoUuid: '1085'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: 一键生成
    dt: string
    fieldName: noAuthErrorCode
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 7041
    ift: update
    inputFieldDescribeId: 0
    name: 错误代码
    requestParamName: noAuthErrorCode
    sessionParamName: null
    uuid: '7041'
    validate: null
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
