api:
  alias: ty-update-app-role
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-11-09T19:09:00Z
  description: 修改应用角色
  id: 447
  method: POST
  name: 修改应用角色
  type: ty
  url: ty-update-app-role
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-update-app-role
    attributes: null
    description: null
    id: 781
    index: 2
    legoAlias: update
    oiAlias: ty_app_role
    processControllerAlias: null
    uuid: '781'
  inputFields:
  - alias: id
    apiLegoId: 781
    apiLegoUuid: '781'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: 应用角色id
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4304
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '4304'
    validate: ''
  - alias: name
    apiLegoId: 781
    apiLegoUuid: '781'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: 名称
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4305
    ift: update
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '4305'
    validate: ''
  - alias: description
    apiLegoId: 781
    apiLegoUuid: '781'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: 描述
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4306
    ift: update
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '4306'
    validate: ''
  - alias: superFlag
    apiLegoId: 781
    apiLegoUuid: '781'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: 超级角色
    dt: string
    fieldName: superFlag
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4308
    ift: update
    inputFieldDescribeId: 0
    name: 超级角色
    requestParamName: superFlag
    sessionParamName: null
    uuid: '4308'
    validate: ''
  - alias: resources
    apiLegoId: 781
    apiLegoUuid: '781'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: 资源列表
    dt: string
    fieldName: resources
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 4309
    ift: update
    inputFieldDescribeId: 0
    name: 资源列表
    requestParamName: resources
    sessionParamName: null
    uuid: '4309'
    validate: ''
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
