api:
  alias: ty-up-apiLego
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-02-25T10:03:02Z
  description: null
  id: 666
  method: POST
  name: API乐高上移
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty-up-apiLego
    attributes: null
    description: null
    id: 1342
    index: 1
    legoAlias: read
    oiAlias: ty_api_lego
    processControllerAlias: null
    uuid: '1342'
  inputFields:
  - alias: order_field
    apiLegoId: 1342
    apiLegoUuid: '1342'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9408
    ift: common
    inputFieldDescribeId: 32
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '9408'
    validate: null
  - alias: order
    apiLegoId: 1342
    apiLegoUuid: '1342'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: order
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9409
    ift: common
    inputFieldDescribeId: 44
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '9409'
    validate: null
  - alias: group_field
    apiLegoId: 1342
    apiLegoUuid: '1342'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9410
    ift: common
    inputFieldDescribeId: 45
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '9410'
    validate: null
  - alias: id
    apiLegoId: 1342
    apiLegoUuid: '1342'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 9411
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '9411'
    validate: '[{"validateName":"required"}]'
  - alias: index
    apiLegoId: 1342
    apiLegoUuid: '1342'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: index
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9412
    ift: read
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: index
    sessionParamName: null
    uuid: '9412'
    validate: null
  - alias: apiAlias
    apiLegoId: 1342
    apiLegoUuid: '1342'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: apiAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9419
    ift: read
    inputFieldDescribeId: 0
    name: API别名
    requestParamName: apiAlias
    sessionParamName: null
    uuid: '9419'
    validate: null
  - alias: id
    apiLegoId: 1342
    apiLegoUuid: '1342'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9422
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '9422'
    validate: null
  outputFields:
  - alias: currentApiLego
    apiLegoId: 1342
    apiLegoUuid: '1342'
    description: ''
    dt: string
    fieldName: data
    fieldValue: null
    handle: ''
    id: 1478
    name: data
    oft: common
    outputFieldDescribeId: 32
    response: false
    uuid: '1478'
- apiLego:
    apiAlias: ty-up-apiLego
    attributes: null
    description: null
    id: 1343
    index: 2
    legoAlias: read
    oiAlias: ty_api_lego
    processControllerAlias: null
    uuid: '1343'
  inputFields:
  - alias: order_field
    apiLegoId: 1343
    apiLegoUuid: '1343'
    attributes: null
    connectorPath: ''
    constant: index
    ct: eq
    description: null
    dt: string
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 9413
    ift: common
    inputFieldDescribeId: 32
    name: 排序字段
    requestParamName: order_field
    sessionParamName: null
    uuid: '9413'
    validate: ''
  - alias: order
    apiLegoId: 1343
    apiLegoUuid: '1343'
    attributes: null
    connectorPath: ''
    constant: DESC
    ct: eq
    description: null
    dt: string
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: constant
    id: 9414
    ift: common
    inputFieldDescribeId: 44
    name: 排序
    requestParamName: order
    sessionParamName: null
    uuid: '9414'
    validate: ''
  - alias: group_field
    apiLegoId: 1343
    apiLegoUuid: '1343'
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: group_field
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: null
    id: 9415
    ift: common
    inputFieldDescribeId: 45
    name: 群组字段
    requestParamName: group_field
    sessionParamName: null
    uuid: '9415'
    validate: null
  - alias: apiAlias
    apiLegoId: 1343
    apiLegoUuid: '1343'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: apiAlias
    fieldTpl: ${node.currentApiLego.apiAlias}
    fieldValue: null
    fromApiLegoId: 1342
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '1342'
    fvt: template
    id: 9416
    ift: condition
    inputFieldDescribeId: 0
    name: API别名
    requestParamName: apiAlias
    sessionParamName: null
    uuid: '9416'
    validate: ''
  - alias: index
    apiLegoId: 1343
    apiLegoUuid: '1343'
    attributes: null
    connectorPath: ''
    constant: null
    ct: lt
    description: null
    dt: int
    fieldName: index
    fieldTpl: ${node.currentApiLego.index}
    fieldValue: null
    fromApiLegoId: 1342
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '1342'
    fvt: template
    id: 9417
    ift: condition
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: index
    sessionParamName: null
    uuid: '9417'
    validate: ''
  - alias: id
    apiLegoId: 1343
    apiLegoUuid: '1343'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9420
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '9420'
    validate: null
  - alias: index
    apiLegoId: 1343
    apiLegoUuid: '1343'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: index
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: 9421
    ift: read
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: index
    sessionParamName: null
    uuid: '9421'
    validate: null
  outputFields:
  - alias: prevApiLego
    apiLegoId: 1343
    apiLegoUuid: '1343'
    description: ''
    dt: string
    fieldName: data
    fieldValue: null
    handle: '[{"handleName":"notNullJudge","params":"不能上移"}]'
    id: 1479
    name: data
    oft: common
    outputFieldDescribeId: 32
    response: false
    uuid: '1479'
- apiLego:
    apiAlias: ty-up-apiLego
    attributes: null
    description: null
    id: 1344
    index: 3
    legoAlias: update
    oiAlias: ty_api_lego
    processControllerAlias: null
    uuid: '1344'
  inputFields:
  - alias: index
    apiLegoId: 1344
    apiLegoUuid: '1344'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: index
    fieldTpl: ${node.prevApiLego.index}
    fieldValue: null
    fromApiLegoId: 1343
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '1343'
    fvt: template
    id: 9423
    ift: update
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: index
    sessionParamName: ''
    uuid: '9423'
    validate: ''
  - alias: id
    apiLegoId: 1344
    apiLegoUuid: '1344'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 9424
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '9424'
    validate: null
  outputFields: [
    ]
- apiLego:
    apiAlias: ty-up-apiLego
    attributes: null
    description: null
    id: 1345
    index: 4
    legoAlias: update
    oiAlias: ty_api_lego
    processControllerAlias: null
    uuid: '1345'
  inputFields:
  - alias: id
    apiLegoId: 1345
    apiLegoUuid: '1345'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: ${node.prevApiLego.id}
    fieldValue: null
    fromApiLegoId: 1343
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '1343'
    fvt: template
    id: 9425
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '9425'
    validate: ''
  - alias: index
    apiLegoId: 1345
    apiLegoUuid: '1345'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: index
    fieldTpl: ${node.currentApiLego.index}
    fieldValue: null
    fromApiLegoId: 1342
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '1342'
    fvt: template
    id: 9426
    ift: update
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: index
    sessionParamName: null
    uuid: '9426'
    validate: ''
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
