api:
  alias: ty_b_home
  authType: ty_b_session
  category: config
  content: null
  createDate: 2018-07-14T14:56:53Z
  description: ''
  id: 1607
  method: POST
  name: B端应用列表
  type: ty
  url: ''
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty_b_home
    attributes: null
    description: ''
    id: 9765
    index: 1
    legoAlias: list
    oiAlias: ty_supplier_app
    processControllerAlias: null
    uuid: 3672C05D-0BB5-4719-9763-5F6922863CFB1531551425779
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 3672C05D-0BB5-4719-9763-5F6922863CFB1531551425779
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 87140
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: F37962D5-AC13-43C1-8A13-2A3D602BAD011531551425779
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 3672C05D-0BB5-4719-9763-5F6922863CFB1531551425779
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 87141
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: 8F816CFA-7ED4-407D-92B1-853F3439C8731531551425779
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 3672C05D-0BB5-4719-9763-5F6922863CFB1531551425779
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 87142
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: D1C6E9CF-1099-497D-A65A-09A013E1D2D11531551425779
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: 3672C05D-0BB5-4719-9763-5F6922863CFB1531551425779
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 87143
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: 396E258E-9419-443F-A819-EA1991AFA74A1531551425779
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: 3672C05D-0BB5-4719-9763-5F6922863CFB1531551425779
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 87144
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: 71591E46-EE67-47B5-93CC-3F42DD1FF6081531551425779
    validate: null
  - alias: supplierSerialNumber
    apiLegoId: 0
    apiLegoUuid: 3672C05D-0BB5-4719-9763-5F6922863CFB1531551425779
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: supplierSerialNumber
    fieldTpl: ${session.TY_SESSION_B_USER.supplierCommpanySerialNumber}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 87145
    ift: condition
    inputFieldDescribeId: 0
    name: 租户序列号
    requestParamName: supplierSerialNumber
    sessionParamName: ''
    uuid: 04C479C2-8996-480C-A0E5-205C879308D51531551487950
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: 3672C05D-0BB5-4719-9763-5F6922863CFB1531551425779
    attributes: null
    connectorPath: '[{"alias":"ty_supplier_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 87146
    ift: read
    inputFieldDescribeId: 0
    name: 应用别名-名称
    requestParamName: name
    sessionParamName: ''
    uuid: F901C7C2-BDB6-4BB9-9AF0-41F991353D591531551686496
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: 3672C05D-0BB5-4719-9763-5F6922863CFB1531551425779
    attributes: null
    connectorPath: '[{"alias":"ty_supplier_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 87147
    ift: read
    inputFieldDescribeId: 0
    name: 应用别名-别名
    requestParamName: alias
    sessionParamName: ''
    uuid: C7620036-3AE6-45EF-9507-6F53BF20260F1531551686497
    validate: null
  - alias: online
    apiLegoId: 0
    apiLegoUuid: 3672C05D-0BB5-4719-9763-5F6922863CFB1531551425779
    attributes: null
    connectorPath: '[{"alias":"ty_supplier_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: boolean
    fieldName: online
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 87148
    ift: read
    inputFieldDescribeId: 0
    name: '应用别名-是否上线 '
    requestParamName: online
    sessionParamName: ''
    uuid: AB4BF056-3AAB-4A2A-AFF8-2FF5CB6C0F671531551686497
    validate: null
  - alias: online
    apiLegoId: 0
    apiLegoUuid: 3672C05D-0BB5-4719-9763-5F6922863CFB1531551425779
    attributes: null
    connectorPath: '[{"alias":"ty_supplier_app_c1"}]'
    constant: '1'
    ct: eq
    description: ''
    dt: boolean
    fieldName: online
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 87149
    ift: condition
    inputFieldDescribeId: 0
    name: '应用别名-是否上线 '
    requestParamName: online
    sessionParamName: ''
    uuid: EDCA9ED6-B6AA-41D6-BBE0-4CB1A77949751531551708394
    validate: null
  - alias: entrance
    apiLegoId: 0
    apiLegoUuid: 3672C05D-0BB5-4719-9763-5F6922863CFB1531551425779
    attributes: null
    connectorPath: '[{"alias":"ty_supplier_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: entrance
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 87150
    ift: read
    inputFieldDescribeId: 0
    name: 应用别名-入口页
    requestParamName: entrance
    sessionParamName: ''
    uuid: 9FE8A731-93DB-415F-B6DE-D6A7F4CD041D1531552952320
    validate: null
  - alias: icon
    apiLegoId: 0
    apiLegoUuid: 3672C05D-0BB5-4719-9763-5F6922863CFB1531551425779
    attributes: null
    connectorPath: '[{"alias":"ty_supplier_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: icon
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 87151
    ift: read
    inputFieldDescribeId: 0
    name: 应用别名-ICON别名
    requestParamName: icon
    sessionParamName: ''
    uuid: 8956BF60-1DCA-4AB2-9C35-96FF94D9BFAB1531552952320
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 0
    apiLegoUuid: 3672C05D-0BB5-4719-9763-5F6922863CFB1531551425779
    description: ''
    dt: ''
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 12496
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 936F5C95-F31A-4515-AFF2-DE8BB1E790381531551425779
authTypes:
- alias: ty_b_session
  description: TY的B端供应商session校验
  id: 4
  judgeAPIAlias: ty_b_session_check
  name: B端登录校验
  noAuthErrorCode: null
