api:
  alias: ty_get_count_ config
  authType: null
  category: config
  content: null
  createDate: 2018-06-27T21:15:36Z
  description: 模型，接口，应用的总数
  id: 1354
  method: GET
  name: 垦菲阁模型等总数
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty_get_count_ config
    attributes: null
    description: ''
    id: 7561
    index: 1
    legoAlias: count
    oiAlias: ty_ds
    processControllerAlias: null
    uuid: 1BD6AB98-D095-4090-A8B3-9292A25739151530105285157
  inputFields:
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: 1BD6AB98-D095-4090-A8B3-9292A25739151530105285157
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68472
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: 7C2928AB-93A5-4A7E-9782-65EBB6F97E371530105285157
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: 1BD6AB98-D095-4090-A8B3-9292A25739151530105285157
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68473
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: DB86F4F5-E671-46B1-975C-9D0FE78336BA1530105285157
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 1BD6AB98-D095-4090-A8B3-9292A25739151530105285157
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68474
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: 6DCFBB96-EB7C-47AC-85A8-512487B0D66C1530105285157
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 1BD6AB98-D095-4090-A8B3-9292A25739151530105285157
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68475
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: 34FA13BA-5C2D-4B23-A8BE-B95505793C3C1530105285158
    validate: null
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 1BD6AB98-D095-4090-A8B3-9292A25739151530105285157
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68476
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: 47031C74-95C2-4836-9CFB-82F18D5E30EF1530105285158
    validate: null
  - alias: owerId
    apiLegoId: 0
    apiLegoUuid: 1BD6AB98-D095-4090-A8B3-9292A25739151530105285157
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: owerId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 68477
    ift: condition
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: ''
    uuid: 2EFF1D82-17CD-43FD-B025-CD85A1FFE6331530105298453
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 1BD6AB98-D095-4090-A8B3-9292A25739151530105285157
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68478
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: 6754CC22-238E-42CF-8E30-C6719DEAF78D1530105380809
    validate: null
  outputFields:
  - alias: dsCount
    apiLegoId: 0
    apiLegoUuid: 1BD6AB98-D095-4090-A8B3-9292A25739151530105285157
    description: ''
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 10028
    name: 记录条数
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 30A0E4B3-CBDB-44BB-9505-A0AC5EFB19E41530105285158
- apiLego:
    apiAlias: ty_get_count_ config
    attributes: null
    description: ''
    id: 7562
    index: 2
    legoAlias: count
    oiAlias: ty_api
    processControllerAlias: null
    uuid: BAB1EB86-FD3B-41BF-9EB1-4A3EEEA8CDCE1530105397727
  inputFields:
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: BAB1EB86-FD3B-41BF-9EB1-4A3EEEA8CDCE1530105397727
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68479
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: 097E4216-1395-446C-B0B4-24359D372B3B1530105397728
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: BAB1EB86-FD3B-41BF-9EB1-4A3EEEA8CDCE1530105397727
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68480
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: CBA3DC7A-2731-4FBA-89B9-8D087755E9C21530105397728
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: BAB1EB86-FD3B-41BF-9EB1-4A3EEEA8CDCE1530105397727
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68481
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: 43D4EEED-D6B3-41ED-979A-FC552C109C0F1530105397728
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: BAB1EB86-FD3B-41BF-9EB1-4A3EEEA8CDCE1530105397727
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68482
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: BDCF46B6-8190-4929-8BBA-9B46AB52176A1530105397728
    validate: null
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: BAB1EB86-FD3B-41BF-9EB1-4A3EEEA8CDCE1530105397727
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68483
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: C5B801F1-FA79-4AB7-B5E1-70BB71A0F0111530105397728
    validate: null
  - alias: owerId
    apiLegoId: 0
    apiLegoUuid: BAB1EB86-FD3B-41BF-9EB1-4A3EEEA8CDCE1530105397727
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: owerId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 68484
    ift: condition
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: ''
    uuid: A651D2E4-9A10-425F-BD9F-680D1730DDEC1530105409053
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: BAB1EB86-FD3B-41BF-9EB1-4A3EEEA8CDCE1530105397727
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68485
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: 2EC4FF7C-6490-48EB-AE86-F844C3CD7F821530105422950
    validate: null
  outputFields:
  - alias: apiCount
    apiLegoId: 0
    apiLegoUuid: BAB1EB86-FD3B-41BF-9EB1-4A3EEEA8CDCE1530105397727
    description: ''
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 10029
    name: 记录条数
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: E2C68AE3-0723-4467-931A-97E64DF7D8F21530105397728
- apiLego:
    apiAlias: ty_get_count_ config
    attributes: null
    description: ''
    id: 7563
    index: 3
    legoAlias: count
    oiAlias: ty_app
    processControllerAlias: null
    uuid: 5E686C42-288A-4D32-9E1B-21CB0A8236F31530105445793
  inputFields:
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: 5E686C42-288A-4D32-9E1B-21CB0A8236F31530105445793
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68486
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: FEF39921-27A2-4F48-8FD6-CC08922B37E41530105445793
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: 5E686C42-288A-4D32-9E1B-21CB0A8236F31530105445793
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68487
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: D9A48E2F-C4D1-4A46-A135-22BACC2828EC1530105445793
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 5E686C42-288A-4D32-9E1B-21CB0A8236F31530105445793
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68488
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: 1689F281-960C-4BAF-84A2-07BD24F480D21530105445793
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 5E686C42-288A-4D32-9E1B-21CB0A8236F31530105445793
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68489
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: DF1B1207-B5CE-4848-84C8-C3B9176ED6471530105445793
    validate: null
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 5E686C42-288A-4D32-9E1B-21CB0A8236F31530105445793
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68490
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: FB5FBB28-BC10-4D75-B9C9-F819B4C692681530105445793
    validate: null
  - alias: owerId
    apiLegoId: 0
    apiLegoUuid: 5E686C42-288A-4D32-9E1B-21CB0A8236F31530105445793
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: owerId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 68491
    ift: condition
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: ''
    uuid: 7015A580-FA78-4B28-B5A4-5263D70972421530105459879
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 5E686C42-288A-4D32-9E1B-21CB0A8236F31530105445793
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 68492
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: 428EA8DE-5EC9-470F-A4ED-84D911EFD5351530105463772
    validate: null
  outputFields:
  - alias: appCount
    apiLegoId: 0
    apiLegoUuid: 5E686C42-288A-4D32-9E1B-21CB0A8236F31530105445793
    description: ''
    dt: string
    fieldName: count
    fieldValue: null
    handle: ''
    id: 10030
    name: 记录条数
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 158C2F85-6E27-427D-AB08-9A7309C384161530105445793
authTypes: null
