api:
  alias: ty_page_appPage
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-03-26T13:47:59Z
  description: 根据应用别名获取应用下所有页面信息
  id: 787
  method: GET
  name: 获取应用下所有页面
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty_page_appPage
    attributes: null
    description: ''
    id: 5771
    index: 1
    legoAlias: page
    oiAlias: ty_page
    processControllerAlias: null
    uuid: '1665'
  inputFields:
  - alias: page
    apiLegoId: 0
    apiLegoUuid: '1665'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: page
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 53634
    ift: common
    inputFieldDescribeId: 0
    name: 请求页码
    requestParamName: page
    sessionParamName: ''
    uuid: '11832'
    validate: ''
  - alias: pageSize
    apiLegoId: 0
    apiLegoUuid: '1665'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: pageSize
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 53635
    ift: common
    inputFieldDescribeId: 0
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: ''
    uuid: '11833'
    validate: ''
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: '1665'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 53636
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: '11834'
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: '1665'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 53637
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: '11835'
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: '1665'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: ''
    id: 53638
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: '11836'
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: '1665'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 53639
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: '11837'
    validate: ''
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: '1665'
    attributes: null
    connectorPath: ''
    constant: '["name","alias","appAlias"]'
    ct: eq
    description: ''
    dt: string
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: constant
    id: 53640
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: '11838'
    validate: ''
  - alias: appAlias
    apiLegoId: 0
    apiLegoUuid: '1665'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: appAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 53641
    ift: condition
    inputFieldDescribeId: 0
    name: 应用别名
    requestParamName: appAlias
    sessionParamName: ''
    uuid: '11839'
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '1665'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53642
    ift: read
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: ''
    uuid: '11840'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '1665'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53643
    ift: read
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: ''
    uuid: '11841'
    validate: null
  - alias: appAlias
    apiLegoId: 0
    apiLegoUuid: '1665'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: appAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 53644
    ift: read
    inputFieldDescribeId: 0
    name: 应用别名
    requestParamName: appAlias
    sessionParamName: ''
    uuid: '11842'
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 0
    apiLegoUuid: '1665'
    description: ''
    dt: string
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 8029
    name: page_data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '1856'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
