api:
  alias: ty_page_update_sort
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-11-07T20:37:26Z
  description: ''
  id: 2913
  method: POST
  name: 页面排序调整
  type: ty
  url: ''
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty_page_update_sort
    attributes: null
    description: null
    id: null
    index: null
    legoAlias: batchSave
    oiAlias: ty_page
    processControllerAlias: null
    uuid: 7B1402E4-2233-4B59-A7D0-E9C8CBA077D71541594255503
  inputFields:
  - alias: list_Param
    apiLegoId: null
    apiLegoUuid: 7B1402E4-2233-4B59-A7D0-E9C8CBA077D71541594255503
    attributes: null
    connectorPath: null
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: list_Param
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: common
    inputFieldDescribeId: 12
    name: 批量添加list
    requestParamName: list_Param
    sessionParamName: null
    uuid: D9A98673-99CE-45AD-B859-CC739B7B6A701541594255503
    validate: '[{"validateName":"required"}]'
  - alias: parentId
    apiLegoId: null
    apiLegoUuid: 7B1402E4-2233-4B59-A7D0-E9C8CBA077D71541594255503
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: parentId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: update
    inputFieldDescribeId: null
    name: 父ID
    requestParamName: parentId
    sessionParamName: null
    uuid: 9069C0E0-5C91-4A4E-8C76-DE3E0459D5E11541594289426
    validate: null
  - alias: sort
    apiLegoId: null
    apiLegoUuid: 7B1402E4-2233-4B59-A7D0-E9C8CBA077D71541594255503
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: sort
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: update
    inputFieldDescribeId: null
    name: 排序
    requestParamName: sort
    sessionParamName: null
    uuid: 322B512F-26D0-4DE1-A7FC-1D0BBDD1F7991541594289426
    validate: null
  - alias: updateDate
    apiLegoId: null
    apiLegoUuid: 7B1402E4-2233-4B59-A7D0-E9C8CBA077D71541594255503
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: time
    fieldName: updateDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: update
    inputFieldDescribeId: null
    name: 更新时间
    requestParamName: updateDate
    sessionParamName: null
    uuid: 70EB31FB-7506-4760-9319-5868001679231541594351405
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: id
    apiLegoId: null
    apiLegoUuid: 7B1402E4-2233-4B59-A7D0-E9C8CBA077D71541594255503
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: ''
    id: null
    ift: update
    inputFieldDescribeId: null
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: FB17E5F4-A74C-4BCF-B42C-691B6F3EF1631541596839358
    validate: null
  outputFields:
  - alias: list_unique_value
    apiLegoId: null
    apiLegoUuid: 7B1402E4-2233-4B59-A7D0-E9C8CBA077D71541594255503
    description: null
    dt: null
    fieldName: list_unique_value
    fieldValue: null
    handle: null
    id: null
    name: 批量添加的主键id列表
    oft: common
    outputFieldDescribeId: 14
    response: true
    uuid: 883510C0-93C5-4E67-B6C5-A7A23CF649FF1541594255503
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
