api:
  alias: ty_tenant_app_create
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-07-14T00:51:05Z
  description: ''
  id: 1604
  method: POST
  name: 添加租户应用
  type: ty
  url: ''
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty_tenant_app_create
    attributes: null
    description: ''
    id: 9727
    index: 1
    legoAlias: add
    oiAlias: ty_tenant_app
    processControllerAlias: null
    uuid: ABF92818-7E98-4419-9332-50FE1B234B0C1531500671848
  inputFields:
  - alias: tenantSerialNumber
    apiLegoId: 0
    apiLegoUuid: ABF92818-7E98-4419-9332-50FE1B234B0C1531500671848
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: tenantSerialNumber
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 86835
    ift: create
    inputFieldDescribeId: 0
    name: 租户序列号
    requestParamName: tenantSerialNumber
    sessionParamName: ''
    uuid: E34B89A1-7D51-4840-880F-2DD218455BDD1531500707337
    validate: null
  - alias: appAlias
    apiLegoId: 0
    apiLegoUuid: ABF92818-7E98-4419-9332-50FE1B234B0C1531500671848
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: appAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 86836
    ift: create
    inputFieldDescribeId: 0
    name: app别名
    requestParamName: appAlias
    sessionParamName: ''
    uuid: 98EC26F8-DA45-4774-8D51-CC76972730871531500707337
    validate: null
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: ABF92818-7E98-4419-9332-50FE1B234B0C1531500671848
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: time
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 86837
    ift: create
    inputFieldDescribeId: 0
    name: 安装日期
    requestParamName: createDate
    sessionParamName: ''
    uuid: 01B95DAE-E180-473C-9212-88F04F08A4FA1531500707337
    validate: '[{"validateName":"systemTimeAssign"}]'
  outputFields:
  - alias: unique_value
    apiLegoId: 0
    apiLegoUuid: ABF92818-7E98-4419-9332-50FE1B234B0C1531500671848
    description: ''
    dt: ''
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 12458
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: AFEBC487-6931-4A6E-BD38-C7F7FBB4DADE1531500671848
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
