api:
  alias: ty_tenant_app_page
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-07-14T00:27:54Z
  description: ''
  id: 1603
  method: POST
  name: 租户应用列表
  type: ty
  url: ''
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty_tenant_app_page
    attributes: null
    description: ''
    id: 9725
    index: 1
    legoAlias: page
    oiAlias: ty_tenant_app
    processControllerAlias: null
    uuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
  inputFields:
  - alias: page
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: page
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 86820
    ift: common
    inputFieldDescribeId: 0
    name: 请求页码
    requestParamName: page
    sessionParamName: ''
    uuid: A6F750F0-2E5E-42D0-9841-F90B428708201531499288015
    validate: null
  - alias: pageSize
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: pageSize
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 86821
    ift: common
    inputFieldDescribeId: 0
    name: 每页条数
    requestParamName: pageSize
    sessionParamName: ''
    uuid: BE9C0DB5-B4F1-460A-81BC-B73AE50A9A881531499288015
    validate: null
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 86822
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: B367B18B-B358-4FA4-B057-8EFDE1A501591531499288015
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 86823
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: FC900025-5C83-40F6-88F8-3E11380BB2321531499288015
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 86824
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: 741909B1-0D56-4062-9A8F-6B12629FC7571531499288015
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 86825
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: B64A7AF5-E975-4712-AB14-E4B5AB6699341531499288015
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 86826
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: 3CB73A9D-D1E7-4451-91CF-DBFAEAAE3A2E1531499288015
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 86827
    ift: read
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: 38F39190-654A-47AC-90EB-7C20B29BDB6A1531499541085
    validate: null
  - alias: tenantSerialNumber
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: tenantSerialNumber
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 86828
    ift: read
    inputFieldDescribeId: 0
    name: 租户序列号
    requestParamName: tenantSerialNumber
    sessionParamName: ''
    uuid: 272ACBC5-3186-450D-B1D4-058F66E70B381531499541085
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    attributes: null
    connectorPath: '[{"alias":"ty_tenant_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 86829
    ift: read
    inputFieldDescribeId: 0
    name: app别名-名称
    requestParamName: name
    sessionParamName: ''
    uuid: DB4CA4EA-B767-46F4-9DAB-F100C00281191531499541085
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    attributes: null
    connectorPath: '[{"alias":"ty_tenant_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 86830
    ift: read
    inputFieldDescribeId: 0
    name: app别名-别名
    requestParamName: alias
    sessionParamName: ''
    uuid: 2E6F5E2C-0EC1-46A2-80D0-96DF56A617A61531499541085
    validate: null
  - alias: userType
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    attributes: null
    connectorPath: '[{"alias":"ty_tenant_app_c1"}]'
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: userType
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 86831
    ift: read
    inputFieldDescribeId: 0
    name: app别名-用户类型
    requestParamName: userType
    sessionParamName: ''
    uuid: 62765AF4-D209-48F0-B368-7414593B3E931531499541085
    validate: null
  - alias: createDate
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: time
    fieldName: createDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 86832
    ift: read
    inputFieldDescribeId: 0
    name: 安装日期
    requestParamName: createDate
    sessionParamName: ''
    uuid: E898DEE4-E9C3-4D9A-B37F-F59A481AFA6C1531499541085
    validate: null
  - alias: tenantSerialNumber
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: tenantSerialNumber
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 86833
    ift: condition
    inputFieldDescribeId: 0
    name: 租户序列号
    requestParamName: tenantSerialNumber
    sessionParamName: ''
    uuid: 07DD2470-9CEE-4628-9066-B419E4E9821E1531499555244
    validate: null
  - alias: appAlias
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: appAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 86834
    ift: condition
    inputFieldDescribeId: 0
    name: app别名
    requestParamName: appAlias
    sessionParamName: ''
    uuid: CFC2913E-6175-400C-A757-ADC24C37D6651531499555244
    validate: null
  outputFields:
  - alias: page_data
    apiLegoId: 0
    apiLegoUuid: 888E7290-96D4-4233-91F5-1CA7D38700781531499288015
    description: ''
    dt: ''
    fieldName: page_data
    fieldValue: null
    handle: ''
    id: 12456
    name: page_data
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: B6E2B7A4-7753-4883-A7DE-7F2955D19BE11531499288015
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
