api:
  alias: ty_tenant_user_list
  authType: ty_auth
  category: config
  content: null
  createDate: 2018-05-30T15:09:05Z
  description: null
  id: 1225
  method: POST
  name: 租户用户列表
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: ty_tenant_user_list
    attributes: null
    description: ''
    id: 5647
    index: 1
    legoAlias: list
    oiAlias: ty_user
    processControllerAlias: null
    uuid: 679A7E19-12F7-4E6C-8A7E-6540E0C6F0BD1527664154098
  inputFields:
  - alias: order_field
    apiLegoId: 0
    apiLegoUuid: 679A7E19-12F7-4E6C-8A7E-6540E0C6F0BD1527664154098
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52051
    ift: common
    inputFieldDescribeId: 0
    name: 排序字段
    requestParamName: order_field
    sessionParamName: ''
    uuid: E24F3C67-C976-483C-8180-065056C5555E1527664154098
    validate: null
  - alias: order
    apiLegoId: 0
    apiLegoUuid: 679A7E19-12F7-4E6C-8A7E-6540E0C6F0BD1527664154098
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: order
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52052
    ift: common
    inputFieldDescribeId: 0
    name: 排序
    requestParamName: order
    sessionParamName: ''
    uuid: 7632D538-7351-404D-AB23-CFE88AB25DF61527664154098
    validate: null
  - alias: group_field
    apiLegoId: 0
    apiLegoUuid: 679A7E19-12F7-4E6C-8A7E-6540E0C6F0BD1527664154098
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: group_field
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52053
    ift: common
    inputFieldDescribeId: 0
    name: 群组字段
    requestParamName: group_field
    sessionParamName: ''
    uuid: 61ED78AB-E904-4E33-B444-335599413C991527664154098
    validate: null
  - alias: keywords
    apiLegoId: 0
    apiLegoUuid: 679A7E19-12F7-4E6C-8A7E-6540E0C6F0BD1527664154098
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: keywords
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52054
    ift: common
    inputFieldDescribeId: 0
    name: 关键字搜索
    requestParamName: keywords
    sessionParamName: ''
    uuid: 50A156BF-B097-452C-9AEE-81A4308E6EDA1527664154098
    validate: null
  - alias: global_search_fields
    apiLegoId: 0
    apiLegoUuid: 679A7E19-12F7-4E6C-8A7E-6540E0C6F0BD1527664154098
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: global_search_fields
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52055
    ift: common
    inputFieldDescribeId: 0
    name: 全局搜索字段(单表)
    requestParamName: global_search_fields
    sessionParamName: ''
    uuid: 057B6534-DC9B-4BBC-B0EF-94B7CD7B47C21527664154098
    validate: null
  - alias: xingMing
    apiLegoId: 0
    apiLegoUuid: 679A7E19-12F7-4E6C-8A7E-6540E0C6F0BD1527664154098
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: xingMing
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52056
    ift: read
    inputFieldDescribeId: 0
    name: 姓名
    requestParamName: xingMing
    sessionParamName: ''
    uuid: E83F2803-0868-4D42-8317-C2EF64F87B5B1527664199571
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: 679A7E19-12F7-4E6C-8A7E-6540E0C6F0BD1527664154098
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 52057
    ift: read
    inputFieldDescribeId: 0
    name: 用户别名
    requestParamName: alias
    sessionParamName: ''
    uuid: 7ECAB5CF-EA25-4D19-BF7B-C032E5C6E0EC1527664199571
    validate: null
  - alias: tenantSerialNumber
    apiLegoId: 0
    apiLegoUuid: 679A7E19-12F7-4E6C-8A7E-6540E0C6F0BD1527664154098
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: tenantSerialNumber
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.tenantSerialNumber}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 52058
    ift: condition
    inputFieldDescribeId: 0
    name: 租户序列号
    requestParamName: tenantSerialNumber
    sessionParamName: ''
    uuid: B59B6EAD-D97B-4B46-AC57-70B536A1F8D41527664207499
    validate: null
  outputFields:
  - alias: data_list
    apiLegoId: 0
    apiLegoUuid: 679A7E19-12F7-4E6C-8A7E-6540E0C6F0BD1527664154098
    description: ''
    dt: ''
    fieldName: data_list
    fieldValue: null
    handle: ''
    id: 7891
    name: 列表数据
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 4F823AFA-737B-47F6-BDD5-69A4E3DC5E191527664154099
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
