api:
  alias: update-oi
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-05T11:30:31Z
  description: 更新OI
  id: 279
  method: POST
  name: 更新OI
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: update-oi
    attributes: null
    description: ''
    id: 2879
    index: 1
    legoAlias: uniqueness
    oiAlias: ty_oi
    processControllerAlias: null
    uuid: EB8490E5-A430-4A4D-A4FA-6E3438B8FBA11524136169600
  inputFields:
  - alias: resource
    apiLegoId: 0
    apiLegoUuid: EB8490E5-A430-4A4D-A4FA-6E3438B8FBA11524136169600
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: resource
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23241
    ift: condition
    inputFieldDescribeId: 0
    name: resource
    requestParamName: resource
    sessionParamName: ''
    uuid: D5ED796F-C4FB-4012-9156-B2DA2F48B62D1524136187288
    validate: null
  - alias: dsAlias
    apiLegoId: 0
    apiLegoUuid: EB8490E5-A430-4A4D-A4FA-6E3438B8FBA11524136169600
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: dsAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23242
    ift: condition
    inputFieldDescribeId: 0
    name: dsAlias
    requestParamName: dsAlias
    sessionParamName: ''
    uuid: 0C6D7E50-E134-4489-A4F3-643AC82AD5311524136187289
    validate: '[{"validateName":"required"}]'
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: EB8490E5-A430-4A4D-A4FA-6E3438B8FBA11524136169600
    attributes: null
    connectorPath: ''
    constant: ''
    ct: neq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23243
    ift: condition
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: ''
    uuid: D1C7222A-50C2-441A-8978-D13AE6E9FC131524136248083
    validate: '[{"validateName":"required"}]'
  outputFields:
  - alias: is_unique
    apiLegoId: 0
    apiLegoUuid: EB8490E5-A430-4A4D-A4FA-6E3438B8FBA11524136169600
    description: ''
    dt: ''
    fieldName: is_unique
    fieldValue: null
    handle: '[{"handleName":"dataResultJudge","params":"true,数据源下模型资源必须唯一"}]'
    id: 3474
    name: 是否唯一
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: A965485A-94FE-456E-91A3-11479304021E1524136169600
- apiLego:
    apiAlias: update-oi
    attributes: null
    description: ''
    id: 2880
    index: 2
    legoAlias: update
    oiAlias: ty_oi
    processControllerAlias: null
    uuid: '390'
  inputFields:
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '390'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 23244
    ift: condition
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: ''
    uuid: '1099'
    validate: '[{"validateName":"required"}]'
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '390'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23245
    ift: update
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: '1100'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '390'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23246
    ift: update
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: '1101'
    validate: null
  - alias: resource
    apiLegoId: 0
    apiLegoUuid: '390'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: resource
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23247
    ift: update
    inputFieldDescribeId: 0
    name: resource
    requestParamName: resource
    sessionParamName: ''
    uuid: '1102'
    validate: null
  outputFields: [
    ]
- apiLego:
    apiAlias: update-oi
    attributes: null
    description: ''
    id: 2881
    index: 3
    legoAlias: objectRecombine
    oiAlias: null
    processControllerAlias: null
    uuid: 712F980C-7A89-4811-BB21-B116E5D44B791523864432202
  inputFields:
  - alias: dataType
    apiLegoId: 0
    apiLegoUuid: 712F980C-7A89-4811-BB21-B116E5D44B791523864432202
    attributes: null
    connectorPath: ''
    constant: data
    ct: ''
    description: ''
    dt: ''
    fieldName: dataType
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 23248
    ift: common
    inputFieldDescribeId: 0
    name: 转换类型(data/list)
    requestParamName: dataType
    sessionParamName: ''
    uuid: 306BFAC4-985A-45FE-B412-3E32B59F0EA01523864432202
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: 712F980C-7A89-4811-BB21-B116E5D44B791523864432202
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23249
    ift: memory
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: ''
    uuid: 05887212-C635-4F5B-AE2B-CFDC3C6D8B9B1523864463182
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: 712F980C-7A89-4811-BB21-B116E5D44B791523864432202
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23250
    ift: memory
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: ''
    uuid: 96C14D8E-C9F1-48D3-8481-AD5682843ADC1523864477291
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: 712F980C-7A89-4811-BB21-B116E5D44B791523864432202
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23251
    ift: memory
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: ''
    uuid: EFA51C35-D8F4-40FE-8206-CFB075AF6FB61523864493389
    validate: null
  - alias: resource
    apiLegoId: 0
    apiLegoUuid: 712F980C-7A89-4811-BB21-B116E5D44B791523864432202
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: resource
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23252
    ift: memory
    inputFieldDescribeId: 0
    name: 资源名
    requestParamName: resource
    sessionParamName: ''
    uuid: B8C4E13B-4B60-4803-B8FF-1F120FBEF8351523864518464
    validate: null
  outputFields:
  - alias: oiData
    apiLegoId: 0
    apiLegoUuid: 712F980C-7A89-4811-BB21-B116E5D44B791523864432202
    description: ''
    dt: ''
    fieldName: data
    fieldValue: null
    handle: ''
    id: 3475
    name: 重组对象
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: A5C8C8CB-A76B-48B7-A577-B601D7D11CBA1523864432202
- apiLego:
    apiAlias: update-oi
    attributes: null
    description: 更新oi 日志记录
    id: 2882
    index: 4
    legoAlias: add
    oiAlias: ty_model_log
    processControllerAlias: null
    uuid: B8653FDB-6052-46BF-855C-B8F2E826B0E01523864535195
  inputFields:
  - alias: operatorId
    apiLegoId: 0
    apiLegoUuid: B8653FDB-6052-46BF-855C-B8F2E826B0E01523864535195
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: operatorId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 23253
    ift: create
    inputFieldDescribeId: 0
    name: 操作人ID
    requestParamName: operatorId
    sessionParamName: ''
    uuid: B4AC5CA5-E3BD-451C-84CA-0D04DC57C9221523864575292
    validate: null
  - alias: operatorName
    apiLegoId: 0
    apiLegoUuid: B8653FDB-6052-46BF-855C-B8F2E826B0E01523864535195
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operatorName
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.xingMing}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 23254
    ift: create
    inputFieldDescribeId: 0
    name: 操作人姓名
    requestParamName: operatorName
    sessionParamName: ''
    uuid: 5CDD003C-373E-49DD-9B14-4708B89A4CE41523864575292
    validate: null
  - alias: operateDate
    apiLegoId: 0
    apiLegoUuid: B8653FDB-6052-46BF-855C-B8F2E826B0E01523864535195
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: time
    fieldName: operateDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 23255
    ift: create
    inputFieldDescribeId: 0
    name: 操作时间
    requestParamName: operateDate
    sessionParamName: ''
    uuid: 4F140026-9887-4085-83E1-53D3DFCD44071523864575292
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: operateContent
    apiLegoId: 0
    apiLegoUuid: B8653FDB-6052-46BF-855C-B8F2E826B0E01523864535195
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateContent
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: oiData
    fromApiLegoUuid: 712F980C-7A89-4811-BB21-B116E5D44B791523864432202
    fvt: output
    id: 23256
    ift: create
    inputFieldDescribeId: 0
    name: 详细操作内容
    requestParamName: operateContent
    sessionParamName: ''
    uuid: BF3EA55B-2F8A-4D01-8A75-BA59FC74DEFD1523864575292
    validate: null
  - alias: operateAlias
    apiLegoId: 0
    apiLegoUuid: B8653FDB-6052-46BF-855C-B8F2E826B0E01523864535195
    attributes: null
    connectorPath: ''
    constant: ty_oi
    ct: eq
    description: ''
    dt: string
    fieldName: operateAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 23257
    ift: create
    inputFieldDescribeId: 0
    name: 操作模型别名
    requestParamName: operateAlias
    sessionParamName: ''
    uuid: 37712156-5FE7-4305-AB74-2DEA4F5F30801523864575292
    validate: null
  - alias: operateDes
    apiLegoId: 0
    apiLegoUuid: B8653FDB-6052-46BF-855C-B8F2E826B0E01523864535195
    attributes: null
    connectorPath: ''
    constant: 更新OI
    ct: eq
    description: ''
    dt: string
    fieldName: operateDes
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 23258
    ift: create
    inputFieldDescribeId: 0
    name: 操作描述
    requestParamName: operateDes
    sessionParamName: ''
    uuid: F248247A-9450-4D67-AA01-4FC8CBC2EA5A1523864575292
    validate: null
  outputFields:
  - alias: unique_value
    apiLegoId: 0
    apiLegoUuid: B8653FDB-6052-46BF-855C-B8F2E826B0E01523864535195
    description: ''
    dt: ''
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 3476
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: C634E6CA-7EEF-4FCE-8997-717E21BE8A631523864535195
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
