api:
  alias: update-ad
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-01T11:22:25Z
  description: 更新积木属性
  id: 259
  method: POST
  name: 更新积木属性
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: update-ad
    attributes: null
    description: ''
    id: 2662
    index: 1
    legoAlias: update
    oiAlias: ty_attribute_describe
    processControllerAlias: null
    uuid: '357'
  inputFields:
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '357'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 20689
    ift: update
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: ''
    uuid: '962'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '357'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 20690
    ift: update
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: ''
    uuid: '963'
    validate: null
  - alias: attributeName
    apiLegoId: 0
    apiLegoUuid: '357'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: attributeName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 20691
    ift: update
    inputFieldDescribeId: 0
    name: 属性名
    requestParamName: attributeName
    sessionParamName: ''
    uuid: '964'
    validate: null
  - alias: dt
    apiLegoId: 0
    apiLegoUuid: '357'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: dt
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 20692
    ift: update
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: dt
    sessionParamName: ''
    uuid: '965'
    validate: null
  - alias: parentId
    apiLegoId: 0
    apiLegoUuid: '357'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: parentId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 20693
    ift: update
    inputFieldDescribeId: 0
    name: 父级id
    requestParamName: parentId
    sessionParamName: ''
    uuid: '966'
    validate: null
  - alias: et
    apiLegoId: 0
    apiLegoUuid: '357'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: et
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 20694
    ift: update
    inputFieldDescribeId: 0
    name: 编辑器类型
    requestParamName: et
    sessionParamName: ''
    uuid: '967'
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '357'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 20695
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '968'
    validate: '[{"validateName":"required"}]'
  - alias: etData
    apiLegoId: 0
    apiLegoUuid: '357'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: etData
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 20696
    ift: update
    inputFieldDescribeId: 0
    name: 编辑器数据
    requestParamName: etData
    sessionParamName: ''
    uuid: '1420'
    validate: null
  - alias: etProps
    apiLegoId: 0
    apiLegoUuid: '357'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: etProps
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 20697
    ift: update
    inputFieldDescribeId: 0
    name: 编辑器属性
    requestParamName: etProps
    sessionParamName: ''
    uuid: '1969'
    validate: null
  - alias: rules
    apiLegoId: 0
    apiLegoUuid: '357'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: rules
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 20698
    ift: update
    inputFieldDescribeId: 0
    name: 规则
    requestParamName: rules
    sessionParamName: ''
    uuid: 2EB276A4-9B1F-459D-B5B5-9A68FDD14D7F1524018629910
    validate: null
  - alias: type
    apiLegoId: null
    apiLegoUuid: '357'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: update
    inputFieldDescribeId: null
    name: 积木属性类型
    requestParamName: type
    sessionParamName: null
    uuid: BF5691AA-92FA-4EFC-A978-341F7CB935CC1533726427021
    validate: null
  - alias: sort
    apiLegoId: null
    apiLegoUuid: '357'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: int
    fieldName: sort
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: update
    inputFieldDescribeId: null
    name: 排序
    requestParamName: sort
    sessionParamName: null
    uuid: 06A3AE37-74A3-4A7D-8CDA-C3A756A0F6A31533726427021
    validate: null
  - alias: disabled
    apiLegoId: null
    apiLegoUuid: '357'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: boolean
    fieldName: disabled
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: update
    inputFieldDescribeId: null
    name: 禁用
    requestParamName: disabled
    sessionParamName: null
    uuid: 2D655820-C394-4906-B25A-0A5DAF9762D81533801521429
    validate: null
  - alias: supportXCX
    apiLegoId: null
    apiLegoUuid: '357'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: boolean
    fieldName: supportXCX
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: update
    inputFieldDescribeId: null
    name: 支持小程序
    requestParamName: supportXCX
    sessionParamName: null
    uuid: 7D614206-900C-49D1-B29F-9C8DF03F01FA1533801521429
    validate: null
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
