api:
  alias: update-ed
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-01T11:24:17Z
  description: 更新积木事件
  id: 261
  method: POST
  name: 更新积木事件
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: update-ed
    attributes: null
    description: null
    id: 359
    index: 1
    legoAlias: update
    oiAlias: ty_event_describe
    processControllerAlias: null
    uuid: '359'
  inputFields:
  - alias: id
    apiLegoId: 359
    apiLegoUuid: '359'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 973
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '973'
    validate: '[{"validateName":"required"}]'
  - alias: name
    apiLegoId: 359
    apiLegoUuid: '359'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 974
    ift: update
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '974'
    validate: null
  - alias: description
    apiLegoId: 359
    apiLegoUuid: '359'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 975
    ift: update
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '975'
    validate: null
  - alias: eventName
    apiLegoId: 359
    apiLegoUuid: '359'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: eventName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 976
    ift: update
    inputFieldDescribeId: 0
    name: 事件名称
    requestParamName: eventName
    sessionParamName: null
    uuid: '976'
    validate: null
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
