api:
  alias: update-page-layout
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-07T14:47:17Z
  description: 更新页面布局
  id: 293
  method: POST
  name: 更新页面布局
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: update-page-layout
    attributes: null
    description: null
    id: 418
    index: 1
    legoAlias: update
    oiAlias: ty_page
    processControllerAlias: null
    uuid: '418'
  inputFields:
  - alias: name
    apiLegoId: 418
    apiLegoUuid: '418'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1255
    ift: update
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '1255'
    validate: null
  - alias: description
    apiLegoId: 418
    apiLegoUuid: '418'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1256
    ift: update
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '1256'
    validate: null
  - alias: layout
    apiLegoId: 418
    apiLegoUuid: '418'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: layout
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1257
    ift: update
    inputFieldDescribeId: 0
    name: 布局
    requestParamName: layout
    sessionParamName: null
    uuid: '1257'
    validate: null
  - alias: layoutType
    apiLegoId: 418
    apiLegoUuid: '418'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: layoutType
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1258
    ift: update
    inputFieldDescribeId: 0
    name: 布局类型
    requestParamName: layoutType
    sessionParamName: null
    uuid: '1258'
    validate: null
  - alias: alias
    apiLegoId: 418
    apiLegoUuid: '418'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1259
    ift: condition
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '1259'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
