api:
  alias: update-bb
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-01T11:18:02Z
  description: 更新积木
  id: 255
  method: POST
  name: 更新积木
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: update-bb
    attributes: null
    description: ''
    id: 3556
    index: 1
    legoAlias: update
    oiAlias: ty_building_block
    processControllerAlias: null
    uuid: '353'
  inputFields:
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '353'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 29766
    ift: update
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: ''
    uuid: '949'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '353'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 29767
    ift: update
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: ''
    uuid: '950'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '353'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 29768
    ift: condition
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: ''
    uuid: '952'
    validate: '[{"validateName":"required"}]'
  - alias: type
    apiLegoId: 0
    apiLegoUuid: '353'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 29769
    ift: update
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: ''
    uuid: '2368'
    validate: null
  - alias: icon
    apiLegoId: 0
    apiLegoUuid: '353'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: icon
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 29770
    ift: update
    inputFieldDescribeId: 0
    name: 图标
    requestParamName: icon
    sessionParamName: ''
    uuid: '4579'
    validate: null
  - alias: platform
    apiLegoId: 0
    apiLegoUuid: '353'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: platform
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 29771
    ift: update
    inputFieldDescribeId: 0
    name: 平台
    requestParamName: platform
    sessionParamName: ''
    uuid: '9146'
    validate: null
  - alias: tags
    apiLegoId: 0
    apiLegoUuid: '353'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: tags
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 29772
    ift: update
    inputFieldDescribeId: 0
    name: 标签
    requestParamName: tags
    sessionParamName: ''
    uuid: '9147'
    validate: null
  - alias: interactive
    apiLegoId: 0
    apiLegoUuid: '353'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: interactive
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 29773
    ift: update
    inputFieldDescribeId: 0
    name: 交互
    requestParamName: 'on'
    sessionParamName: ''
    uuid: 5C4D5DAD-0640-443A-8BEB-BB9E4DC7AE3B1524899094922
    validate: null
  - alias: defaultProps
    apiLegoId: null
    apiLegoUuid: '353'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: defaultProps
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: update
    inputFieldDescribeId: null
    name: 默认属性
    requestParamName: defaultProps
    sessionParamName: null
    uuid: 6473A993-DC91-49DC-9499-3D73DB16FF011533621524916
    validate: null
  - alias: module
    apiLegoId: null
    apiLegoUuid: '353'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: boolean
    fieldName: module
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: update
    inputFieldDescribeId: null
    name: 是否模块
    requestParamName: module
    sessionParamName: null
    uuid: 44EF5BC0-49E0-40BB-9CDF-62A4BFD7FECE1533984802836
    validate: null
  - alias: content
    apiLegoId: null
    apiLegoUuid: '353'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: content
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: update
    inputFieldDescribeId: null
    name: 模块内容
    requestParamName: content
    sessionParamName: null
    uuid: 98F44199-9E40-4CBB-9D0A-AAF55D2BA7C11533984802837
    validate: null
  - alias: config
    apiLegoId: null
    apiLegoUuid: '353'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: boolean
    fieldName: config
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: update
    inputFieldDescribeId: null
    name: 配置使用
    requestParamName: config
    sessionParamName: null
    uuid: D9A23D29-69CD-4DB7-899B-46461B16F8851534836013056
    validate: null
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
