api:
  alias: update-outputfield
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-17T11:16:05Z
  description: null
  id: 206
  method: POST
  name: 更新outputField
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: update-outputfield
    attributes: null
    description: null
    id: 253
    index: 1
    legoAlias: update
    oiAlias: ty_output_field
    processControllerAlias: null
    uuid: '253'
  inputFields:
  - alias: name
    apiLegoId: 253
    apiLegoUuid: '253'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 258
    ift: update
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '258'
    validate: null
  - alias: description
    apiLegoId: 253
    apiLegoUuid: '253'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 259
    ift: update
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '259'
    validate: null
  - alias: apiLegoId
    apiLegoId: 253
    apiLegoUuid: '253'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: apiLegoId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 260
    ift: update
    inputFieldDescribeId: 0
    name: apiLegoId
    requestParamName: apiLegoId
    sessionParamName: null
    uuid: '260'
    validate: null
  - alias: fieldName
    apiLegoId: 253
    apiLegoUuid: '253'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 261
    ift: update
    inputFieldDescribeId: 0
    name: 字段名
    requestParamName: fieldName
    sessionParamName: null
    uuid: '261'
    validate: null
  - alias: fieldValue
    apiLegoId: 253
    apiLegoUuid: '253'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fieldValue
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 262
    ift: update
    inputFieldDescribeId: 0
    name: 字段值
    requestParamName: fieldValue
    sessionParamName: null
    uuid: '262'
    validate: null
  - alias: oft
    apiLegoId: 253
    apiLegoUuid: '253'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: oft
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 263
    ift: update
    inputFieldDescribeId: 0
    name: 输入类型
    requestParamName: oft
    sessionParamName: null
    uuid: '263'
    validate: null
  - alias: response
    apiLegoId: 253
    apiLegoUuid: '253'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: response
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 264
    ift: update
    inputFieldDescribeId: 0
    name: 是否返回前端
    requestParamName: response
    sessionParamName: null
    uuid: '264'
    validate: null
  - alias: alias
    apiLegoId: 253
    apiLegoUuid: '253'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 265
    ift: update
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '265'
    validate: null
  - alias: handle
    apiLegoId: 253
    apiLegoUuid: '253'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: handle
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 266
    ift: update
    inputFieldDescribeId: 0
    name: 格式化
    requestParamName: handle
    sessionParamName: null
    uuid: '266'
    validate: null
  - alias: dt
    apiLegoId: 253
    apiLegoUuid: '253'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: dt
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 267
    ift: update
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: dt
    sessionParamName: null
    uuid: '267'
    validate: null
  - alias: outputFieldDescribeId
    apiLegoId: 253
    apiLegoUuid: '253'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: outputFieldDescribeId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 268
    ift: update
    inputFieldDescribeId: 0
    name: 描述id
    requestParamName: outputFieldDescribeId
    sessionParamName: null
    uuid: '268'
    validate: ''
  - alias: id
    apiLegoId: 253
    apiLegoUuid: '253'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 269
    ift: condition
    inputFieldDescribeId: 0
    name: 条件id
    requestParamName: id
    sessionParamName: ''
    uuid: '269'
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
