api:
  alias: update-buzz
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-08T10:38:10Z
  description: 更新buzz
  id: 300
  method: POST
  name: 更新buzz
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: update-buzz
    attributes: null
    description: ''
    id: 8732
    index: 1
    legoAlias: update
    oiAlias: ty_code
    processControllerAlias: null
    uuid: '428'
  inputFields:
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '428'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 79500
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: '1395'
    validate: '[{"validateName":"required"}]'
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '428'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 79501
    ift: update
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: ''
    uuid: '1396'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '428'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 79502
    ift: update
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: ''
    uuid: '1397'
    validate: null
  - alias: code
    apiLegoId: 0
    apiLegoUuid: '428'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: code
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 79503
    ift: update
    inputFieldDescribeId: 0
    name: 代码
    requestParamName: code
    sessionParamName: ''
    uuid: '1398'
    validate: null
  - alias: type
    apiLegoId: 0
    apiLegoUuid: '428'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: type
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 79504
    ift: update
    inputFieldDescribeId: 0
    name: 类型
    requestParamName: type
    sessionParamName: ''
    uuid: '1399'
    validate: '[]'
  - alias: appAlias
    apiLegoId: null
    apiLegoUuid: '428'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: appAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: null
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: null
    ift: update
    inputFieldDescribeId: null
    name: 对应app
    requestParamName: appAlias
    sessionParamName: null
    uuid: 7CC32D3E-7872-440F-97C4-CF95E0107EE11536831964335
    validate: null
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
