api:
  alias: update-connector
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-05T15:36:29Z
  description: 更新OI连接器
  id: 287
  method: POST
  name: 更新OI连接器
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: update-connector
    attributes: null
    description: ''
    id: 2235
    index: 1
    legoAlias: update
    oiAlias: ty_connector
    processControllerAlias: null
    uuid: '403'
  inputFields:
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '403'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16579
    ift: condition
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: '1135'
    validate: '[{"validateName":"required"}]'
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '403'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16580
    ift: update
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: '1136'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '403'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16581
    ift: update
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: '1137'
    validate: null
  - alias: fromFieldName
    apiLegoId: 0
    apiLegoUuid: '403'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: fromFieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16582
    ift: update
    inputFieldDescribeId: 0
    name: fromFieldName
    requestParamName: fromFieldName
    sessionParamName: ''
    uuid: '1138'
    validate: null
  - alias: toOIAlias
    apiLegoId: 0
    apiLegoUuid: '403'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: toOIAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16583
    ift: update
    inputFieldDescribeId: 0
    name: toOIAlias
    requestParamName: toOIAlias
    sessionParamName: ''
    uuid: '1139'
    validate: null
  - alias: toFieldName
    apiLegoId: 0
    apiLegoUuid: '403'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: toFieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16584
    ift: update
    inputFieldDescribeId: 0
    name: toFieldName
    requestParamName: toFieldName
    sessionParamName: ''
    uuid: '1140'
    validate: null
  outputFields: [
    ]
- apiLego:
    apiAlias: update-connector
    attributes: null
    description: ''
    id: 2236
    index: 2
    legoAlias: objectRecombine
    oiAlias: null
    processControllerAlias: null
    uuid: F16B57C0-F7E1-45A9-856A-AB4CCEA182541523867883727
  inputFields:
  - alias: dataType
    apiLegoId: 0
    apiLegoUuid: F16B57C0-F7E1-45A9-856A-AB4CCEA182541523867883727
    attributes: null
    connectorPath: ''
    constant: data
    ct: ''
    description: ''
    dt: ''
    fieldName: dataType
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 16585
    ift: common
    inputFieldDescribeId: 0
    name: 转换类型(data/list)
    requestParamName: dataType
    sessionParamName: ''
    uuid: 48DFEF68-DE4E-4322-9288-D13BC4127FCA1523867883727
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: F16B57C0-F7E1-45A9-856A-AB4CCEA182541523867883727
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16586
    ift: memory
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: 30C4F31E-D006-4099-B62B-807AE67DF7F61523867907163
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: F16B57C0-F7E1-45A9-856A-AB4CCEA182541523867883727
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16587
    ift: memory
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: ''
    uuid: 5AD0B106-C43C-42CC-A539-004022688EEC1523867934655
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: F16B57C0-F7E1-45A9-856A-AB4CCEA182541523867883727
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16588
    ift: memory
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: ''
    uuid: 62E37C07-08E1-4976-A03F-FA1D15C56F3C1523867947601
    validate: null
  - alias: fromFieldName
    apiLegoId: 0
    apiLegoUuid: F16B57C0-F7E1-45A9-856A-AB4CCEA182541523867883727
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: fromFieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16589
    ift: memory
    inputFieldDescribeId: 0
    name: 源字段
    requestParamName: fromFieldName
    sessionParamName: ''
    uuid: 224BCC7D-DEAB-492F-BEB3-824A97FBA2361523867963920
    validate: null
  - alias: toOIAlias
    apiLegoId: 0
    apiLegoUuid: F16B57C0-F7E1-45A9-856A-AB4CCEA182541523867883727
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: toOIAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16590
    ift: memory
    inputFieldDescribeId: 0
    name: 目标OI别名
    requestParamName: toOIAlias
    sessionParamName: ''
    uuid: 57A7EFDD-DE90-484D-A226-C79AEF0C9B041523867980335
    validate: null
  - alias: toFieldName
    apiLegoId: 0
    apiLegoUuid: F16B57C0-F7E1-45A9-856A-AB4CCEA182541523867883727
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: toFieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 16591
    ift: memory
    inputFieldDescribeId: 0
    name: 目标字段
    requestParamName: toFieldName
    sessionParamName: ''
    uuid: 393CD416-4274-4943-B2DE-859F46D626A21523867998939
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 0
    apiLegoUuid: F16B57C0-F7E1-45A9-856A-AB4CCEA182541523867883727
    description: ''
    dt: ''
    fieldName: data
    fieldValue: null
    handle: '[{"handleName":"objectToJson"}]'
    id: 2620
    name: 重组对象
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 91B20177-CDF1-4550-8D6E-7EEDA46EA4E31523867883727
- apiLego:
    apiAlias: update-connector
    attributes: null
    description: ''
    id: 2237
    index: 3
    legoAlias: add
    oiAlias: ty_model_log
    processControllerAlias: null
    uuid: 67FA3BE6-A9B1-408D-963F-1D1E284958281523868025956
  inputFields:
  - alias: operatorId
    apiLegoId: 0
    apiLegoUuid: 67FA3BE6-A9B1-408D-963F-1D1E284958281523868025956
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: operatorId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 16592
    ift: create
    inputFieldDescribeId: 0
    name: 操作人ID
    requestParamName: operatorId
    sessionParamName: ''
    uuid: 15800FD7-63D9-458C-B280-99FDDC42D5091523868037688
    validate: null
  - alias: operatorName
    apiLegoId: 0
    apiLegoUuid: 67FA3BE6-A9B1-408D-963F-1D1E284958281523868025956
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operatorName
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.xingMing}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 16593
    ift: create
    inputFieldDescribeId: 0
    name: 操作人姓名
    requestParamName: operatorName
    sessionParamName: ''
    uuid: B88BFF87-0A50-47F1-8D25-94E12743BB4A1523868037688
    validate: null
  - alias: operateDate
    apiLegoId: 0
    apiLegoUuid: 67FA3BE6-A9B1-408D-963F-1D1E284958281523868025956
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: time
    fieldName: operateDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 16594
    ift: create
    inputFieldDescribeId: 0
    name: 操作时间
    requestParamName: operateDate
    sessionParamName: ''
    uuid: BC1F84BF-F395-40F5-821A-164B3802EDB31523868037688
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: operateContent
    apiLegoId: 0
    apiLegoUuid: 67FA3BE6-A9B1-408D-963F-1D1E284958281523868025956
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateContent
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: data
    fromApiLegoUuid: F16B57C0-F7E1-45A9-856A-AB4CCEA182541523867883727
    fvt: output
    id: 16595
    ift: create
    inputFieldDescribeId: 0
    name: 详细操作内容
    requestParamName: operateContent
    sessionParamName: ''
    uuid: 05967E39-DFF6-4FC1-A113-0A3EAB0D49B01523868037688
    validate: null
  - alias: operateAlias
    apiLegoId: 0
    apiLegoUuid: 67FA3BE6-A9B1-408D-963F-1D1E284958281523868025956
    attributes: null
    connectorPath: ''
    constant: ty_connector
    ct: eq
    description: ''
    dt: string
    fieldName: operateAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 16596
    ift: create
    inputFieldDescribeId: 0
    name: 操作模型别名
    requestParamName: operateAlias
    sessionParamName: ''
    uuid: 6EF8EDB0-3A18-431A-8F81-69AABEDF1BA51523868037688
    validate: null
  - alias: operateDes
    apiLegoId: 0
    apiLegoUuid: 67FA3BE6-A9B1-408D-963F-1D1E284958281523868025956
    attributes: null
    connectorPath: ''
    constant: 更新连接器
    ct: eq
    description: ''
    dt: string
    fieldName: operateDes
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 16597
    ift: create
    inputFieldDescribeId: 0
    name: 操作描述
    requestParamName: operateDes
    sessionParamName: ''
    uuid: C6195DFF-27C7-445F-B526-2FC5F156294F1523868037688
    validate: null
  outputFields:
  - alias: unique_value
    apiLegoId: 0
    apiLegoUuid: 67FA3BE6-A9B1-408D-963F-1D1E284958281523868025956
    description: ''
    dt: ''
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 2621
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: 01F9A965-EEE6-4C08-8332-C407383ADEFD1523868025956
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: -400
