api:
  alias: update-md
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-04T14:56:51Z
  description: 更新积木方法
  id: 270
  method: POST
  name: 更新积木方法
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: update-md
    attributes: null
    description: null
    id: 372
    index: 1
    legoAlias: update
    oiAlias: ty_method_describe
    processControllerAlias: null
    uuid: '372'
  inputFields:
  - alias: id
    apiLegoId: 372
    apiLegoUuid: '372'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1027
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: null
    uuid: '1027'
    validate: '[{"validateName":"required"}]'
  - alias: name
    apiLegoId: 372
    apiLegoUuid: '372'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1028
    ift: update
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '1028'
    validate: null
  - alias: description
    apiLegoId: 372
    apiLegoUuid: '372'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1029
    ift: update
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '1029'
    validate: null
  - alias: buildingBlockAlias
    apiLegoId: 372
    apiLegoUuid: '372'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: buildingBlockAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1030
    ift: update
    inputFieldDescribeId: 0
    name: 积木别名
    requestParamName: buildingBlockAlias
    sessionParamName: null
    uuid: '1030'
    validate: null
  - alias: methodName
    apiLegoId: 372
    apiLegoUuid: '372'
    attributes: null
    connectorPath: ''
    constant: null
    ct: null
    description: null
    dt: null
    fieldName: methodName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 1031
    ift: update
    inputFieldDescribeId: 0
    name: 方法名
    requestParamName: methodName
    sessionParamName: null
    uuid: '1031'
    validate: null
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
