api:
  alias: update_user_password
  authType: '["ty_auth"]'
  category: config
  content: null
  createDate: 2018-05-02T13:08:18Z
  description: 修改TY用户的密码
  id: 1108
  method: POST
  name: 修改TY用户密码
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: update_user_password
    attributes: null
    description: ''
    id: 4008
    index: 1
    legoAlias: uniqueness
    oiAlias: ty_user
    processControllerAlias: null
    uuid: 60F83EE8-1F43-4250-AD08-95D774EFD3471525237913145
  inputFields:
  - alias: id
    apiLegoId: 0
    apiLegoUuid: 60F83EE8-1F43-4250-AD08-95D774EFD3471525237913145
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 33312
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: 9F9C879C-C723-426D-983B-2F015E6E081C1525237945319
    validate: '[{"validateName":"required"}]'
  outputFields:
  - alias: is_unique
    apiLegoId: 0
    apiLegoUuid: 60F83EE8-1F43-4250-AD08-95D774EFD3471525237913145
    description: ''
    dt: ''
    fieldName: is_unique
    fieldValue: null
    handle: ''
    id: 5436
    name: 是否唯一
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: 7F319A06-55E4-454B-A31F-F1A69724D4771525237913145
- apiLego:
    apiAlias: update_user_password
    attributes: null
    description: ''
    id: 4009
    index: 2
    legoAlias: update
    oiAlias: ty_user
    processControllerAlias: null
    uuid: BCE5FDAC-7B6C-4E07-A6E7-D428BA174EA91525237761804
  inputFields:
  - alias: password
    apiLegoId: 0
    apiLegoUuid: BCE5FDAC-7B6C-4E07-A6E7-D428BA174EA91525237761804
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: password
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 33313
    ift: update
    inputFieldDescribeId: 0
    name: 密码
    requestParamName: password
    sessionParamName: ''
    uuid: F2C1E970-3242-4DA4-B535-78CE4DAD69781525237783129
    validate: '[{"validateName":"md5Encrypt"}]'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: BCE5FDAC-7B6C-4E07-A6E7-D428BA174EA91525237761804
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 33314
    ift: condition
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: 38FE8B6C-3ABD-4F06-BB01-A8B18635B8A91525237835376
    validate: '[{"validateName":"required"}]'
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
