api:
  alias: update-inputfield
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-08-17T11:16:05Z
  description: null
  id: 205
  method: POST
  name: 更新inputField
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: update-inputfield
    attributes: null
    description: null
    id: 252
    index: 1
    legoAlias: update
    oiAlias: ty_input_field
    processControllerAlias: null
    uuid: '252'
  inputFields:
  - alias: name
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: name
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 231
    ift: update
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: null
    uuid: '231'
    validate: null
  - alias: description
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: description
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 232
    ift: update
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: null
    uuid: '232'
    validate: null
  - alias: apiLegoId
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: apiLegoId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 233
    ift: update
    inputFieldDescribeId: 0
    name: apiLegoId
    requestParamName: apiLegoId
    sessionParamName: null
    uuid: '233'
    validate: null
  - alias: fieldName
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fieldName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 234
    ift: update
    inputFieldDescribeId: 0
    name: 字段名
    requestParamName: fieldName
    sessionParamName: null
    uuid: '234'
    validate: null
  - alias: constant
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: constant
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 235
    ift: update
    inputFieldDescribeId: 0
    name: 常量值
    requestParamName: constant
    sessionParamName: null
    uuid: '235'
    validate: null
  - alias: ct
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: ct
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 236
    ift: update
    inputFieldDescribeId: 0
    name: 条件类型
    requestParamName: ct
    sessionParamName: null
    uuid: '236'
    validate: null
  - alias: ift
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: ift
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 237
    ift: update
    inputFieldDescribeId: 0
    name: 输入类型
    requestParamName: ift
    sessionParamName: null
    uuid: '237'
    validate: null
  - alias: fvt
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fvt
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 238
    ift: update
    inputFieldDescribeId: 0
    name: 数据来源
    requestParamName: fvt
    sessionParamName: null
    uuid: '238'
    validate: null
  - alias: fromApiLegoId
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fromApiLegoId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 239
    ift: update
    inputFieldDescribeId: 0
    name: output来源id
    requestParamName: fromApiLegoId
    sessionParamName: null
    uuid: '239'
    validate: null
  - alias: alias
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: alias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 240
    ift: update
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: null
    uuid: '240'
    validate: null
  - alias: attributes
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: attributes
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 241
    ift: update
    inputFieldDescribeId: 0
    name: 属性
    requestParamName: attributes
    sessionParamName: null
    uuid: '241'
    validate: null
  - alias: validate
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: validate
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 242
    ift: update
    inputFieldDescribeId: 0
    name: 校验
    requestParamName: validate
    sessionParamName: null
    uuid: '242'
    validate: null
  - alias: connectorPath
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: connectorPath
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 243
    ift: update
    inputFieldDescribeId: 0
    name: 连接器
    requestParamName: connectorPath
    sessionParamName: null
    uuid: '243'
    validate: null
  - alias: dt
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: null
    connectorPath: null
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: dt
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 244
    ift: update
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: dt
    sessionParamName: null
    uuid: '244'
    validate: null
  - alias: inputFieldDescribeId
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: inputFieldDescribeId
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 245
    ift: update
    inputFieldDescribeId: 0
    name: 描述id
    requestParamName: inputFieldDescribeId
    sessionParamName: null
    uuid: '245'
    validate: ''
  - alias: id
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: id
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 246
    ift: condition
    inputFieldDescribeId: 0
    name: 条件id
    requestParamName: id
    sessionParamName: ''
    uuid: '246'
    validate: '[{"validateName":"required"}]'
  - alias: fromApiLegoOutputFieldAlias
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fromApiLegoOutputFieldAlias
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 657
    ift: update
    inputFieldDescribeId: 0
    name: output参数名称
    requestParamName: fromApiLegoOutputFieldAlias
    sessionParamName: null
    uuid: '657'
    validate: ''
  - alias: requestParamName
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: requestParamName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 658
    ift: update
    inputFieldDescribeId: 0
    name: 请求参数名称
    requestParamName: requestParamName
    sessionParamName: null
    uuid: '658'
    validate: ''
  - alias: sessionParamName
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: ''
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: sessionParamName
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: '0'
    fvt: request
    id: 659
    ift: update
    inputFieldDescribeId: 0
    name: session参数名称
    requestParamName: sessionParamName
    sessionParamName: null
    uuid: '659'
    validate: ''
  - alias: fieldTpl
    apiLegoId: 252
    apiLegoUuid: '252'
    attributes: null
    connectorPath: ''
    constant: null
    ct: eq
    description: null
    dt: string
    fieldName: fieldTpl
    fieldTpl: null
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: null
    fromApiLegoUuid: null
    fvt: request
    id: 8787
    ift: update
    inputFieldDescribeId: 0
    name: 字段值模板
    requestParamName: fieldTpl
    sessionParamName: null
    uuid: '8787'
    validate: null
  outputFields: [
    ]
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
