api:
  alias: update-ds
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-05T10:09:17Z
  description: 更新模型
  id: 273
  method: POST
  name: 更新模型
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: update-ds
    attributes: null
    description: ''
    id: 2112
    index: 1
    legoAlias: update
    oiAlias: ty_ds
    processControllerAlias: null
    uuid: '382'
  inputFields:
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '382'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: '0'
    fvt: request
    id: 15655
    ift: condition
    inputFieldDescribeId: 0
    name: alias
    requestParamName: alias
    sessionParamName: ''
    uuid: '1058'
    validate: '[{"validateName":"required"}]'
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '382'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15656
    ift: update
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: '1059'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '382'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15657
    ift: update
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: '1060'
    validate: null
  - alias: dst
    apiLegoId: 0
    apiLegoUuid: '382'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: dst
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15658
    ift: update
    inputFieldDescribeId: 0
    name: dst
    requestParamName: dst
    sessionParamName: ''
    uuid: '1061'
    validate: null
  - alias: connectionUrl
    apiLegoId: 0
    apiLegoUuid: '382'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: connectionUrl
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15659
    ift: update
    inputFieldDescribeId: 0
    name: connectionUrl
    requestParamName: connectionUrl
    sessionParamName: ''
    uuid: '1062'
    validate: null
  - alias: connectionUsername
    apiLegoId: 0
    apiLegoUuid: '382'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: connectionUsername
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15660
    ift: update
    inputFieldDescribeId: 0
    name: connectionUsername
    requestParamName: connectionUsername
    sessionParamName: ''
    uuid: '1063'
    validate: null
  - alias: connectionPassword
    apiLegoId: 0
    apiLegoUuid: '382'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: connectionPassword
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15661
    ift: update
    inputFieldDescribeId: 0
    name: connectionPassword
    requestParamName: connectionPassword
    sessionParamName: ''
    uuid: '1064'
    validate: null
  - alias: dsConfigFrom
    apiLegoId: 0
    apiLegoUuid: '382'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: dsConfigFrom
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15662
    ift: update
    inputFieldDescribeId: 0
    name: 数据库链接来源
    requestParamName: dsConfigFrom
    sessionParamName: ''
    uuid: '3823'
    validate: null
  - alias: owerId
    apiLegoId: 0
    apiLegoUuid: '382'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: owerId
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15663
    ift: update
    inputFieldDescribeId: 0
    name: 负责人ID
    requestParamName: owerId
    sessionParamName: ''
    uuid: '8898'
    validate: null
  - alias: owerName
    apiLegoId: 0
    apiLegoUuid: '382'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: owerName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15664
    ift: update
    inputFieldDescribeId: 0
    name: 负责人名称
    requestParamName: owerName
    sessionParamName: ''
    uuid: '8899'
    validate: null
  outputFields: [
    ]
- apiLego:
    apiAlias: update-ds
    attributes: null
    description: ''
    id: 2113
    index: 2
    legoAlias: objectRecombine
    oiAlias: null
    processControllerAlias: null
    uuid: '2110'
  inputFields:
  - alias: dataType
    apiLegoId: 0
    apiLegoUuid: '2110'
    attributes: null
    connectorPath: ''
    constant: data
    ct: ''
    description: ''
    dt: string
    fieldName: dataType
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 15665
    ift: common
    inputFieldDescribeId: 0
    name: 转换类型(data/list)
    requestParamName: dataType
    sessionParamName: ''
    uuid: '15639'
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '2110'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15666
    ift: memory
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: ''
    uuid: '15640'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '2110'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15667
    ift: memory
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: ''
    uuid: '15641'
    validate: null
  - alias: alias
    apiLegoId: 0
    apiLegoUuid: '2110'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: alias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15668
    ift: memory
    inputFieldDescribeId: 0
    name: 别名
    requestParamName: alias
    sessionParamName: ''
    uuid: '15642'
    validate: null
  - alias: dst
    apiLegoId: 0
    apiLegoUuid: '2110'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: dst
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15669
    ift: memory
    inputFieldDescribeId: 0
    name: 模型类型
    requestParamName: dst
    sessionParamName: ''
    uuid: '15643'
    validate: null
  - alias: connectionUrl
    apiLegoId: 0
    apiLegoUuid: '2110'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: connectionUrl
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15670
    ift: memory
    inputFieldDescribeId: 0
    name: 链接地址
    requestParamName: connectionUrl
    sessionParamName: ''
    uuid: '15644'
    validate: null
  - alias: connectionUsername
    apiLegoId: 0
    apiLegoUuid: '2110'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: connectionUsername
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15671
    ift: memory
    inputFieldDescribeId: 0
    name: 链接用户名
    requestParamName: connectionUsername
    sessionParamName: ''
    uuid: '15645'
    validate: null
  - alias: connectionPassword
    apiLegoId: 0
    apiLegoUuid: '2110'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: connectionPassword
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15672
    ift: memory
    inputFieldDescribeId: 0
    name: 链接密码
    requestParamName: connectionPassword
    sessionParamName: ''
    uuid: '15646'
    validate: null
  - alias: dsConfigFrom
    apiLegoId: 0
    apiLegoUuid: '2110'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: dsConfigFrom
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 15673
    ift: memory
    inputFieldDescribeId: 0
    name: 数据源来源
    requestParamName: dsConfigFrom
    sessionParamName: ''
    uuid: '15647'
    validate: null
  outputFields:
  - alias: data
    apiLegoId: 0
    apiLegoUuid: '2110'
    description: ''
    dt: string
    fieldName: data
    fieldValue: null
    handle: '[{"handleName":"objectToJson"}]'
    id: 2491
    name: 重组对象
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: '2489'
- apiLego:
    apiAlias: update-ds
    attributes: null
    description: 插入日志
    id: 2114
    index: 3
    legoAlias: add
    oiAlias: ty_model_log
    processControllerAlias: null
    uuid: '2111'
  inputFields:
  - alias: operatorId
    apiLegoId: 0
    apiLegoUuid: '2111'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: operatorId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 15674
    ift: create
    inputFieldDescribeId: 0
    name: 操作人ID
    requestParamName: operatorId
    sessionParamName: ''
    uuid: '15649'
    validate: null
  - alias: operatorName
    apiLegoId: 0
    apiLegoUuid: '2111'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operatorName
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.xingMing}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 15675
    ift: create
    inputFieldDescribeId: 0
    name: 操作人姓名
    requestParamName: operatorName
    sessionParamName: ''
    uuid: '15650'
    validate: null
  - alias: operateDate
    apiLegoId: 0
    apiLegoUuid: '2111'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: time
    fieldName: operateDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 15676
    ift: create
    inputFieldDescribeId: 0
    name: 操作时间
    requestParamName: operateDate
    sessionParamName: ''
    uuid: '15651'
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: operateContent
    apiLegoId: 0
    apiLegoUuid: '2111'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateContent
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: data
    fromApiLegoUuid: '2110'
    fvt: output
    id: 15677
    ift: create
    inputFieldDescribeId: 0
    name: 详细操作内容
    requestParamName: operateContent
    sessionParamName: ''
    uuid: '15652'
    validate: null
  - alias: operateAlias
    apiLegoId: 0
    apiLegoUuid: '2111'
    attributes: null
    connectorPath: ''
    constant: ty_ds
    ct: eq
    description: ''
    dt: string
    fieldName: operateAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 15678
    ift: create
    inputFieldDescribeId: 0
    name: 操作模型别名
    requestParamName: operateAlias
    sessionParamName: ''
    uuid: '15653'
    validate: null
  - alias: operateDes
    apiLegoId: 0
    apiLegoUuid: '2111'
    attributes: null
    connectorPath: ''
    constant: 更新模型
    ct: eq
    description: ''
    dt: string
    fieldName: operateDes
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 15679
    ift: create
    inputFieldDescribeId: 0
    name: 操作描述
    requestParamName: operateDes
    sessionParamName: ''
    uuid: '15654'
    validate: null
  outputFields:
  - alias: unique_value
    apiLegoId: 0
    apiLegoUuid: '2111'
    description: ''
    dt: ''
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 2492
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: '2490'
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
