api:
  alias: update-field
  authType: ty_auth
  category: config
  content: null
  createDate: 2017-09-05T11:43:20Z
  description: 更新OI字段
  id: 282
  method: POST
  name: 更新OI字段
  type: ty
  url: null
  version: version_2
apiLegoViews:
- apiLego:
    apiAlias: update-field
    attributes: null
    description: ''
    id: 2913
    index: 1
    legoAlias: uniqueness
    oiAlias: ty_field
    processControllerAlias: null
    uuid: D59CB136-7D7A-4CA7-A32B-54DEDB5A297A1524129179923
  inputFields:
  - alias: fieldName
    apiLegoId: 0
    apiLegoUuid: D59CB136-7D7A-4CA7-A32B-54DEDB5A297A1524129179923
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: fieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23458
    ift: condition
    inputFieldDescribeId: 0
    name: fieldName
    requestParamName: fieldName
    sessionParamName: ''
    uuid: 62320DF0-BF10-4FA2-8023-D07825DF1C841524129329895
    validate: '[{"validateName":"required","params":"字段名为必填字段"}]'
  - alias: oiAlias
    apiLegoId: 0
    apiLegoUuid: D59CB136-7D7A-4CA7-A32B-54DEDB5A297A1524129179923
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: oiAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23459
    ift: condition
    inputFieldDescribeId: 0
    name: oiAlias
    requestParamName: oiAlias
    sessionParamName: ''
    uuid: 5BC4A7A8-C53B-4479-9458-47FA78D5175B1524129329895
    validate: '[{"validateName":"required"}]'
  - alias: id
    apiLegoId: 0
    apiLegoUuid: D59CB136-7D7A-4CA7-A32B-54DEDB5A297A1524129179923
    attributes: null
    connectorPath: ''
    constant: ''
    ct: neq
    description: ''
    dt: int
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23460
    ift: condition
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: 99C04F4D-557F-4FA4-B0D1-6B0EC15750501524136630718
    validate: '[{"validateName":"required"}]'
  outputFields:
  - alias: is_unique
    apiLegoId: 0
    apiLegoUuid: D59CB136-7D7A-4CA7-A32B-54DEDB5A297A1524129179923
    description: ''
    dt: ''
    fieldName: is_unique
    fieldValue: null
    handle: '[{"handleName":"dataResultJudge","params":"true,模型下的字段名必须唯一"}]'
    id: 3511
    name: 是否唯一
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: 464D0DF7-FE5D-4023-B056-84BC66E550411524129179925
- apiLego:
    apiAlias: update-field
    attributes: null
    description: ''
    id: 2914
    index: 2
    legoAlias: update
    oiAlias: ty_field
    processControllerAlias: null
    uuid: '393'
  inputFields:
  - alias: id
    apiLegoId: 0
    apiLegoUuid: '393'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23461
    ift: condition
    inputFieldDescribeId: 0
    name: id
    requestParamName: id
    sessionParamName: ''
    uuid: '1113'
    validate: '[{"validateName":"required"}]'
  - alias: name
    apiLegoId: 0
    apiLegoUuid: '393'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23462
    ift: update
    inputFieldDescribeId: 0
    name: name
    requestParamName: name
    sessionParamName: ''
    uuid: '1114'
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: '393'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23463
    ift: update
    inputFieldDescribeId: 0
    name: description
    requestParamName: description
    sessionParamName: ''
    uuid: '1115'
    validate: null
  - alias: fieldName
    apiLegoId: 0
    apiLegoUuid: '393'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: fieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23464
    ift: update
    inputFieldDescribeId: 0
    name: fieldName
    requestParamName: fieldName
    sessionParamName: ''
    uuid: '1116'
    validate: null
  - alias: dt
    apiLegoId: 0
    apiLegoUuid: '393'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: dt
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23465
    ift: update
    inputFieldDescribeId: 0
    name: dt
    requestParamName: dt
    sessionParamName: ''
    uuid: '1117'
    validate: null
  - alias: pk
    apiLegoId: 0
    apiLegoUuid: '393'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: pk
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23466
    ift: update
    inputFieldDescribeId: 0
    name: pk
    requestParamName: pk
    sessionParamName: ''
    uuid: '1118'
    validate: null
  - alias: fieldValue
    apiLegoId: 0
    apiLegoUuid: '393'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: fieldValue
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23467
    ift: update
    inputFieldDescribeId: 0
    name: fieldValue
    requestParamName: fieldValue
    sessionParamName: ''
    uuid: '1119'
    validate: null
  - alias: fieldLength
    apiLegoId: 0
    apiLegoUuid: '393'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: ''
    description: ''
    dt: ''
    fieldName: fieldLength
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23468
    ift: update
    inputFieldDescribeId: 0
    name: fieldLength
    requestParamName: fieldLength
    sessionParamName: ''
    uuid: '1120'
    validate: '[{"validateName":"integerTypeCheck"},{"validateName":"numRangeCheck","params":"0,2147483647"}]'
  - alias: group
    apiLegoId: 0
    apiLegoUuid: '393'
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: group
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23469
    ift: update
    inputFieldDescribeId: 0
    name: group
    requestParamName: group
    sessionParamName: ''
    uuid: '12695'
    validate: null
  outputFields: [
    ]
- apiLego:
    apiAlias: update-field
    attributes: null
    description: ''
    id: 2915
    index: 3
    legoAlias: objectRecombine
    oiAlias: null
    processControllerAlias: null
    uuid: ED978A12-01D4-4187-BFCE-D586322B709B1523866989786
  inputFields:
  - alias: dataType
    apiLegoId: 0
    apiLegoUuid: ED978A12-01D4-4187-BFCE-D586322B709B1523866989786
    attributes: null
    connectorPath: ''
    constant: data
    ct: ''
    description: ''
    dt: ''
    fieldName: dataType
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 23470
    ift: common
    inputFieldDescribeId: 0
    name: 转换类型(data/list)
    requestParamName: dataType
    sessionParamName: ''
    uuid: 7D35DF54-2AA0-4AC3-8616-5F037D42BA421523866989786
    validate: null
  - alias: id
    apiLegoId: 0
    apiLegoUuid: ED978A12-01D4-4187-BFCE-D586322B709B1523866989786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: id
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23471
    ift: memory
    inputFieldDescribeId: 0
    name: ID
    requestParamName: id
    sessionParamName: ''
    uuid: 08901601-BCDA-46C7-82AC-9166B6C5966E1523867020773
    validate: null
  - alias: name
    apiLegoId: 0
    apiLegoUuid: ED978A12-01D4-4187-BFCE-D586322B709B1523866989786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: name
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23472
    ift: memory
    inputFieldDescribeId: 0
    name: 名称
    requestParamName: name
    sessionParamName: ''
    uuid: E77F834D-13EC-477A-A7C6-DF72F5A5B1861523867039072
    validate: null
  - alias: description
    apiLegoId: 0
    apiLegoUuid: ED978A12-01D4-4187-BFCE-D586322B709B1523866989786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: description
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23473
    ift: memory
    inputFieldDescribeId: 0
    name: 描述
    requestParamName: description
    sessionParamName: ''
    uuid: 02265FD9-2C76-41B1-9FFC-34FA0BD33BDB1523867058844
    validate: null
  - alias: fieldName
    apiLegoId: 0
    apiLegoUuid: ED978A12-01D4-4187-BFCE-D586322B709B1523866989786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: fieldName
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23474
    ift: memory
    inputFieldDescribeId: 0
    name: 字段名
    requestParamName: fieldName
    sessionParamName: ''
    uuid: 52A11730-10A3-42D2-9C05-7DC27CF49D101523867073815
    validate: null
  - alias: dt
    apiLegoId: 0
    apiLegoUuid: ED978A12-01D4-4187-BFCE-D586322B709B1523866989786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: dt
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23475
    ift: memory
    inputFieldDescribeId: 0
    name: 数据类型
    requestParamName: dt
    sessionParamName: ''
    uuid: 71DFA112-6A35-4CF3-9833-0578BB7663281523867088786
    validate: null
  - alias: pk
    apiLegoId: 0
    apiLegoUuid: ED978A12-01D4-4187-BFCE-D586322B709B1523866989786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: pk
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23476
    ift: memory
    inputFieldDescribeId: 0
    name: 是否主键
    requestParamName: pk
    sessionParamName: ''
    uuid: 358CFD1C-F597-422F-BF26-9BE754E8C9571523867103162
    validate: null
  - alias: fieldLength
    apiLegoId: 0
    apiLegoUuid: ED978A12-01D4-4187-BFCE-D586322B709B1523866989786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: fieldLength
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23477
    ift: memory
    inputFieldDescribeId: 0
    name: 字段长度
    requestParamName: fieldLength
    sessionParamName: ''
    uuid: AF642CC0-337F-4A4C-9BF0-2013D35CAEDA1523867120031
    validate: null
  - alias: group
    apiLegoId: 0
    apiLegoUuid: ED978A12-01D4-4187-BFCE-D586322B709B1523866989786
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: ''
    fieldName: group
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: request
    id: 23478
    ift: memory
    inputFieldDescribeId: 0
    name: 分组
    requestParamName: group
    sessionParamName: ''
    uuid: 7A0C7884-BD0F-49E0-8AC5-89B09F98348A1523867137762
    validate: null
  outputFields:
  - alias: fieldData
    apiLegoId: 0
    apiLegoUuid: ED978A12-01D4-4187-BFCE-D586322B709B1523866989786
    description: ''
    dt: ''
    fieldName: data
    fieldValue: null
    handle: '[{"handleName":"objectToJson"}]'
    id: 3512
    name: 重组对象
    oft: common
    outputFieldDescribeId: 0
    response: true
    uuid: 9CBD70D0-088D-4C93-BEF3-0A7F23EEDEA71523866989786
- apiLego:
    apiAlias: update-field
    attributes: null
    description: ''
    id: 2916
    index: 4
    legoAlias: add
    oiAlias: ty_model_log
    processControllerAlias: null
    uuid: F6104598-E377-45A2-B282-9520FB77501D1523867199868
  inputFields:
  - alias: operatorId
    apiLegoId: 0
    apiLegoUuid: F6104598-E377-45A2-B282-9520FB77501D1523867199868
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: int
    fieldName: operatorId
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.id}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 23479
    ift: create
    inputFieldDescribeId: 0
    name: 操作人ID
    requestParamName: operatorId
    sessionParamName: ''
    uuid: E2D2D507-4B96-4B0C-80A9-0CE8C69DEC141523867211821
    validate: null
  - alias: operatorName
    apiLegoId: 0
    apiLegoUuid: F6104598-E377-45A2-B282-9520FB77501D1523867199868
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operatorName
    fieldTpl: ${session.TY_SESSION_CONFIG_USER.xingMing}
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: template
    id: 23480
    ift: create
    inputFieldDescribeId: 0
    name: 操作人姓名
    requestParamName: operatorName
    sessionParamName: ''
    uuid: 79E5D517-167E-4C17-BE39-52406591C4D91523867211821
    validate: null
  - alias: operateDate
    apiLegoId: 0
    apiLegoUuid: F6104598-E377-45A2-B282-9520FB77501D1523867199868
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: time
    fieldName: operateDate
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: ''
    id: 23481
    ift: create
    inputFieldDescribeId: 0
    name: 操作时间
    requestParamName: operateDate
    sessionParamName: ''
    uuid: CF1E5C8C-3E81-4105-BAF6-91C8F39EC6631523867211821
    validate: '[{"validateName":"systemTimeAssign"}]'
  - alias: operateContent
    apiLegoId: 0
    apiLegoUuid: F6104598-E377-45A2-B282-9520FB77501D1523867199868
    attributes: null
    connectorPath: ''
    constant: ''
    ct: eq
    description: ''
    dt: string
    fieldName: operateContent
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: fieldData
    fromApiLegoUuid: ED978A12-01D4-4187-BFCE-D586322B709B1523866989786
    fvt: output
    id: 23482
    ift: create
    inputFieldDescribeId: 0
    name: 详细操作内容
    requestParamName: operateContent
    sessionParamName: ''
    uuid: EAF08321-362A-4AEC-8C7C-C10684DA34C91523867211821
    validate: null
  - alias: operateAlias
    apiLegoId: 0
    apiLegoUuid: F6104598-E377-45A2-B282-9520FB77501D1523867199868
    attributes: null
    connectorPath: ''
    constant: ty_field
    ct: eq
    description: ''
    dt: string
    fieldName: operateAlias
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 23483
    ift: create
    inputFieldDescribeId: 0
    name: 操作模型别名
    requestParamName: operateAlias
    sessionParamName: ''
    uuid: BF8D8443-E055-4E62-85D2-952369F2A2091523867211821
    validate: null
  - alias: operateDes
    apiLegoId: 0
    apiLegoUuid: F6104598-E377-45A2-B282-9520FB77501D1523867199868
    attributes: null
    connectorPath: ''
    constant: 更新字段
    ct: eq
    description: ''
    dt: string
    fieldName: operateDes
    fieldTpl: ''
    fieldValue: null
    fromApiLegoId: 0
    fromApiLegoOutputFieldAlias: ''
    fromApiLegoUuid: ''
    fvt: constant
    id: 23484
    ift: create
    inputFieldDescribeId: 0
    name: 操作描述
    requestParamName: operateDes
    sessionParamName: ''
    uuid: DFE43217-438E-48BF-B564-2D32D86E32601523867211821
    validate: null
  outputFields:
  - alias: unique_value
    apiLegoId: 0
    apiLegoUuid: F6104598-E377-45A2-B282-9520FB77501D1523867199868
    description: ''
    dt: ''
    fieldName: unique_value
    fieldValue: null
    handle: ''
    id: 3513
    name: 添加唯一值
    oft: common
    outputFieldDescribeId: 0
    response: false
    uuid: 990746F8-914B-418E-8D74-42C687B950F71523867199869
authTypes:
- alias: ty_auth
  description: TYSession校验
  id: 1
  judgeAPIAlias: ty_auth_check
  name: E端登录校验
  noAuthErrorCode: null
